### ISSUE TITLE
Text Size (LV)

### ISSUE THREAD

**Issue by allanj-uaag** [w3c/wcag21#11]
<body>

<h2><span id="SC_Shortname">SC Shortname</span></h2>

<p>Text Size </p>

<h2><span id="SC_Text">SC Text</span></h2>

<p>Except   for images of text, text can be resized without assistive technology up   to the user agent maximum without loss of content and functionality. </p>

<h3><span id="Current_WCAG_1.4.4">Current WCAG 1.4.4</span></h3>

<p>Except   for captions and images of text, text can be resized without assistive   technology up to 200 percent without loss of content or functionality. </p>

<h3><span id="Proposed_Change:">Proposed Change:</span></h3>

<p>Except for captions and images of text, text can be resized without assistive technology up to 200 percent @@the user agent maximum without loss of content and functionality@@. </p>

<h2><span id="Suggested_Priority_Level">Suggested Priority Level</span></h2>

<p>Level A </p>

<h2><span id="Related_Glossary_additions_or_changes">Related Glossary additions or changes</span></h2>

<p>None </p>

<h2><span id="What_Principle_and_Guideline_the_SC_falls_within.">What Principle and Guideline the SC falls within.</span></h2>

<p>Principle 1, Guideline <a rel="nofollow" href="http://www.w3.org/TR/2008/REC-WCAG20-20081211/#visual-audio-contrast-scale">1.4.4 Resize text</a></p>

<h2><span id="Description">Description</span></h2>

<p>A   person can increase or decrease text-size only. Non-text content does   not change. A key functionality to preserve is that complete lines of   text fit within the viewport. For any block of text, the last word of a   line is the immediate predecessor of the first word in the next line in   reading order. No exceptions. Also, text fits within bounding boxes,   lines, and columns if present. Finally, margins should not change with   text size. </p>

<h2><span id="Benefits">Benefits</span></h2>

<blockquote>
  <p>Some people need larger text in order to perceive letters. Although   increasing size is most common, some people with tunnel vision and good   visual acuity may prefer smaller letters so they can see more words at a   time. </p>
  <p>Example issues: </p>
  <ul>
    <li> Text settings don't increase the text in tool-tip text and other pop-up text </li>
    <li> Text settings don't increase the text in images </li>
    <li> Text settings don't increase the text in maps </li>
  </ul>
  <p><strong>User Need</strong> - Text Size: Users can change the text size (font size) of all text, without zooming the entire interface.  - Source: <a rel="nofollow" href="http://w3c.github.io/low-vision-a11y-tf/requirements.html#text-size">Accessibility Requirements for People with Low Vision, Section 3.3.1: text size</a></p>
</blockquote>

<h2><span id="Testability">Testability</span></h2>

<ol>
  <li> Display content in a user agent. </li>
  <li> Increase text size to the maximum. </li>
  <li> Check whether text scales and is perceivable. </li>
</ol>

<p>Expected Results </p>

<ul>
  <li> Check #3 is true. </li>
</ul>

<h2><span id="Techniques">Techniques</span></h2>

<h3><span id="All_Existing_Techniques_for_Changed_SC">All Existing Techniques for Changed SC</span></h3>

<ul>
  <li> <a rel="nofollow" href="https://www.w3.org/TR/WCAG20-TECHS/C28">C28: Specifying the size of text containers using em units (CSS)</a></li>
  <li> Techniques for relative measurements
    <ul>
      <li> <a rel="nofollow" href="https://www.w3.org/TR/WCAG20-TECHS/C12">C12: Using percent for font sizes (CSS)</a></li>
      <li> <a rel="nofollow" href="https://www.w3.org/TR/WCAG20-TECHS/C13">C13: Using named font sizes (CSS)</a></li>
      <li> <a rel="nofollow" href="https://www.w3.org/TR/WCAG20-TECHS/C14">C14: Using em units for font sizes (CSS)</a></li>
      <li> <a rel="nofollow" href="https://www.w3.org/TR/WCAG20-TECHS/C22">C22: Using CSS to control visual presentation of text</a></li>
    </ul>
  </li>
</ul>

<h3><span id="New_Techniques">New Techniques</span></h3>

<ul>
  <li> Ensuring that there is no loss of content or functionality when the   text resizes and text containers do not change when resized up to user   agent maximum. To be based on <a rel="nofollow" href="https://www.w3.org/TR/WCAG20-TECHS/G179">G179</a>, which is currently limited to a 200% maximum. </li>
  <li> Failure of Success Criterion 1.4.4 when resizing visually rendered   text up to user agent maximum causes the text, image or controls to be   clipped, truncated or obscured.  To be based on <a rel="nofollow" href="https://www.w3.org/TR/WCAG20-TECHS/F69">F69</a>, which is currently limited to a 200% maximum. </li>
</ul>

<h2><span id="Related_Information">Related Information</span></h2>

<h3><span id="Actions">Actions</span></h3>

<ul>
  <li><a rel="nofollow" href="https://www.w3.org/WAI/GL/low-vision-a11y-tf/track/actions/76">ACTION-76: When users change font size and list out the cases for the sc</a> on Scott McCormack, August 25, 2016 </li>
</ul>

<h3><span id="Articles">Articles</span></h3>

<ul>
  <li><a rel="nofollow" href="https://www.w3.org/WAI/tutorials/page-structure/styling/#font-size">Font size</a> -  Education and Outreach Working Group Tutorial </li>
</ul>

<h3><span id="Email">Email</span></h3>

<ul>
  <li><a rel="nofollow" href="https://lists.w3.org/Archives/Public/public-low-vision-a11y-tf/2016Sep/0054.html">Text Size</a> - Wayne Dick, 14 September 2016
    <ul>
      <li><a rel="nofollow" href="https://lists.w3.org/Archives/Public/public-low-vision-a11y-tf/2016Sep/0057.html">Re: Text Size</a> Jim Allan, 14 September 2016 </li>
      <li><a rel="nofollow" href="https://lists.w3.org/Archives/Public/public-low-vision-a11y-tf/2016Sep/0055.html">Text Size SC</a> - Wayne Dick, 14 September 2016 </li>
    </ul>
  </li>
  <li><a rel="nofollow" href="https://lists.w3.org/Archives/Public/public-low-vision-a11y-tf/2016Sep/thread.html#msg14">Thread: Re: lvtf-ACTION-70: Write font sc</a> - LVTF List </li>
  <li><a rel="nofollow" href="https://lists.w3.org/Archives/Public/w3c-wai-gl/2016JulSep/thread.html#msg73">Thread: 1100% may be physically impossible and still not achieve the results on smaller monitors</a> - WCAG WG List </li>
  <li><a rel="nofollow" href="https://lists.w3.org/Archives/Public/public-low-vision-a11y-tf/2016Jul/">Thread: 1100% enlargement</a> - LVTF List </li>
  <li><a rel="nofollow" href="https://lists.w3.org/Archives/Public/public-low-vision-a11y-tf/2016Sep/thread.html#msg14">Thread: lvtf-ACTION-70: Write font sc</a> - LVTF List </li>
  <li><a rel="nofollow" href="https://lists.w3.org/Archives/Public/public-low-vision-a11y-tf/2016Feb/0042.html">Requirements doc</a> - Alastair Campbell, 18 February 2016 </li>
</ul>

<h3><span id="GitHub">GitHub</span></h3>

<ul>
  <li><a rel="nofollow" href="https://github.com/w3c/low-vision-SC/issues/5">WCAG 1.4.8 item 5 200% #5 LVTF GitHub SC Issue #5</a></li>
  <li><a rel="nofollow" href="https://github.com/w3c/low-vision-SC/issues/14">Text Size (User Need 3.3.1) - LVTF GitHub SC Issue #14</a></li>
</ul>

<h3><span id="Minutes">Minutes</span></h3>

<ul>
  <li><a rel="nofollow" href="https://www.w3.org/2016/09/15-lvtf-minutes.html#item04">15 September 2016 LVTF minutes</a></li>
  <li><a rel="nofollow" href="https://www.w3.org/2016/05/19-lvtf-minutes.html">5 May 2016 LVTF minutes</a></li>
  <li><a rel="nofollow" href="https://www.w3.org/2016/05/19-lvtf-minutes.html#resolution01">19 May 2016 LVTF minutes</a></li>
  <li><a rel="nofollow" href="https://www.w3.org/2016/09/01-lvtf-minutes.html">1 September 2016 LVTF minutes</a></li>
</ul>

<h3><span id="Wiki_Pages">Wiki Pages</span></h3>

<ul>
  <li> <a rel="nofollow" href="https://www.w3.org/WAI/GL/low-vision-a11y-tf/wiki/User_stories_-_use_cases#Size_Limitations">Use cases</a> - LVTF Wiki </li>
</ul>

</body>

**Comment by DavidMacDonald** [comment]
"up to 200 percent @@the user agent maximum"

Huh? How can you exceed the user agent maximum with the user agent?

**Comment by jnurthen** [comment]
Can someone explain how stating that it has to work up to the user agent maximum works in practice? If I develop content which conforms and then someone develops or extends a  user agent which allows a greater zoom level and now my content fails despite it being the same? 
I don't think I can support this without there being a specific zoom level specified. 

Regards,
James.

**Comment by alastc** [comment]
I think this one is defunct, the Resize all content and Reflow should cover the same use-cases and are (more) testable.

**Comment by allanj-uaag** [comment]
closed covered by #58 and #77
