### ISSUE TITLE
Timeouts

### ISSUE THREAD

**Issue by lseeman** [w3c/wcag21#14]
-  [ SC for viewing](https://rawgit.com/w3c/wcag21/timeouts_ISSUE-14/guidelines/sc/21/timeouts.html) | [SC for editing](https://github.com/w3c/wcag21/blob/timeouts_ISSUE-14/guidelines/sc/21/timeouts.html)
-   [ understandable language definition for viewing](https://rawgit.com/w3c/wcag21/timeouts_ISSUE-14/guidelines/terms/21/understandable-language.html) | [understandable language definition for editing](https://github.com/w3c/wcag21/blob/timeouts_ISSUE-14/guidelines/terms/21/understandable-language.html)
-  [ SC in full draft guideline](https://rawgit.com/w3c/wcag21/timeouts_ISSUE-14/guidelines/#timeouts)

## Open issues and Surveys
Open issues: https://www.w3.org/WAI/GL/wiki/WCAG_2.1_SC_status#Issue_14_-_Timeouts
Surveys (Links to surveys require W3C Member access):
- [Results of Questionnaire Timeouts May 2, 2017](https://www.w3.org/2002/09/wbs/35422/Timeouts_Issue14/results) 

## SC Shortname
Timeouts

## SC Text

**For the current SC text, follow the links above. Below is the initially proposed text, which is now out of date**
Where content can time out, the content must also conform to all of the below:

- Loss of data: The user can easily return to the same point in a task, without data loss, for a period of at least one week as the default, or via a user-settable option available throughout the task. If the data will only be preserved for a limited time, the user is informed of the length of time that data are preserved at the start of the task.
- Timing adjustable: The function to turn off, adjust, or extend timing is controlled by a simple action, and is labeled with simple, understandable language.
- Aware: The user is informed of timeout limits at the start of the task, including the length of the warning.

## Suggestion for Priority Level

(A)

## Related Glossary additions or changes

- sensitive information
information that can put users at risk, or information a user wishes to protect
- essential
if removed, would fundamentally change the information or the functionality of content; and information and functionality cannot be achieved in another way that would conform
- safe standardized techniques
standardized by WCAG, other W3C groups, or by the platform, browser, or operating system, where user vulnerabilities are not exposed without informed consent (This will be a discussion, and is not yet finalized.)
- understandable language
conforms to all understandable-language success criteria

## What Principle and Guideline the SC falls within.

Principle 2, Guideline 2.2

This is an update to SC 2.2.1

## Description

The use of timed events can present significant barriers for users with cognitive disabilities, as these users may require more time to read content or to perform functions, such as completing an online form.

During the completion of an online process for reserving a hotel room and purchasing a plane ticket, a user with a cognitive impairment may become overwhelmed with the amount of instruction and data input required to complete the process. The user may not be able to complete the process in one sitting, and may need to take a break. Users should be able to leave a process without losing their current place within the process, and without losing data that have already been entered. If users cannot take a break and check their work, many will often be unable to complete a task correctly.

While making a purchase on an e-commerce Web site, a user with a cognitive disability may not remember required information (e.g., a phone number or a zip code) that may seem easy to remember for users without a cognitive impairment. Users with cognitive disabilities may need additional time to look up the information required to complete a transaction, without losing their place in the process, and without losing data that have already been entered.

In another example, users’ cognitive skills may temporarily diminish as they get tired. They then must stop the task for that day, and continue it when they are feeling better, and when their reading or processing skills are back to their higher levels.

For situations where the absence of a timed event would significantly change the intended functionality of an application (e.g., an auction or another real-time event), it is important to ensure that users with disabilities are properly notified. Notifications should include information about timed events, and an indication of the duration of the time given. As well, they should include mechanisms clearly labeled to adjust, extend, or stop the duration of an event, to allow users to fully engage and interact with Web content and functionality. For example, if an e-commerce Web site's checkout process provides secure credit card transactions, the user is notified of the timeout, and is given at least 120 seconds to extend it.

These experiences have been reported by members of the task force who have various cognitive impairments. There is significant user research indicating that timed events rarely help anyone; and can cause stress and frustration.

It should be noted that many users, within 20 seconds, cannot read instructions to extend a time limit. We thus extended the time limit to 120 seconds.

We also require simple text conforming to the understandable language success criteria.

## Benefits

This Success Criterion helps users who need additional time performing tasks or reading content. This can include the following.

- A Web site uses a client-side time limit to help protect users who may step away from their computers. After a period of inactivity, the Web page asks if the user needs more time. If the user does not respond within 120 seconds, a timeout occurs. The user is able to request more time at least 10 times.
- A Web page has a section that automatically updates with the latest headlines in a rotating fashion. There is an interactive control that is easy to activate and is labeled with simple text. It allows the user to extend the length of time, between each update, to as much as ten times the default. The control can be operated by mouse, keyboard, or touch.
- A ticket-purchasing web site allows users two minutes to confirm purchase of selected seats, but warns users when their time is almost out. It allows users to extend this time limit at least 10 times using a simple action, which is labeled with simple text, such as a button labeled "Extend time limit".
- In an auction, there is a time limit on the amount of time a user has to submit a bid. Because the time limit applies to all users who want to bid on an item, it would be unfair to extend the time limit for one user. Therefore, a time limit is required for this type of activity. No extension, adjustment, or deactivation of such a time limit is required by this Success Criterion.

The Success Criterion helps people with a variety of disabilities including the following.

- People with physical disabilities, who often need more time to react, to type, and to complete activities. - People with low vision need more time to locate things on screen, and to read. People who are blind, and who use screen readers, may need more time to understand screen layouts, to find information, and to operate controls. People, who have cognitive or language limitations, need more time to read and to understand. People who are deaf, and who communicate in sign language, may need more time to read textual information (which may be a second language for some).
- In circumstances where a sign-language interpreter may be relating audio content to a user who is deaf, control over time limits is also important.
- People with reading disabilities, cognitive limitations, and learning disabilities, who may need more time to read or to comprehend information, can pause content to have additional time to read it.

This Success Criterion helps people with many different cognitive disabilities, including people with:

- language-related disabilities;
- memory-related disabilities;
- focus-and-attention-related disabilities; and
- disabilities that affect executive function and decision making.

## Related Resources

Resources are for information purposes only. No endorsement is intended or implied.

- User Needs Table 3: Entering data, error prevention & recovery
- Background research document

## Techniques

- Do not expire a session timeout unless there has been a week of inactivity.
- If a situation exists where a timeout is appropriate, use a mechanism to prevent data loss, and a conformant mechanism with clear controls, to turn off, adjust, or extend the timeout. The mechanism(s) should include both a warning and the ability to return to the original point.

Timed events rarely help anyone; and can cause stress and frustration.

## Testability

For Web Content

- Check if there is a timeout (over a week). If there is no timeout, then it conforms.
- If there is a timeout, confirm it is an exception. If there is no exception, it fails. If it is a Real-time or Essential Exception, it passes.
- Where there is a Security Exception or 20 Hour Exception, confirm it conforms to the criteria of No loss of data, Timing adjustable, and Aware.

Test for Timing Adjustable, as has been addressed in WCAG 2.0.

Test for Aware. It can be confirming, at the first screen of a task, that a timeout limit is provided.

Test for no loss of data. It could be:

1. Begin entering data, into a process containing multiple Web forms, over more than one page.
2. Complete the first form on Page 1 in the process, and proceed to Page 2 in the process.
3. On Page 2 of the process, stop interacting with the page.
4. Wait for a period fewer than 168 hours (1 week).
5. Confirm that the following are both true.
- It is possible to return to Page 2 in the process.
- All data previously entered into the form are able to be retrieved by default, via a standardized system setting, or via a user preference that has a conformant interface.

**Comment by joshueoconnor** [comment]
Assigned to Chaohai Ding - https://www.w3.org/WAI/GL/wiki/SC_Managers_Phase1

**Comment by chaohaiding** [comment]
Looks good for me.

**Comment by joshueoconnor** [comment]
@chaohaiding Is there a Pull request ready to go for this?

**Comment by lseeman** [comment]
Attempt at reworking as a stand alone

Timeouts: Sessions and content do not use timeouts of less then 20 hours of inactivity or there is an essential exception for the timeout.  Where there is a time out all of the following must also be true.
   -No loss of data: The user can easily return to the same point in a task, without data loss, for a period of at least one week as the default, or via a user-settable option available throughout the task. At the start of the task, the user is informed of the length of time that data are preserved.
    -Timing adjustable: The function to turn off, adjust, or extend timing is controlled by a simple action, and is labeled with simple, understandable language. A user- or an administrator-settable time-limit minimum must be provided to complete any controlling action, or the user must be given at least 120 seconds to extend the time limit. The user is allowed to extend the time limit at least ten times. Note that all user settings must be easy to configure, and use standardized techniques when available.
    -Aware: At the start of a task, the user is informed of timeout limits, including the length of the warning. 

Note: This success criterion helps ensure that users can complete tasks, without unexpected changes in content or context, which are a result of a time limit. This success criterion should be considered in conjunction with Success Criterion 3.2.1, which sets limits on changes of content or context as a result of user action.

define essential exception for time outs as one of the following
 -Security Exception: Where security may be at risk, a session can time out after 30 minutes of inactivity. Where financial or sensitive information is at risk, the timeout can be shorter
    Real-time Exception: The time limit is a required part of a real-time event (for example, an auction), and no alternative to the time limit is possible.
    Essential Exception: The time limit is essential, and extending it would invalidate the activity.
       User-Agreed: The timeout period is not less than a minimum timeout period to which the user has agreed.


define simple, understandable language as conforming to the SC on plain language

**Comment by DavidMacDonald** [comment]
I've been asked to comment on this: 
I think it is a very large ask. The negotiations that went into the current wording in 2.0 were not insignificant. The current warning minimum is a dialogue with 20 seconds to respond to a 5 word question with a one key answer. 

>"Do you need more time?"         Yes       no 

@lseeman  wrote
"many people can not read the pop up telling them how to extend the session in just 20 seconds"

I would like to read more information about this. Is there a study somewhere, or a blog entry or some other indication of this? If it can be demonstrated that this has caused significant problems for people with cognitive disabilities, perhaps it can be extended to 30 seconds or on the outside 45 seconds more. I've dealt with quite a few financial institutions, and this 20 second warning is the make/break thing for them. They said "oh, ok we can provide the WCAG extension, because the user has to respond, and has not walked away from the computer." But if it's much longer there is a risk that the computer has been abandoned and is unattended. I think any site that has security concerns would need an exemption from more than 20 seconds.

Have we every received a comment from the public on this? I don't remember any. I think the last bullet is a reasonable addition to the current SC.

>Aware: At the start of a task, the user is informed of timeout limits, including the length of the warning, and that there is an option available to extend.

**Comment by lseeman** [comment]
I cant read it often in the 20 seconds given. I am relitively light in this space. we tried to excluded these concerns by having a user settable or administrator-settable time-limit . in other words, if you have a 20 seconds time limit the adminstator or user agreed. In other words, if you work at a bank, the administator can set a time limit. If it is at home, you will need to agree.

**Comment by lseeman** [comment]
Rachel, I wil go with your wording

**Comment by jnurthen** [comment]
What kind of sites that require a login would not be covered by the security exception? The reason to have a login is normally for security so I would apply this exception to pretty much all content I can think of in my domain.

For many sites 30 minutes of inactivity is also too long. Take for an example someone accessing something which requires a login from a library computer - the timeout is intended to protect people from others causing them harm if they forget to logout or are otherwise distracted. Requiring such a long timeout seems counterproductive.

**Comment by lseeman** [comment]
Hi, See the comment to David above
Making a travel booking is a good example. you pick the date. add your passport information, get a cup of tea so that you have the enegy to check if you copied it correctly (you know that cna happen) and the whole thing times out. then you call your travel agent. You know you will just make more mistakes then next time. ypou can not use that  site if you need brakes or to check your work

**Comment by jnurthen** [comment]
@lseeman Why would it not be acceptable for this travel site to time you out and when you log in again your session is resumed? If I were booking a ticket on a public access computer and I got distracted I would not want my passport information to be available to others.

Besides - booking a plane ticket would fall under the real-time or essential exception anyway. Ticket pricing and availability does vary in real-time so this wouldn't apply here anyway.

**Comment by lseeman** [comment]
What I often get is "your session is about to time out due to inactivity from this station. if you wish to continue the session press cancel within the next 20 seconds, otherwise press OK"

By the time I figuer out what to do it is all gone. All my work all my data....

**Comment by jnurthen** [comment]
@lseeman who is that reply to? I did not mention anything about the 20 second time.

**Comment by lseeman** [comment]
I will remove change the text to the following
. A user- or an administrator-settable time-limit minimum must be provided to complete any controlling action, or the user must be given at least 20 seconds to extend the time limit. The user is allowed to extend the time limit at least ten times. Note that all user settings must be easy to configure, and use standardized techniques when available

In other words I removed increasing the time limit. 
@DavidMacDonald @jnurthen I think it now addresses your issues :)

**Comment by jnurthen** [comment]
@lseeman No it doesn't address my issues at all. I did not comment on that part of the proposal.
1) It seems to me that almost every site with a login can claim the security exception. The reason for a login is normally that there is some sort of sensitive information whether that is PII, credit card info, bank info, customer data, or simply privileged data. I think that having this exception complicates the SC and it should be removed. All sites should be able to have a time out so long as there is no data loss when it occurs.
2) The 30 minute timeout is too long. If a page times out and there is no data loss what is the harm? I understand that it might sometimes be annoying but we have to balance security with these requirements.

**Comment by lseeman** [comment]
we can add a AAA 
Timing adjustable (extended) : When timed events are used, the user must be given at least 300 seconds to extend the time limit.

**Comment by lseeman** [comment]
@jnurthen not everyone can manage the login process, what ever we put in place, for accessible authentification not everyone will be able to use it. 

I can change the security exception to : Security Exception: Where security may be at risk, a session can time out

**Comment by DavidMacDonald** [comment]
>What I often get is "your session is about to time out due to inactivity from this station. if you wish to continue the session press cancel within the next 20 seconds, otherwise press OK"

What if we say something like: 

>If the time out message is more than "x" characters, then the warning remains on the page for "y" seconds.

- x could be something like 30 characters
- y could be something like 1 minute.

**Comment by jnurthen** [comment]
@lseeman that does not seem relevant to this SC. If someone cannot log in then their logged in session cannot expire.

**Comment by lseeman** [comment]
Timeouts: Where content can time out,  the content must also conform to all of the below.
Loss of data: The user can easily return to the same point in a task, without data loss, for a period of at least one week as the default, or via a user-settable option available throughout the task. If the data will only be preserved for a limited time, the user is informed of the length of time that data are preserved at the start of the task.
Timing adjustable: The function to turn off, adjust, or extend timing is controlled by a simple action, and is labeled with simple, understandable language. 
Aware: The user is informed of timeout limits at the start of the task, including the length of the warning.

@jnurthen @DavidMacDonald - Is this OK? We can add the rest as a AAA

**Comment by jnurthen** [comment]
I'll have to see the entire thing once ready but I think it could be ok.

**Comment by lseeman** [comment]
@jnurthen the whole thing
			

		<p>Where content can  time out, the content must also conform to all of the below.<ul><li>
Loss of data: The user can easily return to the same point in a task, without data loss, for a period of at 
least one week as the default, or via a user-settable option available throughout the task. If the data will 
only be preserved for a limited time, the user is informed of the length of time that data are preserved at the start of the task.</li><li>
Timing adjustable: The function to turn off, adjust, or extend timing is controlled by a simple action, and is labeled with simple, understandable language.</li><li>
Aware: The user is informed of timeout limits at the start of the task, including the length of the warning.</li></ol>

**Comment by lseeman** [comment]
I am going to get ready for bed. (it is past midnight)

If I don't here anything soon I will assume we have consensus with the new wording
:) 

All the best

Lisa Seeman

LinkedIn, Twitter





---- On Thu, 09 Feb 2017 23:48:59 +0200 James Nurthen&lt;notifications@github.com&gt; wrote ---- 

I'll have to see the entire thing once ready but I think it could be ok.

**Comment by lseeman** [comment]
pull request 116 
We also want to make a AAA for all the stuff that was taken out

**Comment by awkawk** [comment]
Updated the issue description to reflect the FPWD text.

**Comment by CharlesBelov** [comment]
There is often the use case where one is required to check that one has agreed to the terms of service, privacy policy, or other terms. If the site visitor activates the link to the terms of service, I would expect that the time limit needs to be automatically extended to that which would allow the visitor to actually read the terms of service, privacy policy, or other terms.

**Comment by lseeman** [comment]
New wording proposed:

Where a session can time out and form information that has been submitted by the user can be lost before the task is complete, the user is informed of the length of time that the data is preserved and the length of inactivity that generates the time out, at the start of the task, unless the  user can return to the same point in a task without data loss for a minimum of a 24 hours. 

And we need to make sure simple, understandable language scope  includes timing adjustable messages

**Comment by lseeman** [comment]
change from todays call
   					
 Where data can be lost due to timeouts, users are warned at the start of a process about the length of inactivity that generates the timeout, unless submitted data is preserved for a minimum of a 24 hours.
 
small change from Davids wording in that it alowes for people to preserve the data :
Davids wording:
Where data can be lost due to timeouts that are less than 24 hours,  users are warned at the start of a process about the length of inactivity that generates the timeout

However the task fource can live with iether wording

**Comment by jake-abma** [comment]
Objectively conforming to the tekst as is would be broadly interpretable.

> Loss of data: The user can easily return to the same point in a task...

What is the definition for easy here? Returning to the exact spot on a web page when login in again would solve the ‘returning easily’ but when a process is activated on a certain page and part of a modal with multiple steps and I was logged out on step 4, is this also part of an easy return?

> or via a user-settable option available throughout the task.

How to interpret a “user-settable option” here? As in that I can check a check box on step 3 which says something like: “would you like to save your data after  your session is logged out and you didn’t complete all steps?” Will this comply?

> If the data will only be preserved for a limited time, the user is informed of the length of time that data are preserved at the start of the task.

Adding this option will open up all opportunities to not adhere to all previous text as basically all data is preserved for a limited time (what is the definition for limited here?).  Also do we allow a very short period here and within this time is it still  mandatory to be able to easily return?

I can imagine developers will use this as an escape to leave it as is and not improving the accessibility.
At the third bullet point (Aware: …) the user must already be informed of time outs at the start of the task, do we have to supplement this here with the length of time data is preserved (and thus this doesn’t need to be part of the default message?)

**Comment by jake-abma** [comment]
> Timing adjustable: The function to turn off, adjust, or extend timing is controlled by a simple action, and is labeled with simple, understandable language.

Simple and understandable here is also broadly interpretable and can’t be objectively be determined.

**Comment by jake-abma** [comment]
> Aware: The user is informed of timeout limits at the start of the task, including the length of the warning.

What is expected to be present in the message / information? Only that there’s a timeout at some point or does it have to say after how much time this timeout happens? (If this is the case we can remove the last sentence at the first bullet point)

**Comment by jake-abma** [comment]
> or the user must be given at least 120 seconds to extend the time limit. https://github.com/w3c/wcag21/issues/14#issuecomment-278380985

SC 2.2.1 is already a hard sell for security and although 20 seconds is for lots of people not enough to respond properly, 120 seconds will probably be not accepted as a standard, specially for financial services so exceptions should be defined.

**Comment by jake-abma** [comment]
> Security Exception: Where security may be at risk, a session can time out after 30 minutes of inactivity. Where financial or sensitive information is at risk, the timeout can be shorter. https://github.com/w3c/wcag21/issues/14#issuecomment-278380985

Besides that 30 minutes is a long time for lots of sites, what is sensitive information here? And will this be determined by the web site owner or the user? Also this sentence opens up an opportunity not to change anything.

**Comment by awkawk** [comment]
Suggested re-wording:
For each time limit set by the content where data entered by the user can be lost, the user is advised about the length of inactivity that generates a timeout unless any user-entered data is preserved for at least 24 hours after the timeout.

**Comment by DavidMacDonald** [comment]
I can live [with that](https://github.com/w3c/wcag21/issues/14#issuecomment-299944440). @awkawk

**Comment by lseeman** [comment]
works for me

**Comment by DavidMacDonald** [comment]
The only thing I notice is 

> unless any user-entered data is preserved for at least 24 hours after the timeout

Do we need to add "...is preserved and available to the user ..." 

other wise they may preserve the data on the back end but not repopulate the form.

**Comment by DavidMacDonald** [comment]
How about this? It borrows from [SC 3.3.3 the concept of "is known"](https://www.w3.org/TR/UNDERSTANDING-WCAG20/minimize-error-suggestions.html) 
It addresses [Alex Li's comment](https://www.w3.org/2017/05/09-ag-minutes.html#item06) on the conference call. 

Identify Time Limits: For each time limit set by the content where user-entered data can be lost and the time limit is known, the user is advised about the time limit at the start of the process.

**Comment by Ryladog** [comment]
I do not think we need and the time limit is known language

 

​​​​​* katie *

 

Katie Haritos-Shea 
Principal ICT Accessibility Architect (WCAG/Section 508/ADA/AODA)

 

Cell: 703-371-5545 |  <mailto:ryladog@gmail.com> ryladog@gmail.com | Oakton, VA |  <http://www.linkedin.com/in/katieharitosshea/> LinkedIn Profile | Office: 703-371-5545 |  <https://twitter.com/Ryladog> @ryladog

NOTE: The content of this email should be construed to always be an expression of my own personal independent opinion, unless I identify that I am speaking on behalf of Knowbility, as their AC Rep at the W3C - and - that my personal email never expresses the opinion of my employer, Deque Systems.

**Comment by DavidMacDonald** [comment]
Capturing mailing list item here:

What I often get is "your session is about to time out due to inactivity from this station. if you wish to continue the session press cancel within the next 20 seconds, otherwise press OK"

What if we say something like: 

If the time out message is more than "x" characters, then the warning remains on the page for "y" seconds.

x could be something like 30 characters
y could be something like 1 minute.

**Comment by goodwitch** [comment]
@lseeman can you change the "Suggestion for Priority Level" from "A" to "AA"  in the very first comment at the very top of this issue...so anyone reading this, will know that this is being proposed as a "AA"?

**Comment by jake-abma** [comment]
@goodwitch @lseeman The Proposed Level is AAA, not AA

As the proposed Level is AAA and thus the security objections of extending the message for the respond time will not be applicable anymore I would suggest to still look if we can add this here.

Informing about the Timeouts (and possibly the time you’ll have to extend this / 20 seconds…) but not providing a way to extend this if you’re not able to respond in limited time would be a missed opportunity.

If (20 seconds) security is not the issue and if the default is 20 seconds to respond BUT 40 or 60 or … would also be an option to choose from we solve one of the core issues this SC is about anyway.
