### ISSUE TITLE
Success Criterion 3.1.7 Plain Language (Minimum)

### ISSUE THREAD

**Issue by ysmartin** [w3c/wcag21#149]
I would like to raise two interrelated concerns regarding the current wording of this success criterion, namely, that it is 1) too specific (seeming more like a set of techniques rather than a success criterion) and 2) too English-focused. As a consequence, it goes against one of the acceptance criteria for WCAG 2.1 SCs ("be as broad as possible") and against W3C Internationalization goals. I completely adhere to the rationale for this criterion (I may subscribe the whole description and intent sections in #30); however, I do not support the way how it has been implemented.

In particular:
> **Simple tense.** Use present tense and active voice.

This assumes the English system of grammatical tenses and voices. What about tenseless languages (e.g. Chinese)? Or languages with a middle voice (e.g. Swedish)? And what about other verbal categories such as mood and aspect (in many languages "imperfective" and "subjunctive" are not so exotic as in English, or "conditional" is a tense in its own). As a native Spanish speaker, I am particularly wondering about usual constructions in Spanish e.g. subjectless passive "se" or periphrastic verbal constructions (which convey nuances in tense, aspect or mood).
Even in English, this is not clear enough: Is present continuous accepted or proscribed? Do we consider constructions with modals as kind of periphrastic tenses (e.g. conditional with would)? And what about "going to"? Is reported speech (which changes of tenses) acceptable or shall we use direct speech instead?

Moreover, the exceptions invalidate the very own aim of this SC:
> When a passive voice or a tense (other than present tense) is clearer.
> When describing or discussing past or future events, the present tense is not required.

So, in summary this part of the SC means: "Use active present when it refers to current events and it is the clearest way to express it, otherwise, use past tense when it refers to past events or it is clearer and, well, you may also use passive voice if you aim to say e.g. 'press Help if you get stuck' "

As an alternative, I would suggest that the success criteria recommended:
1) the use of verbal categories (e.g. tense, mood, aspect) that match their principal time values in their respective language. (A counter example would be "In 1492, Columbus sails to the West and discovers America", a so called historical present, where a present tense conveys a past value).
2) the avoidance of archaic or seldom used verbal forms (e.g. simple past in French).
3) the avoidance of complex instructions which require the use of relative tenses. E.g. "Once you have sent the message, and while you are waiting for the answer, but before the time expires..." Well, maybe this is an example of a complicated process, of which the tense usage is only a symptom, but I think the example is clear.
That said, I would not even be happy with this proposed approach, and I would suggest deeper research in the topic and consulting which experts on legibility/readability/intelligibility and linguists in general.

> **Simple, clear, and common words** Use the most common 1500 words or phrases or, provide words, phrases or abbreviations that are the most-common form to refer to the concept in the identified context.

Of course, avoiding jargon is a must for cognitive accessibility (and for usability in general). "Get money" is perhaps easier than "Cash withdrawal". But the use of the most common 1500 words seems to me an arbitrary choice that brings a reminiscence of controlled vocabularies such as that of Special English. (Controlled vocabularies perhaps are not perfect for cognitive accessibility, but we have other problems here.)

We come again with the problem of internationalisation: Does the same figure apply to different languages? The frequency distribution of words in heavily fusional languages differs a lot from that of English (e.g. "go" in English translates into many different words in Spanish depending on gramatical tense, mood, aspect, number and person, roughly speaking). The frequency of stems or lexemes may seem more relevant here (or not?)

Moreover... is a "word" the same in different languages? Think about the distinction between a lexical and a grammatical word. The concept of "word" may not be as useful on the one hand in heavily analytic languages (e.g. Mandarin, where there is no "word boundary" as such), nor on agglutinative languages (German, Turkish, Japanese... where many stems are "glued" together in single words).

Besides, there may be a trade-off between precision and recognition of a word.

And last but not least, nothing is said here regarding polysemic words and homographs (controlled vocabularies such as Basic English usually also recommend using each word with a single meaning, e.g. "close" as in "opposite to open" vs "close" as in "near").

> **Double negatives** Double negatives are not used.

Depending on its meaning, it can be too English-centric (E.g. double negatives are compulsory in many Spanish sentences, What about French which requires a double negative by syntax? Or Esperanto where antonyms use the "mal-" prefix by default?), or it can be too narrow, as the problem may lie on the negation itself ("I'm feeling sick" is clearer than "I don't feel well").

On the other hand, I am missing references to other complex language constructions, and usual constructions whose meaning may be ambiguous. I am thinking about e.g. any referential construction, and specifically anaphoric constructions. E.g. "John told Peter that he was awful, and then he said" (who is each "he"?, this is an intentionally simple example with a high degree of ambiguity)

Regarding exceptions, besides what it has been said above:
> The content will be penalized for not conforming to a given writing style (such as a CV, dissertation, or Ph.D. proposal).

This contradicts the scope of application of the SC ("instructions, labels, navigational elements, and error messages which require a response to continue")

To wrap it up: 1) things one may take for granted in English are completely different in other languages, 2) linguistics is a quite complex cake with many thin layers that seem the same when you eat it, but not when you cook it.

**Edited** to fix some typos and language errors. Now that I re-read it, I think that the objections I have raised above put also in doubt the proper testability of this SC.

**Comment by mbgower** [comment]
@ysmartin. Please see #30 (the original post on Plain Language) for a bunch more comments on this SC.

**Comment by ysmartin** [comment]
@mbgower thank you for the pointer. Although I was aware of the discussion in that thread and I reference it from here; I have filed a new issue according to the instructions in the WCAG 2.1 PWD. There are some aspects in that thread which I have not commented, as I understand they did not make it to the published SC. Anyway, I can comment there instead if you consider it more appropriate than here on a separate issue.

**Comment by FionaHolder** [comment]
@mbgower Off topic for this thread, but I would also appreciate guidance on whether we are supposed to be commenting against the issues for the new SC, or raising new issues as suggested in the PWD. How would you like my concerns to be raised?

**Comment by mbgower** [comment]
> There are some aspects in that thread which I have not commented, as I understand they did not make it to the published SC. Anyway, I can comment there instead if you consider it more appropriate than here on a separate issue.

@ysmartin, I wasn't saying you should put comments in the old thread. I just wanted to ensure you were aware of its existence, as with this new issue, I couldn't see any obvious way it was currently cross-referenced. That may be intentional (see below)!

> I would also appreciate guidance on whether we are supposed to be commenting against the issues for the new SC, or raising new issues as suggested in the PWD. How would you like my concerns to be raised?

@FionaHolder. Here is the guidance on how to participate, that came out in a recent email:

> *Comments*
> 
> To comment, the Working Group requests input be filed as issues at:
>   https://github.com/w3c/wcag21/issues/
> 
> Please raise new issues for your comments, putting each separate topic into a separate issue. If it is not feasible to file issues in this tool, you can also submit comments by email to:
>   public-agwg-comments@w3.org
> 
> The Working Group requests comments on this draft be filed by 31 March 2017. The Working Group plans to publish updated Working Drafts frequently over the course of 2017 to incorporate input received and continued review of proposals.

---

@awkawk and @michael-n-cooper, a few questions:

1. Am I muddying the water by referencing the historical issue thread?
2. Do you want working group members themselves raising new issues against the FPWD criteria?
3. Assuming "yes" to both of those, is it proper that I open new issues for each point I do not feel was addressed with the SC version that was published as draft?

Sorry for these newbie questions on my part. When I see your responses, I'll trim the off-topic material from this thread.

**Comment by awkawk** [comment]
@mbgower: 
1. Muddy or not, these are the waters we have, so I don't think that it is a problem to point out that there is some discussion history elsewhere for context.
2. I would prefer that group members raise issues in the context of the group, but know that this won't always happen. Raising an issue against the FPWD is the right process for public comment and works for a company that has a member on AG WG but wants to add comments as well.
3. If the question is whether to create one monster issue or to break out the points, granular is better. In some cases, such as "here's 50 typos in the FPWD" which will be editorial it is fine to group items.
4. If Fiona or anyone else agrees completely with another issue, commenting on that issue should be sufficient. One might simply put "+1 to this issue".  If two people create identical issues I expect that we will close one and add information to the other to indicate that this was not just one person's comment.

**Comment by FionaHolder** [comment]
Thanks to @mbgower and @awkawk for the clarification. I will raise the couple of comments I have already added to issues as new public comment issues to follow the process better.

**Comment by awkawk** [comment]
@ysmartin Thanks for the comment - the Working Group has not reached consensus on this proposed SC so it is deferred for future consideration.
