### ISSUE TITLE
Should Popup Interference be separate?

### ISSUE THREAD

**Issue by awkawk** [w3c/wcag21#154]
Scott Hollier (http://hollier.info/wcag21draft/):
For the last SC on the list I’m not entirely sure about this one.  The idea is that there’s more control around On Hover and On Focus.  It seems like a logical improvement to On Focus in WCAG 2.0 rather than a standalone SC.

**Comment by diyasur** [comment]
Logical improvement but my only concern is whats the alternative with big information text for increased text options?

**Comment by steverep** [comment]
I think the latest language in the draft for Content on Hover or Focus makes it clear why this criterion is not suitable for merging with SC 3.2.1, On Focus.  The former is about the ability to perceive such content, whereas the latter is about not having unpredictable changes of context when landing on them.

That said, Why should the unpredictable changes of context be limited to focus?  Perhaps we should add hover to 3.2.1, although the argument could be made that focus would be needed anyway to pass 2.1.1.

**Comment by DavidMacDonald** [comment]
> although the argument could be made that focus would be needed anyway to pass 2.1.1.

That's right

**Comment by awkawk** [comment]
Response from WG (sent to Scott's email): 
Scott, this is in response to your comment on the initial draft of WCAG 2.1 related to the Popup Interference success criteria that was proposed. The intent of this SC is to ensure that adjacent content and the new content itself is accessible, whereas the intent of 3.1.2 is related to not unexpectedly changing the user’s context. As a result the group has kept these separate, and we hope that the latest version (now called “content on hover or focus” https://www.w3.org/TR/WCAG21/#content-on-hover-or-focus) helps make this more clear.
