### ISSUE TITLE
Single-key shortcuts

### ISSUE THREAD

**Issue by awkawk** [w3c/wcag21#155]
Scott Hollier (http://hollier.info/wcag21draft/):
 The statement for this SC is ‘Single-character shortcuts are not the only way activate a control, unless a mechanism is available to turn them off or remap them to shortcuts with two or more characters.’  If I understand the concept correctly it seems like a good idea but the language here seems a bit clunky and it’d be good to tidy up the wording.

**Comment by DavidMacDonald** [comment]
How about:

>Single-character shortcuts are not the only way activate a control, unless a mechanism is available to replace them for shortcuts that use two or more characters.

**Comment by DavidMacDonald** [comment]
fixed in commit
> Single-character shortcuts are not used to activate a control, unless a mechanism is available to replace them with shortcuts that use two or more characters.

**Comment by awkawk** [comment]
The language has been revised since this comment was made, and is in the editor's draft as the "pointer gestures" SC (http://rawgit.com/w3c/wcag21/master/guidelines/index.html#pointer-gestures)
