### ISSUE TITLE
1.3.4 Support Personalization (minimum) - Not clear what developers are required to do

### ISSUE THREAD

**Issue by FionaHolder** [w3c/wcag21#161]
http://myaccessible.website/2017/03/wcag-2-1-review-1-3-4-support-personalization-minimum/

Are developers expected to just provide attributes / markup to make context clear to potentially support personalization features provided by a user agent, or are they also supposed to be including some form of personalization library within their application for the user to make configuration changes?

It's not immediately clear to me what developers are responsible for here. Is it like ARIA, where we add attributes and let user agents interpret those, or is there more work involved in user settings?

My main concern with this criterion is that the standardized technique for achieving this in HTML is not mature enough for its inclusion, in my opinion. The [semantics proposal](https://w3c.github.io/personalization-semantics/) is still just an editors draft and therefore not endorsed by the W3C. I also believe that the technique for HTML implementation should explicitly reference these semantics and not leave it open to there being multiple standards. This makes it clearer for developers and testers.

**Comment by awkawk** [comment]
@FionaHolder The Support Personalization (minimum) SC has been substantially modified in response to your feedback and that of others. Please review the latest version (renamed "purpose of controls": https://www.w3.org/TR/WCAG21/#purpose-of-controls) - we would appreciate your thoughts on the changed SC.
