### ISSUE TITLE
3.3.8 Undo - Not clear how this differs from 3.3.4

### ISSUE THREAD

**Issue by FionaHolder** [w3c/wcag21#163]
http://myaccessible.website/2017/03/wcag-2-1-review-3-3-8-undo/

3.3.8 is easy to understand at first glance, but I think there is too much room for interpretation. It makes it very clear that in a multi-stage form, you must offer the ability to go back. What isn't clear is whether Undo must be available once the form has been submitted.

We already have, in WCAG 2.0, Success Criterion 3.3.4: Error Prevention, which includes the fact that submissions should be reversible and users must have the opportunity to **review** submissions. This is a Level AA criterion, and so I'm not sure what the addition of this new 3.3.8 criterion is trying to solve, apart from putting some onus on Level A sites. 

Also, this has none of the caveats that make 3.3.4 possible, like allowing a user to phone up and cancel an order. ​

It needs clarifying how this differs from the existing criterion for Error Prevention.

**Comment by awkawk** [comment]
Thanks for the comment - the Working Group has not reached consensus on this proposed SC so it is deferred for future consideration.
