### ISSUE TITLE
Some links to definitions missing on draft

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/wcag21#168]
The definition terms are not linked in the FPWD for [accidental activation](https://rawgit.com/w3c/wcag21/change-of-content_ISSUE-2/guidelines/#accidental-activation). Two of the terms are correctly listed in glossary, but there are no links to them in the SC text. One term needs to be added. It was approved for the draft, so it's a little bug that it's not in.

- up-event
- [Platform assistive technology that remaps touch gestures](https://rawgit.com/w3c/wcag21/change-of-content_ISSUE-2/guidelines/#dfn-platform-assistive-technology-that-remaps-touch-gestures)
- Single Pointer Activation (Needs to be added)

Single Pointer Activation: One point of contact with the screen (vs. multi-touch). A pointer can be any point of contact on the screen made by a mouse cursor, pen, touch (including multi-touch), or other pointing input device. This model makes it easier to write sites and applications that work well no matter what hardware the user has. For scenarios when device-specific handling is desired, this specification also defines properties for inspecting. Pointer Events (REC) Pointer Events Level 2 (ED)] 

This Issue #65  and the links to Up-Event and Single Pointer Activation definitions are dead in that issue as a result of the missing links in FPWD

**Comment by michael-n-cooper** [comment]
WG participants now can fix editorial issues like this. To add a definition link, find the branch in which work on the SC is meant to happen, i.e., accidental_activation_ISSUE-65 for this example. In guidelines/index.html, uncomment the lines that load the terms, and in the SC file put an empty <a> tag around the usages of the terms - the script turns them into proper links.

**Comment by awkawk** [comment]
How about we just link "pointer" and then add a line in the pointer definition that indicates that pointers can be single-touch or multi-touch?

**Comment by awkawk** [comment]
Fixed in editor's draft.
