### ISSUE TITLE
Why do all the links seem to have "change-of-content_ISSUE-2" in the address

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/wcag21#169]
For Instance
`https://rawgit.com/w3c/wcag21/change-of-content_ISSUE-2/guidelines/#dfn-single-character-shortcut`

**Comment by DavidMacDonald** [comment]
Ohh, it's the branch... and every branch has all of the SCs in it... got it.

**Comment by joshueoconnor** [comment]
It looks like thats a version on a particular branch that you are looking at. For example if you change 'change-of-content_ISSUE-2' you'll see the master branch version. [1]

[1] https://rawgit.com/w3c/wcag21/master/guidelines/#dfn-single-character-shortcut
