### ISSUE TITLE
Success Criterion 1.4.13 Printing

### ISSUE THREAD

**Issue by johnfoliot** [w3c/wcag21#173]
The current proposed SC states:

> If content can printed, the following are true:
> Resized:
> Content can be resized up to 200% without loss of content or **_functionality_**

During an internal review of this SC, it was noted that due to the nature of transitioning from "web-based" to print, any interactive functionality would be lost, including both hyperlinks as well as when hyperlinks are indicated by text alone (eg. "...the <a href &#61; '"">results< /a> can be found at..." versus "...the results can be found at <a href &#61; "">https://url_to_results< /a>..." - with the actual URL specified in text on the html document)

Because of this, sending any web content to "Print" will automatically mean the content is losing functionality, so this requirement is likely inappropriate as stated.

**Comment by awkawk** [comment]
Thanks for the comment - the Working Group has not reached consensus on this proposed SC so it is deferred for future consideration.
