### ISSUE TITLE
Requirement for PDF forms to be Interactive

### ISSUE THREAD

**Issue by gabicohen** [w3c/wcag21#175]
Currently the is no requirement for PDF forms that are downloaded from WEB sites for the purpose of filling up and sending back to be interactive. It means that one has to print the file and fill it up on a paper. This method is not accessible for blind people because they cannot see the paper (so they cannot fill it up be themselves). 

I propose the make such fileד interactive so blind people will be able to fill them up as well as digitally sign them using a computer (with assistive technology, i.e. screen readers).

**Comment by DavidMacDonald** [comment]
Proposed Response:
Thanks you for your comment. WCAG applies to content at a URL. We understand fillable forms are more accessible to screen reader users.  If content is fillable, then it has to meet the Success Criteria that apply to fillable forms (1.3.1, 4.1.2 etc). If the form is static then there are no additional requirements. WCAG does not apply to content after it is no longer at URL.

If we required all PDFs on WCAG conforming sites to be fillable, it would require a normative change to our definition of Web Content.

This update is a dot release (2.1) and we can't make that kind of a change in this version. We can revisit this issue in the next major release of WCAG, currently called "Silver" depending on the state of fillable PDF forms at that time, and considering any new definition of content that may be used in that standard.

**Comment by steverep** [comment]
> If we required all PDFs on WCAG conforming sites to be fillable, it would require a normative change to our definition of Web Content.

I don't agree with this.  We already consider PDF a web technology and have techniques for it and there's no need for a change to 2.0 to accomplish this.  I think we ought to mark this down for consideration in possible future releases of WCAG as a potential new success criterion.  In very plain language, we'd want an SC which says: "If the technologies being used can have interactive forms, then forms should be able to be filled out without printing."  I'm sure there would be a lot of discussion on exceptions and different UI components, but this could be done.  Unfortunately we're past the point of new SC for 2.1.

**Comment by michael-n-cooper** [comment]
I don't think we will ever be able to require that PDF forms always be fillable, as it goes outside our web scope. We can recommend it and explain why it's more accessible. But mandating for any technology something like "if technology supports feature X you must use feature X and then follow WCAG for that feature" will be seen as a big overreach, there are lots of reasons people don't use all available features of the technologies they have chosen. And a requirement for something that seems obvious to us like PDF forms could be the start of a slippery slope where we are asked to start considering that for all sorts of features and technologies, and we really shouldn't go there.

**Comment by steverep** [comment]
> I don't think we will ever be able to require that PDF forms always be fillable, as it goes outside our web scope. 

I really need help understanding why this is outside the scope of the web.  WCAG 2.0 currently has over 20 documented PDF techniques, including several on creating accessible forms.

> We can recommend it and explain why it's more accessible. But mandating for any technology something like "if technology supports feature X you must use feature X and then follow WCAG for that feature" will be seen as a big overreach, 

I'm very confused by this statement.  You simply cannot conform to WCAG without relying on technologies to have certain features, and authors to use those features (e.g. if you want a heading or a table, mark it up properly with the technology's feature).

> there are lots of reasons people don't use all available features of the technologies they have chosen. And a requirement for something that seems obvious to us like PDF forms could be the start of a slippery slope where we are asked to start considering that for all sorts of features and technologies, and we really shouldn't go there.

In the case of PDF forms that are not designed to be filled electronically, I'd venture to say that the most common reason is that the author had no idea how to do it properly and did not consider impact to people with disabilities.  We create exceptions for valid reasons.

To the point of a response though, this argument can be had later since we cannot support any new criteria at this time.  However, I would like to see us keep it for future consideration rather than dismissing it as impossible.

**Comment by steverep** [comment]
This has been [recorded for future consideration on the AGWG wiki](https://www.w3.org/WAI/GL/wiki/Potential_Accessibility_Guidelines).
