### ISSUE TITLE
Success Criterion 1.4.13 Printing

### ISSUE THREAD

**Issue by kvlville** [w3c/wcag21#176]
It’s not clear what method is being used to resize the web page; user can resize the web page from the browser window or resize the web page from the print settings. Is it assumed that the user resizes/scales the web page from the print settings? There are multiple techniques to resize the web page other than the two mentioned above.

> Content can be resized up to 200% without loss of content or **functionality**

What is meant by “_loss of functionality_” when printing a web page?

**Comment by awkawk** [comment]
Thanks for the comment - the Working Group has not reached consensus on this proposed SC so it is deferred for future consideration.
