### ISSUE TITLE
Success Criterion 3.1.7 Plain Language (Minimum)

### ISSUE THREAD

**Issue by kvlville** [w3c/wcag21#177]
The requirements needed to meet this SC are all good and relevant.

However, the requirement “_Simple, clear, and common words_” might be confusing and leaves too much room for interpretation. It seems that meeting this specific requirement can be extremely laborious. For a reviewer it might be challenging to determine if the word or phrase is actually the most common word or phrase. This should be more specific and more clear how to meet this requirement.

> context and a context specific word frequency list (and glossary) has been identified in an accessibility statement or other known technique
A word frequency list has to be generated from at least 1000 sources from the same context.

> lists of a language's words grouped by frequency of occurrence within some given text corpus
Word lists should also give the meaning of the usage.

How is it possible to do this in practice?

**Comment by FionaHolder** [comment]
I was going to raise this myself, but to avoid creating a duplicate issue, I agree with this concern.

Especially as it includes phrases, it leaves it pretty open to interpretation as to where we would get the data from. It does make it the kind of task that is best verified by automated means with manual intervention, which isn't a bad thing in itself. It would be pretty tedious and time consuming to verify this one entirely manually.

**Comment by lseeman** [comment]
refrencing this comment  #30

**Comment by awkawk** [comment]
Thanks for the comment - the Working Group has not reached consensus on this proposed SC so it is deferred for future consideration.
