### ISSUE TITLE
Microsoft comment on Interruptions

### ISSUE THREAD

**Issue by alexswli** [w3c/wcag21#182]
Definition of easily available:

a. We cannot give GPII a blanket endorsement as whatever they end up doing is the very definition of "easily available".  If GPII implements something that is objectively demonstrable to meet a threshold of "easily available", they can be used as an example.  But GPII or any other organization for that matter can never be cited as the definition of a technical term.

b. It is indeterminably as to which part of ISO 9241-112 applies here.

c. It is indeterminably as to how the second bullet from "easily available" applies here.

Clarity of text:

a. It is unclear as to what constitutes as an interruption or user initiated change of content.  Are autofill, spell check, or auto suggest considered user initiated?  Does an indicator showing the number of unread message or time of day count as an interruption or non-user initiated change of content?

Implementable:

a. There ought to be real time and essential exceptions, as with WCAG 2.2.1

b. The appropriate way to implement this is to respect the Quiet hour function in OS.  But browsers do not rely such info yet.  It does not seem to make sense to impose this on web content authors until we can get the browsers to rely the info and techniques exist for the content authors.

**Comment by lseeman** [comment]
we have better wording that address this issue at https://www.w3.org/WAI/GL/wiki/2.2.7_Revision

**Comment by awkawk** [comment]
Official WG response: Thank you for your comment. This SC has been removed from the draft and will be able to be considered in a future revision.
