### ISSUE TITLE
Microsoft Comment on Support Personalization

### ISSUE THREAD

**Issue by alexswli** [w3c/wcag21#183]
Definition of standardized technique:

a. I don't think it is possible for web content to gain direct access to native platform APIs.

b. WCAG techniques are not normative.  But this definition effectively make them normative.

Helpful:

a. Personalization is not the only reason to make content programmatically determinable.  We recommend the removal of "so that personalization is available".

b. This SC ought to merge with WCAG 4.1.2.

**Comment by awkawk** [comment]
@alexswli This SC has changed substantially and the latest version is available at https://www.w3.org/TR/WCAG21/#purpose-of-controls. As your comments relate to the previous version, closing this issue.
