### ISSUE TITLE
Microsoft Comments on Adapting Text

### ISSUE THREAD

**Issue by alexswli** [w3c/wcag21#186]
Implementable:

a. This SC is more suitable for the browsers than for content authors.  As long as desktop browsers has the functionality, I think this is an unnecessary requirement for content authors. 

b. Note that this does not work for mobile browsers today.  But that is not the fault of content authors.  Given that, it is better to not put the load on content authors.

2. Clarity of Text:

a. The SC is about text as the title and SC suggest.  But it is not scoped to text content as it is currently structured. As such, one can mistakenly think that it applies to images of text.  Please scope this SC properly.

**Comment by WayneEDick** [comment]
Authors who code flexible pages will have no problem with these changes. A
browser cannot fix an inflexible page.

On Thursday, March 30, 2017, alexswli <notifications@github.com> wrote:
> Implementable:
>
> a. This SC is more suitable for the browsers than for content authors. As
long as desktop browsers has the functionality, I think this is an
unnecessary requirement for content authors.
>
> b. Note that this does not work for mobile browsers today. But that is
not the fault of content authors. Given that, it is better to not put the
load on content authors.
>
> Clarity of Text:
>
> a. The SC is about text as the title and SC suggest. But it is not scoped
to text content as it is currently structured. As such, one can mistakenly
think that it applies to images of text. Please scope this SC properly.

**Comment by alastc** [comment]
> a. This SC is more suitable for the browsers than for content authors. As long as desktop browsers has the functionality, I think this is an unnecessary requirement for content authors.

This is not the case, at least not to the extent needed for support. You can apply these settings via a browser (some in settings, some need an extension or bookmarklet), but there are various things authors can do to prevent those from taking effect in a meaningful way.

The aim is that authors use techniques that allow for adaptation, so whilst the test is to apply adaptations, the techniques are things for authors.

> b. Note that this does not work for mobile browsers today. But that is not the fault of content authors. Given that, it is better to not put the load on content authors.

This can be applied in mobile browsers, it is more limited but it is possible for some sites using bookmarklets. Also, the techniques should align with things that help 'reader mode' in safari. (I assume there are equivalents on android.)

Also, should we deny people with low vision this possibility on desktop because mobile doesn't support it? (As well.) The techniques & failures will all be about the content, not the device used.

> As such, one can mistakenly think that it applies to images of text.

There is an exception for that, probably added after you looked:

> Captions and images of text are exempt.

**Comment by mraccess77** [comment]
It is my view that there are things the author can do to break this such as using fixed sized containers that hide overflowed content.  So this goes beyond what the browser can overcome.

**Comment by lauracarlson** [comment]
Hi @alexswli ,

Alex wrote:

> Implementable:
> 
> a. This SC is more suitable for the browsers than for content authors. As long as desktop browsers has the functionality, I think this is an unnecessary requirement for content authors.
> 
> b. Note that this does not work for mobile browsers today. But that is not the fault of content authors. Given that, it is better to not put the load on content authors.
> 
> 2. Clarity of Text:
> 
> a. The SC is about text as the title and SC suggest. But it is not scoped to text content as it is currently structured. As such, one can mistakenly think that it applies to images of text. Please scope this SC properly.

Thank you for your comment.

The latest SC text, which the AG Working Group has agreed to accept into editors draft for public comment is:

> If the technologies being used allow the [user agent](https://www.w3.org/TR/WCAG20/#useragentdef) to [adapt](https://rawgit.com/w3c/wcag21/adapting-text_ISSUE-74-78-79/guidelines/terms/21/adapt.html) [style properties](https://rawgit.com/w3c/wcag21/adapting-text_ISSUE-74-78-79/guidelines/terms/21/style-properties.html) of [text](https://www.w3.org/TR/WCAG20/#textdef), then no loss of [essential](https://www.w3.org/TR/WCAG20/#essentialdef) content or functionality occurs by adapting all of the following:
> 
> 1. line height (line spacing) to at least 1.5 times the font size
> 2. spacing underneath paragraphs to at least 2 times the font size
> 3. letter spacing (tracking) to at least 0.12 times the font size
> 4. word spacing to at least 0.16 times the font size
> 
> Note: Examples of text that are typically not affected by [style properties](https://rawgit.com/w3c/wcag21/adapting-text_ISSUE-74-78-79/guidelines/terms/21/style-properties.html) are open [captions](https://www.w3.org/TR/WCAG20/#captionsdef) and [images of text](https://www.w3.org/TR/WCAG20/#images-of-textdef), which are not expected to adapt.
> 
> Editor's note: The Working Group seeks to include overriding text color, background color, and font-family as part of this SC, but is not yet able to identify a way to do so that is sufficiently testable.

It has a scoping clause in place and explains images of text that images of text are not expected to adapt. Does does this text alleviate your concerns? 

Thanks again,
Laura

**Comment by awkawk** [comment]
@alexswli The comments you raise have been addressed in the latest version: https://www.w3.org/TR/WCAG21/#adapting-text - closing this issue.
