### ISSUE TITLE
Microsoft comment on Device Sensors

### ISSUE THREAD

**Issue by alexswli** [w3c/wcag21#188]
Clarity of text: 
a. This SC is largely duplicative of WCAG 2.1.1.  Adding another SC to demand the same creates friction to conformity and confusion.  Please consider merging this SC with 2.1.1.

**Comment by awkawk** [comment]
@alexswli Closing this comment since the comment is noted and the working group has a work item to figure out the connection/relationship/merger between the current Device Sensors SC and 2.1.1.
