### ISSUE TITLE
Microsoft comment on Speech Input

### ISSUE THREAD

**Issue by alexswli** [w3c/wcag21#189]
Implementable:

a. Please investigate techniques without relying on testing with speech recognition software, then provide specific and explicit requirement instead of demanding all content authors to constantly keep track of how every speech recognition application works.

**Comment by mraccess77** [comment]
The intent of the Speech Input SC is to make sure that speech input users can voice the name of controls -- the accessible name of a control should match the visual label to assist in activating it by voice and not accidentally activating something else.

**Comment by awkawk** [comment]
@alexswli This SC has been substantially changed in the latest version (https://www.w3.org/TR/WCAG21/#accessible-name) - thank you for your comment.
