### ISSUE TITLE
Microsoft Comment on Timeouts

### ISSUE THREAD

**Issue by alexswli** [w3c/wcag21#190]
Testable: 

a. No objective and reliable way for testers or content authors to conclude what is easy, simple, or understandable.

Implementable:

a. There should also be a real-time event and essential exceptions.  For example a ticket seller cannot predict when a concert will sell out and thus invaliding the activity.  Please apply similar exception from 2.2.1.

Clarity of Text:

a. It is implicit that this SC can only apply to situations where unique user identifications can reliably be tracked.  Please make it explicit.

**Comment by lseeman** [comment]
#14

**Comment by awkawk** [comment]
@alexswli This SC has been substantially changed in the latest version (https://www.w3.org/TR/WCAG21/#timeouts) - thank you for your comment.
