### ISSUE TITLE
Microsoft comment on Animation from Interactions

### ISSUE THREAD

**Issue by alexswli** [w3c/wcag21#191]
Clarity of text: 

a. It is unclear as to whether the "AND" and "OR" in the definition of significant animation are intentional.  The propose test does not clarify because there's no mention of testing for "synchronization with user action".

b. The end of the SC "while still performing the same action" appears to be placing a time dimensional boundary around the user doing something--ie the SC does not apply when the user is not doing something.  It is unclear whether it is intentional.

**Comment by steverep** [comment]
@alexswli, I had brought up your issue (b) shortly before FPWD, but it did not make it in the draft.  My reading/recommendation was that there should be no time-dependence, and suggested new wording as follows:

> User interactions do not trigger significant animations which are not an essential part of the action, {unless | except where] a mechanism is available to pause, stop, or hide such animations [when performing the same action].

Please see my recent comment in issue #18 for full context.  Does this address part (b) of Microsoft's comment?

**Comment by awkawk** [comment]
@alexswli This SC has been changed in ways that we believe address your comment in the latest version (https://www.w3.org/TR/WCAG21/#animation-from-interactions) - thank you for your comment.
