### ISSUE TITLE
Microsoft comment on Pointer inputs with additional sensors

### ISSUE THREAD

**Issue by alexswli** [w3c/wcag21#194]
Helpfulness:

The proposed SC is a little too sweeping as additional input such as pressure is essential for scenarios such as painting and calligraphy. Similar to 2.1.1, which allows keyboard exception where the path is important, we ought to provide exception for underlying function that requires input beyond x y coordinates.

**Comment by detlevhfischer** [comment]
For reference:
This is a comment on issue [#66 Pointer inputs with additional sensors](https://github.com/w3c/wcag21/issues/66)

**Comment by DavidMacDonald** [comment]
+1 on new language

**Comment by Ryladog** [comment]
+1

 

​​​​​* katie *

 

Katie Haritos-Shea 
Principal ICT Accessibility Architect (WCAG/Section 508/ADA/AODA)

 

Cell: 703-371-5545 |  <mailto:ryladog@gmail.com> ryladog@gmail.com | Oakton, VA |  <http://www.linkedin.com/in/katieharitosshea/> LinkedIn Profile | Office: 703-371-5545 |  <https://twitter.com/Ryladog> @ryladog

NOTE: The content of this email should be construed to always be an expression of my own personal independent opinion, unless I identify that I am speaking on behalf of Knowbility, as their AC Rep at the W3C - and - that my personal email never expresses the opinion of my employer, Deque Systems.

**Comment by awkawk** [comment]
@alexswli Thanks for the comment - the Working Group has not reached consensus on this proposed SC so it is deferred for future consideration.
