### ISSUE TITLE
Microsoft comment on Touch with Assistive Technology

### ISSUE THREAD

**Issue by alexswli** [w3c/wcag21#195]
Implementable:

Similar to the proposed SC on Speech Input, this SC is placing a very high burden on content authors to know and work around the behavior every AT in the market.  If we have something specific that we want content authors to do, let's map that out.  Otherwise, this SC appears misplaced.

**Comment by DavidMacDonald** [comment]
This only applies to "Platform AT that remaps keystrokes". That's a fancy way of saying the "screen reader that ships with the OS." 

- VoiceOver on iOS, and MacOS
- TalkBack with Android
- Narrator with Windows

We should also add a clause that gives an exception for a bug in the Screen Reader, so the author is not responsible for work arounds.

**Comment by mraccess77** [comment]
Personally I don't feel this is about knowing all the details of all AT but instead knowing that you can't rely on assistive technology users on mobile having access to a robust way to use the keyboard interface.  For example, on iOS w/ Safari it is not possible to get keyboard based ARIA combo boxes to change values when they rely on keyup events from up and down arrow.

**Comment by patrickhlauke** [comment]
at a base level, i would say it boils down to:
- things need to be focusable
- things can't rely on gestures other than activation (no swipes, multitouches, etc as they're always intercepted by touch AT unless user does a "passthrough" gesture, where available)
- things can't rely on user being able to arbitrarily hit a keyboard key (this nuance differentiates it from the regular 2.1.1 Keyboard, where this *would* be acceptable to pass)

**Comment by awkawk** [comment]
@alexswli Thanks for the comment - the Working Group has not reached consensus on this proposed SC so it is deferred for future consideration.
