### ISSUE TITLE
Microsoft comment on Plain Language

### ISSUE THREAD

**Issue by alexswli** [w3c/wcag21#197]
Testable:

a. The proposed SC is subjective.  Content authors will not be able to meet them with any degree of certainty or reliability.

Clarity of text:

a. This proposed SC contains a large number ambiguous terms without definitions--leaving too much room for interpretation.

b. It is too difficult to parse out the various requirements and exceptions in the text.

c. The SC text fails to meet the requirements it is trying to imposed on other content authors.

Implementable:

a. On top of the subjectivity, ambiguity, and complexity, this SC is impossible to implement in large scale given the large number of content authors in a democratized society.

b. Along the line of democracy, this SC has serious conflict with freedom of speech.  Imposing it on content authors will put the legitimacy of WCAG in deep trouble.

Helpfulness:

a. I can see that the SC is well intended and that some of its ideas can be of help to comprehension.  But we need to study the effectiveness of these ideas.  Some of them seem a bit arbitrary.

b. There is a great deal of language dependency where the SC does not make sense or seems inapplicable.  

c. Understand that imposing all these requirements to content authors is not feasible.  There may be ways where we can make content more comprehensible with AI via authoring tools, browsers, or OS.  I am open to discussion on experimentations and innovation.

**Comment by awkawk** [comment]
Thanks for the comment - the Working Group has not reached consensus on this proposed SC so it is deferred for future consideration.
