### ISSUE TITLE
Microsoft comment on Manageable Blocks

### ISSUE THREAD

**Issue by alexswli** [w3c/wcag21#198]
Clarity of text:

a. We have similar reservation on this SC as with the Plain Language SC.  But we acknowledge this SC has less ambiguity and less complexity.

Helpfulness:

a. Likewise as Plain Language SC, I am open to finding ways to experiment and research.  But this is not an imposition that should go on content authors' shoulders.

**Comment by awkawk** [comment]
@alexswli Thanks for the comment - the Working Group has not reached consensus on this proposed SC so it is deferred for future consideration.
