### ISSUE TITLE
Microsoft comment on Accidental Activation

### ISSUE THREAD

**Issue by alexswli** [w3c/wcag21#199]
Can you provide code example of how web content can fail this SC?

**Comment by DavidMacDonald** [comment]
Maybe @patrickhlauke would like to step in with a code example.

**Comment by patrickhlauke** [comment]
for regular controls (i.e. not situations that have been exempted, where activating immediately is required - such as games, piano applications, etc), binding to down events, such as
```
blah.addEventListener('mousedown', ...);
blah.addEventListener('touchstart', ...);
blah.addEventListener('keydown', ...);
blah.addEventListener('pointerdown', ...);
```
instead of up events

```
blah.addEventListener('mouseup', ...);
blah.addEventListener('touchend', ...);
blah.addEventListener('keyup', ...);
blah.addEventListener('pointerup', ...);
```

or even just

```
blah.addEventListener('click', ...); /* leave it up to the UA's default click handling */
```

**Comment by patrickhlauke** [comment]
further potential failure: reacting to over/enter/focus, or even out/leave/blur (again, when not essential to the activity)

```
/* bad examples, lead to immediate (and accidental) activation */
blah.addEventListener('mouseover', ...);
blah.addEventListener('mouseenter', ...);
blah.addEventListener('mouseout', ...);
blah.addEventListener('mouseleave', ...);
blah.addEventListener('focus', ...);
blah.addEventListener('blur', ...);
blah.addEventListener('pointerover', ...);
blah.addEventListener('pointerenter', ...);
blah.addEventListener('pointerout', ...);
blah.addEventListener('pointerleave', ...);
```

(e.g. imagine a button which activates / triggers a behavior once the user so much as moves the mouse over it)

**Comment by patrickhlauke** [comment]
and to clarify: this is all specifically about "activation" (i.e. triggering a particular action, such as submitting a form, loading a new page/content, etc). it does not mean authors should not be allowed to bind to anything other than up or click events. by all means react to focus/blur, pointerover, etc (e.g. to open/close an additional dropdown menu, display a tooltip, etc).

**Comment by patrickhlauke** [comment]
i suppose this is related (when it comes to actually loading / navigating to a new page or similar) to current WCAG 2.0 3.2.1 On Focus / 3.2.2 On Input / 3.2.5 Change on Request,

**Comment by mraccess77** [comment]
I've used a number of web pages where I pinch zoom in and drag my one finger around the screen to read the page and as I do the content gets triggered to move to a new page because it is listening to a touch start event.

**Comment by awkawk** [comment]
@alexswli Closing as this was answered 5 months ago.
