### ISSUE TITLE
New SC Proposal: Programmatic notification is provided for each change in content that indicates an action was taken or that conveys information

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/wcag21#2]
# Current versions of SC and Definitions
- [SC for viewing](https://rawgit.com/w3c/wcag21/change-of-content_ISSUE-2/guidelines/sc/21/change-of-content.html) | [SC for editing](https://github.com/w3c/wcag21/blob/change-of-content_ISSUE-2/guidelines/sc/21/change-of-content.html)
- [Change of Content definition for viewing](https://rawgit.com/w3c/wcag21/change-of-content_ISSUE-2/guidelines/terms/21/change-of-content.html) | [Change of Content definition for editing](https://github.com/w3c/wcag21/blob/change-of-content_ISSUE-2/guidelines/terms/21/change-of-content.html)
- [primary purpose of the page definition for viewing](https://rawgit.com/w3c/wcag21/change-of-content_ISSUE-2/guidelines/sc/21/primary-purpose-of-the-page.html) | [primary purpose of the page definition for editing](https://github.com/w3c/wcag21/blob/change-of-content_ISSUE-2/guidelines/sc/21/primary-purpose-of-the-page.html)
- [SC in full draft guideline](https://rawgit.com/w3c/wcag21/change-of-content_ISSUE-2/guidelines/#change-of-content)

# SC Short Name

Change of content
# SC Text

Programmatic notification is provided for each change in page content unless one or more of the following is true:  <br />

1. There is a programmatically determinable relationship between the new content and the control that triggers it;
2. The user has been advised of the behavior before using the control;
3. The change in content is not a result of a user action and not related to the the primary purpose of the page.

Editor's Note for next draft: "The working group is seeking input to account for situations where there is frequent, or constant updating."

# Suggested Priority Level

Level AA
# Related Glossary additions or changes

- Change of content: changes made to a web page after it has been delivered to the user agent, whether or not initiated by the user
- primary purpose of the page: If removed, the page would loose it's meaning or main reason for existing.

# What Principle and Guideline the SC falls within

Principle: Perceivable<br />
3.2

# Description (Intent)

This Success Criteria is intended to help users of assistive technology be aware of changes that many users can easily see and understand. 
There are a number of cases where content changes on a page after it is loaded. Users who are blind or have low vision that rely on a screen reader may have trouble knowing that information on a page changed. They may be working on the part of the page which is not near where changes have occurred on a page. It may be on a part of the web page that they have already read and wouldn't consider reviewing that part of the page for unannounced changes. 

These messages would be very short in nature, such as:
- "Your shopping cart has been updated, 5 items"
- "Your form was successfully submitted."
- "There are 5 results for your search"
- "There are 3 errors on this form"
- "Scores updated"
- "content loading" (when a busy indicator is onscreen)

Examples of situations where this type of notification would be appropriate include:
<ul>
 <li>Interactive controls may change the page based on a users selection</li>
<li> Filter / sort selections of data already displayed on page add/remove content</li>
<li>Additions and subtractions to/from a cart</li>
<li>A notification that 'support by chat' is available for this task at hand, or</li>
<li>Results of form submission when they are displayed on same page</li>
<li>A global error message placed above the form saying "form submission failed etc." or a thank you message after completion of a multi-step process, </li>
<li>On switching from grid view to list view, </li>
<li>In data table when sort column is changed, </li>
<li>On selecting a different pagination link</li>
<li>When a graphical spinning "busy" signal notifies visual users. </li>
</ul>

<p>Dynamic changes to a page sometimes cause the page to become inactive for a period of time while it is being updated. Users of assistive technology may think the page has crashed and may loose their work if they either reload the page or leave the page thinking the browser crashed. This notification will ensure they are aware that something is happening in the background, the way that sighted users are aware when they see a spinning icon or the words "loading". If there is no such visual indication there is no requirement in the Success Criterion to provide programmatic notification, only when there is a visual notification, is there a requirement to make that notification also programmatic. This is not about the initial wait to load a new page. Those are announced to screen readers.</p>

**Note:** SC 4.1.2 covers notification of changes in content that are a result of a change in the state of a control, such as selecting a new Tab in a tabbed interface, opening and closing a menu, clicking a link or button that  opens up a dialog or tooltip.  The text of 4.1.2 is "... states, properties, and values that can be set by the user can be programmatically set; and notification of changes to these items is available to user agents, including assistive technologies."
# Specific Benefits of Success Criterion 

Users of assistive technology will know what changed on the page, and will be able to make decisions based on that information. 
## Benefits
- Users who are blind will know if a shopping cart was successfully updated, or if form was successfully submitted, or if there were errors on their form.
- Helps people with visual disabilities, cognitive limitations, and motor impairments by reducing the chance that a control will be accidentally activated or action will occur unexpectedly.
- Individuals who are unable to detect changes on the page will be able to know what people who can see those changes know.
## Justification and Evidence

This issue is currently a best practice recommended by most WCAG evaluators, and most evaluators have come across situations where a screen reader user became confused because something changed on the page that they were unaware of. There is a long thread on the mail archives which started here: https://lists.w3.org/Archives/Public/w3c-wai-gl/2016AprJun/0808.html. The current wording is a result of those discussions and has good momentum from working group members on the list.

There was an issue which filed against WCAG for WCAG next. See Issue 12 here https://www.w3.org/WAI/GL/wiki/Post_WCAG_2_Issues_Sorted 
## Testability

This can be tested programmatically or functionally. In the code, identify elements that show/hide content etc,  and ensure they have programming that exposes the user to notifications about this new data. Functionally, a screen reader can be run while the page is updating to determine changes to the page are announced to the user.
### Related Resources

This is also in the Pearson guideline 5 http://wps.pearsoned.com/accessibility/115/29601/7577872.cw/index.html 

COGA has a similar notification SC which is a little wider currently. https://rawgit.com/w3c/coga/master/extension/rapid-and-direct-feedback.html
## Techniques
- Using aria-live to notify a user of changes in content<br />

### possible narrowing of scope to user initiated changes
Editor note: we are seeking input about whether to limit this success criteria to user initiated changes by inserting the word "user initiated" before the word "change" and removing the last bullet.Editor note: we are seeking input about whether to limit this success criteria to user initiated changes by inserting the word "user initiated" before the word "change" and removing the last bullet.

**Comment by LivioMo** [comment]
There is a situation where WCAG 2 are difficult to understand and/or test: JS scripts not available for any reason. Some technicians don't try pages with JS disabled, so if a content disappear they don't see and the page is nominee accessible, but is not true...

**Comment by awkawk** [comment]
@DavidMacDonald Is this still covered by M15? (doesn't seem to be)

**Comment by WilcoFiers** [comment]
> There are more than x notifications per minute.

You'll still need to fill this in.

**Comment by DavidMacDonald** [comment]
This needs an MAFT Label.

**Comment by jnurthen** [comment]
Wouldn't this (as written) require that an advertisment on a page which animates would need to provide notification? If so we need to write something to exclude that case - maybe limit this to content which is related to the primary purpose of the page?

**Comment by DavidMacDonald** [comment]
Responding to James
5. The new content is not related to the the primary purpose of the page AND is not a result of a user action.

**Comment by DavidMacDonald** [comment]
Programmatic notification is provided for each change in content that indicates an action was taken or that conveys information, unless one or more of the following is true: 

# The change immediately follows the control that triggered it, in the programmatic reading order.
# There is an accessibility supported programmatic relationship between the new content and the user # activated control that triggers it.
# The user has been advised of the behavior before using the component.
# There are more than 5 notifications per minute.

**Comment by jnurthen** [comment]
- The word immediately needs defining in (1). What is immediately? If there is a <br> between the control and the content - is that immediatly following? How much - and what type of content - is allowed between the control and the content?
- Isn't the loading indicator in #3 and example of this? Why does it need to be a separate SC?

**Comment by lseeman** [comment]
Isnt this part of role name state - change of state?

**Comment by DavidMacDonald** [comment]
@lseeman  4.1.2 addresses updates only components not other types of content

**Comment by DavidMacDonald** [comment]
asa

**Comment by DavidMacDonald** [comment]
@jnurthen I've merged issue#3 in as an example. 

Immediately was intended to mean it follows it in the DOM, and there is no content between the control and the new content, otherwise it would need to be referenced or announced, which  think gives a lot of flexibility.

**Comment by jnurthen** [comment]
@DavidMacDonald so my example with a `<br>` would be ok then as that is not "content" so I stand by my comment that immediately needs defining so it is clear what is allowed and what is not.

**Comment by DavidMacDonald** [comment]
@jnurthen "Immediately follows" is a bit hard to scope this way. I think the concern can be addressed by defining "Programmatic reading order" to exclude machine code not typically presented to the end user

"Programmatic reading order"
The order of content presented to the end user.
Note: code used for layout and programming which is typically not presented to the end user is not considered in calculating the programmatic reading order..

**Comment by joshueoconnor** [comment]
This needs to be clearer around exactly what a component is IMO.

**Comment by joshueoconnor** [comment]
We also need a definition for control.

**Comment by WayneEDick** [comment]
How can a user turn these comments off? Sometimes actions can be relevant, but you want to concentrate on what you are doing.

**Comment by WayneEDick** [comment]
The programmatic reading order looks like "correct reading sequence" already defined in WCAG 2.0 glossary.

**Comment by WayneEDick** [comment]
This really needs coordination with [Issue 54](https://github.com/w3c/wcag21/issues/54).
It is stated in plain language. There is a problem with the language in  [Issue 2](https://github.com/w3c/wcag21/issues/2). 

What does this cover that is not covered by  [Issue 54](https://github.com/w3c/wcag21/issues/54)?

**Comment by mapluke** [comment]
I agree with Wayne that there "is a problem with the language". One example is that it is unclear what the "except" (in the third line of the four line 51 word sentence) "programmatic notification" applies to. I've read this definition several times and I'm still not sure I have fully got the correct intended meaning.

**Comment by mapluke** [comment]
In attempting to co-ordinate with [Issue 54](https://github.com/w3c/wcag21/issues/54), I believe that there is a major difference that must be overcome. [Issue 54](https://github.com/w3c/wcag21/issues/54) states what is **really** needed by users "programmatically-determinable, rapid feedback in the primary modalities of the content". However, [Issue 2](https://github.com/w3c/wcag21/issues/2) calls for "Programmatic notification", which only requires that a user agent should be able to "extract and present this notification to users in different modalities". This success criterion.would be met if the feedback was presented to users in a different modality to the primary modality of the content, or even if no feedback was actually presented.

**Comment by DavidMacDonald** [comment]
@mapluke 
The main use case for #2  is using "aria-live" regions. Programmatic notification refers to providing the information to the accessibility API. This is a reasonably well understood part of WCAG for accessibility professionals doing audits. We avoid using the API term in the definition for a number of reasons.

Issue #54 only requires notification on the successful or failure of the completion of a task, so there a re a number of things not covered. I added exception number 6 to address Issue #54 and I think its good for us to coordinate the this one and #54.  

>The user action results in a success or failure response from the page, in which case visual >feedback (such as text) AND a programmatic notification are provided

**Comment by rachaelbradley** [comment]
Sorry to weigh in late ,but comparing #2 and #54, I question whether we should be combining them.  Issue #2 addresses changes in content, regardless of whether it is initiated by the user or not. It is  placed in perceivable because the central focus is ensuring users are either aware of the change in content after the page is rendered, either through notification or through encountering the change as part of the natural reading order.  Issue #54 focuses on ensuring users receive feedback about the results of their actions in order to avoid mistakes, and is placed under 3.3 accordingly. Not all user actions results in content changes, some result in potentially confusing changes in context (for example: sending an email where the email closes). While there is overlap for actions that result in content changes, I believe merging them leads to an overburdened SC.  I suggest we consider reducing the overlap rather than merging them.  Below are the wordings of the two success criteria together with #2 slightly edited to reduce the overlap. 

#2 Programmatic notification is provided for each change in content that conveys information, unless one or more of the following is true:
1.The change immediately follows the control that triggered it, in the programmatic reading order.
2.There is an accessibility supported programmatic relationship between the new content and the user # activated control that triggers it.
3.The user has been advised of the behavior before using the component.
4.There are more than 5 notifications per minute.
5.The change in content is not related to the primary purpose of the page AND is not a result of a user action.

#54 The success or failure of every user initiated action is clearly indicated to the user by visual, programmatically-determinable, rapid feedback in the primary modalities of the content. Audio feedback is supported. 

I would add a note that in cases where a user action results in a change in content, both criteria apply and that clearly written notification that the content changed could be considered to satisfy #54.

**Comment by mapluke** [comment]
@DavidMacDonald 
Your seven-word explanation of "Programmatic notification" is **exactly** what I would have expected it to mean. The problem I have is that the 52-word multi-clause sentence that is **supposed** to explain it is, in my view, almost impossible to parse. COGA guidelines suggest only one idea per sentence. Depending on how you count them there are probably six or seven ideas in this sentence! Maybe this can be re-examined and re-drafted to clearly say what is intended - it probably needs more than one sentence.

**Comment by DavidMacDonald** [comment]
@mapluke Updated the definition to simplify to one idea per sentence.

**Comment by DavidMacDonald** [comment]
Issue 54 covers
* Changes that involve actions that have a "success or failure" outcome
* Visual feedback of that success or failure
* Programmatic Feedback (i.e., aria-live) of that success or failure
* Audio feedback of that success or failure that is *self generated* from the browser and web page (not a via screen reader)
* Settings to turn off this self generating audio feedback

Issue #2 covers
* All changes in content (not just success failure), so they don't need to be triggered by the user... (i.e., baseball score update, or stock change)
* Is limited to programmatic feedback (i.e., aria-live) not visual or self generating audio
Issue 2 has the following exemptions
* Has exceptions for when a user clicks a button and the new content follows immediately after the button
* allows an exception if there the code "aria-controls" makes an programmatic association between the button and the new content, which could then be somewhere else on the page
* If there is a warning to the user that new content will be inserted when they click something beforehand then no notification is necessary 
changes not related to the primary purpose of the page are exempt from notifications (i.e., advertisements that refresh)
* if there are more than x notifications a minute there is an exemption.

I tried an early attempt to merge #54 by adding bullet 6 to Issue #2

The only thing this leaves out of #54 is the self generating audio feedback and the requirement for personalization to turn it off. I think that is a requirement that is too wide for the current web, until personalization on web pages becomes main stream.

#54 is simpler to understand. #2 has already been through the painful grooming process of adding exception, which is what makes Wayne say it seems complicated. But I think any notification SC will end up with a list of exceptions like #2.

There is also a consideration about WCAG SC 4.1.2 which overlaps, and requires notification to changes to components. But I don't think we can easily morph "component" into something that would be satisfactory for either Issue #54 or #2. So we can park that for now, understanding that someone might bring it up during discussions.

**Comment by DavidMacDonald** [comment]
OR we could just leave them separate for the first draft

**Comment by DavidMacDonald** [comment]
@rachaelbradley if we separate them you can leave out the programmatic part of #54 because it's in here.

**Comment by DavidMacDonald** [comment]
Most recent version is:

Programmatic notification is provided for each change in content that indicates an action was taken or that conveys information, unless one or more of the following is true:  <br />
1. The change immediately follows the control that triggered it, in the reading order.
2. There is an accessibility supported relationship between the new content and the control that triggers it.
3. The user has been advised of the behavior before using the component. 
4. There are more than 5 notifications per minute.
5. The change in content is not not a result of a user action AND not related to the the primary purpose of the page.

**Comment by LJWatson** [comment]
This feedback is based on a collective review by @PatrickLauke, @IanPouncey, @JSpellman and @LJWatson 

This SC addresses a valid set of use cases, and appears to be practical and realistic to achieve. We have one small suggestion though... 

"1. The change immediately follows the control that triggered it, in the programmatic reading order." 

There may be times when a notification would be helpful in this situation. For example, when a control causes a set of search results to be filtered and
the control comes before the search results in the DOM. For this reason, we suggest that this exception is dropped from the SC.

**Comment by DavidMacDonald** [comment]
@LJWatson @patrickhlauke @Ianpouncey @jspellman
I'm a little nervous about removing the exception for new content immediately following the control. Wouldn't that mean that every show/hide button would have to place a live region on the new content... well perhaps the aria-expanded change of state would be sufficient notification in that case. Thoughts?

**Comment by DavidMacDonald** [comment]
Most recent version after a plain language pass is:

Programmatic notification is provided for each change in content that indicates an action was taken or that conveys information, unless one or more of the following is true:  <br />
1. There is an accessibility supported relationship between the new content and the control that triggers it.
2. The user has been advised of the behavior before using the component. 
3. There are more than 5 notifications per minute.
4. The change in content is not not a result of a user action AND not related to the the primary purpose of the page.

**Comment by joshueoconnor** [comment]
Good work all - @WayneEDick and @DavidMacDonald if this is ready can you submit a PR for survey and let me know? Thanks

**Comment by DavidMacDonald** [comment]
@joshueoconnor  yes its ready

**Comment by joshueoconnor** [comment]
@DavidMacDonald Great stuff - please submit a PR against this. @WayneEDick

**Comment by joshueoconnor** [comment]
This seems related to the COGA SC Task Completion #21

**Comment by awkawk** [comment]
Updated the issue description to reflect the FPWD text and reopening issue.

**Comment by awkawk** [comment]
David, how does a common model that I'm seeing on a lot of news sites fit into this? On a page with a long article, there will be 2-3 paragraphs and then a "read more" button, then another article or page footer information. If you click the "read more" button then the rest of the article is loaded into the page. 

Would this fail?

**Comment by DavidMacDonald** [comment]
@awkawk The way I would advise a client to conform in this case would be something like this.

```<p>Lipsum... <a href...>read more</a></p>
<span id="notification" aria-live="polite"></span>```

On clicking "read more" 
```<span id="notification" aria-live="polite">full article loaded</span>```

**Comment by mraccess77** [comment]
@DavidMacDonald I might also want to see an aria-controls in there as well so it's clear what new content was loaded.  It's also been my experience that aria-live can be hit or miss to whether it actually works with different screen readers.  There is also the challenge of screen readers seeing the new content.  While we should good support for DOM mutation listeners it seems screen readers can miss content updates even with aria-live or an alert is used.

**Comment by awkawk** [comment]
Is there a way to do it without ARIA? How would this be done with a native mobile application or software application where "software program" is the unit of evaluation instead of "web page" (per WCAG2ICT)?

WCAG2ICT does apply to WCAG 2.0 but we should be thinking about the impact on it for 2.1.

**Comment by DavidMacDonald** [comment]
an alert, popup, inline comment, or any other programmatic notification.

**Comment by mraccess77** [comment]
@awkawk in IOS native apps you can send screen changed events and screen layout change events that can be detected by the screen reader.  These can also be accompanied by a control to focus or a string to announce.  https://developer.apple.com/reference/uikit/uiaccessibilitylayoutchangednotification

**Comment by DavidMacDonald** [comment]
> @mraccess77  I might also want to see an aria-controls in there as well so it's clear what new content was loaded.

That is the intent of the first bullet. We can't say "wai-aria controls" but that is what a "accessibility supported relationship between the new content and the control that triggers it."

**Comment by kwahlbin** [comment]
We need a definition for "primary purpose of the page"

**Comment by DavidMacDonald** [comment]
Here's a first shot at a definition Primary Purpose 

> If removed, the page would loose it's meaning or main reason for existing.

**Comment by joshueoconnor** [comment]
I think drop programmatic from "Programmatic notification is provided for each change in page content unless one or more of the following is true:". It's mentioned in the qualifying clauses.
