### ISSUE TITLE
Microsoft comment on Change of Content

### ISSUE THREAD

**Issue by alexswli** [w3c/wcag21#201]
Clarity of text

a. We do not understand the first exception, particularly as to the meaning of accessibility supported relationship.

b. There ought to be an exception on standardized technique similar to that of Personalization SC

**Comment by steverep** [comment]
@alexswli, the points raised by this issue seem unrelated to the latest SC text.  Should this be closed?

**Comment by alexswli** [comment]
@steverep, please close this issue.
