### ISSUE TITLE
Microsoft comment on Minimize user errors

### ISSUE THREAD

**Issue by alexswli** [w3c/wcag21#202]
Clarity of text:

a. There are significant issues with the definition of Common input errors on top of what's noted in the editor's note.  Have a supportive technique does not make a type of error common.  The reliability of the supportive technique can put the viability of the technique in question.

b. Where do the errors need to be documented or reported to be consider common?  According to this definition, all errors who was told to somebody or simply documented but never shared are common.  This definition defies common understanding of the word common and makes the SC not usable.

c. There is no definition for reliably.

**Comment by lseeman** [comment]
#13

**Comment by awkawk** [comment]
@alexswli Thanks for the comment - the Working Group has not reached consensus on this proposed SC so it is deferred for future consideration.
