### ISSUE TITLE
Microsoft comment on Undo

### ISSUE THREAD

**Issue by alexswli** [w3c/wcag21#203]
Testable:

a. "Clearly" and "Unwanted" are subjective.

Implementable:

a. This SC needs real-time event and essential exceptions similar to that of 2.2.1

b. There is a limit as to how much time can be given to perform undo.  An expectation of unbounded, in terms of time, undo is not feasible.

**Comment by awkawk** [comment]
Thanks for the comment - the Working Group has not reached consensus on this proposed SC so it is deferred for future consideration.
