### ISSUE TITLE
Microsoft comment on Provide Support

### ISSUE THREAD

**Issue by alexswli** [w3c/wcag21#204]
Testable:

a. This SC is very subjective--making it untestable, unclear, and unimplementable.

Helpfulness:

a. We do not know what kind of content would actually "helps".  Therefore, there is no way to assess the degree of helpfulness to people with disabilities.  Take the most straight forward requirement here as an example. How does one go about providing content to express something as simple as "Tim has two pencils.", which contains numerical information that is actually helpful?  How do we go about assessing the helpfulness?  I also suspect content that helps one user can perhaps not help or even confuse another user.

**Comment by lseeman** [comment]
referencing the issue #32

**Comment by awkawk** [comment]
@alexswli Thanks for the comment - the Working Group has not reached consensus on this proposed SC so it is deferred for future consideration.
