### ISSUE TITLE
TPG comment on 2.2.4 Interruptions

### ISSUE THREAD

**Issue by jspellman** [w3c/wcag21#206]
Until browsers or the OS provide a mechanism for suppressing
interruptions, this SC effectively mandates provision of a web-based
personalisation widget. We don't think that is appropriate for a Level
AA SC, but rather than push it to Level AAA, we suggest simplifying and
strengthening the SC to remove that requirement.

Here is our suggested SC:

"Changes that move focus or interrupt the display of content are
deliberately user initiated, or are necessitated by an emergency. (Level
AA)"

There would need to be a definition of "interrupt" and/or some examples.
There would also need to be a definition of "deliberately
user-initiated", which might be something like:

"Deliberately user initiated: An intentional discrete action such as
clicking, pressing a key or speaking a voice command." 

[submitted on behalf of engineers at The Paciello Group]

**Comment by joshueoconnor** [comment]
Relates to Interruptions Minimum SC http://rawgit.com/w3c/wcag21/master/guidelines/index.html#interruptions-minimum

**Comment by mbgower** [comment]
@jspellman I think this is intended to be for 2.2.7. You should rename the issue so it shows up in filtering if someone is using the SC number.

**Comment by joshueoconnor** [comment]
@jspellman Here is the current review on this SC https://www.w3.org/2002/09/wbs/35422/interruptions-minimum-review/ does this version address any of your concerns? If so can this be closed?

**Comment by awkawk** [comment]
Official WG response: Thank you for your comment. This SC has been removed from the draft and will be able to be considered in a future revision.
