### ISSUE TITLE
Success Criterion 3.1.X Plain Language Summary of site

### ISSUE THREAD

**Issue by mpiggot** [w3c/wcag21#209]
(Level A)
When a website requires for most of its pages a reading ability more advanced than the primary
education level, a summary page that does not require reading ability more advanced than the
primary education level, is available as supplemental content. This Plain Language Summary page
includes:
 Information about the purpose of the site
 Summary explanations of and links to the 5 most used pages on the site
 Contact information
 The summary page is clearly identified by a non-verbal icon, such as the Easy-to-Read
Logo at www.easy-to-read.eu

**Comment by mpiggot** [comment]
**Success Criterion 2.4.X Navigation to plain language summary
(Level A)**
The link to a Plain Language Summary page of a site is provided in the upper part of the entry
page of a site through a non-verbal icon, such as the Easy-to-Read Logo at www.easy-to-read.eu

**Comment by lseeman** [comment]
@joshueoconnor I think they are proposing a new Success cryteria

**Comment by jim-work** [comment]
I think this is proposing a new Success Criteria and is not related to #30

**Comment by lseeman** [comment]
It could be a replacement. but it doesnt address all the types of content we have.

**Comment by joshueoconnor** [comment]
Can this one be closed? Is it OTBE?  https://github.com/w3c/wcag21/issues/149
