### ISSUE TITLE
Oracle Comment on 1.3.4 Support Personalization

### ISSUE THREAD

**Issue by cwadamsoforacle** [w3c/wcag21#212]
It needs to be clarified if the author is responsible to apply the Personalizations if a suitable framework is not available. It is currently unclear if this is required.

It is hard to understand how an author can determine the importance of something in a UI. Different users have different tasks that they need to undertake in a complex UI and as such some things are critical to one user but completely unimportant to another. How can an author make this determination?

Many things already have metadata which could be used to support personalization - I hope this is not asking people to add more metadata to every object. For example a required field is obviously important and it should not be necessary to mark it as such if it is already required

In the Important information definition the word opportunities is used. We do not understand how this can be consistently interpreted.

The definition of standardized techniques includes WCAG techniques. You cannot reference non-normative techniques in a normative definition.

It is very hard to comment on this until the Personalization Document is available - further comments should be expected once this is available and has implementations.

Would software applications be covered by this - or would they be exempt assuming no personalization support?

As this is not implementable today we would recommend this to be at AAA level.

**Comment by awkawk** [comment]
@cwadamsoforacle The SC in question has changed substantively in response to your feedback and that provided by others. Please review the updated version at https://www.w3.org/TR/WCAG21/#purpose-of-controls
