### ISSUE TITLE
Oracle comment on 1.4.11 Resize Content

### ISSUE THREAD

**Issue by cwadamsoforacle** [w3c/wcag21#214]
The word 'meaning' doesn't make sense in the sentence. 'Understand' or 'comprehend' may make sense.

It is not possible to resize content and avoid horizontal scrolling on mobile devices. Without this ability it would be necessary to add zoom widgets to every page in order to allow content to resize.

Having this at level A seems strange when 1.4.4 is at level AA. I would propose adding this at level AA and potentially moving 1.4.4 to level A. Otherwise 1.4.4 needs to be obsoleted.

**Comment by alastc** [comment]
(Commenting as myself for clarification, not an official working group response.)

> The word 'meaning' doesn't make sense in the sentence. 'Understand' or 'comprehend' may make sense.

The last part of the sentence needs to map to the earlier "content or functionality", e.g. "use" maps to "functionality".

Whilst I agree people "understand" or "comprehend" content, what they understand/comprehend will vary depending on them. The "meaning" is what the content provides, and therefore a better term for what is being tested. 

> It is not possible to resize content and avoid horizontal scrolling on mobile devices. Without this ability it would be necessary to add zoom widgets to every page in order to allow content to resize.

This is a narrow path to walk in WCAG SCs, but the idea is that the _content_ has to be able to resize to 400% (and we're suggesting a starting point of 1280px wide with a browser with zoom for testing). 

Whilst the majority of mobile based browsers (except Opera) don't reflow content, that doesn't mean someone with low vision would be forced to use a mobile device, they can choose an appropriate device/screen size and benefit from this ability.

The understanding document can make clear there is no need for onscreen widgets unless you cannot use a technique such as media queries in CSS (or tagged docs in PDF).

> Having this at level A seems strange when 1.4.4 is at level AA. I would propose adding this at level AA and potentially moving 1.4.4 to level A. Otherwise 1.4.4 needs to be obsoleted.

I think 1.4.4 is still useful for content that is excepted from this SC (e.g. text within data tables). Would you be in favour of modifying 1.4.4 to align them better in WCAG 2.1? Or would you rather leave 1.4.4 as it is?

**Comment by alastc** [comment]
Hi @cwadamsoforacle,

The SC text has gone through significant revision, [latest version here](https://rawgit.com/w3c/wcag21/resize-content_ISSUE-77/guidelines/sc/21/resize-content.html).

I believe it addresses the issues raised:

* My comment above covers the use of 'meaning', unless you have another suggestion for something that the content does?
* The new approach of saying '320px equivalent width' covers the mobile aspect.
* It is now at level A, although I should consider raising the current 1.4.4 to A to make it easier to comprehend as a whole.

Is there anything you can't live with before this goes into draft?

Thanks,

-Alastair
