### ISSUE TITLE
Oracle comment on 1.4.12 Graphics Contrast

### ISSUE THREAD

**Issue by cwadamsoforacle** [w3c/wcag21#215]
It is not clear how we would determine the meaningful part of a graphic. If we were to have a multi-color image and some of the colors meet the contrast requirement - for example if the center of the image meets the contrast requirement with the background, but the edges do not (a blur kind of effect) how would we determine if the image meets the requirement or not?

Does this standard apply to the contrast of the graphic vs. it's surrounding environment?  Or to its content as well?  Given the intent, I would think that this includes the content of the graphic (in the event that the graphic contains separate elements which each convey a distinct meaning).  However, the current write-up reads like this is written to apply to the graphic and it's surrounding content, and does not apply to the elements within the graphic.

Recommend existing contrast ratio requirement to be reduced to 3.0. If multiple states need to be communicated based on color, having a requirement of 4.5:1 for each state to the background AND a requirement of 4.5:1 between the 2 different states would lead to a very limited choice of colors.

**Comment by DavidMacDonald** [comment]
Personally I agree, to reduce to 3:1. I think text requires more contrast than graphics, charts etc. so choosing a value below our current text requirement s seems reasonable.

**Comment by alastc** [comment]
Regarding the multi-colour image, that comes down to working out what the "graphical object"s are that are "essential to understanding". I wrote more about that in [an article](https://alastairc.ac/2017/03/graphics-contrast/).

I'll have a look at the current write-up in #9, perhaps the references to icons confuse the message for more complex graphics.

Regarding 3:1, that is being discussed as graphics might be easier to discern than text, but we need folks to Low Vision to confirm, it may not be straightforward.

**Comment by joshueoconnor** [comment]
@alastc @lauracarlson  Do you think this item can be closed? Due to current Graphics contrast SC in public draft? https://www.w3.org/TR/WCAG21/#graphics-contrast

**Comment by joshueoconnor** [comment]
@cwadamsoforacle Thanks for your comment - I think the use of the current ratio has been agreed on by the LVTF.
