### ISSUE TITLE
Oracle comment on 1.4.14 User Interface Component Contrast

### ISSUE THREAD

**Issue by cwadamsoforacle** [w3c/wcag21#219]
If we have things that have different colors for selected and non-selected, then meeting the 4.5:1 ratio for both and also having a "significant" (currently defined as 3:1 in WCAG) difference between the two seems almost impossible. We suggest changing to 3:1 and removing the thick line exception.

We would encourage thoughts on combining 1.4.14 and 1.4.12. We think it is possible to produce a single SC which covers both Graphics and User Interface Components.

**Comment by goodwitch** [comment]
@cwadamsoforacle I think you make a good point.  I'm going to ask @joshueoconnor if we can have this as a survey question for AG.  Suggestion for Survey Question:  For 1.4.14 User Interface Component Contrast 

- This SC is ready to go as is.
- This SC should just have a 3:1 color contrast requirement (and remove the thick line exception).
- This SC has significant issues with testability, implementability, or backward compatibility. My suggestions to address these are...	
- This SC has other significant issues. My suggestions to address these are...	
- This SC has minor editorial issues. My suggestions to address these are...

And, we will keep in mind the idea to combine 1.4.14 and 1.4.12. But for now, we will leave them separate.

**Comment by goodwitch** [comment]
@cwadamsoforacle as the SC Manager for this proposal, I've added notes to indicate that we are open to considering removing the 4.5 to 1 requirement (and falling back to just 3 to 1).  We have not made a final determination to drop 4.5 to 1 (there are pros and cons).  So for now, we are leaving the SC text to include the 4.5 to 1 requirement (plus a note about maybe changing it)...and letting it go to public comment as it is.  See https://rawgit.com/w3c/wcag21/user-interface-component-contrast-minimum_ISSUE-10/guidelines/sc/21/user-interface-component-contrast-minimum.html

We have also deeply considered trying to combine this proposed SC with 1.4.11 Graphics Contrast.  At this time, we are just noting that as a possibility...but Alastair and I both agree that these two are best left separate at this time (for clarity and accuracy).  We will continue to look to see if it is possible to combine as the dust starts to settle.
