### ISSUE TITLE
Rewrite of 4.1.2  Name, Role, Value

### ISSUE THREAD

**Issue by lseeman** [w3c/wcag21#22]
# Current versions of SC and Definitions

- [SC for viewing](https://rawgit.com/w3c/wcag21/name-role-value_ISSUE-22/guidelines/sc/21/name-role-value.html) | [SC for editing](https://github.com/w3c/wcag21/blob/name-role-value_ISSUE-22/guidelines/sc/21/name-role-value.html)
- [Author-settable properties definition for viewing](https://rawgit.com/w3c/wcag21/name-role-value_ISSUE-22/guidelines/terms/21/author-settable-properties.html) | [Author-settable properties definition for editing](https://github.com/w3c/wcag21/blob/name-role-value_ISSUE-22/guidelines/terms/21/author-settable-properties.html)
- [SC in full draft guideline](https://rawgit.com/w3c/wcag21/name-role-value_ISSUE-22/guidelines/#name-role-value)

Branch
https://github.com/w3c/wcag21/tree/name-role-value_ISSUE-22

# Short name: 4.1.2 Name, Role, State, Value
Proposed  by Lisa Seeman and Richard Schwerdtfeger

**Current**
4.1.2 Name, Role, Value: For all user interface components (including but not limited to: form elements, links and components generated by scripts), the name and role can be programmatically determined; states, properties, and values that can be set by the user can be programmatically set; and notification of changes to these items is available to user agents, including assistive technologies. (Level A)

**Proposed** 
4.1.2 Name, Role,@@ State,@@ Value: For all user interface components (including but not limited to: form elements, links and components generated by scripts)

- the name and  role of the component @@can be programmatically determined, 
- the @@ states, author-settable properties, and values of the component can be programmatically determined, @@
- states, author-settable properties, and values that can be set by the user can be programmatically set, by  user agents, including assistive technologies and
- notification of changes @@to any@@ of these items is available to user agents, including assistive technologies.

## Glossary
author-settable properties – properties that can be set by the author in the markup or native coding language to provide information about the user interface components or its relationship to other components  the document.

## Description 
The intent of this change is to provide the following clarifications 
•	Initial values   properties and states must   be programmatically determined, including the initial states and values
•	Initial settings of values, properties  and states need to be accessible.
•	States, properties, and values that can be set by the user can be programmatically set; by user agents including assistive technology.
•	What properties need to be accessible is clarified 

## Benefit
We have seen web developer feel they have conformed without making the states accessible, as the values were originally  clear. This rewording clarifies what needs to be done.

## Testability
 Current  tests and techniques

**Comment by joshueoconnor** [comment]
@DavidMacDonald Its not clear to me what this is about. 'and values that can be set by the user can be programmatically set; ' it is not usual that the end user will set these values at all. Unless they are technical/web people and understand these things. It's not clear to me how though - tbh.

Is the idea that this is a repair SC? Is this suggesting that the end user will over ride the DOM values or add them if they don't exist? What tools will they use to do that? Are there common tools that are easy to use that allow end users who may benefit from this kind of technical remedial/repair work? Maybe if some of those were included in a notes/supporting section this maybe clearer. 

As an SC this won't work with compiled native apps etc as role/state properties can only be set by the author.

**Comment by DavidMacDonald** [comment]
@lseeman @joshueoconnor I don't think it is requiring that user be able to change these things, only that if they are author settable, that if they can be set by the user, they can also be set using the users AT... sounds reasonable.
