### ISSUE TITLE
Oracle comment on 1.4.15 Adapting Text

### ISSUE THREAD

**Issue by cwadamsoforacle** [w3c/wcag21#222]
Specifying a specific font and particular color schemes seems problematic.

It is not specified how the user would be allowed to override these. If a user chooses to use a user style sheet and causes an application to break (by for example showing hidden content) then it needs to be clear that this is not a failure of the application but of the user style sheet. Similarly, as some user agents have chosen to remove user style sheets, breaking the CSS cascade model which was designed to allow a user to override anything - would this be a failure of the author or the user agent?

If a solution does not have the technology to allow overrides is this a failure?

**Comment by alastc** [comment]
> as some user agents have chosen to remove user style sheets

It is not anticipated that users would remove all styles to override the font, and the understanding document can make that point.

That level of override applies more to the linearisation SC #58 which does need to override the styles more (although not necessarily by dropping them altogether).

> If a solution does not have the technology to allow overrides is this a failure?

I'm not sure what you mean by solution here, is it the general platform (e.g. PDF) or the website?

**Comment by jnurthen** [comment]
Laura - this was a comment by someone who is not a member of the WG - it is a public comment.

**Comment by lauracarlson** [comment]
Thanks, James!

**Comment by lauracarlson** [comment]
So from today's AG WG minutes:

MC: when it comes to formal response tracking member comments are treated as public comments
https://www.w3.org/2017/04/25-ag-minutes.html#item03

@michael-n-cooper , @joshueoconnor is this one tagged correctly?

**Comment by lauracarlson** [comment]
(Replying as myself for clarifications, not on behalf of the working group.)

Hi @cwadamsoforacle ,

Thank you for your comment.

> Specifying a specific font and particular color schemes seems problematic.

I agree. Specific font and particular color schemes would have their challenges.

>It is not specified how the user would be allowed to override these. If a user chooses to use a user style sheet and causes an application to break (by for example showing hidden content) then it needs to be clear that this is not a failure of the application but of the user style sheet. 

Understanding and technique documents would explain the details.

> Similarly, as some user agents have chosen to remove user style sheets, breaking the CSS cascade model which was designed to allow a user to override anything - would this be a failure of the author or the user agent?

I don't see how it could be an author failure, as an author is responsible for content.

> If a solution does not have the technology to allow overrides is this a failure?

The HTML stack and PDF should work. Are there any other technologies beyond these 2 are you concerned about?

**Comment by jnurthen** [comment]
While there is not much new development, there are legacy applications which will be running on intranets for a long time. Even though browsers are disabling plug-ins by default there are many internal web applications which will be reliant on them for quite some time into the future.
Examples of this are Flash and Java.

I also question if Java Web Start would be covered by WCAG. The application is started from a URL and the application is downloaded, installed updated and run directly when clicking on a URL in a web page.

**Comment by alastc** [comment]
> there are many internal web applications which will be reliant on them for quite some time into the future.

But would they be trying to meet WCAG 2.1? If they are legacy surely 2.0 would be the appropriate guidelines?

**Comment by jnurthen** [comment]
@alastc possibly true. I just want to be clear on the scope.

**Comment by lauracarlson** [comment]
Hi @jnurthen ,

>I also question if Java Web Start would be covered by WCAG. The application is started from a URL and the application is downloaded, installed updated and run directly when clicking on a URL in a web page.

Good question. [I asked on the AG list](https://lists.w3.org/Archives/Public/w3c-wai-gl/2017AprJun/0356.html). Some people have responded. Some have questions for you.

**Comment by lauracarlson** [comment]
Hi @cwadamsoforacle ,

You wrote:

> Specifying a specific font and particular color schemes seems problematic.
> 
> It is not specified how the user would be allowed to override these. If a user chooses to use a user style sheet and causes an application to break (by for example showing hidden content) then it needs to be clear that this is not a failure of the application but of the user style sheet. Similarly, as some user agents have chosen to remove user style sheets, breaking the CSS cascade model which was designed to allow a user to override anything - would this be a failure of the author or the user agent?
> 
> If a solution does not have the technology to allow overrides is this a failure?

Thank you for your comment.

The latest SC text, which the AG Working Group has agreed to accept into editors draft for public comment is:

> If the technologies being used allow the [user agent](https://www.w3.org/TR/WCAG20/#useragentdef) to [adapt](https://rawgit.com/w3c/wcag21/adapting-text_ISSUE-74-78-79/guidelines/terms/21/adapt.html) [style properties](https://rawgit.com/w3c/wcag21/adapting-text_ISSUE-74-78-79/guidelines/terms/21/style-properties.html) of [text](https://www.w3.org/TR/WCAG20/#textdef), then no loss of [essential](https://www.w3.org/TR/WCAG20/#essentialdef) content or functionality occurs by adapting all of the following:
>
> 1. line height (line spacing) to at least 1.5 times the font size
> 2. spacing underneath paragraphs to at least 2 times the font size
> 3. letter spacing (tracking) to at least 0.12 times the font size
> 4. word spacing to at least 0.16 times the font size
> 
> Note: Examples of text that are typically not affected by [style properties](https://rawgit.com/w3c/wcag21/adapting-text_ISSUE-74-78-79/guidelines/terms/21/style-properties.html) are open [captions](https://www.w3.org/TR/WCAG20/#captionsdef) and [images of text](https://www.w3.org/TR/WCAG20/#images-of-textdef), which are not expected to adapt.
> 
> Editor's note: The Working Group seeks to include overriding text color, background color, and font-family as part of this SC, but is not yet able to identify a way to do so that is sufficiently testable.

It has a scoping clause in place. Does that alleviate your concern regarding when technology does not to allow overrides?

The SC Text does not specify a particular font or particular color schemes. As it states, we are  investigating these aspects. If you have suggestions, we would love to hear them.

Thanks again,
Laura

**Comment by joshueoconnor** [comment]
@cwadamsoforacle Would you like to respond to @lauracarlson on this, are you happy for us to close this comment?

**Comment by joshueoconnor** [comment]
@cwadamsoforacle I'm closing this - it looks like @lauracarlson reply addressed this well, thanks.
