### ISSUE TITLE
Oracle comment on 1.4.16 Popup Interference

### ISSUE THREAD

**Issue by cwadamsoforacle** [w3c/wcag21#225]
It needs to be clarified if the label for a form field is part of the triggering content for the input element. This has particular relevance on mobile where there is limited screen real estate. When entering into a text field all of the following may be present on the screen:

- Label
- Form Field
- Soft Keyboard
- Popup containing hint text of what to fill in (for example password rules)

Sometimes the popup is lengthy. It must be displayed - or some of the other proposed SCs would fail but there is not enough screen real estate to completely avoid a partial overlap of the form field. It is avoided as much as possible but sometimes it is just not feasible.

All the use cases cited in the linked issue are based on mouse users. Due to this, why is there a requirement to not have an overlap of the triggering content for focus as well as hover.

**Comment by WayneEDick** [comment]
Thank you for your comments. 
First we understand how lengthy popups can be necessary. 
The problem is that when long popups cannot be turned off, the user cannot use the information presented.
The user needs a way to hide the popup long enough to use it. The way popups appear in large text is much different than the author's positioning anticipated.

Note this is the most rough of the low vision SCs and may be withdrawn  from 2.1.

**Comment by steverep** [comment]
Hi @cwadamsoforacle,

The latest language for this criterion, [Content on Hover or Focus](https://www.w3.org/TR/WCAG21/#content-on-hover-or-focus), is substantially different from that used to generate this comment, so perhaps some or all of these concerns have been addressed.  In any case, I'll attempt to translate a response in the context of the current language.

> It needs to be clarified if the label for a form field is part of the triggering content for the input element. 

Hmm... The current language leaves that up to the author I suppose.  If the label responds on focus or hover and the label is what is being triggered, then the SC would apply.  If the control is the trigger, then there would be no requirement to not obscure the label, although I'd consider that poor for general usability.

> Sometimes the popup is lengthy. It must be displayed - or some of the other proposed SCs would fail but there is not enough screen real estate to completely avoid a partial overlap of the form field. It is avoided as much as possible but sometimes it is just not feasible.

I'm not sure I understand.  You seem to be implying that such popup content *must* fit on screen, but that is not an accessibility requirement nor could it be easily guaranteed for all screen sizes, magnification levels, etc.  Is the proposed SC to which you are referring in the current editor's draft?

> All the use cases cited in the linked issue are based on mouse users. Due to this, why is there a requirement to not have an overlap of the triggering content for focus as well as hover.

Magnified views generally work by following the pointer and keyboard focus as the panning impetus.  If I primarily use a keyboard with a magnified view, then my best or only view of a trigger may be when I tab to it.  If additional content pops up and obscures it, it may not be possible to ever see the trigger under the magnification I need.

**Comment by joshueoconnor** [comment]
@cwadamsoforacle The candidate SC that made the draft (that was based on Popup Interference) is now called 'Content on Hover or Focus' https://www.w3.org/TR/WCAG21/#content-on-hover-or-focus. I feel this should address your initial concerns.

It seems that the current SC wording is clear that we are talking about a user interface components that can receive focus, and the SC is also clear about what is NOT covered (such as visual presentation that is controlled by the browser and not the author.
