### ISSUE TITLE
Oracle comment on 2.1.4 Speech Input

### ISSUE THREAD

**Issue by cwadamsoforacle** [w3c/wcag21#227]
This is written like a Functional Performance Criteria not a Technical Standard. This is so broad and would require a content author to know details of (all) speech recognition packages and how they work.

**Comment by DavidMacDonald** [comment]
I agree personally speaking

**Comment by awkawk** [comment]
@cwadamsoforacle This SC has been substantially changed in the latest version (https://www.w3.org/TR/WCAG21/#accessible-name) - thank you for your comment.
