### ISSUE TITLE
Oracle comment on 2.2.6 Timeouts

### ISSUE THREAD

**Issue by cwadamsoforacle** [w3c/wcag21#230]
'Easily' is not defined in the loss of data section.

Does the preserving of data for a "limited time" mean if it is more than a week or less than a week?

This may add cognitive load to a site. For example, if I am on a shopping site and I add something to my cart. I decide I don't want it  and go away for a few days.  I would not want it to be there if I were to come back to the site a few days later for something else. Perhaps limit this to authenticated sites.

Also the messages I get to tell me how long things will stay in my session could add confusion to what should be a simple task.

**Comment by lseeman** [comment]
#14

**Comment by awkawk** [comment]
@cwadamsoforacle This SC has been substantially changed in the latest version (https://www.w3.org/TR/WCAG21/#timeouts) - thank you for your comment.
