### ISSUE TITLE
Oracle comment on 2.2.8 Interruptions

### ISSUE THREAD

**Issue by cwadamsoforacle** [w3c/wcag21#231]
Definition of 'Emergency' does not cover many required use cases.  'Emergency' needs to be broadened to cover anything which may cause data loss.

**Comment by joshueoconnor** [comment]
@cwadamsoforacle Emergency is now defined here https://www.w3.org/TR/WCAG21/#dfn-emergency 

as "a sudden, unexpected situation or occurrence that requires immediate action to preserve health, safety, or property". This definition has working group consensus. Thanks.

**Comment by joshueoconnor** [comment]
@cwadamsoforacle Note, also the current draft of the candidate SC for update https://www.w3.org/TR/WCAG21/#interruptions

**Comment by joshueoconnor** [comment]
@cwadamsoforacle  Note, the current candidate SC https://www.w3.org/TR/WCAG21/#interruptions
