### ISSUE TITLE
Oracle comment on 2.4.11 Single Key Shortcuts

### ISSUE THREAD

**Issue by cwadamsoforacle** [w3c/wcag21#232]
I don't know where a user interface would ever fail this. Pretty much all UIs allow a pointer interface which would be another way to do the equivalent of a single key shortcut.  I question the purpose of this SC.

I'm assuming keys like "DEL" and "Backspace" would be allowed as they are not keyboard characters.

**Comment by DavidMacDonald** [comment]
From the description

>Speech Input users generally work in a single mode where they can use a mix of dictation and speech commands. This works well because the user knows to pause before and after commands, and commands are usually at least two words long. So, for instance, a user might say a bit of dictation, e.g. "the small boat", then pause, and say a command to delete that dictation, e.g. "Delete Line". In contrast, if the user were to say the two phrases together without a pause, the whole phrase would come out as dictation, e.g. "the small boat delete line". Although speech input programs often include modes that listen only for dictation or only for commands, most speech users use the all-encompassing mode all the time because it is a much more efficient workflow (it would increase command inefficiency by 300% if users were to to change to command mode and back before and after issuing a command).

>Speech users can also speak most keyboard commands, e.g. "press Control Foxtrot" without any problems. If the website or app is keyboard enabled, the speech user can also write a native speech macro that calls the keyboard command, e.g. "This Print" to carry out "Ctrl+F"

>Single key shortcuts are the exception. While using single letter keys as controls might be appropriate and efficient for keyboard users, single key shortcuts are disastrous for speech users. Because only a single key is used to trip a command, a spoken word can become a barrage of single key commands if the cursor focus happens to be in the wrong place.

>If the cursor focus is in the gmail main window, for instance, and someone enters an office and says "Hey Kim" and the speech user's microphone picks that up, "y" archives the current message. "k" moves down one conversation and "m" mutes a message or thread. Or, if the speech user looks up and says "Hey Mike" without remembering to turn off the microphone, the same three things happen in a different sequence. In contrast, in a webpage or app that doesn't use single-character shortcuts nothing happens (or if the focus is in text field there's a bit of stray text that be easily seen and undone.)

>So to fully include speech users, single-key shortcuts must not be the only way to carry out a control, and a mechanism must be available to turn off all single key shortcuts.

>This success criterion is becoming increasingly important in the mobile realm as growing number of apps more fully enable keyboard controls (see resources).

**Comment by jnurthen** [comment]
@DavidMacDonald but as written the SC does not require this. It only requires a mechanism to turn off single key shortcuts if they are the only way to activate a control.

**Comment by DavidMacDonald** [comment]
@jnurthen You are right! 

> Single-character shortcuts are not the only way activate a control, unless a mechanism is available to turn them off or remap them to shortcuts with two or more characters.

It should be

> Single-character shortcuts are not used activate a control, unless a mechanism is available to turn them off or remap them to shortcuts with two or more characters.

**Comment by joshueoconnor** [comment]
@cwadamsoforacle This SC is now in the FPWD, you can see it here. https://www.w3.org/TR/WCAG21/#character-key-shortcuts 

The use cases are clear - including Speech to Text users who wish to avoid inadvertent triggering of action within the UI, or Keyboard only users with mobility issues, who wish to also avoid triggering actions.
