### ISSUE TITLE
Oracle comment on 2.5.1 Target Size

### ISSUE THREAD

**Issue by cwadamsoforacle** [w3c/wcag21#233]
Links in a body of text seem like they would be an issue. Guaranteeing 44px would seem to require very large line spacing which would very much limit the amount of information which can be shown on a page. Sometimes information density is critical for an application.

How could you ever have an on-screen keyboard on a cellphone with this? It would not be possible as it only allows 8 keys across a row on an iPhone (for example) whereas there are 10 letter keys on the top letter row of a QWERTY keyboard. Changing the layout is not an option for some users.

How about wearables such as a smart watch? Would the same target size apply there as on a larger display?

**Comment by DavidMacDonald** [comment]
I personally agree inline links in text should be exempt.

**Comment by DavidMacDonald** [comment]
Summary of requests
- Blocks of text links of 44px not doable (reduced to 22px)
- mandatory layout such as a keyboard onscreen (created exception for mandatory layout, which is layout that needs to be preserved to maintain its meaning, citing example of on screen keyboard.)
- exception for wearables, such as smart watch (I don't think http sites are viewed on watches currently, do we need further investigation?)

**Comment by patrickhlauke** [comment]
exception for wearables is far too vague. what screen size does the wearable have? the user's finger size doesn't change whether they're tapping on a phone/tablet/desktop/smartwatch screen. so why would something that's too small to confidently tap on, say, a small phone screen be suddenly ok on a smartwatch or similar?

**Comment by patrickhlauke** [comment]
taking the apple watch as an example, it appears it runs at a resolution of around 272px x 340px for the smaller model, and 312px x 390px for the larger one. i'd say even taking the 44px x 44px large target size, that's plenty of room for controls. and you wouldn't want to go much smaller at risk of making these truly un-tappable.

**Comment by jnurthen** [comment]
Patrick. The watch resolution is not what you have stated. It is 136x170 CSS pixels (for the small one). You are quoting the physical resolution which is not what we are talking about here.

**Comment by patrickhlauke** [comment]
ah, my mistake. not having one around, i seem to have stumbled on the physical pixel counts rather than CSS ones. nonetheless, i'd say even here i'd say from an ease of use point of view, i could still see controls around 40ish pixels squared being at the edge of "can be tapped unambiguously and comfortably"

**Comment by joshueoconnor** [comment]
@cwadamsoforacle There are two SCs now in the FPWD that we would be happy for you to review. https://www.w3.org/TR/WCAG21/#target-size and https://www.w3.org/TR/WCAG21/#target-size-no-exception
