### ISSUE TITLE
Oracle comment on 2.5.3 Touch With Assitive Technology

### ISSUE THREAD

**Issue by cwadamsoforacle** [w3c/wcag21#234]
This reads like a functional performance criteria not a technology success criteria. It is impossible to know what to do based on this and requires content authors to be familiar with all the different ways that AT might remap touch gestures.

**Comment by DavidMacDonald** [comment]
The best way to pass this is to not take over basic gestures with custom gestures. If custom gestures are used, there would be a requirement n at to interfere with basic gestures for the Screen Readers that ship with the operating system (VoiceOver/TalkBack/Narrator). Which are publicly available and we'll provide the links. So yes, if custom gestures are required there would be several minutes of homework to ensure the new gestures don't mess with the Screen Reader.

**Comment by jnurthen** [comment]
Add Kindle Fire screen reader too as this is not the same as Talkback. I think there are Chromebooks with touchscreens - so add Chromevox. In order to test these you need to have hardware available - so does every accessibility tester need to have all of these devices? If not - how can they possibly test this SC?

**Comment by detlevhfischer** [comment]
@jnurthen 
I think it would be realistic / be expected to draw a line what has been included in testing and have disclaimers that test will not and cannot cover all devices and UA/AT combinatons. 
So a test would specify the accessibility baseline (as defined, for example, in [WCAG EM Step 1.c: Define an Accessibility Support Baseline](https://www.w3.org/TR/WCAG-EM/#req1c)

**Comment by patrickhlauke** [comment]
> The best way to pass this is to not take over basic gestures with custom gestures. If custom gestures are used, there would be a requirement not to interfere with basic gestures for the Screen Readers that ship with the operating system

for web content, it's not actually possible to take over basic gestures / interfere with screen reader gestures. these are simply intercepted by the user agent/screen reader and never reach the web page/javascript. unless a user (where available) explicitly uses a "passthrough gesture", touch AT users simply can't make gestures (with exception of activation gestures, which most touch AT remaps from being just a single tap to a double tap...but that's invisible/transparent to the javascript, which only receives a single "tap" as mediated by the AT) on a webpage.

so this is not so much about needing to test in all different UAs/ATs on touch devices, but rather: don't rely on gestures (beyond a tap) - so no reliance on the user being able to swipe, pinch, spread, multitouch, etc. which incidentally boils down to what in effect is 2.1.1 Keyboard (and was part of my original suggestion to simply extend/generalise 2.1.1)

**Comment by patrickhlauke** [comment]
and yes, i know that it's possible for NATIVE applications to interfere/override AT's gesture recognition, but as we're hashing out currently on the WCAG mailing list, this is about *web content* accessibility guidelines, and not *native* accessibility guidelines. and while it's true that, as @jnurthen often points out, capabilities only available on native have a tendency to find their way into the web platform eventually, it seems ambitious to define this speculatively for something that is not available in ANY user agent at this point (and not spec'd or planned currently either)

**Comment by awkawk** [comment]
@cwadamsoforacle Thanks for the comment - the Working Group has not reached consensus on this proposed SC so it is deferred for future consideration.
