### ISSUE TITLE
Oracle comment on 3.1.8 Manageable Blocks

### ISSUE THREAD

**Issue by cwadamsoforacle** [w3c/wcag21#237]
'Relative pronouns' presumably is to limit relative clauses. What about languages which don't have relative pronouns but still have relative clauses (I think Chinese falls into this category)?

What is a 'Word'? I'm not a linguist but I believe some languages have different definitions of word to how we understand it in English such as German with its compound words or Chinese & Japanese where there is no defined word boundary in text. How would an evaluator know what is a word for the purposes of this test?

There needs to be an exception for user text - for example in an error message often the text the user types is reflected back in the error message.

What about legal documents - where these cannot be changed?  How could these meet this SC?  An example is the final screen of making a credit card purchase where there is a legal agreement you have to agree to by selecting a checkbox.

**Comment by awkawk** [comment]
@cwadamsoforacle Thanks for the comment - the Working Group has not reached consensus on this proposed SC so it is deferred for future consideration.
