### ISSUE TITLE
Oracle comment on 3.2.6 Accidental Activation

### ISSUE THREAD

**Issue by cwadamsoforacle** [w3c/wcag21#238]
We have concerns that this is too technology specific. The bullet points seem to be techniques for how to avoid accidental activation in certain technologies - not a success criteria.

**Comment by DavidMacDonald** [comment]
Up-Event as it applies to WCAG  will have a generic definition. We have several versions without Up-Event, but this seems to be the most understandable for those reading it. 

>Up-Event: The activation of a component when the trigger stimulus is released. On different platforms the "up-event" may be called different things, such as "touchend" or "mouseup".
Example: For touchscreen interaction, the event is triggered when a finger is lifted from the touchscreen at the end of a tap.

**Comment by joshueoconnor** [comment]
This SC has been iterated and is now in the FPWD. [1]

@cwadamsoforacle  Please add any follow up comments against that. While it does relate to single point input devices primarily and are valid use cases for this SC - it may be relevant to other technologies also. [2]

[1] https://www.w3.org/TR/WCAG21/#accidental-activation 
[2] https://www.w3.org/TR/WCAG21/#dfn-single-pointer-activation
