### ISSUE TITLE
Oracle comment on 3.2.7 Familiar Design 

### ISSUE THREAD

**Issue by cwadamsoforacle** [w3c/wcag21#239]
'Easily identifiable' is an inherently subjective measure.

'An adaptive user interface design that can be personalized' - is any amount of personalization sufficient to meet this? Who is to say that any personalization would make it 'easily identifiable'?

'A user interface design that was used successfully by users in a prior version of the application' - this is inherently subjective and not a repeatable test.

This standard seems to prevent adoption of the "next big idea", and leaves no room for innovation.

**Comment by Thad-Code** [comment]
Thank you for your feedback. I have presented the comments to the COGA task force for potential updates.

**Comment by awkawk** [comment]
@cwadamsoforacle Thanks for the comment - the Working Group has not reached consensus on this proposed SC so it is deferred for future consideration.
