### ISSUE TITLE
Oracle comment on 3.3.7 Minimize User Errors

### ISSUE THREAD

**Issue by cwadamsoforacle** [w3c/wcag21#240]
Based on the available information (and the fact that definitions are missing/incomplete), this standard is entirely subjective.

How would corrections for data such as 'dates' be handled, as different languages employ different date formats?

**Comment by lseeman** [comment]
#13

**Comment by awkawk** [comment]
@cwadamsoforacle Thanks for the comment - the Working Group has not reached consensus on this proposed SC so it is deferred for future consideration.
