### ISSUE TITLE
Oracle comment on 3.2.8 Undo

### ISSUE THREAD

**Issue by cwadamsoforacle** [w3c/wcag21#241]
What is the scope for undo history retention? On a web form, for example, are we talking about all field input history since the form was rendered? Should undo history survive navigating back to a previous page in a multi-page web form? There needs to be some limits placed on this.

Does undo need to be able to occur even once the user has reviewed and saved their action? There needs to be an end-point where the transaction is complete.

**Comment by awkawk** [comment]
Thanks for the comment - the Working Group has not reached consensus on this proposed SC so it is deferred for future consideration.
