### ISSUE TITLE
Oracle comment on 3.2.9 Provide Support

### ISSUE THREAD

**Issue by cwadamsoforacle** [w3c/wcag21#242]
Determining what would help a user in every situation will be very difficult to judge.

Would this SC require that every form on a page have a summary?  For example would a form to reset your password be required to have the text "This form resets your password"?

Would help documents themselves be required to have help? Reference manuals would always be longer than 300 words. I'm not sure what sort of support information we could provide which would help a user.

**Comment by lseeman** [comment]
referencing the issue #32 

we tried to  address this via sufficient techneques - will try and rework it

**Comment by awkawk** [comment]
@cwadamsoforacle Thanks for the comment - the Working Group has not reached consensus on this proposed SC so it is deferred for future consideration.
