### ISSUE TITLE
Clarification on "language versions" within definition of "set of web pages"

### ISSUE THREAD

**Issue by srodriguezvazquez** [w3c/wcag21#244]
Under the definition of "set of web pages", it reads: 

      --> Different language versions would be considered different sets of Web pages.

I would like to suggest that a clarification on what is understood by "language version" (from a technical perspective) is included in WCAG 2.1, either here (under set of web pages) or as a new entry in the glossary. This would facilitate the decision-making process in terms of accessibility compliance in the case of multilingual websites. The rationale for this suggestion is that different localisation strategies may have been adopted to create parallel web content in different languages. When referring to localisation, I am following W3C's definition: https://www.w3.org/International/questions/qa-i18n 

In WCAG-EM 1.0, language versions are considered as individual websites in terms of accessibility compliance: 
_Website in Multiple Versions
    Some websites are available in multiple versions that are independent of one another in use, that is, using one version does not require or depend on using another version of the website. For example, a website may have a mobile version and there may be versions of **a website in different languages that meet this characteristic. Usually each such website version has a different set of URIs.** Such website versions can be considered as individual websites for evaluation._

This would be clearly the case in the following examples, as these language versions are independent of one another in use: 
- http://www.banquemondiale.org/  (FR) and http://www.worldbank.org/ (EN)
- http://en.comune.fi.it/ (EN)  and  http://www.comune.fi.it (IT)

Would it be also the case when the different language versions share the same domain name? For instance: 
- Within www.canada.ca, we have: https://www.canada.ca/en.html (EN) and  https://www.canada.ca/fr.html (FR)
- www.ikea.com, which contains a global gateway to the different locales (www.ikea.com/es; www.ikea.com/ro, etc.)

Thanks

**Comment by joshueoconnor** [comment]
Thanks @srodriguezvazquez. This question may be best addressed by @michael-n-cooper.

**Comment by michael-n-cooper** [comment]
I believe this is a comment on WCAG 2.0 content which we are not addressing in WCAG 2.1. I suggest closing and / or filing in the [WCAG 2.0 repository](https://github.com/w3c/wcag/issues/) for eventual processing there.

**Comment by joshueoconnor** [comment]
Issue logged https://github.com/w3c/wcag/issues/310 as suggested by @michael-n-cooper
