### ISSUE TITLE
Oracle comment on 2.2.7 Animation From Interactions 

### ISSUE THREAD

**Issue by cwadamsoforacle** [w3c/wcag21#246]
For the definition of 'significant animation,' I am having great difficult parsing "animation which continues for more than 3 seconds, or is synchronized with a user action (e.g. parallax scrolling effects), and affects more than 1/3 of the viewport." How does the 'and' apply in this? Does 'affects more than 1/3 of the viewport.' apply to both 'animation which continues for more than 3 seconds' and 'is synchronized with a user action' or just to 'is synchronized with a user action'?

Would an animation which is slower due to network or resource limitations and hence takes longer than 3 seconds in some situations fail this? If it would then this is hard to test in all situations.

**Comment by awkawk** [comment]
@cwadamsoforacle This SC has been changed in ways that we believe address your comment in the latest version (https://www.w3.org/TR/WCAG21/#animation-from-interactions) - thank you for your comment.
