### ISSUE TITLE
Oracle comment on 3.1.9 Extra Symbols

### ISSUE THREAD

**Issue by cwadamsoforacle** [w3c/wcag21#247]
'Topical Pictorial Symbol' needs to be defined. Do the symbols need to be unique for each topic or can standard symbols be used (such as warning sign, stop sign, etc.)?

**Comment by awkawk** [comment]
@cwadamsoforacle Thanks for the comment - the Working Group has not reached consensus on this proposed SC so it is deferred for future consideration.
