### ISSUE TITLE
user information

### ISSUE THREAD

**Issue by lseeman** [w3c/wcag21#25]
Links not working...
-  [ SC for viewing](https://rawgit.com/w3c/wcag21/user-information_ISSUE-25/guidelines/sc/21/user-information.html) | [SC for editing](https://github.com/w3c/wcag21/blob/user-information_ISSUE-25/guidelines/sc/21/user-information.html)
-  [ harm definition for viewing](https://rawgit.com/w3c/wcag21/user-information_ISSUE-25/guidelines/terms/21/harm.html) | [harm definition for editing](https://github.com/w3c/wcag21/blob/user-information_ISSUE-25/guidelines/terms/21/harm.html)
-  [ identify the user definition for viewing](https://rawgit.com/w3c/wcag21/user-information_ISSUE-25/guidelines/terms/21/identify-the-user.html) | [identify the user definition for editing](https://github.com/w3c/wcag21/blob/user-information_ISSUE-25/guidelines/terms/21/identify-the-user.html)
-  [ SC in full draft guideline](https://rawgit.com/w3c/wcag21/user-information_ISSUE-25/guidelines/#user-information)

<h2>SC Shortname: <strong id="docs-internal-guid-f26e61d2-512d-9fa6-c7de-3fc22b2cc08a">User Information</strong></h2>
    <h2>SC text</h2>
    <p dir="ltr"><strong id="docs-internal-guid-f26e61d2-512d-9fa6-c7de-3fc22b2cc08a2">User Information</strong>: Use known techniques to keep sensitive user information safe <span id="docs-internal-guid-9beb1966-67bc-40a5-1342-3a15f296d634">that can be used to <em>identify the user</em> or identify that user may have a disability.W</span>arn users of any known risk.</p>
    <h2>Priority Level</h2>
    <p dir="ltr">A</p>
    <h2>Suggestion for Priority Level (A/AA/AAA)</h2>
    <p>A</p>
    <h2>Related Glossary additions or changes</h2>
    <p><strong>Harm:</strong> Loss of or damage to a person's right, property, or physical or mental well-being. Where it is unclear if something is a damage we consider a test to be that over 80% of random people asked would consider it to be a damage as defined above. </p>
    <p><span id="docs-internal-guid-9beb1966-67c0-8078-4753-d4fa6e3420a3"><strong>Identify the user:</strong> Personally identifiable user information is information that may by itself or in conjunction with other information be used to discover the identity of, locate, or contact a specific perso</span>n</p>
    <h2>What Principle and Guideline the SC falls within.</h2>
    <p>
        Suggested priciple is 2,and we suggest changing guideline 2.3  from</p>
    <ul>
        <li>Do not design content in a way that is known to cause seizures.</li>
    </ul>
    <p>to</p>
    <ul>
        <li>Do not design content in a way that is known to harm users.</li>
    </ul>
    <h2>Description and Benefits</h2>
    <p dir="ltr">Don&rsquo;t store personal information that could be used to harm a user <span id="docs-internal-guid-9beb1966-67be-464c-9583-1f218318556e">without being very careful to minimise any risk to the user</span>.</p>
    <p dir="ltr">Examples: storing information, which suggests a user user has Dementia, may make a target for scams; or storing information, which suggests a user has an intellectual disability, may make a target for predators. </p>
    <p dir="ltr">A predatory company could send requests for money, saying &ldquo;you haven&rsquo;t made your donation&rdquo; despite the user having made one. </p>
    <p dir="ltr">It is vital that users stay safe.</p>
    <p dir="ltr">Another consideration is that many users have weak executive functioning, and are thus less likely to identify risks correctly.</p>
    The benefit of this SC is to keep users safe while online.
    <h3 id="resources2">Related Resources (optional)</h3>
    <p>Issue papers: <a href="https://rawgit.com/w3c/coga/master/issue-papers/safety.html">Online </a></p>
    <p>Also see </p>
    <ul>
        <li><a href="https://rawgit.com/w3c/coga/master/gap-analysis/">Gap analysis </a></li>
        <li> <a href="https://rawgit.com/w3c/coga/master/gap-analysis/table.html">User needs table 1</a></li>
        <li><a rel="nofollow" href="https://w3c.github.io/wcag/coga/user-research.html">Background research document</a></li>
    </ul>
    <h2>Testability</h2>
    <ul>
        <li>
            Step 1. Identify if user information is being stored. (If no, then pass. If yes, then continue.)
        </li>
        <li>Step 2. Identify if one of the known techniques are used. </li>
        <li>Step 3. Identify that the risks are available to users in clear language. </li>
    </ul>
    <br>
    <h2>Acceptable &nbsp;outcomes:</h2>
    <p>
        No to Step 1<br>
        OR
        <br>
        Yes to all three steps.
    </p>
    <h2>Techniques</h2>
    <ol>
        <li>For personalization information: Use functional requirements for personalization that do not suggest &nbsp;users have disablities. </li>
        <li>Use approved security techniques, in your jurisdiction, for sensitive data.</li>
        <li>Obtain approval by the <em>Helsinki Committee for Human Rights</em>, which is a an ethics committee used by the European Union.</li>
        <li>Failure technique to be added: associating a user to a code that is used mainly for people with cognitive disabilities.
        </li>
    </ol>
    <p>Advisory techniques</p>
    <ul>
        <li>Chat options prevent any exchange of personal information.</li>
        <li>Users are regularly warned to avoid scams.</li>
        <li>
            Getting help, and/or reporting something worrying, is easy-to-do, and includes a statement that users will
            never be penalized for reporting something.
        </li>
        <li>
            An easy-to-use feature is provided for users to report to cyber crime fighters in their
            jurisdictions.
        </li>
        <li>
            Easy-to-use videos and tips with explanations provided about cyber criminals, how to stay safe,
            and how to report anything found odd.
        </li>
        <li>Server-side solutions, such as analytics, are employed to find cyber-criminals.</li>
        <li>
            Advertisements and paid articles are clearly marked, as external content, in an easy-to-understand
            way.
        </li>
        <li>Sites offering sexual content, or intended for chats of a sexual nature, state that clearly.</li>
    </ul>
    <p>See also</p>
    <p dir="ltr" id="docs-internal-guid-9beb1966-67bd-a78e-1178-780b2386ae86"><a href="https://www.owasp.org/index.php/Client_Side_Testing">https://www.owasp.org/index.php/Client_Side_Testing</a></p>
    <p dir="ltr"><a href="https://www.owasp.org/index.php/Cross-site_Scripting_(XSS)">https://www.owasp.org/index.php/Cross-site_Scripting_(XSS)</a></p>
    <a href="https://www.owasp.org/index.php/Transport_Layer_Protection_Cheat_Sheet#Rule_-_Keep_Sensitive_Data_Out_of_the_URL">https://www.owasp.org/index.php/Transport_Layer_Protection_Cheat_Sheet#Rule_-_Keep_Sensitive_Data_Out_of_the_URL</a>
        <h2> working groups notes (optional)</h2>
        <p>We could (if needed ) make this AA and make the following A :</p>
        <p dir="ltr">Use known techniques to keep sensitive user information safe <span id="docs-internal-guid-9beb1966-67bc-40a5-1342-3a15f296d">that can be used to  identify that user may have a disability.W</span>arn users of any known risk.</p>

**Comment by joshueoconnor** [comment]
Assigned to Chaohai Ding - https://www.w3.org/WAI/GL/wiki/SC_Managers_Phase1

**Comment by chaohaiding** [comment]
Possible an overlap with Issue #20 Safety and #6 Support Personalization.

**Comment by chaohaiding** [comment]
The user information SC is possible overlapped with some parts of Safety and Support Personalization.

Suggestions to use hashed algorithms to keep sensitive user information. "Use known techniques to keep sensitive user information safe that can be used to identify that user may have a disability.Warn users of any known risk." 

Suggestions for the Related Resources (optional): Issue papers: Issue #20 Safety and #6 Support Personalisation.

For Advisory techniques:

"Users are regularly warned to avoid scams." does this regularly warning cause user distractive, especially for people with cognitive disabilities?

"Sites offering sexual content, or intended for chats of a sexual nature, state that clearly." is overlapped with the Techniques part in Issue #20 Safety, with "Indicating when a site contains or offers sexual content, or is intended for chats of a sexual nature"

Some typos:
1. "Suggested **priciple** is 2 .." in What Principle and Guideline the SC falls within, should be "Suggested **principle**"
2. "Examples: storing information, which suggests a **user user** has Dementia," in Description and Benefits, should "Examples: storing information, which suggests a user has Dementia"
3. "1.For personalization information: Use functional requirements for personalization that do not suggest  users have **disablities**. ..." in Techniques should "disabilities"

**Comment by joshueoconnor** [comment]
@chaohaiding Is there a Pull request ready to go for this?

**Comment by mbgower** [comment]
This seems to be in draft and could be better defined. I feel like it is trying to introduce the notion of privacy into WCAG, which isn’t a defined principle. Certainly many jurisdictions have existing legislation that covers such material. 
This is tied in with concepts of user preferences and personalization, and I suspect that whatever infrastructure is developed in that arena will have to address this. But I don't think such architectural considerations are best in an authoring standard. As it stands, this is far-reaching and not super well-thought out. The techniques are not even techniques.
