### ISSUE TITLE
WebAIM Feedback - SC 1.4.12 – Graphics Contrast

### ISSUE THREAD

**Issue by jared-w-smith** [w3c/wcag21#251]
We believe additional clarification and research is needed regarding the relevance of the current WCAG-defined contrast requirements to modern displays and users. These WCAG formulas and thresholds for contrast are primarily based on research conducted in 2001 on an Amiga 1000 display. Display technology and user adeptness has certainly changed significantly since then, yet few people question the applicability of this research to the modern web. WebAIM will soon be conducting research into human perception of contrasts and mapping this user data to the WCAG thresholds to provide some insight into these questions.

As with the existing text contrast success criteria, additional clarity is needed to define testability of contrast with gradient backgrounds, text (or, in this case, graphical element) borders/shadows, ‘busy’ backgrounds, etc. The 4.5:1 threshold would result in very limited color options in many designs.

WebAIM highly welcomes the addition of a contrast requirement for graphical content, but additional clarity and scope is needed for this success criterion to be viable.

**Comment by awkawk** [comment]
@jared-w-smith The Graphics contrast SC has changed substantially since this comment was submitted. Included in the changes is a 3:1 contrast ratio.
