### ISSUE TITLE
WebAIM Feedback - SC 1.4.14 – User Interface Component Contrast (Minimum)

### ISSUE THREAD

**Issue by jared-w-smith** [w3c/wcag21#253]
This SC is very difficult to understand as written. It simply is not clear which components need to be measured against which other components. Additional clarification is needed. Despite the current lack of clarity, addition of contrast requirements for indicating user interaction states for elements is very welcome.

**Comment by goodwitch** [comment]
@jared-w-smith I'm wondering if the proposed understanding content that is available at the top of issue #10 User Interface Component Contrast (Minimum) is the best way to solve this.  As with many SC (both current and proposed)...the thought patterns that go into truly understanding it take time to absorb.  And some things are best understood via examples (which is why the current draft Understanding has so many examples. 

If you take into account the draft Understanding and examples, do you think this SC can move forward for a wider review as is?  (knowing that refinements will likely be made...but that the core concepts will remain the same).

**Comment by jared-w-smith** [comment]
@goodwitch Yes, the additional content and examples are helpful (though took quite a bit to fully process). But these would be non-normative - I think more could probably be done to tighten the success criterion language itself.

Are there "graphical objects for user interface components" that extend beyond visual focus indicator, selection indicator, and border(s). If not, I think explicitly defining these up front would be most helpful - rather than defining them in a note. It's confusing to not have a sense as to what this applies to until you get to the end of the SC text. This necessitates reading it all at least twice. 

If there are other types of "graphical objects for user interface components", it begs the question of what these possibly might be. It's this type of ambiguity that causes author anxiety.

I'll take some time to see if I can parse this better and maybe propose some ideas, or at least better define what is still confusing to me. Thanks!

**Comment by DavidMacDonald** [comment]
I posted a possible rewording to tighten it up.

https://github.com/w3c/wcag21/issues/10#issuecomment-290120982

except when the component is inactive.

> Definition of visual identifiers of User Interface Components: A visual indication that the component is interactive.   This may be a border, icon, or other visual indication (which doesn't rely on color alone). Focus and selection indicators represent separate states of the interface component which also require these contrast minimums.

If we want the 2 tier contrast 4.5:1 and 3:1 we could still use the same language for the first sentence.

>All essential visual identifiers of user interface components have a contrast ratio of at least 4.5:1, except for the following situations:

**Comment by jared-w-smith** [comment]
@DavidMacDonald Yes! This is much more clear. Very nice! I'll need to go back and review it all in context, but this resolves most of the questions I had about scope and applicability.

**Comment by goodwitch** [comment]
@DavidMacDonald and @jared-w-smith 

I love this rewording!  For the moment, I'm going to leave the "definition" as a "note"...because when I make it a definition (at this point) confusion sets back in.  We can move it to the glossary after we settle on the proposed SC language as a larger group.

**Comment by goodwitch** [comment]
@jared-w-smith I've updated the SC text at issue #10 User Interface Component Contrast (Minimum).  Let me know if this resolves this issue.

**Comment by jared-w-smith** [comment]
@goodwitch solicited additional comments.

I still think that additional clarity would be very helpful. For example, it references "user interface components", which is a VERY broad term. But this is defined just below as being "A visual indication that the component is interactive." - a MUCH narrower scope.

Why not just combine these and reword as "All essential visual indicators that a user interface component is interactive have..."? This is, I think, much more clear and removes the need for a broad term that is defined more narrowly elsewhere in the SC text itself.

The exceptions are not worded as exceptions, but instead as additional statements that must be considered. The Inactive definition is oxymoronic - it refers to "inactive user interface components", but you've defined "user interface components" as being "interactive". Something can't be inactive and interactive at the same time.

How about:
> ... except for the following situations:
> 1. Minimum width and height: Where the essential visual indicators have a minimum width and height of at least 3 CSS pixels and a contrast ratio of at least 3:1.
> 2. Inactive: Where the component is disabled or otherwise inactive.

**Comment by goodwitch** [comment]
@jared-w-smith I love your rewording suggestion to change the SC from:

> "All essential visual identifiers of user interface components have a contrast ratio of at least 4.5:1 against the immediate surrounding color(s)"
> 
> to
> 
> "All essential visual identifiers **that a** user interface component **is interactive** have a contrast ratio of at least 4.5:1 against the immediate surrounding color(s)"

And I've implemented this change!

As for the exceptions, I'm going to leave them as is for now.  I patterned this proposed SC after WCAG 2.0 SC 1.4.3 Contrast (Minimum).  

1.  "Thicker" vs "Minimum width and height" - I have a sneaking suspicion that this SC will be simplified to only include one color contrast ratio requirement and the "thicker"/"min width and height" piece will get dropped.  So, I'm not going to wordsmith it.  But if I'm wrong, and that part stays in...we can revisit.
2. "Inactive user interface component" is an already published normative phrase in [WCAG 2.0 SC 1.4.3 Contrast Minimum ](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html).  See "Incidental: Text or images of text that are part of an **inactive user interface component**, that are pure decoration, that are not visible to anyone, or that are part of a picture that contains significant other visual content, have no contrast requirement."

**Comment by Ryladog** [comment]
I am confused with "All essential visual identifiers that a user interface component is interactive have a contrast ratio of at least 4.5:1 against the immediate surrounding color(s)"....

Maybe: "All essential visual identifiers that is an interactive user interface component have a contrast ratio of at least 4.5:1 against the immediate surrounding color(s)"

**Comment by Ryladog** [comment]
Improved/corrected: "All essential visual identifiers that are interactive user interface components have a contrast ratio of at least 4.5:1 against the immediate surrounding color(s)"

**Comment by jared-w-smith** [comment]
@Ryladog The issue with your wording is that it conflates the visual identifiers with the user interface components. These often would be separate things.

As an example, a focus outline is a visual identifier, but the link or form control that outline surrounds is the user interface component. Similarly, for a button with an icon and text, the visual identifier is only the graphical components of the icon and button, but the interface component is the button itself (which comprises the icon, the text, some whitespace, etc.). We're only concerned about the contrast of the visual identifiers, not all aspects of the component itself.

@goodwitch I truly hope the "Thicker" exemption doesn't go away. Consider my last example above - a button with a "thick" icon and large text ("large" as defined in 1.4.3). The text of the button would be AA conformant with 3:1 contrast, yet if there is no "Thicker" exemption, the icon must then have 4.5:1 contrast. This seems rather constraining.

**Comment by goodwitch** [comment]
@jared-w-smith good news...if the "thicker" part goes away...I bet the only color contrast requirement for "visual identifiers that a user interface component is interactive" would be 3 to 1.  Theory is that reading letters (and needing to see the fine detail of each letter) requires 4.5 to 1.  But that 3 to 1 on user interface components will be sufficient...even for low vision users yet.  Jury is still out on this...but I don't think 4.5 to 1 is gonna get consensus.

**Comment by Ryladog** [comment]
@jared-w-smith My point is, is this correct English?  "All essential visual identifiers that a user interface component is interactive have a contrast ratio of at least 4.5:1 against the immediate surrounding color(s)"....I don't think so....

**Comment by jared-w-smith** [comment]
@goodwitch Ah! This makes a lot more sense. Thanks!

It would, of course, be optimal if these were all addressed in one place in WCAG - a 3:1 threshold for everything at Level A, then everything 4.5:1 at AA (except the Large Text/Thicker Interface Components at 3:1), then everything at 7:1 at AAA (except Text/Thicker Interface Components at 4.5:1).

@Ryladog Yes, the wording is a bit odd. How about...
"All essential visual identifiers that indicate that a user interface component is interactive have a..."?

**Comment by Ryladog** [comment]
@jared-w-smith Yes!! Much better....:-)

**Comment by goodwitch** [comment]
Ooooo @Ryladog I like that.  @jared-w-smith what do you think?  Do you like Katie's proposed wording change?
