### ISSUE TITLE
WebAIM Feedback - SC 2.1.4 – Speech Input

### ISSUE THREAD

**Issue by jared-w-smith** [w3c/wcag21#256]
“All functionality of the content does not obstruct…” is difficult to understand and measure. Suggested rewording – “Commands that can be triggered via speech input are not obstructed by author-defined functionality.”

This success criteria presents two scenarios. The first is when a user speaks a word that matches a functional element on the page, and the speech control software triggers that functional element without user’s intending to do so. Assuming that speech control actually worked this way (my experience has been that triggering functionality requires additional speech activation, such as speaking “Click Products” rather than simply “Products”), the only way to avoid this conflict would be for authors to either not provide functional elements or not use words to define them. This clearly is untenable. This is an obscure user agent issue that should not be of concern to authors.

The other scenario presents a situation where a button that visually presents the text “Submit” is not identified with this text semantically, thus causing the voice control user to not know how to activate this control. This scenario is somewhat covered by other success criteria in 2.0, but is not covered at all by this proposed SC text. Restructuring this SC to address this issue would be a welcome improvement – perhaps “Interface controls have programmatically determined text that matches or is equivalent to the visually presented text or functionality of that control”… or similar.

WebAIM does not support the adoption of this SC as drafted.

**Comment by awkawk** [comment]
@jared-w-smith This SC has been substantially changed in the latest version (https://www.w3.org/TR/WCAG21/#accessible-name) - thank you for your comment.
