### ISSUE TITLE
WebAIM Feedback - SC 2.2.6 – Timeouts

### ISSUE THREAD

**Issue by jared-w-smith** [w3c/wcag21#257]
This Level A success criterion is generally untestable. There’s no way to objectively measure “easily return”, “simple action”, or “simple, understandable language”. This also omits obvious exceptions where time limits are essential or unavoidable.

It is not reasonable or appropriate to ask authors to record all user actions and states (presumably even client-side ones), and then provide seamless loss of data for users that abandon and then return to an activity up to a week later. There are many instances where the user states cannot possibly be tracked. In many instances, such tracking would be unethical and illegal – the example scenario suggests that a travel site must store and _then re-present_ a user’s credit card number after a week, even without user permission to do so.

The requirement to inform the user ahead of time would seemingly necessitate lengthy and confusing informative messages on all pages that have timed components – “Your session will time out in 20 minutes. You will have a five minute warning period before you are logged out and will have 120 seconds to respond to this warning message.” The complexity of such a warning may introduce more difficulty and overhead than the timeout itself.
The primary issues introduced by timeouts are already generally addressed via the existing 2.1.1 SC (Level A).

WebAIM does not support the adoption of this SC as drafted, but may support a clarified and improved version at Level AAA.

**Comment by lseeman** [comment]
#14

**Comment by awkawk** [comment]
@jared-w-smith This SC has been substantially changed in the latest version (https://www.w3.org/TR/WCAG21/#timeouts) - thank you for your comment.
