### ISSUE TITLE
WebAIM Feedback - SC 2.2.8 – Interruptions (minimum)

### ISSUE THREAD

**Issue by jared-w-smith** [w3c/wcag21#259]
This success criterion is at odds with 2.2.1 and 2.2.6 which prescribe pop-ups and notifications to inform of time-outs. It also conflicts with the new SC 3.2.8 (Change of Content) which requires that users be notified of content changes. How can authors inform users of a time-out or content change to meet one success criterion when such notifications are disallowed by another?

“Interruptions” is not clearly defined. Are dynamic form validation messages (such as slightly delayed indications of an unavailable username) “interruptions”? Auto-complete suggestions? Chat messages or new e-mail notifications that are a core function of an application? In cases where interruptions are important, but not an “emergency”, critical functionality could be lost, thus resulting in notable negative impact on the user experience.

Until standard mechanisms are available for client-side control over such interruptions, the only mechanism for meeting this success criterion is via a user control, which itself introduces cognitive load and comes at notable author effort. This would be at odds with important and critical messaging systems in modern web applications.

WebAIM would support adoption of this SC, but only at Level AAA.

**Comment by joshueoconnor** [comment]
Thanks for the comment - this SC is under active review by the working group  - your suggestion to support this SC at AAA is noted. Closing this comment  [1] https://www.w3.org/2002/09/wbs/35422/interruptions-minimum-review/results
