### ISSUE TITLE
WebAIM Feedback - SC 2.4.11 – Single-key Shortcuts

### ISSUE THREAD

**Issue by jared-w-smith** [w3c/wcag21#260]
The explanation of the success criterion indicates that it is intended to stop conflicts with voice control software triggering single-key shortcuts in a page. This seems to clearly fall into the realm of the voice control user agent to distinguish dictation input from activations of user controls. If voice control software triggers an “A” shortcut anytime this letter or a word containing this letter is voiced (at least not without a qualifier – “Click A”), this clearly is a user agent deficiency, not an authoring issue.

However, the SC language (“Single-character shortcuts are not the only way activate a control, unless…”) does not generally help in this scenario at all – an author simply needs to provide an additional “way” for the user to get this functionality. For example, the presented scenario of “Y” triggering Gmail’s “archive message” functionality would never be a failure because additional interface options are available to perform this functionality (e.g., an “Archive Message” interface button). It would be relatively rare for authors to rely _entirely_ on a shortcut key to trigger such functionality.

This SC should additionally be clarified to only apply to author-defined shortcuts, and not to user-agent shortcuts. And only to alpha-numeric shortcuts, not Esc (to close menus/dialogs) or Space (to trigger checkboxes), for example. Otherwise this would cause authors to override user-agent functionality, such as creating a custom select input because the browser otherwise provides single-key functionality (e.g., hitting “U” on a State select menu jumps to “Utah”). This could also be interpreted to prohibit auto-complete functionality (for example) which provides varying controls/options with each individual key press.

This SC also discourages the use of single-key shortcuts which can be extremely useful for many other users with disabilities, primarily users with visual or motor disabilities that rely on efficient keyboard interactions. It would be very atypical for a Level A SC to discourage a technique that provides long-standing, accessibility-supported functionality for many users in order to address the needs of a small audience of users in an extremely narrow scope of applicability – when users with voice control software (that is incapable of differentiating user input from activation of user controls) errantly voice a command that matches a single-key short defined in an application that doesn’t have an alternative for that functionality or an option to customize or disable that shortcut. This seems more suited for AAA or as an advisory technique.

WebAIM does not support the adoption of this SC as drafted, but may support a clarified and improved version at Level AAA.

**Comment by DavidMacDonald** [comment]
I suggest a meeting with Kim who is the champion of this SC. Summary of your comments:
- should only refer to alpha numeric keys that are used in dictation
- should be scoped to page level, not component level (i.e., drop down first letter navigation - not sure its actually done that way, need to investigate that.
- explain better that AT (Dragon) use context base switching between dictate and function mode and single keys mess that up.
- further investigation necessary into single key shortcuts currently in use to help other disabilities.

**Comment by DavidMacDonald** [comment]
> This SC also discourages the use of single-key shortcuts which can be extremely useful for many other users with disabilities, primarily users with visual or motor disabilities that rely on efficient keyboard interactions. 

@jared-w-smith  We understand from experts for Dragon users that this is real problem. The solution can be well addressed in a standard such as WCAG. It's testable, implementable etc...

The SC allows sites to use single key shortcuts if they provide a way to turn them off. This seems like a reasonable balance of the needs of two groups. It's not hard to provide a mechanism to disable shortcuts on a page. The button would tell the JavaScript to stop calling those key bindings.

Is there research on single key shortcuts for people with motor disabilities that you would like to point us to? Or a group you think we should discuss this with?

**Comment by KimPatch** [comment]
We've narrowed the "single-key shortcut" language to "single-character-key shortcut" in the text, maybe we should do this in the title as well to prevent misunderstanding going forward.

@jared-w-smith Yes, single key shortcuts are good for some users, there just needs to be a way for speech users to turn them off and access that functionality in a different way. That's what the SC is addressing. Fixing this inherent problem for speech users this way makes it easier for authors to provide singlekey shortcuts for those who want them without making a page dangerous for speech users. 

Let me know if the SC understanding is not clear on why single-character-key shortcuts are clash with speech input.

Thanks for the point about scoping to page level – I like your fix @David McDonald

**Comment by jared-w-smith** [comment]
This wording changes should address the context concerns I had.

> Or a group you think we should discuss this with?

I'd start with the folks that designed this functionality in Dragon. It still seems very odd to have an SC that asks _all_ authors to implement and evaluate a workaround to a somewhat isolated issue that is present in one user agent (Dragon). In the effort that we've taken to author, analyze, and discuss this, Nuance certainly could have implemented functionality to prevent single key events being passed to the page.

I also think this is adequately covered already by UAAG. Nuance's lack of responsiveness to web standards should not result in significant author/evaluation effort. Could you imagine the outcry if a SC were written to specifically address a JAWS bug or deficiency? I have difficulty supporting an SC that does the same for Dragon.

**Comment by mraccess77** [comment]
I'd also point out that single key shortcuts can affect screen reader users badly too.  Just now I thought I was in forms mode with JAWS and I started typing and was taken to a new page because the keys I was typing was tied to a Google single key shortcut.

**Comment by KimPatch** [comment]
Ah – this is not just Dragon, it's an inherent issue with speech input in general.  It's not Nuance's lack of responsiveness to web standards, but an inherent problem with the way speech works – speech is a string of characters so therefore you can pass a whole bunch of characters at once by saying a phrase.

**Comment by jared-w-smith** [comment]
Has anyone contacted voice software vendors about this? Do they even know it's an issue that they could address? I'll admit that I'm not highly familiar with speech input beyond Dragon. I'd be happy to look further into this. What other software does this affect beside Dragon? 

Again, I'm not discounting that this is an issue, but it's not just a voice input issue - it's an input issue - and one that has generally been addressed in other user agents (though not without some difficulty, as @mraccess77 pointed out).

VoiceOver, for example, fully addresses the single key conflict (and potential 'mode' confusion issues) with their input model. This SC would be entirely irrelevant to VO and other user agents that already address this.

It still just feels wrong to ask authors to address something that can and (I think) should be addressed at the user agent level. This feels like WCAG is requiring a "skip link" type hack to address a user agent deficiency. But I could certainly be convinced that this is simply unfixable in voice control software, and that it is really a pervasive issue that only authors can address through additional functionality.

Speaking of "skip links", there has been a significant push for browsers to support single key navigation for headings and landmarks. This would provide significant benefit to many users - and would likely negate the need for "skip links" and AT to provide this navigation functionality. There are extensions and browsers that provide this functionality already. If this functionality is broadly adopted, this SC would then be directly at odds with built in user agent functionality that is intended to address accessibility and usability concerns.

**Comment by KimPatch** [comment]
I'm highly familiar with speech input and have talked with several dozen folks from Nuance over the last two decades about many issues including this one. This is been dogging speech users for years. 

This issue affects any speech input. It's unfixable. Single character key shortcuts are simply not appropriate in a speech input environment. 

If you have access to any speech input program try using it with Gmail – not just a quick demo, but for real work for an hour or so. If you don't have access to speech input but you do have access to a toddler who will occasionally randomly step on your keyboard, you'll run into something similar. It's okay when the random keys just type some gobbledygook in a document that you can backspace away, but it's a much bigger problem when the random keys delete, archive and mute messages and you are left to untangle it.

**Comment by jared-w-smith** [comment]
> This issue affects any speech input. It's unfixable.

It what ways it it "unfixable"?

It does not seem untenable for this software to provide an option or functionality to simply restrict the passing of single key shortcuts to the page. Every other type of AT has been able to reasonably address this. Why not speech input? What makes it distinctly different from every other input mechanism?

I'm not just abjectly arguing with you, I'm sincerely trying to understand why this should be an authoring requirement rather than a speech input software solution. This is the exact question authors are going ask a million times over if this is adopted.

**Comment by mraccess77** [comment]
@jared-w-smith I think it's the keyboard interface that is available.  If you consider what options are available you would get something like this:
* Paste in text
* use an API to send text
* Send the text as individual keys

Sending the keys individually was likely chosen because it is the most reliable solutions across technology and triggers other corresponding structures simulating someone actually typing.

Also, I'd argue that this issue could affect screen readers also.  Screen reader users in forms/focus mode might try to use quick navigation keys and might inadvertently send keys to the app causing changes such as going to other pages.

**Comment by DavidMacDonald** [comment]
WCAG  has always tried to approach its standard from a perspective of practical help for users with disabilities. We never would have required accessibility support otherwise, a11y support simply means that no matter what you do it has to work with AT. As so WCAG does require authors to work around bugs if the bugs cannot be overcome by an alternative AT.

I wouldn't call this a bug in Dragon... but it is a challenge. There have been efforts to address it, which have been unsuccessful. I'd say this is a good candidate for something that fits in WCAG's vision. 

1. It helps users w/ disabilities who have a real need
2. its not onerous for authors to do, fairly trivial to turn off single key shortcuts
3. Its testable 
4. it's a long standing problem

I'd say let's proceed with it addressing concerns as they arise.

**Comment by DavidMacDonald** [comment]
I've turned it a more positive requirements rather than a "thou shall not" to "if ..." This fix turns it from a "don't" statement to an "if". Focusing on providing a mechanism to turn them off than than not doing them.

> If single key shortcuts are used THEN a mechanism....

**Comment by carmacleod** [comment]
Just a comment on this https://github.com/w3c/wcag21/issues/260#issuecomment-292207992:
> Speaking of "skip links", there has been a significant push for browsers to support single key navigation for headings and landmarks. This would provide significant benefit to many users - and would likely negate the need for "skip links" and AT to provide this navigation functionality. There are extensions and browsers that provide this functionality already. If this functionality is broadly adopted, this SC would then be directly at odds with built in user agent functionality that is intended to address accessibility and usability concerns.

The latest (really nice!) cross-browser [landmarks extension](http://matatk.agrip.org.uk/landmarks/) uses multi-key shortcuts by default. This is definitely preferable for keyboarding through landmarks in a web application, because it allows navigation to the next/previous landmark from within any element, including input, select, menu, textarea, and contenteditable elements, as well as authored components like lists and trees, all of which [can or should] accept single-characters as input.

**Comment by joshueoconnor** [comment]
Note - latest version of this SC https://www.w3.org/TR/WCAG21/#character-key-shortcuts

**Comment by joshueoconnor** [comment]
@DavidMacDonald  can this be closed?

**Comment by awkawk** [comment]
Thank you for your comment. Since your comment was logged we have changed the SC and believe that the new SC language (see in editor's draft: http://rawgit.com/w3c/wcag21/master/guidelines/index.html) addresses your concerns.
