### ISSUE TITLE
WebAIM FeedbackSC 2.5.2 – Pointer inputs with additional sensors

### ISSUE THREAD

**Issue by jared-w-smith** [w3c/wcag21#262]
An exception should be added for when additional pointer sensor information is critical to the functionality. WebAIM otherwise supports adoption of this SC as drafted.

**Comment by detlevhfischer** [comment]
I have added a proposal of new SC wording that includes an exception in [my comment to Microsoft's comment on Pointer inputs with additional sensors](https://github.com/w3c/wcag21/issues/194#issuecomment-292544125)

**Comment by awkawk** [comment]
@jared-w-smith Thanks for the comment - the Working Group has not reached consensus on this proposed SC so it is deferred for future consideration.
