### ISSUE TITLE
WebAIM Feedback - SC 2.5.4 – Pointer Gestures

### ISSUE THREAD

**Issue by jared-w-smith** [w3c/wcag21#264]
For touch interfaces, because 2.5.3 (above) seemingly requires alternative mechanisms (such as a “a mobile menu button”) for all simple pointer gestures (and, presumably, all complex ones too), this seems to be a moot requirement if 2.5.3 stands as is. Why would an author provide a simple gesture alternative for a complex gesture when both the simple and complex gestures require a standard button alternative? Or perhaps we’re misinterpreting all of this.

This would have a notable impact on many standard and (potentially) otherwise conformant interfaces, such as Google Maps, many mobile interfaces, etc. WebAIM supports the general intent of this success criterion, but it seems best aligned with Level AA.

**Comment by detlevhfischer** [comment]
For reference:
- This comment #264 refers to issue [#61 Pointer gestures](https://github.com/w3c/wcag21/issues/61). In the WCAG 2.1 draft, this is [SC 2.5.4 Pointer Gestures](https://www.w3.org/TR/WCAG21/#h-pointer-gestures)
- In the comment, Webaim link _Pointer Gestures_ to issue [#63 Touch with Assistive Technology](https://github.com/w3c/wcag21/issues/63). In the WCAG 2.1 draft is [SC 2.5.3 Touch with Assistive Technology](https://www.w3.org/TR/WCAG21/#h-touch-with-assistive-technology).

**SC 2.5.4 Pointer gestures** looks at the default scenario of use, i.e. a situation where assistive technology that remaps gestures is NOT turned on. Users should be able to position a pointer (mouse cursor, finger) over a target, then activate it, without having to drag (or, on touch interfaces, execute complex gestures). **2.5.3 Touch with Assistive Technology**, on the other hand, checks whether all functions can still be operated / activated when the OS screenreader (like VoiceOver or TalkBack) is turned on by the usual means of traversing elements via swiping and activating them by double-tapping.

Take an example:
For a slider widget, meeting _SC 2.5.3 Touch with Assistive Technology_ would require that the slider would need at least one of the following things: 
1. an alternative input (say, `input type="number"`) with a label specifying the value range
2. buttons to increment / decrement the value
3. discrete points along the range that can be screen reader-focused and activated to update the value 

The same slider would already meet _SC 2.5.4 Pointer gestures_ if any single tap on the range would move the thumb there - i.e., there would be no need to pick up the thumb and move it along the range.

**Comment by awkawk** [comment]
@jared-w-smith Thank you for the comment. An updated version of this SC is available at https://www.w3.org/TR/WCAG21/#pointer-gestures
