### ISSUE TITLE
WebAIM Feedback - SC 2.6.2 – Orientation

### ISSUE THREAD

**Issue by jared-w-smith** [w3c/wcag21#265]
This success criterion also seems to be primarily focused on user agent flexibility, not on authoring practices. It is not generally possible for users to fully restrict the device orientation of web content. And if this is or were made possible, would it not be incumbent on the user agent to allow end user override or customization of this (just as they should allow resizing of pixel-defined text, pinch-to-zoom functionality, etc.)?

The problem that is being addressed by this success criteria is either generally non-existent for web content, or needs to be clarified so authors understand what techniques to avoid.

**Comment by mraccess77** [comment]
@jared-w-smith This link https://developer.mozilla.org/en-US/docs/Web/API/CSS_Object_Model/Managing_screen_orientation discussion future support for locking the orientation in web content.  This SC is concerned with web content authors locking the orientation in a way that prevents users from using a different orientation that works for them (with exceptions for essential situations).

**Comment by awkawk** [comment]
We can clarify this in the understanding document

**Comment by awkawk** [comment]
@jared-w-smith Are you ok with this response at this time? We will be clarifying this in the understanding document.

**Comment by jared-w-smith** [comment]
To take a step back, I'd think this could be better addressed by working with the Screen Orientation API folks (https://w3c.github.io/screen-orientation/) to remove the screen.orientation.lock functionality (which still has very limited support). There would seemingly be no implementations of that part of the API that would not violate WCAG 2.1. Certainly there's a potential significant conflict between W3C specifications here. It just seems a stretch for a WCAG SC to distinctly address one portion of a relatively obscure and generally unsupported API that probably shouldn't exist in the first place if that W3C group had any consideration for accessibility.

I also still suggest that clarifying that this applies to author (not user) locking of orientation in the SC language rather than the non-normative documentation would be notably better. There've been several comments recommending this important change.

But these concerns would not stop our support of this SC as written.

**Comment by jared-w-smith** [comment]
@steverep Thank you for pointing out the discussion on #509. That provides clarification on how the API could be utilized and also support this SC. This, however, presumes that the author-provided controls to lock orientation are initially presented in the user's native device orientation. If someone with a mobility disability is presented with those controls in the wrong orientation, it's rather difficult to change the orientation to an accessible one if they can't access them to begin with.

**Comment by steverep** [comment]
Yep, you're right.  Unfortunately, that adds a bit more complexity to language alterations being discussed in that issue, but I can try to incorporate.

**Comment by mbgower** [comment]
> If someone with a mobility disability is presented with those controls in the wrong orientation, it's rather difficult to change the orientation to an accessible one if they can't access them to begin with.

@jared-w-smith, the mechanism would still be on the screen in the wrong orientation and still be actionable, would it not? At worst, a sighted user might need to read the text at a 90 degree angle, which does not seem to represent a significant deterrent for locating a single control.
Am I missing a scenario, or do we have data on user groups that would be unable to interpret a control with text oriented on the other axis?

**Comment by jared-w-smith** [comment]
> At worst, a sighted user might need to read the text at a 90 degree angle, which does not seem to represent a significant deterrent for locating a single control.

If accessing critical controls at a 90 degree angle isn't a deterrent, then why have this SC at all?

>do we have data on user groups that would be unable to interpret a control with text oriented on the other axis?

Not that I'm aware of... which is precisely why the assumption you've made about it not being a deterrent is worrying.

**Comment by steverep** [comment]
I lean towards Jared's thinking on this, and would add the thought of multiple disabilities.  Someone who needs a fixed orientation may also have visual or cognitive disabilities, in which case it could be a show stopper.

**Comment by mbgower** [comment]
> Someone who needs a fixed orientation may also have visual or cognitive disabilities, in which case it could be a show stopper.

Fair enough. But what I was trying to flag was whether this consideration was on a level that it can be dealt with in understanding and techniques, as opposed to needing to go into the SC language.

So if the technique that covers use of this API includes language about this, is that sufficient? Does the existing SC language support us making a failure technique covering someone invoking the API without determining the current orientation of the device?

**Comment by steverep** [comment]
> Does the existing SC language support us making a failure technique covering someone invoking the API without determining the current orientation of the device?

Well, the existing language hasn't even been changed to allow the API, but I would say that most proposals to fix that thus far would prevent documenting such a failure.

**Comment by awkawk** [comment]
Latest version: “Content does not restrict its view and operation to a single display orientation, such as portrait or landscape, unless a specific display orientation is essential.”

We hope this addresses your concern better.
