### ISSUE TITLE
WebAIM Feedback - SC 3.1.7 – Plain Language

### ISSUE THREAD

**Issue by jared-w-smith** [w3c/wcag21#266]
This success criterion has the following issues:
- It is nearly impossible to test due to high levels of subjectivity and an inability to measure to the vague terms and definitions provided.
- It is confusing and (ironically) does not meet its own requirements for plain or concrete language
- It is not applicable to a wide array of web content
- Many of the requirements seem arbitrarily defined and lacking in research-based evidence (e.g., why 1500 most common words as a maximum?)
- How would the 1500 most common words be defined in a way that is accurately testable? Would these be defined in normative WCAG for all languages? If not, the changes to external lists of common words would cause the conformance of content to be subject to changes in language usage over time. This would require significant and frequent testing to determine if all words used are still on the “common” list.
- It relies on mechanisms for user-defined content customization (such as automatically replacing non-literal text with a literal alternative) that do not yet exist. In absence of such techniques, authors must then provide very onerous mechanisms to provide such alternatives programmatically (and these controls would themselves be inherently complex for users to parse).
- It imposes editorial and content restrictions that extend well beyond the scope of WCAG, particularly for Level A conformance

While clearly well-intentioned (many of these **best practices** would certainly do much to improve understandability for many users), this success criterion is too rigid, too restrictive, and too subjective to be reasonably applied by authors to the majority of web content.

WebAIM does not support the adoption of this SC as drafted.

**Comment by lseeman** [comment]
refrencing this comment  #30

**Comment by lseeman** [comment]
@jared-w-smith /webaim, can you give us more specifics? for exampole can you site us some content to which this scope does not apply (please read the exceptions)

**Comment by awkawk** [comment]
Thanks for the comment - the Working Group has not reached consensus on this proposed SC so it is deferred for future consideration.
