### ISSUE TITLE
WebAIM Feedback - SC 3.1.8 – Manageable Blocks

### ISSUE THREAD

**Issue by jared-w-smith** [w3c/wcag21#267]
Like 3.1.7, this success criterion may not be applicable to many instances of content. It seems much too restrictive and difficult to understand and test. Additional research is warranted into these defined thresholds. Does this apply to verbal/auditory “statements” as well as text “statements”?

WebAIM supports adoption of this SC, but only at Level AAA.

**Comment by awkawk** [comment]
@jared-w-smith Thanks for the comment - the Working Group has not reached consensus on this proposed SC so it is deferred for future consideration.
