### ISSUE TITLE
WebAIM Feedback - SC 3.2.6 – Accidental Activation

### ISSUE THREAD

**Issue by jared-w-smith** [w3c/wcag21#269]
Additional clarification of “single-pointer activation” is warranted, otherwise WebAIM supports adoption of this success criterion, though it seems best aligned with Level AA.

**Comment by joshueoconnor** [comment]
This definition has been newly added to the https://www.w3.org/TR/WCAG21/#dfn-single-pointer 
For device specific information see the Pointer Events spec https://www.w3.org/TR/pointerevents/
