### ISSUE TITLE
Clear Text and Voice

### ISSUE THREAD

**Issue by lseeman** [w3c/wcag21#27]
<h2>SC Shortname: Clear Text and Voice</h2>
		        <h2>SC Text</h2>
		        <p><strong>clear text and voice:</strong> Provide clear typography (text and numbers), punctuation, and voice (speech) for readability and comprehension.</p>
<p>Exception: If a specific typography, punctuation, content (text or voice) is  essential.</p>
                <h2>Suggestion for Priority Level (A/AA/AAA)</h2>
                <p>AA</p>
		        <h2>Related Glossary additions or changes</h2>
		        <p>Clear typography (font ), punctuation, or voice is one that is:</p>
                <ul>
                  <li>backed up by user research where COGA users are part of the user testing; or</li>
                  <li>identified in a known WCAG technique; or</li>
                  <li>identified by user preferences (preferred); or</li>
                  <li>defined by an international standard.</li>
                </ul>
		        <h2>What Principle and Guideline the SC falls within</h2>
		        <p>We suggest a new guideline under Principle 3 &quot; <strong>Provide a clear structure and layout</strong>&quot;.</p>
		        <h2>Description and Benefits</h2>
		        <p>The intent of this SC is that users do not need to spend extra cognitive function deciphering letters, numbers, and words, and can focus on understanding the meaning of the content. When words are hard to read or discriminate, users with language-related disabilities will fully focus on identifying the letters, and on building the words. They then have to piece together the words to build the sentence. However, there is a limit to how many cognitive tasks a person can do at the same time. If so much energy is put into identifying the words, it is often not possible to also understand the meaning of a sentence. </p>
<p>This may be avoided by making the task of reading and identifying words easier, so that the user can focus on the meaning.</p>
		        <p>If identifying words takes too much of a user's focus, the content will not be understood, making it not usable.		        </p>
		        <h3><span property="xhv:role" resource="xhv:heading">Layout for Numbers</span></h3>
		        <p>Check use of white space and punctuation; and characters between numbers. Use of spaces and commas within numbers can change how text-to-speech engines read it. This confuses <span id="docs-internal-guid-9beb1966-67fd-20ef-f6f0-9f2dd942d435">people with cognitive disabilities</span>.</p>
		        Where any numbers are presented, their use needs to be considered. If they are representing dates, times, references, telephone numbers, or mathematical notation, their layout impacts on users' understanding. Users need not only to recognize standardized layouts, but also to understand the meaning as the numbers are read aloud by text-to-speech engines. This feature can provide those with dyscalculia, dyslexia, and attention deficit disorder, and those who may be under high-cognitive load or situationally disabled, with a better understanding of the concepts.
		        <h5 id="example-1">Example</h5>
		        <ul>
		          <li>Reference numbers compared to a quantity or a value, e.g., "Ref: 7241500", as opposed to "7,241,500 chickens".</li>
		          <li>Telephone numbers have localized layouts. Text-to-speech readers cope in different ways with the layout. Thus, a telephone symbol and/or a word for telephone/mobile/cell phone, alongside the number, can help avoid confusion.</li>
</ul>
		        <h4><span property="xhv:role" resource="xhv:heading"> Roman Numerals</span></h4>
		        Roman Numerals should be presented in upper case if used in isolation.
<p>Roman Numerals can be presented as lower case or upper case, especially when used with musical notation. However, these may not always be recognized by text-to-speech engines, or may be confused with other navigational elements, such as numerical bullet points. Use of Roman Numerals is not always easily understood. The use of this format for isolated numbers impacts on comprehension for those with dyscalculia, dyslexia, and attention deficit disorder, and should be avoided if possible.</p>
		        <h5 id="examples-5">Examples<span typeof="bookmark"><a href="#roman-numerals" aria-label="Permalink for Examples" title="Permalink for Examples" property="url"><span property="title" content="Examples">§</span></a></span></h5>
		        <p>Text-to-speech engines will try to read the lower case Roman Numeral as a word, e.g., "vi" instead of "VI" - read as /vie/ instead of six.</p>
		        <p><strong>Pass example: </strong>Roman Numerals presented in upper case if used in isolation.</p>
		        <p>Note that a blind person may also be dyslexic, or have a language disability.		        </p>
                <h3 id="resources2">Related Resources </h3>
		        <p>"Am I making myself clear?" Mencap's guidelines for accessible writing http://www.easy-read-online.co.uk/media/10609/making-myself-clear.pdf</p>
                <p>"Top Five Instructional Tips for Students with Down syndrome" http://specialedpost.org/2013/01/31/top-five-instructional-strategies-for-students-with-down-syndrome/</p>
<p>"Down syndrome and Learning" http://inclusive.tki.org.nz/guides/down-syndrome-and-learning/</p>
                <p>See http://www.bdadyslexia.org.uk/about-dyslexia/further-information/dyslexia-style-guide.html<a href="http://dyslexiahelp.umich.edu/sites/default/files/good_fonts_for_dyslexia_study.pdf" title="http://dyslexiahelp.umich.edu/sites/default/files/good_fonts_for_dyslexia_study.pdf"><br>
                </a></p>
                <p><a href="http://dyslexiahelp.umich.edu/sites/default/files/good_fonts_for_dyslexia_study.pdf" title="http://dyslexiahelp.umich.edu/sites/default/files/good_fonts_for_dyslexia_study.pdf">http://dyslexiahelp.umich.edu/sites/default/files/good_fonts_for_dyslexia_study.pdf</a></p>
                <p>Rello et al 2013 - <a href="http://taln.upf.edu/content/biblio/578" title="http://taln.upf.edu/content/biblio/578">http://taln.upf.edu/content/biblio/578</a></p>
                <p><abbr title="World Wide Web Consortium">W3C</abbr> working group draft F82: Failure of Success Criterion 3.3.2 by visually formatting a set of phone number fields but not including a text label <a href="http://www.w3.org/TR/WCAG20-TECHS/F82.html">http://www.w3.org/TR/WCAG20-TECHS/F82.html</a></p>
		        <p>University of Loughborough DDIG - personal perceptions of dyscalculia and Dyspraxia<a href="http://www.lboro.ac.uk/departments/mec/activities/maths-statistics-support/thedyscalculiaanddyslexiainterestgroup/personalperspectives/">http://www.lboro.ac.uk/departments/mec/activities/maths-statistics-support/thedyscalculiaanddyslexiainterestgroup/personalperspectives/</a>.</p>
		        <p>Toepoel, V., Das, M. and van Soest, A. 2006. Design of web questionnaires: The effect of layout in rating scales, Tilberg, , The Netherlands: Tilburg University. (Discussion Paper No. 2006â€30, CentERdta)<a href="https://www.researchgate.net/profile/Vera_Toepoel/publication/4784408_Design_of_Web_Questionnaires_The_Effect_of_Layout_in_Rating_Scales/links/0deec520de9f388043000000.pdf">https://www.researchgate.net/profile/Vera_Toepoel/publication/4784408_Design_of_Web_Questionnaires_The_Effect_of_Layout_in_Rating_Scales/links/0deec520de9f388043000000.pdf</a> (accessed 5th june, 2015)</p>
<p>Hartley, J. and Betts, L. 2010. Four layouts and a finding: the effects of changes in the order of the verbal labels and the numerical values on Likertâ€type scale scores. International Journal of Social Research Methodology, 13: 17-27</p>
                <h3><strong>COGA links </strong></h3>
                <ul>
                  <li> <a href="https://rawgit.com/w3c/coga/master/gap-analysis/table.html">User needs table (table number 5)</a></li>
                  <li><a rel="nofollow" href="https://w3c.github.io/wcag/coga/user-research.html">Background research document</a></li>
                  <li> <a rel="nofollow" href="https://rawgit.com/w3c/coga/master/issue-papers/links-buttons.html">Semantics for adaptive interfaces</a></li>
                </ul>
                <p> issue papers</p>
<ul>
                  <li><a href="https://rawgit.com/w3c/coga/master/issue-papers/multi-modal.html">Multi-modal Content Delivery</a></li>
                  <li><a href="https://rawgit.com/w3c/coga/master/issue-papers/payments.html">Online Payments</a><br>
                  </li>
                  <li><a href="https://rawgit.com/w3c/coga/master/issue-papers/math.html">Numbers and Math</a></li>
                </ul>
                <p><a href="https://rawgit.com/w3c/coga/master/techniques/index.htm">COGA Techniques</a>                </p>
		        <h2>Testability</h2>
		        <ol>
		          <li><span id="docs-internal-guid-9beb1966-67ff-0668-60c8-b4d577e48eb5">Are fonts (text and numbers), punctuation, and voice (speech) known to be clear from the WCAG techniques?</span></li>
		          <li>If not, can the  font, clear punctuation, or voice be changed via an interoperable user setting?</li>
		          <li>If not, has the font, punctuation, or voice usability been tested via user testing with at least five users with reading disabilities?</li>
</ol>
		        <p>Pass result is a yes to one of the above questions.</p>
		        <h2>Techniques</h2>
<ul>
                  <li>Use a plain, evenly-spaced, sans-serif font, such as Arial or other  simple typography, with good spacing, appropriate kerning, and leading, to separate text and  darker-weight fonts. (List of good fonts.)</li>
                  <li>Use appropriate punctuation and spacing when representing numbers and times.</li>
                  <li><span id="docs-internal-guid-9beb1966-6800-62b4-548a-f58f99386413">For left to right languages, use left justification with ragged right edge.</span></li>
                  <li><span id="docs-internal-guid-9beb1966-6800-9ed3-b944-6d4c956e6892">For right to left languages, use right justification with ragged left edge.</span></li>
                  <li>Take care to use bold text just for key items.</li>
				  <li>Avoide using <em>italics</em>, ALL CAPS, or underline for emphasis.</li>
                  <li>Make important information two font sizes bigger.</li>
                  <li>Numbers
                    <ul>
  <li>Reference numbers compared to a quantity or value, e.g., "Ref: 7241500" as opposed to "7,241,500 chickens".</li>
  <li>Telephone numbers have localized layouts. Text-to-speech readers cope in different ways with the layout. Thus, a telephone symbol and/or a word for telephone/mobile/cell phone, alongside the number, can help avoid confusion.</li>
  <li>Numbers representing specific concepts can be recognized by their layout, as well as being read aloud accurately by text-to-speech engines.</li>
  <li>Roman Numerals presented in upper case if used in isolation.</li>
                    </ul>
                  </li>
                </ul>
<2>Failures</h2>
<ul>
  <li>Changing fonts in the same region.(List)</li>
  <li>Using all capital letters inappropriately. </li>
  <li>Using non-standard font alternatives, such as "Cufo'n".</li>
  <li>Roman Numerals presented in lower case.</li>
  <li>Numbers fail to conform to recognized layouts, and are not read aloud accurately by text-to-speech engines.</li>
</ul>         
  <h2> working groups notes (optional)</h2>

**Comment by jspellman** [comment]
It seems as though a lot of this proposal has already been covered in other proposals.  I think this proposal should be revisited once we get other proposals approved to see what is included in this proposal that still isn't covered.   We have a responsibility to the people that use WCAG to be careful not to give potentially contradictory advice by using different wording in different success criteria on the same topic.

**Comment by mbgower** [comment]
The thing that surprised me the most about this SC was that after providing a generic description and benefits section, all examples and guidance is almost exclusively about numbers.
The techniques provide more and broader information; perhaps some of that should be discussed earlier.
My gut instict is that talking about voice is prescriptive, but I haven’t taken the time to really think it through. I still feel that portions of this could be combined with Clear Structure and Relationships successfully.

---
### Description

> If identifying words takes too much of a user's focus, the content will not be understood, making it not usable.

I’d remove this paragraph. It’s already been said a few ways.

### Layout for Numbers

Since this section is currently restricted to whitespace and punctuation, I wonder if this makes sense to combine with Clear Structure and Relationships?

>Check use of white space and punctuation characters between numbers...

What about proximity of numbers or positioning in a sentence?  I find it a bit odd that some of the common usage requirements for numbers are not spelled out here. I located an article that does a decent job of summarizing [number usage that is common amongst many style guides](http://www.getitwriteonline.com/archive/093003Numbers.htm).

Regarding the giant paragraph that begins "Where any numbers are presented..."
Based on the COGA guidance for Simple Language, this should be a set of bullets. I’ve noticed that many of the COGA SC do not follow the Manageable Blocks of Information requirements. Can't help seeing this as a problem with the level of prescription in that SC -- that even the members of the COGA task force are producing material that fails its requirements.

> text to speech engines

I think there needs to be an explanation here that the reading of digits can be controlled by some assistive technologies, which may group large numbers into sets of 2 or more digits (e.g., an ID number of 412191 might be read as “41 21 91” or “412 191” ). 
You have used the term ‘text to speech engines’ as a generic term; I just wanted to point out that "speech synthesizer" used to be the proper term. As long as you feel TTS now includes such physical or software devices, this is fine.

---
### Techniques
> Use a plain, evenly spaced sans serif font such as Arial 

I am very surprised to see this guidance, given last time I looked, there was no consensus on the readability of sans verus serif typefaces. For a discussion, please see [Alex Poole’s summary](http://alexpoole.info/blog/which-are-more-legible-serif-or-sans-serif-typefaces/) of the topic.

>Avoide using italics, ALL CAPS, or underline for emphasis.

First, note the typo on "avoid". More importantly, this is partially odd advice, given that the HTML emphasis tag <em> creates italics. As well, there is a convention to make sparse, redundant use of Allcaps for emphasis since it is surfaced by all screenreaders, unlike bold and italics (e.g., DO NOT turn off the computer without saving your work.) 

> Make important information two font sizes bigger

Ugh! Please remove this. It is advocating conveying information solely by its presentation, with no mention of programmatic equivalency. Madness.

**Comment by lseeman** [comment]
@jspellman can you tell me where the overlap is specifically? I can not see it but it might be a LV one
@mbgower i think there is a strong consensus for LD people because it is easier for people with a low visual memory 
The 2 fonts bigger technique should be deleted. Dont worry about the techniques and description too much. At this point we just need a header of a technique to show the idea that there will be at least one  supporting  technique. We can not edit that stuff npow anyway
