### ISSUE TITLE
WebAIM Feedback - SC 3.2.7 – Familiar Design (Minimum)

### ISSUE THREAD

**Issue by jared-w-smith** [w3c/wcag21#270]
It’s difficult to comment on this success criterion because it is mostly unintelligible and untestable.

How does one measure “easily identifiable and available”? This is not defined.

Why were only “help, navigation to help, and search forms” identified for this design requirement? Is this based on research?

Does this require that all pages provide these three items? Or does this only apply in cases where these are already present?

How can a “platform specific user interface design” apply to web content which is, by its nature, not platform specific? How would an author know what these design patterns are (short of defining them all in normative content)? When platform specific design patterns change, does content that was previous conformant suddenly become non-conformant?

Measuring whether a “design was used successfully by users in a prior version” may not be possible to authors lacking access to a time machine. Why would success in a prior version be relevant to success in the current version? How would an author know that a user needs the fall-back to the prior version short of the user indicating this? Or must the fall-back always be provided (thus making it the primary version, not a fall-back)? Providing a fall-back to a prior “successful” version for only these critical elements would likely violate 3.2.4 which requires consistent identification of such items.

If understood correctly, this would prescribe very specific and rigid design constraints for what are often (by nature of usability) the most prevalent and important items within web content and applications.

WebAIM strongly opposes the adoption of this SC as drafted.

**Comment by Thad-Code** [comment]
Hi, Jared. Thanks for the feedback. I have read your feedback and understand that in its current state WebAIM opposes adoption. In your opinion, could this proposal be reworded to achieve the intended goal or is the intention unclear?

**Comment by jared-w-smith** [comment]
@Thad-Code I'm not sure. I think that significant restructuring of this success criterion is needed to bring it to the necessary level of testability, etc. for WCAG. 

I certainly think these recommendations are a great idea to support cognitive accessibility. They are noble goals and good practices. But I don't think that most of this could be rewritten in a way that would allow it might reach a level where we'd support its inclusion in WCAG. I'd certainly be happy to review and provide feedback on any modifications made to it.

**Comment by Thad-Code** [comment]
Thank you, Jared. At very high-level I have typically considered this SC to be an example of the usage of common UX patterns, although I can't represent the view of the entire TF with that sentiment without speaking to them. We have a call to discuss this SC and I will let you know the outcome.

**Comment by awkawk** [comment]
@jared-w-smith Thanks for the comment - the Working Group has not reached consensus on this proposed SC so it is deferred for future consideration.
