### ISSUE TITLE
WebAIM Feedback - SC 3.2.8 – Change of Content

### ISSUE THREAD

**Issue by jared-w-smith** [w3c/wcag21#271]
This SC is generally supported by WebAIM. It is, however, unclear how the “5 notifications per minute” exemption applies. Because these notifications would generally be triggered by user activation, if the interface allows more than 5 activations per minute, does this success criterion no longer apply? Because one can’t generally control the number of user activations, how is this testable?

Or is this suggesting that after 5 notifications in a minute that the author can disable the notification and still be conformant? In this case, can the notifications be disabled from thenceforth, or must they be re-enabled as soon as the “5 per minute” threshold no longer is applicable (e.g., no longer than 1 minute after the last activation)?

Or is this only intended for notifications that are not user activated, such as an interface that updates content automatically more than 5 times per minute? Clarification on this exemption is needed.

As an editorial note, the definition of “Programmatic notification” is not linked from the success criterion.

Assuming clarification of the above, WebAIM supports adoption of this success criterion.

**Comment by DavidMacDonald** [comment]
Let's work together on this. The intention of the 5 activations per minute was not user activated... it was for web site generated updates such as basketball scores or stock tickers etc... we're open to suggestions.

**Comment by jared-w-smith** [comment]
"Programmatic notification is provided for each change of content that conveys information..." seems adequate. Any notification "that indicates an action was taken" must necessarily convey content, so this seems redundant, right?

Scores or stock ticker would often be "the primary purpose of the page", but 5 or fewer per minute, so not exempted. Such automatically generated changes of content could be very difficult to parse in many cases - 5 per minute that take 12 seconds each, for example.

I thus tend to lean toward notifying of only user-activated changed to content, though that leaves a gap that doesn't cover **important** auto-generated stuff (with "important" inherently being unmeasurable), though many of these cases are covered by other SC (timeouts, error notification, etc.).

How about...

> Programmatic notification is provided for each change of content that conveys information, unless one or more of the following is true:
>
> There is an accessibility supported relationship between the changed content and the control that triggers it.
> The user has been advised of the behavior before using the component.
> The change of content is not a result of a user action AND not related to the the primary purpose of the page.
> The change of content is not a result of a user action AND the changed content remains on the page after the change occurs.

This last item covers the score/ticker issue because the changed content is still readable on the page - there's no need to force them to the user via aria-live, for example. Also, I changed "new content" to "changed content".

As an editorial note, there are 11 instances of "accessibility-supported" and 17 of "accessibility supported". Consistency is needed.

**Comment by awkawk** [comment]
@jared-w-smith The "5 notifications" language has been removed in the latest draft.https://www.w3.org/TR/WCAG21/#change-of-content
