### ISSUE TITLE
WebAIM Feedback - SC 3.3.7 – Minimize user errors

### ISSUE THREAD

**Issue by jared-w-smith** [w3c/wcag21#272]
This necessitates manipulation of user-entered data in ways that could violate data integrity and usability (e.g., a potential failure of 3.2.2 On Input – Level A).

As stated in the Editor’s Note, “common input error” needs additional clarity without relying on non-normative content.

Errors “that have been reported or documented more then [sic] one time” is unmeasurable. This would also create a scenario whereby conformant content could be immediately rendered non-conformant simply by a user reporting an error. How is a “report” defined or measured?

“…and there is a known way to identify them”. Known to whom and in what ways?

Interpretations of “where the corrections can be reliably made” would vary greatly and would certainly be contextually, culturally, and technologically dependent.

WebAIM opposes the adoption of this SC as drafted.

**Comment by lseeman** [comment]
#13

**Comment by awkawk** [comment]
@jared-w-smith Thanks for the comment - the Working Group has not reached consensus on this proposed SC so it is deferred for future consideration.
