### ISSUE TITLE
WebAIM Feedback - SC 3.3.8 – Undo

### ISSUE THREAD

**Issue by jared-w-smith** [w3c/wcag21#273]
“Users are provided with the ability…” Does this require author-supplied mechanisms? Is the Back button sufficient?

“Clearly labeled” is subjective and unmeasurable. “… get back to the place they were at” is ambiguous. Which place? For how long after the action must the user be able to undo and be returned to “the place”? Must a vendor allow a user to “undo” a financial transaction?

“… unwanted loss of data” is subjective to the user, not to the author, and is thus unmeasurable.

This proposed Level A SC would generally render existing 3.3.4 (Level AA) and 3.3.6 (Level AAA) regarding Error Prevention moot because this would require a significantly higher level of error recovery.

Barring significant changes and clarifications, WebAIM strongly opposes the adoption of this SC as drafted.

**Comment by awkawk** [comment]
Thanks for the comment - the Working Group has not reached consensus on this proposed SC so it is deferred for future consideration.
