### ISSUE TITLE
WebAIM Feedback - SC 3.3.9 – Provide Support

### ISSUE THREAD

**Issue by jared-w-smith** [w3c/wcag21#274]
“Content is provided that helps users understand…”. This alone makes this SC untestable. What types of content? How is this content provided? How can one measure whether content helps or does not help user understanding? How much must it help? Which users?

Are there examples of types of “content” that should be provided to help users understand “forms”?

Is there some research-based metric for defining “long documents” as over 300 words? How would providing additional content always aid in understanding content that is already “too long”?

Requiring additional content would increase cognitive load and could decrease understandability for some users with cognitive or learning disabilities. WCAG success criteria that pose such potential conflicts are typically defined at Level AAA.

While well-intentioned and intended to provide best practice guidance, this success criterion is confusing, untestable, and untenable for most web content. WebAIM opposes the adoption of this SC as drafted.

**Comment by lseeman** [comment]
referencing the issue #32 
We should probably go back to the original words which then got moved to sufficient techniques

**Comment by awkawk** [comment]
@jared-w-smith Thanks for the comment - the Working Group has not reached consensus on this proposed SC so it is deferred for future consideration.
