### ISSUE TITLE
Valitity Tests

### ISSUE THREAD

**Issue by WayneEDick** [w3c/wcag21#276]
Algorithm to Test for Adaptation: Spacing and Font Family.
Spacing of text
1. For each content element E that contains text do the following:
set line height 1.5, letter spacing to 0.12 em, and word spacing to 0.16 em.
Pass Test for Spacing: 
1.	Does the page content still fit within the bounds of the containing regions? (e.g. does overflow its boundaries?)
2.	Do words wrap at the end of lines. (e.g. Do lines of text ever run off the page?)
3.	Do content regions enlarge in a way that enables finding all content?
If 1, 2, and 3 pass then the page passes.
Font Family
Pick a font that will maximize disruption.
Example:(Latin characters)
For languages that use Latin alphabets the widest font family will disrupt the format most. From a set of commonly used font families pick the widest. For our set of commonly used fonts we can choose “safe” fonts or use some other reasonable criterion. The criterion for width can be devised in many ways so long as the method is consistent. Print all visible characters out in Unicode order. Pick thee font with the longest string. Use that as the standard font for sufficiency.  An author that passes with that font has satisfied the criterion.
Each language should have a “chosen family” for maximum disruption.
For each language in your page substitute in the chosen family for that language.
Pass Test for Font Family
Apply the Pass Test for spacing given above.

**Comment by lauracarlson** [comment]
Hi @WayneEDick  , @allanj-uaag , and all,

I started a page for this technique in the Wiki: [Allowing for Spacing Override](https://www.w3.org/WAI/GL/wiki/Allowing_for_Spacing_Override).  Will need to add examples.

In addition the start of the understanding doc is in GitHub: [Understanding Adapting text](https://rawgit.com/w3c/wcag21/adapting-text_ISSUE-74-78-79/understanding/21/adapting-text.html).

As always, ideas for improvement  are welcome and appreciated.

Thanks!
Laura

**Comment by awkawk** [comment]
Closing since Laura has collected the info from this issue into a wiki page.
