### ISSUE TITLE
Not accepting SC that we cannot live with ourselves - on our ancillary web pages and our tools

### ISSUE THREAD

**Issue by GreggVan** [w3c/wcag21#278]
I am against accepting/including any requirement that we are not willing and able to apply to our own tools and ancillary pages.    
The working group as a whole has to select SC that are practical.  If things are proposed that we do not know how to meet — or that we are not willing to live with ourselves — then we should not be requiring it of others.  

- I can understand that we can't control the W3C and its website.  
             (I think that is a real shame - but that is outside of the control of the WCAG WG.)
-  But  choosing our tools is not.  So I don't think we should require something - especially at Level A  (or Level AA actually) - that we are not willing to live by ourselves.

We AT LEAST 

- need to be able to prove that it can be done.   
- And if there are tools that we could be using - we should be using them rather than things that are convenient or more efficient but inaccessible. 
--  If there ARE no accessible alternatives 
--  AND we show that the tool we are using COULD meet the guidelines
-- then that is a different matter.  

But otherwise…..    we need to walk the walk — not just talk the talk.

**Comment by mraccess77** [comment]
I take this as a motion to move from github to other tools for this work.  I'm not willing to give up on adapting text in order to keep Github and seems like this is the choice that you have presented.  Do you have a suggestion on what tools we should use Gregg?

**Comment by GreggVan** [comment]
Thanks for asking.

 No I’m not at all saying that we should stop using Github and moved to another tool.

I am just saying that if there is a tool that would meet our guidelines we should be using it.
 Or at the least, we should prove that the tool were using could be designed to meet all of our rules.

Unless there was some way of moving everything we had in tact to a new tool, it would be a nightmare to try to move now. And his him but he pointed out, we couldn’t have chosen a tool in the first place that met 2.1 because we had defined 2.1 yet.

So my comment isn’t that we should move off of GitHub.   But rather, that we should know, and demonstrate, that Github  could be designed to meet all of our success criteria. If there are any success criteria that we cannot figure out how to design Github  to meet, then we shouldn’t be promulgating that success criteria is a required success criteria for general use. In other words, we shouldn’t be promulgating a success criteria that we cannot figure out how to make work on major websites.    that would fail our “generally applicable” requirement


g

**Comment by DavidMacDonald** [comment]
I does seem odd that the issue tracker of Github is designed using table layout... seems very 1990's.    I think switching to DIVs would solve the horizontal scroll problem... 

I'm thinking there may be some crazy engineering reasons for this Github hack of the table element. I hope its not because they just decided to for know good reason. But anyway... there is the fix IMHO. Stop using tables.

**Comment by GreggVan** [comment]
maybe suggest it to them.

will your solution work on all browsers?  (it might not have back when they created it ) 

G

**Comment by DavidMacDonald** [comment]
Yes DIVs work in all modern browsers... Github was started in 2007, I'm not sure if there has been any change to the codebase besides window dressing since then. It would mean a major change in the platform for them to switch to DIVs... there are 14 million users.

**Comment by etisdew** [comment]
As a follow up has there been any success communicating with github?

**Comment by awkawk** [comment]
A useful comment but closing as this is a process comment rather than a comment on an SC specifically.
