### ISSUE TITLE
Trace Comment on Success Criterion 2.2.8 Interruptions (minimum)  Level AA

### ISSUE THREAD

**Issue by GreggVan** [w3c/wcag21#283]
This is another SC I would like to see. 
Interruptions are like animations and can destroy some people’s productivity. 

1.	GOOD that you defined ‘easily available’ in concrete terms. 
2.	You need to define emergency I think.  It will be hard, but it is crucial to the SC so take a stab at it.
3.	I think you need to add “or essential part of the function” or some such.  I worry about adding it but I can think of too many places where you need to have the exception or this SC kills content.    
For Example 
  -  How about a chess game  (or any game) when you are playing the computer.
  -  Someone rings the doorbell   (not an emergency)
  -  It is a simulation
  -  Etc 
4.	What does “as wide a scope as possible” mean?    
     a.	Nice to see GPII in the examples – but I'm not sure what it is an example of? 
     b.	Do you mean “can be set one time via a global variable that applies across websites”? 
5.	Should the second bullet be  “can be set one time and it will apply across pages within the website”   ?
6.	The third bullet sounds like this Level AA provision requires conformance to Level AAA provisions.     Suggest changing end to read  “ can be invoked from each screen where it may be needed, and the path and the control conform at level AA.

**Comment by joshueoconnor** [comment]
@lseeman That this has been iterated, is in the editors draft etc, can this be closed?https://www.w3.org/WAI/GL/wiki/Decisions

**Comment by awkawk** [comment]
This SC has been removed from the draft, so closing this issue.
