### ISSUE TITLE
"Accidental activation" unduly excludes desirable accessibility applications

### ISSUE THREAD

**Issue by jasonjgw** [w3c/wcag21#285]
Consider a Web application that uses haptics, for instance vibration or related means of conveying information, to provide non-visual access to users with disabilities. It is essential to the activity that the user's finger be on the touch surface (e.g., a touch screen) in order to perceive the haptic effect. Therefore, if the application responds to touch events by generating a haptic response, the activity would be invalidated by requiring it to react only to the up event, as the user's finger would then no longer be in contact with the surface and hence the user could not perceive the output.
Similarly, consider a sonification application that generates audio as the user's finger traverses a map or a graph on a touch screen. Again, precluding a response based on the touch event would invalidate the purpose of the activity.
Neither of these issues relates to timing, hence the exception stated as the final list item in the current proposal does not apply here.
I think the easiest solution is to broaden the scope of the exception to cover all cases in which responding to the "down" activation event is essential to the activity. An alternative would be to exclude cases in which the activation causes the application merely to present information rather than to change its state, but I think the distinction between presenting information and changing state is difficult to draw in this context in a way that would be reliable.

**Comment by DavidMacDonald** [comment]
Makes sense, how about: 

> The "down" activation event is essential to the activity and waiting for the up-event would invalidate the activity.

**Comment by patrickhlauke** [comment]
i wouldn't think the haptics nor the sonification example are cases of *activation* though? nothing precludes applications from doing "something" before the up event (like providing feedback or output). the SC is only concerned with triggering an action (following a link, actually pressing a button, etc)

**Comment by DavidMacDonald** [comment]
I think the commit addresses the concern and perhaps others like it without compromising the requirements of the SC.
