### ISSUE TITLE
Latest draft not rendering SCs

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/wcag21#289]
None of the the Success Criteria are showing on the new draft 

https://w3c.github.io/wcag21/guidelines/

**Comment by michael-n-cooper** [comment]
This is because the include files aren't processed when run through the automated commit hook. I've been working on this, but it seems to be a deep problem with Respec. Things work viewed in the browser in rawgit, it's just the automatic generation to github.io that's failing.
