### ISSUE TITLE
Consistent Navigation

### ISSUE THREAD

**Issue by lseeman** [w3c/wcag21#29]
<h1>Consistent Navigation</h1>
<h2>SC Text</h2>
<p><strong>Current:</strong><br>
3.2.3 Consistent Navigation: Navigational mechanisms that are repeated   on multiple Web pages within a set of Web pages occur in the same   relative order each time they are repeated, unless a change is initiated   by the user. (Level AA)</p>
<p><br>
  <strong>Proposed:</strong></p>
<p>3.2.3 Consistent Navigation: Navigational mechanisms that are   repeated on multiple Web pages within a set of Web pages occur in the   same relative order each time they are repeated, unless a change is   initiated by the user. @@Common  navigation, search, and   control elements have a consistent  position within a set of web   pages in the primary modality of the content, <span id="docs-internal-guid-9beb1966-6804-c193-be68-b6ff65ee8ec7">unless a change is initiated by the user.</span>@@</p>
<p>Exception: If an inconsistent layout is an essential part of the main function of the site.</p>
<p> </p>
<h2>Suggestion for Priority Level (AA)</h2>
<p>AA</p>
<h2>Related Glossary additions or changes</h2>
<p>Define the primary modality of the content as modalities considered in the design of the content.</p>
<h2>What Principle and Guideline the SC falls within.</h2>
<p>Principle 3, Guideline 3.2</p>
<h2>Description</h2>
<p>The intent of this success criterion is to  ensure consistent position of common  navigation, search, and   control elements  that appear repeatedly within  a set of Web pages. For example,  controls and menu items consistently positioned across a site.</p>
<h2>Benefits</h2>
<p>  Many users with cognitive and learning disabilities rely heavily on their  familiarity with Web page  components. If identical functions are found in different places, on different Web pages, the Web site will be considerably more  difficult to use. It will be confusing, and increase the cognitive load for  people with cognitive disabilities, increasing mistakes, and limiting some users from accessing the  content. This supports those who have reading and some visual perceptual   difficulties due to Receptive Aphasia, as well as   those with general cognitive learning disabilities. It also helps those   with visual acuity difficulties, where stroke and age-related   disabilities co-occur. Also,  users with memory impairments will need to learn a lot more  to be able to use the Web site, making it impossible for some. Therefore, consistent  styles will increase the number of people who can use the Web site, and will help many others.</p>
<p><br>
</p>
<h2>See also</h2>
<p>Computers helping people with special needed, 14 international   conference ICCHP 2014 Eds. Miesenberger, Fels, Archambault, Et. Al.   Springer (pages 401). Paper: Tablets in the rehabilitation of memory   impairment, K Dobsz et. al.</p>
<p>Neilson-aging</p>
<p>The Aphasia Alliance's Top Tips for 'Aphasia Friendlier' Communication   taken from   http://www.buryspeakeasy.org.uk/documents/Aphasia%20Alliance%20Aphasia%20Friendier%20Communication.pdf</p>
<p>Phiriyapkanon. Is big button interface enough for elderly users, Malardardalen University Press Sweden 2011.</p>
<p><br>
</p>
<h2>COGA Resources </h2>
<ul type="disc">
  <li><a href="https://rawgit.com/w3c/coga/master/gap-analysis/table.html">User needs table       ( Table 5: Simple and clear interface )</a></li>
  <li><a href="https://w3c.github.io/wcag/coga/user-research.html">Background       research document</a>&nbsp;</li>
  <li><a href="https://rawgit.com/w3c/coga/master/issue-papers/links-buttons.html">Semantics for       adaptive interfaces</a></li>
  <li><a href="https://rawgit.com/w3c/coga/master/techniques/index.htm">COGA Techniques</a> (See https://rawgit.com/w3c/coga/master/techniques/index.html#be-predictable)</li>
</ul>
<h2>Testability</h2>
<p>Step 1. Ensure (by  inspection) all components, including navigation components  and icons, are positioned consistently.<br>
</p>
<h2>Techniques</h2>
<ul>
  <li>Using CSS to consistently  position common  navigation, search, and   control elements. </li>
  <li> Using a template to consistently  position common  navigation, search, and   control elements. </li>
</ul>
<p><strong>working groups notes (optional)</strong><br>

**Comment by joshueoconnor** [comment]
Assigned to Thaddeus Cambron (@inclusiveThinking) https://www.w3.org/WAI/GL/wiki/SC_Managers_Phase1

**Comment by inclusiveThinking** [comment]
The phrase "the primary modality of the content" may be confusing. In the definition the term "modalities" is used to define itself. Is there another term or definition that uses less complex language?

**Comment by lseeman** [comment]
the primary modality of the content are the setting and  physical machine interfaces considered at design time such as screen, touch, speech or mouse
Is that clearer?

**Comment by inclusiveThinking** [comment]
Yes, much. It is OK to include that as the term definition?
_primary modality of the content_ - the setting and physical machine interfaces considered at design time such as screen, touch, speech or mouse

**Comment by lseeman** [comment]
sure. put it in the pull request when you are ready

All the best

Lisa Seeman

LinkedIn, Twitter





---- On Tue, 24 Jan 2017 07:39:42 +0200 Thaddeus&lt;notifications@github.com&gt; wrote ---- 

Yes, much. It is OK to include that as the term definition?
 primary modality of the content - the setting and physical machine interfaces considered at design time such as screen, touch, speech or mouse

**Comment by patrickhlauke** [comment]
unless i'm mistaken, this proposed change wants to add "position" as another thing that doesn't change across sets of pages, rather than just relative order? if so, a more terse amendment would perhaps be something along the lines of

"3.2.3 Consistent Navigation: Navigational mechanisms that are repeated on multiple Web pages within a set of Web pages occur in the same relative order @@ *and position in the overall page layout* @@ each time they are repeated, unless a change is initiated by the user. "

which would also avoid any further talk of modalities?

**Comment by detlevhfischer** [comment]
To me it feels as if "the same relative order" implies position (within order) and is not really necessary. I also think that reference to "the primary modality of the content" is unnecessary - we know that stuff will often look different depending on breakpoints and that something like consistency of position is meaningful just within one partcular breakpoint rendering, not across several.
I do not see how this significantly improves on 3.2.3 Consistent Navigation but maybe I have msised something.

**Comment by inclusiveThinking** [comment]
Thank you @patrickhlauke  yes, the definition of consistent design would include consistent position. @lseeman do you have an issue with the suggested change of wording:

"3.2.3 Consistent Navigation: Navigational mechanisms that are repeated on multiple Web pages within a set of Web pages occur in the same relative order @@ and position in the overall page layout @@ each time they are repeated, unless a change is initiated by the user. 

Are we losing some of the benefit provided by the phrase "the primary modality of the content" if we replace with "and position in the overall page layout "?

**Comment by inclusiveThinking** [comment]
Does the following change help with some of the concerns:
3.2.3 Consistent Navigation:Navigational mechanisms that are repeated on multiple Web pages within a set of Web pages occur in the same  position in the overall page layout each time they are repeated, unless a change is initiated by the user.

**Comment by inclusiveThinking** [comment]
If there is no feedback to the last comment then moving forward. Thanks for all the feedback above.

**Comment by patrickhlauke** [comment]
"relative order" - to me at least - implies order in which things are in the DOM and can be reached/tabbed to when navigating sequentially, which can be quite distinct from the visual/layout position (think absolute positioning, flexbox reordering, floating, etc). As such, I'd be more inclined to keep it as originally suggested, i.e.:

> 3.2.3 Consistent Navigation:Navigational mechanisms that are repeated on multiple Web pages within a set of Web pages occur in the same relative order and position in the overall page layout each time they are repeated, unless a change is initiated by the user.

**Comment by joshueoconnor** [comment]
@inclusiveThinking Can you give me a status update on this please? Will there soon be a PR on this or do you need more time?

**Comment by inclusiveThinking** [comment]
I will make a PR this eventing

**Comment by lseeman** [comment]
I am ok with losing the words  "in the primary modality of the content"
Also we are trying to make the all stand alone so we do not want it to be a change to 3.2.3 but make it a completely independent SC

i think that makes it 
Consistent position: Common navigation, search, and control elements have a consistent position within a set of web pages unless a change is initiated by the user

**Comment by inclusiveThinking** [comment]
Thanks for the input all. What is the process for making the final Pull Request based on comments above.

**Comment by mbgower** [comment]
> Common navigation, search, and control elements have a consistent position within a set of web pages in the primary modality of the content, unless a change is initiated by the user.

This seems to me to be merely demonstrative. It doesn’t alter the basic short description’s meaning, and I don’t think needs to be included.

> Exception: If an inconsistent layout is an essential part of the main function of the site.

I assume this line is just a piece of boiler plate; I can’t think of an example of such a site. I’m not sure how valuable it is to have a boiler plate exception. It somewhat diminishes the significance of real exceptions.

> Therefore, consistent styles will increase the number of people who can use the Web site, and will help many others.

We’re not talking about styles here. Was this cut and pasted from another draft SC and just not updated, or is there a consideration for styles in this SC? It is the only occurrence of the word on the page.

---
### Testability
>Step 1. Ensure (by inspection) all components, including navigation components and icons, are positioned consistently.

This “all components” test seems to overreach the SC.

---
### Techniques

> Using a template to consistently position common navigation, search, and control elements.

This bullet is a variation on an existing advisory technique. The CSS technique is new. The other existing techniques are missing. In most of the sections of this SC (Description, Benefits), I've been trying to understand how the content here fits with the existing SC.

**Comment by lseeman** [comment]
Agreed with the overreach in the test section @mbgower and the edits to the discription needs to be reviewed
It is ok if something is an advisory technique is now a sufficient technique now. Making something a requirement is a significant change
