### ISSUE TITLE
Meta-issue: use of issues for collaborative work

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/wcag21#290]
Putting this here mainly for future reference, so feel free to close it as deferred to Silver or something. And it's certainly something that I've mentioned previously on list.

Using "Issues" to shape/rework proposed SC text was, in hindsight, the wrong choice in my view. The whole idea of git/github is that you have a versioning system that allows branching, proposed pull requests for changes, code reviews, code comments (down to very granular line-level comments), etc. And because of the versioning, it's always easy to see how a particular change came to be, jump to a previous state, fork from there, and so on.

So why did we end up using "Issues" instead, the one thing in Github which is NOT versioned? On many of the long proposed SC issues, it's now become increasingly difficult to work out what the latest proposed overall wording of an SC is. In some cases, the first post of the SC has been edited to reflect the latest thinking...and this immediately removes any context of comments made on the issue up until that point, as the previous wording that people were commenting on has disappeared after the edit.

It's too late now, but in future may I suggest that a more appropriate approach would have been to set up a new fork of existing WCAG 2.0, possibly with a new sub-folder for each individual proposed SC, and any refinement/discussion on each individual SC to be done as part of a pull request (and only keeping an issue thread pointing to those PRs for higher-level discussions)?

**Comment by awkawk** [comment]
Patrick, I agree that the process with GitHub has been challenging. I think that you are right that we should reconsider this in the future. Part of the consideration should be the level of familiarity with forks and pull requests.
