### ISSUE TITLE
Support Personalization (Enhanced)

### ISSUE THREAD

**Issue by lseeman** [w3c/wcag21#309]
**SC Shortname**

Support Personalization (enhanced)

**SC Text**
In content implemented using markup languages,  contextual information for controls, symbols and regions can be programmatically determined using a publicly available vocabulary. (AAA)

- [contextual information  definition for viewing](https://rawgit.com/w3c/wcag21/support-personalization_ISSUE-6/guidelines/terms/21/contextual-information.html) | [contextual information   definition for editing](https://github.com/w3c/wcag21/blob/support-personalization_ISSUE-6/guidelines/terms/21/contextual-information.html)

**Level**
AAA

See issue #6 for benefits
 
Techniques:  Semantic and markup techniques in issue #6

**Comment by awkawk** [comment]
Closing because both AA and AAA versions are covered in Issue 6.
