### ISSUE TITLE
Consistent Cues

### ISSUE THREAD

**Issue by lseeman** [w3c/wcag21#31]
<h2>SC Short name</h2>
		        <p><strong>Consistent Cues</strong></p>
		        <h2>SC Text</h2>
		        <p> Provide Consistent Cues: 
	            Within a set of web pages, consistent cues are provided that identify different content types, and  the state of elements and regions, which help the user understand their roles or  states.</p>
<h2>Suggestion for Priority Level (A/AA/AAA)</h2>
<p>(AA)</p>
		        <h2>Related Glossary additions or changes</h2>
		        <p>Content types: The type and function of a content element. Content types are typically defined in HTML tag names, ARIA roles, or personalization semantics. </p>
		        <p>Examples include: roles, types of contact information, types of help,  types of functions, warnings, key points, errors, system messages, notes,  definitions, more information, tables of content, site maps, file types, search, required information, errors, opinions, essential information, types of transaction, types of reminder, usage  instructions, status of elements, invalid fields, non-native content, and sponsored content.</p>
<h2>What Principle and Guideline the SC falls within.</h2>
		        <p>Principle 3, Guideline 3.3 &ldquo;Input Assistance&rdquo;</p>
<h2>Description</h2>
		        <p>The use of inconsistent cues can present significant barriers to users  with cognitive accessibility needs. The intent of this Success Criterion is to  ensure that navigation, operability, and the ability to complete tasks  associated with a website, are fully supported by consistent cues throughout the  website.</p>
<p>For example:</p>
                <ul>
                  <li>A user with cognitive  accessibility needs may have difficulty understanding the state of a particular  control if the mechanism for displaying the state of the control is inconsistent  throughout a website.</li>
                  <li>If the content type and the format required  by an input field are not clearly defined, users with cognitive accessibility  needs may have difficulty determining the format of the information required.</li>
                </ul>
		        <h2>Benefits</h2>
		        <p>The benefit to users with cognitive accessibility needs is that consistent  cues and prompts, provided throughout a website or application, create  familiarity and reduce cognitive load. The advantages of familiarity and  reduced cognitive load are that processes are easier to follow and appear to be  less complex. This may benefit users with cognitive accessibility needs in  several ways, including:</p>
                <ul>
                  <li>If the user perceives the  activity to be too complex, the user may decide to abandon the activity. Therefore, the user will be excluded from the information and/or the services derived from the  completion of the activity. Familiarity and consistent cues will alleviate this  considerably.</li>
                  <li>If an activity relies on  completion  of several tasks, then the likelihood of errors being made during the activity  increases, particularly for users with cognitive accessibility needs, if the  cues provided are inconsistent.</li>
                </ul>
                <p>While providing consistent cues is of benefit to all users, it is of  particular benefit to a wide range of users with differing cognitive accessibility  needs, including users with:</p>
<ul>
                  <li>language-related disabilities;</li>
                  <li>memory-related disabilities;</li>
                  <li>disabilities that affect executive function and decision making; and</li>
                  <li>focus-and-attention-related  disabilities.</li>
                </ul>
<p>Providing consistent cues is a cornerstone of good UX design. They not only benefit users  with diverse cognitive accessibility needs, but also benefit any user who is  unfamiliar with the content. As such, the benefits are not restricted to a  relatively small subset of users.<br>
                  <strong>Related Resources (optional)</strong><br>
</p>
<ul type="disc">
  <li><a href="https://rawgit.com/w3c/coga/master/gap-analysis/table.html">User needs table 5</a></li>
                  <li><a href="https://w3c.github.io/wcag/coga/user-research.html">Background       research document</a></li>
                </ul>
<p>The Aphasia Alliance's Top Tips for 'Aphasia Friendlier' Communication   taken from   http://www.buryspeakeasy.org.uk/documents/Aphasia%20Alliance%20Aphasia%20Friendier%20Communication.pdf</p>
<p>Phiriyapkanon. Is big button interface enough for elderly users, P34, Malardardalen University Press Sweden 2011.</p>
		        <h2>Testability</h2>
		        <p><strong>Test Procedure</strong></p>
<ol>
                  <li>Ensure, by inspection, that headings and regions are identified consistently.</li>
                  <li>Change the states of elements, such as tab panels and selected options. Confirm that each cue is consistent with other cues within a set of web pages.</li>
                </ol>
		        <p><strong>Automatic tests can include if:</strong></p>
		        <p>CSS toggles consistently on different states on similar items;</p>
		        <p>CSS is used consistently on headings, roles, personalization, and semantics.</p>
		        <h2>Techniques</h2>
		        <p>Symbols are available that help the user identify  key content types identified in a glossary section.</p>
		        <p>Using CSS to show a state consistently.</p>
		        <p>Using CSS to consistently show a content type.</p>
		        <p><br>
	            <strong>Failure  Technique:</strong> Adding a star next to key content, as that does not help the user to understand  the context of the key content.</p>       
  <h2> working groups notes (optional)</h2>

**Comment by detlevhfischer** [comment]
I fee that several distinct things are addressed here:

1.  to what extent is there a clear indicaton (cue) of the type of content?
2. - to what extent is the cue used consistently (state of a control, example 1 in description)
3. - to what extent is contextual information sufficient for the user to knowe what to do (example 2 in description related to content type and format)

As to (1), I think it will be important to stress in (a note of) description that many native elements have built-in cues and would pass unless the author takes away the native differentiation via styles  (e.g. presents blockquote, that browers would indent, exactly like normal text; removes colour and outline of links; flattens h1-h6 hierarchy to make headings hard to differentiate etc.)
As to (2), this would work well with checking visually consistent states of custom elements in 4.1.2 and should be easy to test.
As to (3) I think this is the territory of SC 3.3.2 Labels or Instructions and shoukld not be duplicated in this new SC.

**Comment by joshueoconnor** [comment]
@SteveALee Is there a PR ready for this one?

**Comment by SteveALee** [comment]
@joshueoconnor not quite yet - I was waiting for a few days for comments on list. As none, I will now PR, either tomorrow or Monday.

Thanks for assigning to me BTW, I tried to grab it :)

**Comment by SteveALee** [comment]
@detlevhfischer Thank you for some excellent feedback. I will try to address these points in the PR using bullets.

> As to (1), I think it will be important to stress in (a note of) 

Where would such a note be recorded?

**Comment by SteveALee** [comment]
@joshueoconnor see https://github.com/w3c/wcag21/pull/108

**Comment by goodwitch** [comment]
Hi @SteveALee , I was wondering if you could help me find a home for the visual clues provided by table borders.  I'm the manager for the proposed SC User Interface Component Contrast (Minimum) Issue #10 that  only  deals with things that are interactive and rendered/drawn by the browser.  Alastair is the manager for the proposed SC Graphics Contrast #9 which only deals with author created images.  

So, table borders do not fall into either of these proposed SC.  But...we thought, perhaps it might be a good fit for a proposed COGA SC.  Do you think table borders fits into this proposed SC Consistent Cues?
