### ISSUE TITLE
metadata needs to be consistent 

### ISSUE THREAD

**Issue by lseeman** [w3c/wcag21#321]
Our discussion on metadata and usage on it needs to be harmonized
For example 
https://www.w3.org/TR/UNDERSTANDING-WCAG20/appendixC
needs to include issue 6 OR it could limit the scope by changing the title to "about metadata in conformance claims"

**Comment by joshueoconnor** [comment]
@lseeman Can this be closed in light of the current work in 'Identifying common purpose'? https://www.w3.org/TR/WCAG21/#identify-common-purpose

**Comment by joshueoconnor** [comment]
Am closing this and moving it as an issue against WCAG 2.0 https://github.com/w3c/wcag/issues/311
