### ISSUE TITLE
Should the github issues for proposed SC that are in the current WCAG 2.1 PWD be open or closed?

### ISSUE THREAD

**Issue by goodwitch** [w3c/wcag21#324]
@michael-n-cooper @awkawk We have a mixed bag of github issues for proposed SC that are in the current WCAG 2.1 public working draft.  See https://github.com/w3c/wcag21/labels/Integrated%20into%20Draft%20Guidelines Some of these issues are open, and a few of them are closed.  In my mind...they should either all be open (or all be closed).

Also, do we need to find a new SC manager for #2 ?  I think Wayne was the SC Manager and he is taking a bit of a sabbatical.

**Comment by jake-abma** [comment]
@goodwitch @michael-n-cooper @awkawk, I can take it on if Wayne takes a step back

**Comment by michael-n-cooper** [comment]
We'll do an issue-closing pass at some point, but because the issues are still referenced in ednotes of the active version of the spec, we left them open for now. We have added a label to issues whose SC are now in the spec (could be some issues still need it added) which will help the later pass.

**Comment by goodwitch** [comment]
@jake-abma that would be awesome (having you step up as SC manager) for #2  I'll send you a direct email to answer any questions you might have as you jump in :)
