### ISSUE TITLE
The Paciello Group comment on new note in 5.1.2 - Full Pages

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/wcag21#331]
The new note mentions screen sizes, but it's worth being careful that screen size is not the only variable that could trigger a different version/view of the same page. One example would be feature/API detection (i.e. JavaScript that checks for the presence of touch-event support, and from that infers - wrongly perhaps - that the user is on a mobile device). There are also further media queries that can be used by authors to trigger alternative views/layouts. The wording, therefore, could do with being more generalised/not focused only on screen size. If the definition were to be expanded to cover all sorts of factors outside of the user's direct control, need to be careful that this wouldn't turn accidentally into a 508 style "must work without JavaScript or CSS" as the setting (whether JS is turned on or off) may arguably also be "outside of the user's control" in certain environments/situations, though.

**Comment by DavidMacDonald** [comment]
I've looked at this pretty carefully and the current language is to try to address Gregg's concern that it could be too wide. For instance, if a page was customized to work with voice over a car, it would fail. 

I think everyone agrees on screen size customizations.... If you can suggest further tweaks I'm all ears, but it is very fragile, since it's a conformance requirement and affects EVERY SC including WCAG 2 SCs

Currently, [41 out of 42 evaluators already interpret size variations as being covered under WCAG 2](https://twitter.com/davidmacd/status/885863118517264385)  
which will help ensure the note will pass the scrutiny of CR... I was hoping to get the note into WCAG 2 but it failed to get consensus.

 I think it would be at risk if the net thrown wider. My preference is not to mess with it.

**Comment by joshueoconnor** [comment]
@patrickhlauke If you'd like to suggest some language around this, please do. Otherwise if you both feel the current language is sufficient - or at least manages scope in a practical way when all factors are considered - then let me know if this can be closed @DavidMacDonald

**Comment by patrickhlauke** [comment]
The current note reads:

> A full page includes each variation of the page that is automatically generated by the page for various screen sizes. Each of these variations needs to conform (or needs to have a conforming alternate version) in order for the entire page to conform.

An initial suggestion may be (with a bracketed additional sentence, which could probably do with wordsmithing).

> A full page includes each variation of the page that is automatically generated by the page based on device/user agent characteristics (such as viewport/screen size, the presence of a particular set of device sensors/APIs, or the user agent string itself). [These characteristics are generally not directly changeable by the user, unless they switch to a different device/user agent.] Each of these variations needs to conform (or needs to have a conforming alternate version) in order for the entire page to conform.

This now still includes the screen size clause, but does widen the net in a logical way, I'd say.

**Comment by awkawk** [comment]
(Official WG Response)
Thank you for your comment. Other methods of detecting the device being used tend to cause content to be served at a different URL, and we cannot ensure that it will not be the same page. We think the current wording strikes the correct balance as a clarification of conformance of a page in a way that is consistent with backward compatibility.

**Comment by patrickhlauke** [comment]
> Other methods of detecting the device being used tend to cause content to be served at a different URL, 

For the record, I was not merely talking about "the device being used", but user agent characteristics (of which screen size are only a subset). I disagree with this generalisation. The exact same technology used to change page presentation/content based on viewport width/height (CSS media queries and, to an extent JS based width/height checks) can be used to check for many other characteristics leading to the same "variation". 

Conversely, if the problem this tries to avoid is that things may be served from a different URL: this can also be true of screen size checks (a site checking width/height and redirecting to a different URL). And more generally, if this redirection happens automatically based on characteristics (such as screen size) outside of the user's control, it's irrelevant whether it's the same or different URL - functionally, it would count as the same URL since it's the only representation of that page available to the user (and not something that the user can actively choose to navigate to as an alternative)
