### ISSUE TITLE
The Paciello Group comment on SC 2.5.1 - Target Size

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/wcag21#332]
> "In-Page: The target is a text link where the destination is on the same page."

Why limit this to "text" links only? As discussed at length before, why not *any* kind of link, or in fact any kind of control (a `<button>` for instance)?

Also, as this would effectively cover skip links, would this not adversely affect users with mobility impairments who will benefit the most from in-page links, as these would be exempt from being easily usable by this user group?

"The target is in a block of text." needs a stronger definition of what constitues a "block of text".

Should this SC have "a mechanism is available..." as well? For instance, an explicit user setting that allows the user to switch to a "touch-friendly" layout (similar to what Office 2013 offers in its UI when running on a touch-enabled laptop)?

The choice of "five" grouped items appears arbitrary - which it likely is.

There are still some concerns about whether or not this SC would best be suited as a "best practice" (which would allow wording that's a bit more generic and open to interpretation, such as "all important controls", which can't be used in normative testable SCs of course).

**Comment by awkawk** [comment]
We have made several changes to the SC text to address your concerns:
Text links: the SC is not limited to only text links (this is not a change), but text-based links within a sentence or block of text are exempted. Block of text: language was added to include individual sentences as well, but for blocks of text we are continuing to rely on the WCAG 2.0 definition. Mechanism is available: We will address this point in the understanding documentation Five links: removed.
