### ISSUE TITLE
The Paciello Group comment on SC 1.4.14 Content on Hover or Focus

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/wcag21#333]
"Visible trigger" references "essential", which (as noted in feedback for 2.6.1) is specific currently to exceptions for orientation. The definition of "essential" needs to either mention cases of "essential" in this scenario, or there should be separate "essential" definitions (for "essential orientation", "essential content", etc).

> "Either the additional content does not obscure any essential content within the triggering user interface component"

This seems unnecessarily complex to parse. Could this not be rewritten simpler to "...the additional content does not obscure essential content of the trigger"?

**Comment by allanj-uaag** [comment]
lvtf

**Comment by steverep** [comment]
> "Visible trigger" references "essential", which (as noted in feedback for 2.6.1) is specific currently to exceptions for orientation. The definition of "essential" needs to either mention cases of "essential" in this scenario, or there should be separate "essential" definitions (for "essential orientation", "essential content", etc).

I agree and I think this change to the WCAG 2.0 definition of essential was an oversight.  Many new and existing criteria, including this one, expect the 2.0 definition unchanged.  @awk and @joshueoconnor, can we prioritize fixing this to avoid more confusion?

> This seems unnecessarily complex to parse. Could this not be rewritten simpler to "...the additional content does not obscure essential content of the trigger"?

Again, I agree that this is wordy and adds the confusing implication that a trigger is always a UI component.  This was a change made in the last hours before the CFC on #75, and I objected to it.

**Comment by DavidMacDonald** [comment]
+1

**Comment by steverep** [comment]
@patrickhlauke, pending working group approval of pull request #569, the [proposed new language](http://rawgit.com/w3c/wcag21/hoverable-and-persistent/guidelines/#content-on-hover-or-focus) should address your issues.  Note the "essential" issue was already addressed, but this proposal would remove the word completely.
