### ISSUE TITLE
The Paciello Group comment on SC 1.3.4 Contextual Information

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/wcag21#334]
We're fine with this SC in principle, but just to point out that "publicly available vocabulary" normative wording would allow a website to simply invent their own vocabulary, make it publicly available somewhere on the website, and nominally pass. This won't mean any UAs/tools will actually understand this vocabulary in a way that would allow them to expose this information in a meaningful way to users.

**Comment by awkawk** [comment]
Official WG Response: Thank you for your comment. The specific language has been removed from this SC. The point that a website could invent their own vocabulary is valid, as this would be allowed by the current version of the SC, but there would also need to be accessibility support for the vocabulary used to satisfy the SC. The need for support by user agents will make the custom approach substantially less viable.
