### ISSUE TITLE
Reminders

### ISSUE THREAD

**Issue by lseeman** [w3c/wcag21#34]
<h2>SC Shortname</h2>
		        <p><strong> Reminders</strong></p>
		        <h2>SC Text</h2>
		        <p><br>
                <strong>Reminders:</strong> The user is able to  set a reminder for date and time sensitive events.  Reminders must be set only at the users request and the user must be able  to personalize the reminder method. Where a standard mechanism exists for the platform  or technologies, it must be used.</p>
		        <h2>Suggestion for Priority Level (A/AA/AAA)</h2>
		        <p>AA<br>
		        </p>
<h2>Related Glossary additions or changes</h2>
		        <p>Date and time sensitive event:<br>
	            Any event that has to be  completed by a certain time. The time constraints on such  an event may be defined by a calendar date and time or by the total elapsed  time.</p>
<h2>What Principle and Guideline the SC falls within.</h2>
		        <p>Principle 3, Guideline 3.3 - Input Assistance</p>
<h2>Description</h2>
		        <p>Managing events that are time bound (such as meetings, submitting a request by a  certain date or completing a form within a specified time period) can present  significant barriers to users with cognitive accessibility needs. The intent of  this Success Criterion is to ensure that when required, a user can set reminders and the delivery method of the reminder can be personalized by the user.<br>
For example:</p>
                <ul>
                  <li>A user may have difficulty processing and retaining time based information.</li>
                  <li>A user may have difficulty in sequencing time bound events.</li>
                  <li>A user's skills decreases when tired to such an extent that they have to stop a task. They may wish to reschedule the task.</li>
                </ul>
		        <h2>Benefits</h2>
		        <p>The benefit to users with cognitive accessibility needs is that they can manage appointments, deadlines and scedules. The ability  to set reminders can reduce the cognitive load associated when processing time bound  tasks. Time dependent activities  may be monitored and tracked by the user to  ensure that they are completed in a timely manner. This Success Criterion  addresses two broad classes of issues associated with this type of information:</p>
                <ul>
                  <li>If the user perceives the  activity to be too complex the user may decide to abandon the activity and  therefore be excluded from the information and/or services derived from the  completion of the activity.</li>
                  <li>If the activity relies on a  number of distinct events being carried out sequentially over an extended  period of time or if a single event must be completed by a specified date and  time then the likelihood of errors being made during the activity increases,  particularly for users with cognitive accessibility needs. Activities are often missed because the date and time is confused. </li>
                </ul>
                <p>While the ability to set reminders is of benefit to all users, it is of  particular benefit to a wide range of users with differing cognitive accessibility  needs including users with:</p>
                <ul>
                  <li>Learning disabilities</li>
                  <li>Cognitive and memory related disabilities</li>
                  <li>Disabilities that effect  executive function and decision making</li>
                  <li>Focus and attention related  disabilities</li>
                </ul>
                <p>Providing a mechanism to allow users to set  reminders not only benefits users with diverse cognitive accessibility needs  but also benefits any user who uses electronic calendars and task managers. Therefore, the benefits are not restricted to a relatively small subset of users.</p>
                <p><strong>These use cases are fully discussed at:</strong></p>
<p><a href="https://rawgit.com/w3c/coga/master/gap-analysis/table.html">User  needs Table 2: Context and distractions</a></p>
	<h3>Related Resources</h3>
	<p>Resources are for information purposes only. No endorsement is intended or implied.</p>
                <ul>
			<li><a rel="nofollow" href="https://w3c.github.io/wcag/coga/user-research.html">Background research  document</a>
                  <li><a rel="nofollow" href="https://rawgit.com/w3c/coga/master/gap-analysis/">Gap analysis section</a></li>
                  <li><a rel="nofollow" href="https://w3c.github.io/wcag/coga/user-research.html">Background research document</a></li>
                  <li> <a rel="nofollow" href="https://rawgit.com/w3c/coga/master/issue-papers/links-buttons.html">Semantics for adaptive interfaces</a> </li>
                  <li><a rel="nofollow" href="https://rawgit.com/w3c/coga/master/issue-papers/distractions.html">Distraction Issue Paper</a></li>
			<li><a rel="nofollow" href="https://rawgit.com/w3c/coga/master/techniques/index.htm">COGA Techniques</a></li>
                </ul>
		        <h2>Testability</h2>
		        <p>The basis of the Success  Criterion is that there is a mechanism for a user to set a reminder for a date  or time sensitive event. Manual assessment of the success or failure of this Success  Criterion will depend on the tester having a degree of familiarity with what is  considered a time sensitive event.<br>
                <strong>Test Procedure</strong></p>
<ul>
                  <li>Identify any time sensitive events</li>
                  <li>Check that the user is given the option to set a reminder for the event , using a WCAG technique or other standard's technique (when available)</li>
                  <li>Check that the user is given the option not to set a reminder</li>
                  <li>ecommended: Ensure that any reminder mechanism method can be personalized by the  user</li>
                  <li>ecommended:  Ensure that the method of setting a reminder is obvious to all users</li>
                </ul>
                <h2>Techniques</h2>
                <ul>
                  <li>Enable the user to set a reminder  for date and time sensitive events. Reminders should be set only at the user's  request and the user should be able to personalize the reminder method.</li>
                  <li>Using standard scripts and COGA semantics to set reminders</li>
	</ul>        
  <h2> working groups notes (optional)</h2>

**Comment by lseeman** [comment]
some links
https://developer.mozilla.org/en/docs/Web/API/notification
https://www.html5rocks.com/en/tutorials/notifications/quick/
https://developers.google.com/google-apps/calendar/concepts/reminders
if needed we can make a script that does all of them via our coga sematics

**Comment by lseeman** [comment]
we can have the script working by CR for personlizations

**Comment by lseeman** [comment]
https://docs.api.ai/docs/reminders-and-notifications

**Comment by CityMouse** [comment]
Variables that could be considered on 'when to supply a reminder':
Time - at a logical time
Location - prompted when at an appropriate location
Context - on computer vs. mobile, on specific site, etc

**Comment by CityMouse** [comment]
There are various modes that the reminder could be delivered in such as:
	Tactile
	Visual
	Auditory
	Others ??
