### ISSUE TITLE
Success Criterion 1.3.4 Purpose of Controls -  comment 1 

### ISSUE THREAD

**Issue by GreggVan** [w3c/wcag21#340]
>In content implemented using markup languages, the conventional name of conventional form fields, conventional buttons or controls, or conventional links can be programmatically determined.
> 
> EDITOR'S NOTE
> The Working Group seeks feedback on the lists of terms included in the definitions. These lists are likely to change as items are likely to be refined, removed or added.

===========================================

It is usually not a good idea to define things via list.

if you do define things via list, then the list has to be a definitive list not an example list.   Otherwise it will not be testable. People will not know if there are additional items that are intended to be covered or not. 

SOLUTION:
You can do this by simply changing
"The following form field types are documented as widely recognized:"
to
"Conventional form fields" means the following form field types:"

**Comment by goetsu** [comment]
+1 

I'm  concerned by the fact that those value may need to vary depending on the country your are for example a french tool for personalization may use "nom" instead of "name". Because of that It will also be hard and costly to implement when you deal with an international website.

Without an internationally  normative list of values, implemented in real AT worldwide this SC isn't testable and implementable

Also using "name" attribute is a bad idea because name is the value passed when you get result of your form so if for example you have multiple form using same field like "shipping address" "billing address" you simply can't use the same name value for name field

**Comment by jake-abma** [comment]
@GreggVan yes we must be sure we will have a definitive lists and not an example lists and this must be clear from the normative wording.

Just to be sure we’re on the same page this is about all three conventional name lists and their wording:

—————————

- [conventional form fields](https://www.w3.org/TR/WCAG21/#dfn-conventional-form-fields)

> widely recognized form field types
> 
> The following form field types are documented as widely recognized:

- [conventional buttons or controls](https://www.w3.org/TR/WCAG21/#dfn-conventional-buttons-or-controls)

> widely recognized button or control types
> 
> The following form field types are documented as widely recognized:

- [conventional links](https://www.w3.org/TR/WCAG21/#dfn-conventional-links)

> widely recognized link types
> 
> The following link types are documented as widely recognized:

—————————

A new suggested proposal could look like:

—————————

- [conventional form fields](https://www.w3.org/TR/WCAG21/#dfn-conventional-form-fields)

> Widely recognized and defined form field types
> 
> “Conventional form fields” mean the following form field types:

- [conventional buttons or controls](https://www.w3.org/TR/WCAG21/#dfn-conventional-buttons-or-controls)

> Widely recognized and defined button or control types
> 
> “Conventional buttons or controls” mean the following button or control types:

- [conventional links](https://www.w3.org/TR/WCAG21/#dfn-conventional-links)

> Widely recognized and defined link types
> 
> “Conventional links” mean the following link types:

—————————

Would this satisfy your concern?

**Comment by jake-abma** [comment]
@goetsu, thanks for your comments

- The attributes will be in the language of the chooses technique, just as we do with ARIA for instance. A French tool, when encountering the “name” attribute should use that to generate the French value for “name” (or “nom”). If you want you can look at our [draft techniques at COGA Techniques ](https://docs.google.com/document/d/1YiknHDDDdKBdwVTEpxwUpyCaQL_tnpp9CfDlFjCq16E/edit#heading=h.n8sq8t3ebanu) for a possible solution

- By the time we leave CR we are committed to all SC have  working websites and implementations in a few different platforms (or they will be removed from the final draft). Please see [WCAG 2.1 CR Exit Criteria](https://www.w3.org/WAI/GL/wiki/WCAG_2.1_CR_Exit_Criteria) for the details.

- The “name” as defined in the list is not to be used as a direct attribute for an input element but serves as a ‘place holder’ for different technologies which ‘may’ be used for generating the Purpose of Controls via metadata. As an example see the same COGA draft where the ‘name’ will look like: `<input type="text" name="fname" coga-field="name" />`

**Comment by GreggVan** [comment]
yes  - that is testable — and therefor   doable for an author.  

We still have a list — but there is no alternative and this will cover the key items,


Three questions then remain.
is this REALLY a problem   
(I think naming very basic fields with different names is a problem worth addressing ) 
is this REALLY helpful — do people with cognitive disabilities really know what all these terms mean         
(This I don’t know — but I think it is somewhat helpful ) 
is this list the list of key terms that would help people — or a list of everything we can think of.    
(Here I think some common field and control names are important — but the list is very long and I wonder about regimenting some of the less common ones.)
COMPOSE for example is a great example of a BAD term.   NEW MAIL  would be a much better name for a button that created new mail than COMPOSE which violates PLAIN LANGUAGE recommendation.  
MODE is another high level word - where a more specific label might be much more understandable 
Other examples of higher education terms that we would be mandating instead of plain language terms
honorific-prefix
honorific-suffix
cc-number  (instead of credit-card number)
The rest are pretty good.    Maybe we don’t mandate some of these?  or? 
they are good for programmatic identification (so AT can identify them) — but not requiring that they be the terms used for users to see

**Comment by lseeman** [comment]
Hi Gregg 
we are not saying compose should be the lable. just that it's role as a compose button should be programmatically determinable

**Comment by GreggVan** [comment]
ah yes.   Where was my head.  thx  g

**Comment by jake-abma** [comment]
Hi @GreggVan, small wrap up: 

you're last comment for this issue was affirmative:

> yes  - that is testable — and therefor   doable for an author.

The SC has focus and we're collecting all the issues for processing.
Do you want to leave this one open till fixed or can we take this one for processing and close the issue?

NOTE: the term 'conventional' is under investigation (we are discussing this at #486 , #341 and #402)

**Comment by GreggVan** [comment]
yes but I also said 

Three questions then remain.     Did we address those?

**Comment by mbgower** [comment]
@GreggVan said:
>Three questions then remain. is this REALLY a problem (I think naming very basic fields with different names is a problem worth addressing )
is this REALLY helpful 

To answer these two together, I think that this SC will allow for the creation of really helpful constructs (ATs, plug-ins, practices) that will address common problems with inconsistent nomenclature in UI design, as well as allowing a user to potentially transform that UI for their purposes.

> do people with cognitive disabilities really know what all these terms mean (This I don’t know — but I think it is somewhat helpful )

People with cognitive disabilities don't need to know what the terms mean -- they can, for instance, choose a tool that has done the mapping and replaces the author-assigned labels with simplified terms meaningful to user.
There are some quick, demonstrable benefits we can show with existing technology, and LOTS of potential uses.

> is this list the list of key terms that would help people — or a list of everything we can think of. (Here I think some common field and control names are important — but the list is very long and I wonder about regimenting some of the less common ones.)

I wouldn't say this one has been addressed. With the improved wording of the SC, it's now the primary concern. I know @johnfoliot has been looking at it.

**Comment by awkawk** [comment]
Thank you for your comment. We believe that the current version of the SC addresses the testability concern.

**Comment by GreggVan** [comment]
OK
much better 
see 602 for followup
