### ISSUE TITLE
Success Criterion 1.4.11 Graphics Contrast - ratio

### ISSUE THREAD

**Issue by GreggVan** [w3c/wcag21#346]
This should be changing to 3:1  

 All of the research that was done around 4.5:1  was based on readability not discernability.    and discernability is all you need for controls.   

As mentioned in comment #343 -  I am worried that these guidelines are being written without any understanding of the underlying research on which the  contrast numbers in WCAG 2.0 were based.

So suggest that this at least be changed to 3:1

(but still also think this provision needs to withstand the 
<standard test of practicality, do-ability and reasonableness>
        This should not be included  at level AA unless all of the working group members can show how all of the pages on their organizations websites could be made to comply --   including all of the W3C pages.

**Comment by DavidMacDonald** [comment]
Agree with 3:1.
I have proposed that...

**Comment by allanj-uaag** [comment]
lvtf

**Comment by alastc** [comment]
@lauracarlson do you have the quotes to hand from the experts who were consulted?

**Comment by lauracarlson** [comment]
Hi @alastc 

> @lauracarlson do you have the quotes to hand from the experts who were consulted?

Yes.

- [Gordon Legge's email](https://lists.w3.org/Archives/Public/public-low-vision-a11y-tf/2017Jun/0054.html) 
- [August Colenbrander's email](https://lists.w3.org/Archives/Public/public-low-vision-a11y-tf/2017May/0007.html)

Dr. Legge is a Distinguished McKnight Professor at the University of Minnesota on this topic and  head of the Minnesota Laboratory for Low-Vision Research and a founding member and Scientific Co-Director of the Center for Applied and Translational Sensory Science (CATSS).

Dr. Colenbrander is  a Affiliate Senior Scientist  with the The Smith-Kettlewell Eye Research Institute and California Pacific Medical Center.

**Comment by awkawk** [comment]
Thank you, we have changed it to 3:1 for both this and the UI controls (which has been combined).
