### ISSUE TITLE
Success Criterion 2.2.8 Timeouts

### ISSUE THREAD

**Issue by GreggVan** [w3c/wcag21#351]
> Where data can be lost due to user inactivity, users are warned at the start of a process about the length of inactivity that generates the timeout, unless the data is preserved for a minimum of 24 hours of user inactivity.
> 
> NOTE
> Privacy regulations may require explicit user consent before user identification has been authenticated and before user data is preserved. In cases where the user is a minor, explicit consent may not be solicited in most jurisdictions. Consultation with privacy professionals and legal counsel is advised when considering data preservation as an approach to satisfy this success criterion.
> 

==================================================================
Suggest that this be changed to 20 hours rather than 24 hours. When we examine this in WCAG 2.0 there was an issue that came up with holding data for 24 hours.

Changing it to 20 or 22 or 23 hours will not have any significant impact on users but can address issues of holding information for more than a day.

 I wish I could find a reference but I looked and cannot

**Comment by awkawk** [comment]
@GreggVan "Holden data" or "holding data"?

**Comment by GreggVan** [comment]
Holding -      
I fixed it in the comment above

**Comment by rachaelbradley** [comment]
Based on discussion at TPAC, we have amended the success criteria to read:  2.2.8 Where data can be lost due to user inactivity, users are warned about the estimated length of inactivity that generates the data loss unless the data is preserved for a minimum of 20 hours of user inactivity.

**Comment by GreggVan** [comment]
looks good

g
