### ISSUE TITLE
Success Criterion 2.2.9 Animation from interactions

### ISSUE THREAD

**Issue by GreggVan** [w3c/wcag21#352]
> For non-essential animations triggered by a user action, there is a mechanism to disable the animations yet still perform the action.

==================================================================
From this wording it is unclear if  it must be possible to disable the animation before the user action, or if it know that it must be possible to cancel the animation after it launches. The former could make things quite complicated meaning including a special control next to everything that has an animation. For some products this would mean adding a control besides every control or something more abstract like a control at the top of the page etc.

If the intent is only to mean that the person should be able to cancel the animation then this should be made clear.

 POTENTIAL SOLUTION
For non-essential animations triggered by a user action, there is a mechanism to cancel the animations without cancelling the action.

**Comment by alastc** [comment]
Hi Greg,

The intent is that the user can prevent them from happening in the first place, a cancelling mechanism would undermine the benefit as you might have already triggered the vertigo/nausea/negative symptom.

The simple (but under-supported *) method is to use the [prefers-reduced-motion](https://drafts.csswg.org/mediaqueries-5/#prefers-reduced-motion) media query, and any animations are prevented by the user-preference.

In the meantime, the technique would be to have a site-level user preference such as a button at the top, or something in your profile. (Or don't use these types of animation.)

(*) Safari supports it now, Firefox is [prioritising it in 2018](https://bugzilla.mozilla.org/show_bug.cgi?id=1365045), not sure about Chrome/Edge.

**Comment by awkawk** [comment]
Official WG Response: Thank you for your comment. This SC is intended to prevent animation from occurring rather than stopping animation that have started. Support may be provided through the inclusion of multiple controls to prevent animation, as well as by avoiding the use of animation completely, but we expect that growing support for relevant media queries will provide additional ways to support this AAA SC.

**Comment by GreggVan** [comment]
OK
Thx
H

Sent from my iPad

On Jan 3, 2018, at 12:34 PM, Andrew Kirkpatrick <notifications@github.com>
wrote:

Closed #352 <https://github.com/w3c/wcag21/issues/352>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/w3c/wcag21/issues/352#event-1408207874>, or mute the
thread
