### ISSUE TITLE
Success Criterion 2.2.7 Interruptions (minimum)

### ISSUE THREAD

**Issue by GreggVan** [w3c/wcag21#353]
> There is an easily available mechanism to postpone and suppress interruptions and changes in content unless they are initiated by the user or involve an emergency.

==================================================================
Well done. 

You will need a very good "understanding 2.1" writeup for this one to capture all your thoughts on what you thought about and how you addressed all the issues that come up on this.   Every time if find an issue I see how it is covered.    But not clear unless you think carefully about it.   You need to capture all of this while it is fresh in your mind.

**Comment by awkawk** [comment]
Thanks for the comment and advice!
