### ISSUE TITLE
Success Criterion 2.4.11 Character Key Shortcuts

### ISSUE THREAD

**Issue by GreggVan** [w3c/wcag21#355]
> If a keyboard shortcut consisting entirely of one or more character keys is implemented by the content, then a mechanism is available to turn it off or to remap it to a shortcut that uses at least one non-character key.

==================================================================
Interesting -- and clearly explained in the UNDERSTANDING document.   The examples were key.  (which email has these single key commands? )

**Comment by awkawk** [comment]
Gmail has single key commands and a user preference to shut them off.
