### ISSUE TITLE
Success Criterion 2.5.1 Pointer Gestures

### ISSUE THREAD

**Issue by GreggVan** [w3c/wcag21#356]
> All functionality can be operated with a single untimed pointer gesture unless a multipoint or timed gesture is essential.
> 
> NOTE
> This requirement applies to web content which interprets pointer gestures (i.e. this does not apply to gestures that are required to operate the user agent or assistive technology).

==================================================================
This one need work  --  but the fix is relatively easy I think. 

The NOTE should not be used to rewrite the SC.   In many standards - notes are informative and not normative.    If it is desired to limit the provision - the limitations should be in the SC.   So lets look at this.  

According to the SC language -- all keyboard and mouse operations of a computer must be operable with simple gestures  and the web page author is responsible for it.

but you can fix this by putting the note text into SC 

REWRITE:

For web content that interprets pointer gestures, all functionality can be operated with a single untimed pointer gesture unless a multipoint or timed gesture is essential.

However I would suggest an additional change to ensure access without  requiring everyone to only use simple gestures 

REWRITE 2
For web content that interprets pointer gestures, there is at least one mode where all functionality can be operated with a single untimed pointer gesture unless a multipoint or timed gesture is essential, and this mode is **accessibly activatable**. 

DEFINITION (since I think you are using this in several places) accessibly activated. 
**accessibly activatable**. 
it is either the default mode or it can be activated using a control on the page that meets all of the requirements of this standard.   [or you can use the longer form on a previous provision that talks about web wide setting or GPII etc. 

REGARDING YOUR NOTE

The note seems to say The phrase "web content which interprets pointer gestures" means that this does not apply to gestures that are required to operate the user agent or assistive technology.

This seems to say something much broader - which is good.   but the note should be rewriten 
Perhaps 

NOTE: Because of the phrase "web content which interprets pointer gestures", this does not apply to gestures that are required to operate the user agent or assistive technology.

**Comment by detlevhfischer** [comment]
REWRITE 1: 
I think that the rewrite "For web content that interprets..." is unnecessary since the entirwe WCAG explicitly set requirements for web content / web authors. The note is just there to reinforce that distinction - so readers know we are only talking about gestures that web authors choose to listen to via JS.

REWRITE 2:
I think the addition "there is at least one mode where all functionality can be operated with a single untimed pointer gesture" is equally unnecessary as the option to provide an alternative version is generally provided by the conformance requirement 1 (meeting the SC via a conforming alternate version)

DEFINITION of accessibly activatable:
I hope this is redundant if you agree that the option to provide an accessible alternative is already provided via the conformance requirements. 'activatable' seems an odd word that I would prefer to avoid, but then I am not a native speaker.

REGARDING YOUR NOTE:
I am not sure I fully understand the difference between the note currently ibn the draft text and ypur proposal.

The two general issues currently on the table are covered here
- #505, and 
- the mailing list discussion (9. October 2017) on the question whether this SC would generally require that **all** functionality can be operated with a pointer (i.e., a popup that can only be closed via ESC on the keyboard would fail this SC because there are situations where a keyboard interface does not exist and a virtual keyboard -- which may in addition not have the ESC key -- cannot be brought up).

**Comment by GreggVan** [comment]
The more I look at this - the more I am concerned about its premise.

1) this is in extremely bad form.   
You cannot scope a provision in a note.    That is like saying 
   -- all men must be put in prison within 30 days
              Note: this only applies to people who have been convicted of a crime and sentenced to prison. 

If this is to be a success criteria that only applies to x  then the x condition needs to be in the provision -- not in a note.    

2)  This says ALL FUNCTIONALITY.    So if I have web content that interprets pointer gesture - and it also has a text input field on the page --   does it mean that every author has to provide access to that functionality though gestures as well -- i.e. every author needs to provide their own on-screen keyboard?      Since WCAG evaluates SC on a page basis this would seem to be the case.   

If you mean -- ONLY the content that interprets gestures needs to meet this SC  - or ONLY the functionality that is provided via that gesture -  then it should say that.  


Also - what is the definition of untimed gesture.   Does that include multipoint or not?   Does Single mean Single point or single gesture?     Arent all gestures by definition time based?     Do you mean just point and click?   


SUGGESTED CHANGES  -- TO HANDLE TWO OF THE THREE PROBLEMS.   ONE STILL OUTSTANDING. 

> FOR ALL WEB CONTENT THAT INTERPRETS POINTER GESTURES TO PROVIDE FUNCTIONALITY, THAT functionality can be operated with a single POINT untimed pointer gesture unless a multipoint or timed gesture is essential.
> 
> NOTE
> This does not apply to gestures that are required to operate the user agent or assistive technology.
>

Still need a definition of  "single untimed pointer gesture "    or  " single POINT untimed pointer gesture"

**Comment by GreggVan** [comment]
PS  since there is a new release -- do you want me to close this issue and open it as a new issue against the new release?

**Comment by detlevhfischer** [comment]
Hi Gregg, I think it’s alreight to keep it here - the SC text is still in flux anyway. I will respond on substance later. Best, Detlev

**Comment by GreggVan** [comment]
Sorry I don’t follow.  

this can’t be applied to pages that doesn’t have pointer access or doesn’t accept complex gestures.     
Can you explain how those pages could pass this without the exception? 

Also - if you say all functionality — it must apply to all functionality.  Including text input - since that is a function of the page. 

Your point about the os’s having on screen keyboards is exactly my point.  That is up to the OS — and not the author.   Requiring the author to provide access to all functionality from the content - would require the author to include a keyboard - which there is no need for (an additional keyboard) 

g 

Gregg C Vanderheiden
greggvan@umd.edu

**Comment by detlevhfischer** [comment]
Hi Gregg
Can you explain what you mean by "pages that do not have pointer access"? You are not talking command line interfaces I guess? I think a couple of examples might help understanding.

**Comment by GreggVan** [comment]
I meant pages that do not accept gestures —   just clicks and text

g 

Gregg C Vanderheiden
greggvan@umd.edu

**Comment by joshueoconnor** [comment]
@detlevhfischer  I'm not sure here what is the final proposal for group review. Please add a new comment and include, thanks.

**Comment by detlevhfischer** [comment]
@GreggVan 
You wrote

> I  meant pages that do not accept gestures — just clicks and text

It is my understanding that web content can generally be viewed on a variety of UA and most will accept pointer input. I guess you are not referring to pages that are somehow constrained to keyboard only access? You mention clicks. A mouse click as well as a mouse drag-and-drop (as in opening a popup menu and selecting an item) IS a pointer gesture. And things you can click at you can also tap at on a touch screen, so there is your pointer access. 
So perhaps we first have to clarify the terminology here: 'Gesture' is not meant to refer exclusively to touch, but to all input based on a device that points to screen coordinates. At least that was my understanding.

**Comment by GreggVan** [comment]
> On Nov 2, 2017, at 11:55 AM, Detlev Fischer <notifications@github.com> wrote:
> 
> @GreggVan <https://github.com/greggvan>
> You wrote
> 
> I meant pages that do not accept gestures — just clicks and text
> 
> It is my understanding that web content can generally be viewed on a variety of UA and most will accept pointer input.
> 
yes
> I guess you are not referring to pages that are somehow constrained to keyboard only access?
> 
not when I say “click”.    that would be pointer.
> You mention clicks. A mouse click as well as a mouse drag-and-drop (as in opening a popup menu and selecting an item) IS a pointer gesture.
> 
  I’m not sure people classify either as a gesture since the path of the mouse is not taken into account for either.  Only the endpoints.   
> And things you can click at you can also tap at on a touch screen, so there is your pointer access.
> 
> 
Yes  but I don’t understand your point.   

> So perhaps we first have to clarify the terminology here:
> 
YES !
> 'Gesture' is not meant to refer exclusively to touch, but to all input based on a device that points to screen coordinates.
> 
Correct.  but it also has to do with the path and the timing.     Without path or timing changing the result - I’m not sure I would call it a ‘gesture’.    Or I am not sure we SHOULD call it a gesture. 


You can use keyboard commands  (e.g. mouse keys)  to do pointing and dragging.     But you can’t for ‘gestures’.

Also any gesture (other than pointing and dragging) by definition cannot the only way to do something because it requires timing.    Also things that are path dependent are a problem  (unless path dependency (or timing) is require such as rate dependent painting or flying a plane etc.     [these are the exceptions to keyboard input requirement too ]

we are on the other side though with this discussion. 

Hope that  helps clarify

but you are correct — that we need to define gestures.

if you/we want to include clicking and dragging as gestures — then we should define two types

non-time-or-path dependent gestures  (pointing and clicking) 
and 
Time and/or path dependent gestures. 

the are quite different in terms of accessibility.

Gregg

**Comment by awkawk** [comment]
We made the change suggested by David in #456 to clarify this concern.

Latest version:
"All functionality which uses multipoint or timed gestures for operation can be operated with an untimed single-pointer activation, unless a multipoint or timed gesture is essential."
