### ISSUE TITLE
Success Criterion 2.5.3 Target Size

### ISSUE THREAD

**Issue by GreggVan** [w3c/wcag21#357]
> The size of the target is at least 44 by 44 CSS pixels for pointer inputs except when:
> 
> Customizable
> A mechanism is available to change the size of the target independent of the level of page magnification.
> 
> Equivalent
> The target is available through an equivalent link or control on the same page that is at least 44 by 44 CSS pixels.
> 
> Essential
> A particular presentation of target is essential to the information being conveyed.
> 
> In-Page
> The target is a text link where the destination is on the same page.
> 
> Inline
> The target is in a block of text.
> 
> Grouped
> Targets in groups of more than five have at least one dimension that is 44 pixels and the other is at least 22 pixels.
> 
> User agent control
> The appearance of the target is determined by the user agent and is not modified by the author.
> 
> EDITOR'S NOTE
> The exact parameters of the exception on grouped links are still under discussion by the Working Group.

==================================================================
I hate to word this this strongly -- but I have commented many times on this and it still doesnt seem to work.    I do not think this SC is useful or salvageable. 

1) If there are any exceptions -- then either   A) the person cannot use any of those controls so the page is unusable anyway    or   B) those controls can be used by the person so the whole page is usable without this provision. 

2)  the size of the controls is more determined by the device the person uses than it is what the author does. 

This really seems burdensome on authors and designers -- and is really not removing and barriers (see #1 above) to web page use.      It feels like  "but we need to do something for this group" rather than - we have identified a real problem and have a real solution.

**Comment by awkawk** [comment]
In the latest draft we have modified the exceptions substantially and believe that this addresses some of your concerns. Regarding your point about the size of controls being determined by the device, this is why we are using CSS pixels as the measure - to account for different levels of pixel density.

We hope that this helps address your concerns.
