### ISSUE TITLE
Success Criterion 2.5.4 Target Size (no exception)

### ISSUE THREAD

**Issue by GreggVan** [w3c/wcag21#358]
> The size of the target is at least 44 by 44 CSS pixels for pointer inputs.

==================================================================
This one is also impractical on most pages. But since it is AAA -- it does not matter like  2.5.3 Target Size. 

You might consider putting 2.5.3 at AAA   but because of comment #1 under that item -- you should drop many of the exceptions if you moved it to AAA.

**Comment by awkawk** [comment]
We have adjusted the size at AAA for text links, but the base size for targets at AAA is 44x44.  We hope that this helps address your concern.
