### ISSUE TITLE
Success Criterion 2.6.1 Orientation

### ISSUE THREAD

**Issue by GreggVan** [w3c/wcag21#360]
> Content is not locked to a specific display orientation, and functionality of the content is operable in all display orientations, except where display orientation is essential for use of the content.

==================================================================
OK  -- but can content really lock a browser display?   I know that apps can but how can web content do this?  even on mobile devices?    
I tried looking at UNDERSTANDING but there is nothing there to explain this.  This is essential for this provision to explain how this could be an author problem. 

ALSO  what does  "all orientations" mean?        looking up, looking down,  vertical, horizontal,  at an angle ?

if you mean  portrait and landscape - then that should be specified  -- or  "All orientations"   needs to be defined. 

Also wording can be better (if web content can do this) 

Content DOES not LOCK display orientation, and functionality of the content is operable in BOTH PORTRAIT AND LANDSCAPE display orientations, except where display orientation is essential for FUNCTIONALITY of the content.

==================================================================
UPDATE  - after discussion below  - I change my recommendation to just '

**Content DOES not LOCK display to a specific orientation, and functionality of the content is operable in all display orientations, except where display orientation is essential for FUNCTIONALITY of the content.**

and substitution of FUNCTIONALITY for USE is just a suggestion. No strong sentiment. 

The discussion below however Should be captured in the UNDERSTANDING  document -  along with clear discussion of the issue being solved.    

 "All orientations" should also be defined.

**Comment by patrickhlauke** [comment]
> OK -- but can content really lock a browser display? I know that apps can but how can web content do this? even on mobile devices?

See https://www.w3.org/TR/css-device-adapt-1/#orientation-desc (though current support is patchy https://caniuse.com/#search=device%20adaptation)

Also, this isn't just about locking per se. You can use CSS or JS to basically not display a site unless the user actively rotates their device in the right orientation (as just one example, see https://www.robscanlon.com/pleaserotate/)

> if you mean portrait and landscape - then that should be specified -- or "All orientations" needs to be defined.

While portrait/landscape is the classic case, it's possible via JS to detect far more granular orientation values  - see https://developer.mozilla.org/en-US/docs/Web/API/Detecting_device_orientation
Using this API it's conceivable that an author could require a device to be held or moved to specific orientations.

**Comment by GreggVan** [comment]
okay. 
But my FIRST suggested edit above would still be important.    the original language requires the author to state that something is true that is outside of their control. My revised wording changes it to say that the author should not cause that topic (or rather their content should not cause the  problem) which is within their control.

 As to your comment:

> While portrait/landscape is the classic case, it's possible via JS to detect far more granular orientation values - see https://developer.mozilla.org/en-US/docs/Web/API/Detecting_device_orientation
> Using this API it's conceivable that an author could require a device to be held or moved to specific orientations.

I see your point  so  drop my suggested second edit  regarding landscape and portrait.


 What do you think of the third edit substituting "functionality" for "use".      This is just a suggestion. I don't have strong feelings on this at all.

[I added an update to my comment above to reflect this discussion.]

**Comment by patrickhlauke** [comment]
your suggested edit looks fine to me. just wanted to provide some context.

**Comment by DavidMacDonald** [comment]
I'm fine with edits

**Comment by awkawk** [comment]
The latest version of the SC does not refer to locking orientation but the assurance of content can be displayed in an unrestricted manner:

“Content does not restrict its view and operation to a single display orientation, such as portrait or landscape, unless a specific display orientation is essential.”
