### ISSUE TITLE
Guideline 2.6 Additional sensor inputs

### ISSUE THREAD

**Issue by GreggVan** [w3c/wcag21#361]
Guidelines are guidelines....   this is just a header. 
and it isnt clear how ORIENTATION is a sensor input. 

What is the general guideline?  ....and is there really only 1 SC under the guideline? 

hmmm

Maybe  
**Ensure display flexibility** 
or else put this in the same place as the SC dealling with zoom etc.

**Comment by awkawk** [comment]
@GreggVan The reason that this is under Additional Sensor inputs is because the display orientation is determined by the device accelerometer sensor. There are two SC under this GL.

**Comment by steverep** [comment]
@awkawk, orientation is usually determined by a gyroscope, but also may be determined in other ways in the case of desktop monitors.  (Accelerometers measure non-inertial motion).

More to Gregg's comment though, I too have qualms as to whether this new guideline is appropriate for the same reasons I opposed the Device Sensors SC.  It paints a picture that sensors are bad for accessibility, which is simply not true.  Please re-open.
