### ISSUE TITLE
Success Criterion 2.7.1 Accessible Name

### ISSUE THREAD

**Issue by GreggVan** [w3c/wcag21#363]
> Where an active control has a visible label, the accessible name for the control includes the text string used for its visible label.
> 
> NOTE
> A best practice is to place the text string at the start of the text string.

==================================================================
looks good in general

but is this really sufficient?     what if there are multiple controls whose ACCESSIBLE NAME includes the label of this control.     How would the AT know which one was intended.    For example I have 5 controls on the page - all with the visible label  Edit   - and accesible names as follows  "edit name:  "edit address"   "edit phone"   "edit SS#" and  "edit zip" 

that would conform to the SC but not be helpful or operable

**Comment by steverep** [comment]
@GreggVan, assistive technology such as Dragon Naturally Speaking already accounts for this situation.  In your example, the user would invoke the "Edit" buttons, and then be presented with distinct numbers next to all matches so they can choose the correct one.

**Comment by GreggVan** [comment]
Agree.   I was not saying what was there was not useful.  I was just asking if it was enough.    So I am ok with this one. 

One suggested edit though.   The note is a bit ambiguous when it says "place the text string at the start of the text string".     EDITORIAL    perhaps add the words    "place the VISIBLE LABEL text string at the start of the ACCESSIBLE NAME text string"

**Comment by steverep** [comment]
The note has already been clarified as part of a larger issue #371.  The SC now reads:

> **Label in Name:** For active user interface components with labels that include text, the name includes the text of the label.
>
> *NOTE:* A best practice is to have the text of the label at the start of the name.

This latest version can be viewed at http://rawgit.com/w3c/wcag21/master/guidelines/#label-in-name.
