### ISSUE TITLE
Success Criterion 3.2.7 Change of Content

### ISSUE THREAD

**Issue by GreggVan** [w3c/wcag21#365]
> Programmatic notification is provided for each change of content that indicates a user action was taken or that conveys information, unless one or more of the following is true:
> 
> - There is a programmatically determined relationship between the new content and the control that triggers it;
> - The user has been advised of the change of content before or as a result of using the control;
> - The change of content is not a result of a user action AND not related to the primary purpose of the page.
> 
> NOTE
> The Working Group is including this proposed Success Criteria for comment, but has not reached consensus on how to best handle web pages and applications with continual changes of content such as games and simulations and seeks additional input from reviewers on this point.

==================================================================
This one is a bit confusing

programmatic notification is a new term and not defined.   
so you must define it if you are requireing it. 

the second bullet sound cyclical with the provision.   puttint the provision and bullet 2 together gives you something like         -- "you must notify (PN) the user if you change content to notify the user --- unless you notified the user ... as a result of using the control.

so I'm not sure what this is trying to do ---  and there is no UNDERSTANDING document.   

I would start with the UNDERSTANDING document and SUFFICIENT techniques.  I think it will help you sort this one out - and highlight problems and perhaps solutions

**Comment by etisdew** [comment]
I was using described-by and using invisible text for tts to read accessibility instructions. I believe this maybe a relavent implimentation. In my case I was openning sidecar, offered information that they would be focussed on a text input and backtabbing once would take them to the button to close the chat.

The dom changes very visibly and partially obstructs corrisponding content under z-index, is this a sufficient case? I have tested it with JAWs as thats what I use.

**Comment by DavidMacDonald** [comment]
## Proposed Response
Thank you for your comment. The SC is aimed at helping screen readers be notified when something changes on the page.

The understanding document was written with the original proposal last year. 
https://github.com/w3c/wcag21/blob/change-of-content/understanding/21/change-of-content.html

A definition for programmatic notification has been added recently
https://github.com/w3c/wcag21/pull/397/commits/b5c68e17f82feb0cdbbafc273f245b136a7445c4

The second bullet is an exception that allows users to provide advance warning before the user encounters a control that might change content instead of notifying them programmatically after the page was changed. 

Sufficient techniques are documented in the Understanding, these are known WAI-ARIA techniques which have been in regular practice and have been advised by accessibility professionals as a regular part of their advice to authors for several years.

**Comment by joshueoconnor** [comment]
Proposed definition for Programatic Notification has gone to CFC https://lists.w3.org/Archives/Public/w3c-wai-gl/2017OctDec/0024.html

**Comment by GreggVan** [comment]
Programmatic notification.

Notification set by the content which can be announced to the user 
without virtual or actual focus, using methods that are supported by 
user agents, including assistive technologies.

Example: a screen reader announces to a user that their shopping cart 
has been updated after they select an item for purchase.
It is unclear what  “SET by the content” means.   What is set.    Where is the setting? 

We usually say that it must be programmatically determinable  (e.g. the screen reader can tell when it happens) .    But this seems different but I’m not sure exactly what it means or asks for?     or what it does beyond what is already in WCAG 2.0.  

Also do we have sufficient techniques that are supported by AT for doing this? I looked but couldn’t find them. Where do we document them?

thx

g 

Gregg C Vanderheiden
greggvan@umd.edu

**Comment by awkawk** [comment]
Thanks for the comment. This SC has been scoped more narrowly to address status messages (a new defined term) and requiring that the changes are programmatically determinable. We hope that these changes will address your concerns.

**Comment by GreggVan** [comment]
there is not longer a 3.2.7  and no longer a “change of content”

can you tell me where this one has gone? 

Thanks

Gregg

**Comment by steverep** [comment]
Change of Content has been significantly re-scoped and renamed to Status Changes.  You can find the latest here: http://rawgit.com/w3c/wcag21/master/guidelines/#status-changes
