### ISSUE TITLE
5.1.2 Full pages

### ISSUE THREAD

**Issue by GreggVan** [w3c/wcag21#366]
> NOTE
> New A full page includes each variation of the page that is automatically generated by the page for various screen sizes. Each of these variations needs to conform (or needs to have a conforming alternate version) in order for the entire page to conform.
> 

==================================================================
I think this one is a problem.

1) I understand the sentiment but  changing conformance changes the conformance of all the SC  --
 and makes 2.1 NOT a superset of 2.0.   Many of the SC were crafted to work with the conformance as it was.  If you change the conformance you materially change some of the SC. So 2.1 would no longer be "2.0 plus" but materially different (depending on how you change the conformance language.   This can have all sorts of unintended consequences.   You would have to do a thorough evaluation of all the SC and suffiicent techniques etc.   This is at least a 3-4 person month activity I would estimate. 

2) you can't do this as a note. it should be a full conformance requirement

3) I see all sorts of problems with it.   I don't hink this has been thought through across all of the SC and technologies etc.     I think it was looked at simplistically and a couple of situations and seen as helpful there. - and then put in. 

Again - I see the driving force - but it is not something that should be added.

**Comment by DavidMacDonald** [comment]
90% of all evaluators interpret WCAG to already include the break points as part of the full page. 
https://twitter.com/davidmacd/status/885863118517264385

**Comment by awkawk** [comment]
(Official WG Response)
The consensus interpretation of conformance is that a page includes each view of it that targets different screen sizes at that URL. We think this is backwards compatible with WCAG 2.0, and makes it clear. In addition to our consensus, an informal poll of evaluators found that 98% of evaluators already interpret this conformance requirement to include break points as part of the full page.
https://twitter.com/davidmacd/status/885863118517264385
