### ISSUE TITLE
5.2.2 Optional Components of a Conformance Claim

### ISSUE THREAD

**Issue by GreggVan** [w3c/wcag21#367]
> - A list of specific accessibility characteristics of the content, provided in machine-readable metadata.

==================================================================
no problem with this one.

it is an optional claim and only a recommended element. 

tough to do but optional

**Comment by DavidMacDonald** [comment]
It will help epub folks legitimize their metadata proposals for discoverability of online accessible text books etc..

**Comment by awkawk** [comment]
Thanks for the comment.
