### ISSUE TITLE
references to pointer events and pointer events 2

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/wcag21#376]
The definition for [single-pointer activation](https://w3c.github.io/wcag21/guidelines/#dfn-single-pointer-activation) refers to Pointer Events, while the definition for [pointer input](https://w3c.github.io/wcag21/guidelines/#dfn-pointer-input) refers to Pointer Events 2. Unless there's a concrete reason for the difference, they should reference the same version.

**Comment by patrickhlauke** [comment]
PE2 is still in FPWD (though hoping to make final push soon to seal the deal). Are we ok referencing that?

**Comment by joshueoconnor** [comment]
@patrickhlauke sounds good.

**Comment by patrickhlauke** [comment]
I'd actually say that the definition for "pointer input" can also just point to PE Level 1 rather than 2, as that definition is exactly the same in both versions. And this way you're just referencing a REC

**Comment by joshueoconnor** [comment]
@michael-n-cooper  can this be closed?

**Comment by michael-n-cooper** [comment]
I took Patrick's suggestion just to reference the Rec version of Pointer Events. Note it is a normative reference from WCAG 2.1 - though since a Rec, not a Process problem.
