### ISSUE TITLE
Conventional controls, fields, and links - Log In and Log Out

### ISSUE THREAD

**Issue by fuzzbomb** [w3c/wcag21#381]
The list of Conventional Links (as of Sept 2017 WD) currently includes:

- Sign Up
- Sign In
- Sign Out

A large number of websites (and CMS, etc) use the terms "Log In" and "Log Out", effectively as synonyms.  Some websites use them interchangeably.

My suggestion is to include these in the list of conventional names.

Example: The [WordPress.com Log In](https://wordpress.com/log-in) page uses the phrase "Log In" as button text and page `<title>`.  For uses who do not have an account, a "Sign Up" link is included.

**Comment by awkawk** [comment]
Thank you for your comment. The current list is intended to indicate the purpose but not the specific terms used, so authors might use "sign in" or "log in" and from the perspective of the WCAG 2.1 SC both convey the same purpose. The current draft should help make this clear.
