### ISSUE TITLE
Conventional controls, fields, and links - Search

### ISSUE THREAD

**Issue by fuzzbomb** [w3c/wcag21#382]
The current list on conventional controls (Sept 2017 WD) doesn't include any terms relating to search functionality.

I'd suggest we add "Search" as a conventional name, at minimum.

We might also discuss related names which are typically found in advanced search, or facet-browsing interfaces.  In particular, some of the following are common in e-commerce sites with large catalogues.

- Keyword
- Category
- Filter
- Sort (by)
- Order (by)

**Comment by awkawk** [comment]
Thank you for your comment. The intention in this SC is to provide a small core set of purposes. The control information is now focused on user information, but we will keep your suggestions around search purposes in mind for the future.
