### ISSUE TITLE
Add technique for page list

### ISSUE THREAD

**Issue by mattgarrish** [w3c/wcag21#383]
An important tool for accessing digital publications is the page list. This provides a way to locate the page break locations in a print equivalent of the edition, for example, thereby allowing synchronization of text in mixed print-digital environments (e.g., schools).

It's not limited to print, although that's the common use case. It can be used to match up to any statically paginated alternative, such as PDF or even fixed-layout EPUBs (i.e., one document per page).

Page lists have been a central feature both of the DAISY and EPUB formats. DAISY and EPUB 2 use the pageList element in the NCX,[1] and EPUB 3 defines a page-list nav element.[2]

The DPUB-ARIA module also includes a doc-pagelist role, which is expected to be used to identify the same structure in the forthcoming web publications.[3]

We believe it would be useful to include a technique on using the page list to meet the multiple ways requirement, so would like to propose it for consideration.

[1] http://www.daisy.org/z3986/2005/Z3986-2005.html#NCXElem
[2] http://www.idpf.org/epub/31/spec/epub-packages.html#sec-nav-pagelist
[3] https://www.w3.org/TR/dpub-aria-1.0/#doc-pagelist

/cc @clapierre @GeorgeKerscher @avneeshsingh

**Comment by awkawk** [comment]
Suggested new technique for 2.4.5

**Comment by joshueoconnor** [comment]
@mattgarrish Thanks for the suggestion - I'm adding the implementation follow up label and closing this comment.

**Comment by mattgarrish** [comment]
Okay, thanks, just let me know what further you need from us whenever you need it.
