### ISSUE TITLE
Comment on Issue #10 User Interface Components Contrast

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/wcag21#384]
the Editor's note says 

> Under consideration: simplify this Success Criterion by setting the minimum color contrast requirement to 3:1 and removing any need for measuring thickness.

I agree with this and think it should happen in the next draft because of:
* Testing implications of measuring the size of things
* IU Components easier to discern than text which requires 4.5:1

**Comment by awkawk** [comment]
Closing as a duplicate of 489
