### ISSUE TITLE
Success Criterion 3.2.7 Change of Content - Addressing Games

### ISSUE THREAD

**Issue by SuzanneTaylor** [w3c/wcag21#385]
The Working Group requested feedback on "how to best handle web pages and applications with continual changes of content such as games and simulations and seeks additional input from reviewers on this point.”

“Programmatic notification” has not been defined specifically. (I think it should be given a formal definition if used in a SC this prominently.) Assuming “Programmatic notification” is notification that can be processed by AT, for games, there are a couple of issues:

- The most universal input/output for AT is text, and text can be too long (tedious/irritating) in a game environment
- Even if/when AT allows authors or users to specify other types of notifications (e.g. a sound, a vibration) these are likely too generic for a game environment, because they would “break immersion”. For example, if you just fed your virtual pet and they have had enough to eat, you expect a reaction from the pet that is consistent with the visual, haptic or sound design of the game overall. A common operating system sound, for example, would often be out of place.

So, this success criterion should allow game designers to choose between addressing each sensory output type themselves OR using AT-processed output.

Combinations of both techniques, should be allowed as well, and outlined in techniques. For example, you should be able to use sounds for blind players, visual effects for magnification users, and then rely on AT (programmatic notifications) for deaf-blind players. 

(A reasonable question might be, if you have this for the deaf-blind player, why not also make it an option for the blind player? Answer: If the blind player is using sounds at a fast pace for the whole experience, this might be an option that just makes no sense at all and simply wastes player's time if they decide to try it.)

Not sure about the level: It is possible that there should be an exception for certain games at Level AA, and then a guideline with the choice between techniques should be at Level AAA. On the other hand, without this, a Level AA rating for a game would be meaningless on many games for many users.

**Comment by ianhamilton** [comment]
WCAG isn't directly applicable to games, and compliance levels cannot apply to games. Games must by definition be exclusionary, without some kind of challenge they would be a toy or narrative, not a game. And any challenge will exclude some.

Accessibility in games is an optimisation process, avoiding unnecessary barriers, but what constitutes necessary and unnecessary varies wildly from game to game.

For example the WCAG requirements to avoid reliance on timing is entirely appropriate and desirable for a game of chess, but not for call or duty.

Entirely every game has the equivalent of compliance levels, a list of things that are reasonable to try for, but that list is specific to the individual game, and not a general bar that all games can aim for.

For this reason the exemption can't really be for this particular success criteria; it needs to be for most if not all success criteria.

As can be seen from gameaccessibilityguidelines.com the considerations for games are quite different to WCAG. For example the most commonly complained about issues - lack of reconfigurable keys, small text, and colourblind unfriendliness - in the first two instances are not covered by WCAG, and in the third instance covered by WCAG but in a way this does not work for many games, it often simply is not possible to avoid any reliance on colour. Other techniques are used instead.

Apologies for the rambling answer, but I hope it starts to paint a bit of a picture, that while there are of course some exceptions games are usually too different a medium for either the content or the structure of WCAG to be widely or usefully applicable.

**Comment by SuzanneTaylor** [comment]
It's a good point that mention of "games" should be presented carefully so people don't misunderstand. 

WCAG 2.1 is high quality well-informed work, so I think its safe to assume they meant games/simulations that would, for example, be part of a Web property and would otherwise be following WCAG. 
(as opposed to games like COD :-)

**Comment by ianhamilton** [comment]
There isn't really a clear distinction though, there are for example plenty of HTML5 canvas web games that are part of a broader web product but for which even WCAG level A success criteria are not applicable. 

COD wasn't an example of a game that is a separate stand alone piece of software, it was an example of a game mechanic for which the real-time exemption of 2.2.1 applies. 

For WCAG to be relevant to games most of the guidelines would need to be adapted, new guidelines would have to written and added, and 2.2.1 style exemptions added across the board, including exemptions from any A/AA/AAA fixed bar to aim for, all of which wild obviously be a bit much to ask. In both directions, I don't think it would really be appropriate for WCAG to include guidelines for being able to reconfigure your controls or for difficulty levels, as despite being basic fundamentals of game accessibility they are irrelevant to documents and applications.

While WCAG is applicable in its entirety to a small number of games, for example a static entirely interface based game like football manager, these are a very small minority. 

I think the core of it is that even if games happen to be built using web technologies, they are not the kind of content that WCAG is designed for, there are some really fundamental differences. And I've seen first hand the harm that is done when developers try to apply web standard to games and encounter musts that are mechanising impossible to implement without breaking the game.

So to my mind, rather than this being a question about a specific guideline, it would be far better for WCAG 2.1 to contain a general statement on the applicability and incapplicability of the guidelines in general to games.

**Comment by patrickhlauke** [comment]
A more fundamental question perhaps: rather than scoping WCAG 2.1 to say "this doesn't necessarily apply to games, as meeting the requirements of many SCs would effectively invalidate the point of games", isn't it up to website owners to know this and not even try to claim WCAG 2.1 compliance? as in, if i have a site that only contains a game, would I as site owner bother at all with trying to meet WCAG 2.1? or if the game is part of a larger, more traditional site, would I not simply explicitly exclude it in my accessibility statement (i.e. "the site complies with WCAG 2.1 AA, with the exception of the game bit which is out of scope for WCAG 2.1")?

**Comment by ianhamilton** [comment]
I think a couple of other things to consider are are firstly that making that kind of a call at the parent website accessibility statement end would require people working in web to have a deep enough understanding of games, which definitely isn't always the case. Particularly as games are commonly farmed out to third parties to build.

Then also that although there isn't much of WCAG that could be uniformally applied to games as a fixed bar, there are still plenty of things that can be applied to games, it's just that the list of what's applicable varies from game to game, so WCAG & games being an either in or out thing would miss out on some benefits. 

An example I've seen quite a few times is game developers who have been engaged by a client who has a general accessibility requirements, which the game developer sets out to address initially, but then when encountering a guideline that isn't applicable to their game, decides that the entire set of guidelines is therefore irrelevant to them, resulting in painful dialogue and costs further down the line.

Then of course there's the issue of countries adopting WCAG as a legal requirement, in which case there is no flexibility at all to make exceptions, no legal ability to decide at product or orgnisation level that something is out of scope.  

A general statement and exemption within WCAG could help to alleviate all those kind of scenarios, setting out in broad terms what a game is defined as, how WCAG relates and does not relate to games, and how and when elements of it can/should be used. 

WCAG isn't the only area where this is an issue, application of 508 to educational games is another, and a nice example too as it is often just ignored, left as the elephant in the room. So providing a bit of clarity on this at WCAG level could also have wider benefits, particularly with 508/WCAG convergence.

**Comment by patrickhlauke** [comment]
> Then of course there's the issue of countries adopting WCAG as a legal requirement, in which case there is no flexibility at all to make exceptions, no legal ability to decide at product or orgnisation level that something is out of scope.

there is the ability to provide an accessible alternative. taking an example from my recent work (without naming names, of course), a bank offering an interactive "game" (with quicktime events, tetris style sections, a sim city style building part, etc) trying to make it accessible to WCAG 2 were having major problems...in the end, I strongly advised them that making the game itself accessible (beyond things like keyboard access and color perception) would have been almost completely impossible, and to instead focus on providing an alternative that serves the same purpose (which in the case of their game was "give the user some advice on planning for their retirement") using more traditional HTML (with multiple-choice, form-based quizzes etc)

**Comment by patrickhlauke** [comment]
> A general statement and exemption within WCAG could help to alleviate all those kind of scenarios, setting out in broad terms what a game is defined as, how WCAG relates and does not relate to games, and how and when elements of it can/should be used.

what would that look like? I can't think of anything more than "WCAG applies everywhere, except where meeting it would invalidate the objective of the content (but you should try to meet SCs where possible even there, and/or provide an accessible alternative that serves the same purpose if possible)"

**Comment by ianhamilton** [comment]
I think along those lines, the general principle that WCAG should be applied to games where relevant but acceptable to not apply it where it is not relevant.

Although not just about invalidating the objective; there's also an issue of whether the content would be usable even if technically accessible. So for example if implementing text equivalents would not break the game, but even with them the game would not be in any way accessible for people who would make use of those equivalents. 

Also bit of help on how to go about deciding what is relevant to apply and what isn't; working out the equivalent of compliance levels for that individual game, independently of A/AA/AAA. 

And I think also helpful to scope it specifically to games, and define what "games" means. 

Wouldn't want there to be an easy mechanism for a dev to be able to say "I'm making a quiz, that's a game, no accessibility here thanks".

This is all just quick top of the head thoughts though.

**Comment by patrickhlauke** [comment]
i'd be careful not to say "games" specifically though. the same reasoning applies to things like second-life style virtual environments, or 360 campus tours, etc, I'd say.

**Comment by ianhamilton** [comment]
For accessible alternatives.. absolutely, in some instances that would do it. Another example being that one earlier of educational games, where the game is solely there to teach specific goals on the curriculum. But not always, also need to consider game that are there for their own sake, without a broader goal or purpose beyond the emotions the designer wants the player to experience, which wouldn't be something that could reasonably be translated into another medium.

**Comment by ianhamilton** [comment]
> i'd be careful not to say "games" specifically though. the same reasoning applies to things like second-life style virtual environments, or 360 campus tours, etc, I'd say.

Yeah, although I think that's a slightly different issue, about accessibility of environments Vs interfaces. Both of which can apply to games obviously, but then with games, also that a mix of accessibility and inaccessibility is a required part of the experience, and what that mix is being different for each game. 

So for environments more that a different set of guidelines would be applicable; for games more that guidelines aren't applicable in the same way.

**Comment by SuzanneTaylor** [comment]
Game-like elements can appear anywhere and I think we'll see them in software more and more. I think it is clear that WCAG should not take on the added complexity of the full scope of game accessibility. (Keeping standards as short and simple as possible while still being effective is extremely important.) Clarifying that WCAG is not designed as model into which you can fit all games is a good idea.

But, regardless, any SC that *are in WCAG* should be complete in themselves. From discussion above, I think the SC should not include the word "game" or present definitions of "game" but  should describe specific conditions, such as a measure of the frequency and complexity of the "changes of content"

If you have a simulation that has notifications, asking how you apply 3.2.7 is a valid question independent of the lack of applicability of all of WCAG to all games. Maybe:

- AT notifications
- OR handling sensory needs in a more artsy fashion (you hear bubbling when the water starts to boil, but your screen reader speech is not interrupted) [This is the one I particularly want to make sure is allowed]
- Perhaps a frequency that is too high and so results in a complete exception

**Comment by ianhamilton** [comment]
I agree that SCs should not reference games, referring instead to specific interactions makes them much more easily/widely applicable.

For mentioning/defining "game" I meant as part of that WCAG-wide clarification, rather than as part of any individual SC. Is there any mechanism for getting a proposal for that clarification in for 2.1? I've read that the comments window for the current draft is closed now?

**Comment by SuzanneTaylor** [comment]
I think a WCAG-wide statement or educational resource belongs more to 3.0, but I was just dropping by to comment ( @awkawk would know ?) 

As part of an IGDA OER project, Thomas Westin is going to bring up the idea of creating an "education and outreach" type decision tree about games with the WCAG Silver (3.0) working group. The process of writing that will also really quantify the gaps in case any can/should be addressed to better cover gamified software. 

(If it is possible to write a statement that would cover everything and be understandable that would that would be great - I think it would take a flow-chart or decision tree... )

**Comment by ianhamilton** [comment]
Perhaps both? Quick couple of introductory paragraphs to cover some people's needs, then tree for others who need to get into the meat of it a bit more? 

The most important place for it is in 508 as that's where the legally mandated accessibility requirements for games used in education and training come in, and so where there's the biggest clash between what's legally required and actually possible. 

I don't know much about what the process is for WCAG/508 alignment, what version is covered and if future updates will filter across. But I suppose that's what I'm angling for really - to be able to get that kind of clarification in there early enough that it can make it in to 508 too. Even if it's just that couple of paragraphs to start with it ahead of more detail in 3.0 it could still do a fair bit of good in the interim.

**Comment by SuzanneTaylor** [comment]
Other than one type of situation that has never be tested legally (game without learning outcomes in the classroom), I think there are enough options through exception, equivalent facilitation and accommodation to avoid that clash. We don't have an appropriate lawyer on staff to review that type of comment, though, so I can't outline anything in detail. But, I don't agree that there is a clash **_generally_**.  I agree that there are misinterpretations that cause loss of resources and frustration, though.

**Comment by ianhamilton** [comment]
So by exception do you mean exceptions already baked into SCs, e.g. the 2.1.1 exemption for real-time content?

**Comment by ianhamilton** [comment]
Ah sorry I guess you mean this, exceptions for undue burden or fundamental alteration, conditional to alternatives being provided? 

https://www.access-board.gov/guidelines-and-standards/communications-and-it/about-the-ict-refresh/final-rule/text-of-the-standards-and-guidelines#E202-general-exceptions

I hadn't read that before. I guess that covers it, but still feels like a statement covering it at WCAG level would help.

**Comment by SuzanneTaylor** [comment]
I mean that as whole, I don't know of cases where there is a legal requirement to do something that is not possible related to WCAG 2.  There are the exceptions in the SC, protections at the 508 level,  protections in the other laws that reference 508, and protections in laws that don't reference a standard but just call for access (and then people look toward 508 anyway).

(If you have a client or client's customer who is saying they legally must follow 508 for education, this can also be from state laws and even more local policies that point to the 508 standards. )

There is also equivalent facilitation in 508, which helps if the requirement is doable, but would not be effective. For example, take even Audio Description at level AA - sometimes it doesn't make any sense at all to add audio description in existing pauses, because those pauses aren't long enough and the users still wouldn't know what was going on. Luckily, through equivalent facilitation, you are able to design a solution that makes sense:

https://www.access-board.gov/guidelines-and-standards/communications-and-it/about-the-ict-refresh/final-rule/text-of-the-standards-and-guidelines#E101-general

**Comment by SuzanneTaylor** [comment]
"a statement covering it at WCAG level would help"
I agree, something to help people more quickly outline a plan for complex items (like games) would help reduce costs, focus resources on effective solutions and prevent "accessibility burnout".

**Comment by awkawk** [comment]
Thanks for the comment. This SC has been scoped more narrowly to address status messages (a new defined term) and requiring that the changes are programmatically determinable. We hope that these changes will address your concerns.

**Comment by SuzanneTaylor** [comment]
Thanks! Added new issue: #605

**Comment by SuzanneTaylor** [comment]
(yes, the change makes the issue discussed here irrelevant)
