### ISSUE TITLE
What do 'character key' and 'printable' mean?

### ISSUE THREAD

**Issue by r12a** [w3c/wcag21#386]
Success Criterion 2.4.11 Character Key Shortcuts§ 
https://www.w3.org/TR/WCAG21/#character-key-shortcuts

> If a keyboard shortcut consisting entirely of one or more character keys is implemented by the content, then a mechanism is available to turn it off or to remap it to a shortcut that uses at least one non-character key. 

https://www.w3.org/TR/WCAG21/#dfn-character-key

> single printable Unicode code point, any keyboard character that is printable, i.e. letters of the alphabet including capitals, punctuation, numbers, and symbols
> 
> Note that the Space and Enter keys, which return empty spaces rather than characters, are not character keys.

It would be better to more clearly define what is and isn't a 'character key', and what 'printable' means.  (The UI Events specs may help?)  I'm not clear why the space character couldn't be a shortcut key – see it's use, for example, in Thunderbird to scroll down messages then on to the next message.

**Comment by StommePoes** [comment]
Space to scroll down is a regular thing in many applications, including browsers. But you can say the same for the Enter key-- most applications use it to engage a control. In fact, space does this too. It's built into many UIs like selecting checkboxes. Would be good to know what the reasons were for exempting space though.

As a developer, I take "printable keys" as keys who would trigger oninput (except delete), then minus the ones listed in the SC.

**Comment by awkawk** [comment]
(Official WG Response)
Thank you for the comment. We have re-written the criterion to incorporate your suggestion. The updated SC can be viewed at: http://rawgit.com/w3c/wcag21/master/guidelines/index.html#character-key-shortcuts
