### ISSUE TITLE
Adapting Text: Line height and leading

### ISSUE THREAD

**Issue by r12a** [w3c/wcag21#388]
Success Criterion 1.4.13 Adapting Text
https://www.w3.org/TR/WCAG21/#adapting-text

> If the technologies being used allow the user agent to adapt style properties of text, then no loss of essential content or functionality occurs by adapting all of the following:
> Line height (line spacing) to at least 1.5 times the font size
> Spacing underneath paragraphs to at least 2 times the font size

Such changes should produce multiples or additions to existing line heights/leading, particularly where a page contains multiple languages.  For example, Thai or Tibetan text needs much larger line heights relative to font size than english.  If the line height of the english is bumped up, that of the thai and tibetan text should also be increase pro rata – it should certainly not be reduced to match the english.

**Comment by steverep** [comment]
> Such changes should produce multiples or additions to existing line heights/leading, particularly where a page contains multiple languages. 

Specifying the criterion test condition in terms of a factor or addition to existing line height would unnecessarily penalize pages which already use a sufficient line height, so I think we need to keep it as an absolute number which has been shown to affect reading.  That said, we could give different numbers for different languages if needed.

> For example, Thai or Tibetan text needs much larger line heights relative to font size than english. If the line height of the english is bumped up, that of the thai and tibetan text should also be increase pro rata – it should certainly not be reduced to match the english.

First, the criterion does say "at least", so there would be no need to reduce line height to test the condition.  Your point about Thai and Tibetan line heights being much larger is interesting though - what is a typical line height and what happens if it is reduced?

**Comment by r12a** [comment]
@steverep I don't know how to quantify the typical line heights for the various scripts, and it's not clear to me what the answer should be for non-latin scripts, but i could give you some examples that may help illustrate the possible issues.

[1] These two phrases are in Persian and Urdu, using the nastaliq style of arabic. A typical english capital letter would be about the size of the ! mark.  Note how the arabic descenders go way below the point where latin script descenders would stop, and the diagonal baseline can cause there to be a significant distance between the top and bottom of the text.

![screen shot 2017-10-17 at 17 47 05](https://user-images.githubusercontent.com/4839211/31677647-6eac855a-b363-11e7-874a-95b4b523c605.png)

Here is some Tibetan text. Note how the character stack within a syllable. (The W3C text is maybe a little larger than normal in this example.)

![screen shot 2017-10-17 at 17 49 49](https://user-images.githubusercontent.com/4839211/31677756-b7e777ca-b363-11e7-8230-071d1c36218d.png)

Here is some Thai text. Note how much more vertical space is needed, compared to the latin text. If you were working with an old LCD panel, it would be possible to produce adequate english with 8 pixels in height, but thai would require a minimum of 22 pixels.

![screen shot 2017-10-17 at 17 52 05](https://user-images.githubusercontent.com/4839211/31677844-00917638-b364-11e7-93e8-76ed0df4a4a0.png)

[2] However, the above is just about line height.  Typically these scripts _also_ apply more spacing between lines than english does, by default, in order to cleanly separate lines and make the visual balance look right. It's not clear to me how that factors in to the user's needs – whether it eases the issue here, or whether the line leading needs to also increase proportionally.  

[3] Another problem is that a given font size is much more likely to produce wide variations in actual rendered text in non-latin fonts.  For example, compare the same glyphs set to the exact same font-size in Mongolian Baiti and Noto Sans Mongolian:

![](https://cloud.githubusercontent.com/assets/4839211/15365391/03a38354-1d18-11e6-82cf-0db2412a3bb0.png)

This kind of thing is a regular problem in fonts for other scripts too. I'm not sure what we can do about it, but it means that basing the line-height and leading on the font size will have different effects, depending on the font that is used.

**Comment by awkawk** [comment]
Thank you for your comment.

As @steverep said, the criterion does say "at least", so there is no need to reduce line height to test the condition.

You are correct that basing the line-height and leading on the font size will have different effects, depending on the font used. The current metrics were chosen as measures based on Research. McLeish ran from .04 to .25 em tests. McLeish found an increasing curve in reading speed of actual materials up to .25, but it really started to flatten at .20. Previous studies that reported no improvement started at .5em. Right at the flat point. Wayne E. Dick, Ph.D. analyzed the McLeish study and translated from points. Dr. Dick recommended the metrics that the Working Group adopted.

If you know of international research that impacts the current metrics please add them to this issue. As Steve said we could give different numbers for different languages if needed.
