### ISSUE TITLE
Adapting Text: font-family

### ISSUE THREAD

**Issue by r12a** [w3c/wcag21#389]
Success Criterion 1.4.13 Adapting Text
https://www.w3.org/TR/WCAG21/#adapting-text

> If the technologies being used allow the user agent to adapt style properties of text, then no loss of essential content or functionality occurs by adapting all of the following: ...
> The Working Group seeks to include overriding text color, background color, and font-family

Font-family adaptations would need to be sensitive to language changes.  A page containing text in both english and hindi would not necessarily become more readable if a user-defined english font was applied to all the hindi text too (and vice versa).

**Comment by steverep** [comment]
> Font-family adaptations would need to be sensitive to language changes. A page containing text in both english and hindi would not necessarily become more readable if a user-defined english font was applied to all the hindi text too (and vice versa).

Yes, internationalization is one reason that font family is likely not to be included in the final version of this SC.  However, the testability issue relates to being too wide or too narrow with the font to test, and the latter leads to internationalization concerns.  Ultimately though, it is up to the user making the adaptations to be sensitive to language when selecting their fonts (e.g. by having separate selectors in a custom stylesheet).

**Comment by mbgower** [comment]
> if a user-defined english font was applied to all the hindi text too

To elaborate on what @steverep is saying, if the SC makes it an author requirement _not_ to interfere with a user's ability to override the author settings for text attributes, then the author can't be responsible if the user makes a 'poor' decision. If colour was included in this SC and a user chose white text on an almost white background, nothing will be viewable; but that is the user's choice, not the author's responsibility.
Trying to find language that improves user experience, makes responsibilities clear and provides consistent testable results for failures is the challenge.
The text properties specified in the current language (line height, letter spacing, word spacing, space after paragraphs) are measurable, are believed to be achievable, and have been shown to have positive impact on certain user bases.

**Comment by awkawk** [comment]
Thank you for your comment.

The WG decided to remove the font family bullet from the SC per Issue #153.
