### ISSUE TITLE
Critical features

### ISSUE THREAD

**Issue by lseeman** [w3c/wcag21#39]
<h2><strong>SC Text: Critical features</strong></h2>
		        <p><strong>Critical features</strong> and important information are above the fold and are accentuated in the main modality of the content.</p>
		        <h2>Suggestion for Priority Level (A/AA/AAA)</h2>
		        <h2>Related Glossary additions or changes</h2>
		        <dl>
		          <dt>critical features </dt>
		          <dd>features that are required to complete the main role or tasks of the user interface</dd>
		          <dt> main modality of the content  </dt>
		          <dd>modalities considered in the design of the content</dd>
		          <dt>above the fold </dt>
		          <dd>positioned in the upper part of a web page and so visible without scrolling down the page in the main modality of the content.</dd>
			</dl>
<h2>What Principle and Guideline the SC falls within.</h2>
		        <p>Under principle 2, Operable </p>
<p>2.4 Provide ways to help users navigate, find content, and determine where they are. </p>
		        <p><strong>Or</strong></p>
		        <p>Under principle 3 Understandable </p>
		        <p> 3.2 Make Web pages appear and operate in predictable ways, </p>
		        <p><strong>Or</strong></p>
		        <p>Under principle 3 Understandable </p>
		        <p>3.3 Help users avoid and correct mistakes. </p>
		        <h2>Description</h2>
		        <p>The intent of this Success Criterion is that users who do not remember to use the scroll will be able to use critical features.</p>
		        <p>When the main features are under the fold, these users will be unable to complete the main task. Therefore, designers should either have critical features above the fold or have a clearly labeled mechanism to help users find critical feature (such as a menu button).</p>
		        <p> This can also be achieved via personalization. </p>
		        <p>For example , in an application for drafting an email, the send button is a critical feature without which the application has no use. The author must put any critical features, such as send, above the fold.</p>
		        <p>See the section on testability for additional clarity.</p>
		        <h2>Benefits</h2>
<p>People with low executive function, impaired memory, and other cognitive and learning disabilities may not be able to find features that are under the fold and that require the use of the scroll bar. </p>
<p>Many users are happy with important features being &quot;discoverable&quot; where they have to figure out or learn how to use them. The interface becomes a problem to solve. However people with some cognitive and learning disabilities may lack the executive function to figure this out, and people with impaired memory may not remember to use the scroll as a mechanism for finding content.</p>
<h3 id="resources2">See also</h3>
                <ul>
                  <li><a href="https://rawgit.com/w3c/coga/master/gap-analysis/">Gap analysis  </a></li>
                  <li> <a href="https://rawgit.com/w3c/coga/master/gap-analysis/table.html">User needs Table                   4: Help and support                  </a></li>
                  <li><a rel="nofollow" href="https://w3c.github.io/wcag/coga/user-research.html">Background research document</a></li>
                  <li> <a rel="nofollow" href="https://rawgit.com/w3c/coga/master/issue-papers/links-buttons.html">Semantics for adaptive interfaces</a></li>
                  <li><a href="https://rawgit.com/w3c/coga/master/techniques/index.htm">COGA Techniques</a> </li>
                </ul>
		        <h2>Testability</h2>
		        <p>Testing requires three parts:</p>
<p>Part one: Identify critical features</p>
		        <p>Part two: Confirm that they are above the fold in the main modality of the content.</p>
		        <p>Part three: Confirm that they are accentuated in the main modality of the content. </p>
		        <p><strong>Step 1 Identify critical feature </strong></p>
<p>Identify the main role or tasks of the page, such as: </p>
		        <ul>
		          <li>sending an email </li>
		          <li>finding out how to contact us</li>
		          <li>finding out what we do</li>
</ul>
<p><strong>Note that the main role is usually identified in the page title</strong></p>
<p>Perform a dry run of the task. Review the steps involved. Identify what information needs to be read or what events need to be activated for each step and/or the main task. These are the critical features.</p>
		        <p>For example:</p>
		        <ul>
		          <li>If the main role is sending an email, drafting and sending an email are critical features</li>
		          <li>If the main role is finding out how to contact us, then access to the contact information is the critical feature</li>
			</ul>
<p><strong>Step 2: Confirm they are above the fold</strong></p>
		        <p>Load the page in the main modalities of the content, such as a laptop and mobile device. Confirm critical features are viewable, or a clearly labeled mechanism is available to reach them (see sufficient techniques).</p>
		        <p><strong>Step 3: Confirm that they are accentuated in the main modality of the content. </strong></p>
		        <ul>
		          <li>Identify the main modality of the content (such as a visual screen)</li>
		          <li>Confirm that a sufficient technique has been used to accentuate them OR</li>
		          <li>Confirm with a focus group that 9 out of 10 users will consider them accentuated.</li>
</ul>
		        <p>Note: We may need to define semantics in the header, accessibility conformance statement or other mechanism for declaring the main modality.</p>
		        <h2>Techniques</h2>
		        <p>Sufficient techniques for &quot;Critical features are above the fold&quot;</p>
		        <ul>
		          <li>Critical features are above the fold </li>
		          <li>Providing a clear mechanisism to reach critical features above the fold, such as a clear link </li>
		          <li>Using coga-simplification semantics and personalization to identify, position, and accentuate features </li>
		</ul>
		        <p>Sufficient techniques such that critical features are accentuated</p>
                <ul>
                  	<li>Critical features and important information to the user are visually differentiated and accentuated </li>
                  	<li>Critical features appear before the other main content</li>
                  	<li>Using coga-simplification semantics and personalization to identify, position, and accentuate features </li>
			<li>Auditory emphasis using a slightly louder content, a change in the pitch, or a change in the voice</li>
                </ul>          
  <h2> working groups notes (optional)</h2>

**Comment by DavidMacDonald** [comment]
There doesn't appear to be a suggested WCAG Level

**Comment by lseeman** [comment]
A or AA

**Comment by jasonjgw** [comment]
This seems to require the author to make (and document?) problematic assumptions about the size of the viewport in both implementation and evaluation of the success criterion. The making of such assumptions is inconsistent with the diversity of window sizes and devices that users may have. Can this SC be rewritten to avoid these assumptions?

Also, perhaps it should be reworded to use the concept of a task's being essential to an activity.

**Comment by lseeman** [comment]
lets change "Critical features" to " Critical controls" 
and remove "important information
then we have " critical control are above the fold and are accentuated in the main modality of the content."
and change glossary to 
critical control
    controls that are required to complete the main role or activity of the content

**Comment by lseeman** [comment]
the example should be placed before the line that this can be achieved via personalization. I think it is clearer then.

**Comment by SteveALee** [comment]
There's a tonne of info here including testability details but I do not see anything like that in the SCs in the WCAG guidelines source. The yare all much shorter.

**Comment by lseeman** [comment]
I think it is OK, it is just to give an idea if it is testable

All the best

Lisa Seeman

LinkedIn, Twitter





---- On Tue, 24 Jan 2017 19:41:54 +0200 Steve Lee&lt;notifications@github.com&gt; wrote ---- 

There's a tonne of info here including testability details but I do not see anything like that in the SCs in the WCAG guidelines source. The yare all much shorter.

**Comment by SteveALee** [comment]
but a shame to lose so much excellent content. Perhaps it will get archived someplace?

**Comment by awkawk** [comment]
Closing since the pull request was created. Further comments go there: https://github.com/w3c/wcag21/pull/95
