### ISSUE TITLE
Adapting Text: Letter spacing

### ISSUE THREAD

**Issue by r12a** [w3c/wcag21#390]
Success Criterion 1.4.13 Adapting Text§ 
https://www.w3.org/TR/WCAG21/#adapting-text

> If the technologies being used allow the user agent to adapt style properties of text, then no loss of essential content or functionality occurs by adapting all of the following:
> Letter spacing (tracking) to at least 0.12 times the font size;

Is the content author going to allow the user to apply a fixed tracking distance for all text?  I imagine this would be better applied as a multiplier or addition for current tracking.

One reason for this is that i am told that tracking is used in German as a method of emphasis (eg. rather than english italicisation). If you make the tracking for a spaced-out word the same as the surrounding text, the reader would loose a presentational feature that is meaning-related.

Also, there's a question of whether this will affect ligation (eg. fi ligatures) by separating them?

I also have questions about how this woud apply to other scripts.  

Arabic, Assyrian, Mongolian, and N'Ko, for example, are cursive scripts (ie. the letters join).  Again, for Arabic, baseline stretching is often used for emphasising text, for making headings or signage more visible, or for matching the length of adjoining lines of text, etc. When the baseline is stretched, moreover, there are fairly complicated rules about where the stretching is and isn't allowed. I don't believe this is yet covered by the letter-spacing property in CSS.

In other complex scripts, such as Devanagari (used for Hindi), certain combinations of characters combine together, and it's not clear to me how tracking is applied but it's clear that it's not between each character.  If the user is applying the tracking via a CSS property change, that may take care of many of the issues, but not clear to me yet whether all.

Also, is the 0.12 multiplier based on research on English text or on a variety of scripts?  If the former, the spec should probably call that out.

And finally, the text may already have positive or negative tracking set using CSS.  Presumably that setting should be taken into account when adding addition space, rather than just basing the ratio on the font size.

**Comment by mraccess77** [comment]
@r12a wrote One reason for this is that i am told that tracking is used in German as a method of emphasis (eg. rather than english italicisation). If you make the tracking for a spaced-out word the same as the surrounding text, the reader would loose a presentational feature that is meaning-related.

How is this communicated today semantically in a way that can be used by assistive technology such as screen readers?  use of presentation without semantics or text is a failure of SC 1.3.1.   If semantic structure is provided which is required by WCAG then a user can have a custom CSS that might apply another visual difference rather than spacing to the text.  So this isn't an issue if there is semantic structure there.

If the user changes the CSS to something that loses the many communicated structurally that is up to them and not the authors issue.  For example, a user may choose remove bold text in a custom CSS and instead use brackets because bolding is difficult to read. That is the user's choice and doesn't invaldidate anything the author did.

**Comment by r12a** [comment]
I'd not just hope but fully expect, that emphasised text would always be identified semantically, probably using something like the `em` tag in HTML.

The recommendation in the spec reviewed doesn't talk about alternative styling, it just recommends using a minimal amount of additional spacing based on the font-size. 

[In parentheses, I'm still not particularly clear about how all this text adaptation happens. From reading the spec text a few times (maybe not all the right bits), i'm imaging that the reader presses some button or such, and the user agent then increases the tracking in the document by a minimal amount (0.12 times the font size). Please explain for me, if i haven't quite grasped it.]

My concern is that if a user agent just goes ahead and applies a fixed amount of increased spacing to the whole text, without sensitivity to places where tracking is already applied (either for semantics such as emphasis in German, Hebrew, etc, where increased tracking conveys such semantics*, or sometimes just for readability or visual effect, in fact), then the visual representation of the emphasis will simply be lost. I assume that the user agent has to consider what to do with ranges of text where tracking has already been applied, in addition to the font size. And i'm guessing that the spec should make some reference to that.

[* Incidentally, this apparently also reduces the likelihood of inter-character spacing during justification for those languages, to avoid misinterpretation.]

**Comment by mraccess77** [comment]
@r12a The changes would be via user style sheets implemented or customized by the user.  Sure there may be some extensions or publically available ones -- but ultimately a user can turn text into white text on a white background already -- this is not the author's problem -- this is the user's choosing.  If the user wants to keep em tags with a different spacing they can do that in the user stylesheet.  This SC does not dictate that all extensions must set all content to a certain height -- just that the content can be set to that height.

**Comment by goodwitch** [comment]
Have y'all seen the fabulous research/tool that Wayne Dick has been working on?  It helps people find their personal "Text Prescription".  A Text Prescription is the font size, color, family, line spacing, letter spacing and word spacing that works best for you!  It is called TRx  (for Text Rx, or Text Prescription).  It goes far beyond what the proposed SC is doing.  I think it is a beautiful gift to the world of accessibility.  See it and explore it at https://trx.knowbility.org/

**Comment by detlevhfischer** [comment]
Firstly, adding tracking as a means of emphasis is VERY rare in online sources in Germany. You see it sometimes in old lay sites from the 90s (even done by adding spaces between letters).
IF it was used, it would be done properly only by styling based on some semantic element like strong or em, so for those cases user style sheets might adapt to increase tracking values proportionally?
But the main point is that this is really a very rare edge case.

**Comment by awkawk** [comment]
Thank you for your comment.

The intent of this Success Criterion is to help ensure that people with disabilities who override spacing can read text. It allows for a spacing buffer. Applying that buffer is under the user's control.

As @mraccess77 (Jon Avala) stated changes can be made via user style sheets implemented or customized by the user. A bookmarklet has also been developed. As Jon stated the SC does not dictate that authors must set all their content to the specified metrics. Rather, it specifies that an author's content has the ability to be set to those metrics without the loss of content or functionality. The author requirement is to not to interfere with a user's ability to override the author settings.

We have called out the basis for the SC's metrics in the Understanding Document and link to the actual studies in the resources section. If you can provide specific examples of where this would be a problem that would be helpful in our implementation review.
