### ISSUE TITLE
Harmonization of level for 1.2.4 Captions (Live) and 1.2.9 Audio-only (Live) - ideally move 1.2.4 from AA to AAA

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/wcag21#394]
Started the discussion on mailing list https://lists.w3.org/Archives/Public/w3c-wai-gl/2017JulSep/0052.html but don't think we reached an agreement (though the problem itself was aknowledged).

To try and summarise some of what was discussed on mailing list, I opened with:

> 1.2.4 Captions (Live): Captions are provided for all live audio content 
in synchronized media. (Level AA)
>
> My understanding here is that since it's about captions, and 
synchronized media, this does not apply to audio-only (live) content. 
And in fact, at level AA, there's nothing about providing any 
alternative for live audio-only content...only at AAA with 1.2.9?
>
> If so, this seems strange to me. Arguably, providing captions for live 
audio that is part of some synchronized media presentation is slightly 
more complex than providing an alternative for live audio-only. I'd also 
argue that live audio-only (for instance, an internet radio station or 
similar) is more common than live audio as part of a synchronized media 
presentation (full-blown audio/video streamed live presentation, for 
example).
> 
> What's the rationale for having 1.2.9 at AAA while 1.2.4 is AA?

@awkawk replied

> I don’t remember the conversation around this specifically, but I do recall there being a lot of concern even about live captions for synchronized media at AA, so this may have been a compromise.
>
> I can vaguely recall discussion (but may be misremembering) around the volume of audio content that online radio stations and other continuous broadcasters put out, so it may have been done in response to comments.

which, for the time of WCAG 2, makes sense, as live audio streaming was quite prevalent, whereas live video streaming was quite rare due to the technology for it being complex/expensive.

fast forward to now, where it's technically trivial for anybody to add live audio/video streaming to their site (via Google Hangouts, YouTube, Twitch, etc), and I believe the same problem/compromise identified at the time for the volume of audio content now applies to the volume of a/v, and having the requirement for live captioning (which, compared to the actual addition of streaming a/v *is* still difficult, expensive, problematic) at AA makes it pretty much impossible for sites to use a/v streaming if they want to pass WCAG 2.0 (or to explicitly exclude their streaming part in their accessibility statement).

For my part, my preferred way forward here would be to move 1.2.4 Captions (Live) from AA to AAA.

**Comment by DavidMacDonald** [comment]
Most laws and policy I've seen exempt live captioning, which is not the best situation for WCAG or for accessibility, so its reasonable request. However,  demoting live captions to AAA would put us in  a position where conforming to 2.1 might not conform to WCAG 2.0 which our charter section on compatibility does not allow.

**Comment by goodwitch** [comment]
So, I've gotten used to hiring a live transcriber for meetings.  It really is not that big a deal.  Not even super expensive in my book.  I regularly play $125 for an hour meeting to be live transcribed. And the ROI is you get great meeting minutes!  Deque sponsored live transcribers for the A11Y Summit (and all day event).   

I'd prefer to leave this in as AA, and have people justify exceptions.  If an entire government wants to issue an "exception", that is their choice.  I don't think it has diluted the value of WCAG 2.0 A/AA.

**Comment by patrickhlauke** [comment]
glenda...that's good, but certainly not tenable for every site owner wanting to have live streaming (e.g. a twitch stream of them doing a let's play of a game, or something) while still being accessible up to AA (unless they out-of-scope the live streaming part from their claim). whereas if they just streamed audio only, they'd be fine without live transcript (that's the imbalance here that seems strange).

**Comment by goodwitch** [comment]
@patrickhlauke Doh!  I see what you are talking about.  That is bizarre!  We do need to either be all AAA or all AA on this live media stuff.   If I were in charge of the world, I'd make it all AA in WCAG 2.1 (and require anyone who can't afford to caption/transcribe the live content to just say "except for X").   

Thanks for helping me see this imbalance.

**Comment by awkawk** [comment]
Marking as defer since we aren't changing this in 2.1 and even if we were making a change we wouldn't be moving an SC to a lower priority level due to the need for backward compatibility.
