### ISSUE TITLE
Priority of issue 1.3.5

### ISSUE THREAD

**Issue by JonathanPKatz** [w3c/wcag21#399]
Hi all,

I'm concerned that issue 1.3.5 (contextual information, public vocabulary) is set too low at AAA. In many cases users with cognitive disabilities have problems navigating sites that do not have adequate contextual information or text that explains features. Is there a reason this is set at AAA and not AA?

Jonathan

**Comment by awkawk** [comment]
Official WG Response: Thank you for your comment. This SC is paired with a AA SC, "Identify Common Purpose". The AA SC is focused on a constrained set of defined purposes, which the WG feels is testable, and this SC covers an expanded set of purposes.
