### ISSUE TITLE
Idioms and abbreviations in 3.1.3 and 3.1.4

### ISSUE THREAD

**Issue by JonathanPKatz** [w3c/wcag21#400]
Hi,

I'm wondering if it is appropriate to have avoiding idioms and abbreviations as only AAA in the guidelines - the use of idioms for essential functions or safety information, for example, is markedly confusing for both users with cognitive disabilities and second-language speakers of the content language. Is there a reason this is not AA?

Jonathan

**Comment by awkawk** [comment]
closing since it isn't getting into 2.1.
