### ISSUE TITLE
Comment on glossary entry "adapt"

### ISSUE THREAD

**Issue by kerstinp** [w3c/wcag21#409]
In the glossary entry the term "client" is used but in the SC 1.4.13 the term "user agent" is used which can be something different.

**Comment by steverep** [comment]
Hi @kerstinp, I personally agree with you that the definition steps on the toes of the SC.  My feeling is that the glossary term can simply be removed as redundant with the SC itself, i.e. talking about the user agent adapting style properties versus the client adapting formatting.  Would you agree with that approach?

**Comment by kerstinp** [comment]
Hi @steverep, I'm  not sure if the entry could be removed. The glossary entry depends on what is intended with the SC or is included. Overridings of formattings directly in the same format? Changing formattings after converted to another format? Which format? Which software? And so on.

**Comment by alastc** [comment]
Can we change the glossary entry for 'adapting' to use [user-agent](https://w3c.github.io/wcag21/guidelines/#dfn-user-agents)?

**Comment by awkawk** [comment]
Thank you for your comment.

We have updated the SC language. It no longer uses the definition for "adapt", so this issue is resolved.

**Comment by Tomcombi** [comment]
I am getting trouble with this error #409 while using Onenote. Can I resolve this itself or not. If I want  Some [MS One Note Support ](https://babasupport.org/microsoft/ms-onenote-customer-service/485)person to resolve my query sp please support me? Its stop my schedule for work done.
