### ISSUE TITLE
Comment on SC 1.3.4 Contextual Information

### ISSUE THREAD

**Issue by kerstinp** [w3c/wcag21#410]
The term "using a publicly available vocabular" is not in the glossary which makes it hard to comment. To make the intent of this SC clear it would be good if the Working Group would provide a definition of "publicly available vocabular" in the glossary and give two examples for each (control, symbol and region) in the next Working Draft.

**Comment by awkawk** [comment]
Official WG Response: Thank you for your comment. The specific language mentioned in this comment has been removed from this SC.
