### ISSUE TITLE
Comment on SC 1.4.11 Graphics Contrast – Wording 01

### ISSUE THREAD

**Issue by kerstinp** [w3c/wcag21#411]
I think this is minor issue and just for avoiding misunderstandings:

SC 1.4.11 introduces the new term "object" which is not defined in the glossary. Because of object-element in HTML and 'object' is in PDF a technical term it would be better either not using "object" or adding a definition in the glossary.

**Comment by alastc** [comment]
I think the [latest version](https://w3c.github.io/wcag21/guidelines/#graphics-contrast) addresses this:
"Graphical Objects: Parts of graphics required to understand the content..."

It is the title/header of that bit, but immediately described as 'parts of the graphic', does that help?

**Comment by kerstinp** [comment]
@alastc 

A bit better, but I'm still not happy. I think there should be an entry in the glossary what exactly is meant.

**Comment by alastc** [comment]
Does the understanding document help?
https://rawgit.com/w3c/wcag21/graphics-contrast/understanding/21/graphics-contrast.html

We used to have a definition for graphical objects (based on an SVG / ARIA spec), but the feeling was it didn't help much and was better done in the understanding.

**Comment by kerstinp** [comment]
I don't think that the understanding would help much. The understanding is not normative. I think the SC itself probably in combination with the glossary should clarify what exactly is in the scope and what not.

**Comment by alastc** [comment]
Dredging up the definition of "graphical object" based on the SVG/ARIA one:
> A graphic or section of a graphic that represents a distinct object or sub-component with semantic meaning. It may be a component of a larger structured graphic such as a chart or map.

I'm not convinced that is helpful though. I realise there is some overlap with objects in HTML, but the synonyms aren't an improvement: element, article, item etc.

The basic problem is that an exact definition is not possible, as we are talking about the range of things that humans can perceive. As humans we can see something like a line in a graphic and say "yes, that's a district part of a graphic", but defining that (more than we have) is a very difficult, I can't see a way to usefully acheive that.

**Comment by awkawk** [comment]
(Official WG response) 
Thank you for your comment. The term graphical object was selected to be generic as it covers a wide range of parts of graphics. Defining the term object (beyond the current text or the dictionary definition) does not appear to help. However, the Understanding document does include a large section to provide context and examples, and that is being expanded.
