### ISSUE TITLE
Comment on SC 1.4.11 Graphics Contrast – Wording 02

### ISSUE THREAD

**Issue by kerstinp** [w3c/wcag21#412]
This SC is very much needed for visually impaired people but can be hard to pass for content producers. People might try to find reasons for not doing this. I'm therefore a bit unhappy with the wording of the exception "Sensory": 

> "primarily intended to create a visual sensory experience has no contrast requirement;"

Could not the following happen: People might say: I don't have to anything because it's "primarily intended to create a visual sensory experience", which could lead to time-consuming discussions on what the specific intention was. 

Also the term "essential" is I feel critical when we think about testing procedures.

**Comment by alastc** [comment]
I think the latest version addresses this, the only exception is now for 'essential':
https://w3c.github.io/wcag21/guidelines/#graphics-contrast

**Comment by kerstinp** [comment]
@alastc 

Yes I think this could work and would adress my comment. I feel the wording needs some improvements and should be more like in 1.4.5 and 1.4.6 for a better understanding:

"The visual presentation of User Interface Components and Graphical Objects  have a contrast ratio of at least 3:1 against adjacent color(s), except for the following:

...."

**Comment by alastc** [comment]
Hi @kerstinp,

By having the two sections to the SC (instead of two SC) each exception lines up with it's description:

> The visual presentation of the following have a contrast ratio of at least 3:1 against adjacent color(s):
> 
> **User Interface Components:** 
> Visual information used to indicate states and boundaries of active user interface components, except where the appearance of the component is determined by the user agent and not modified by the author;
>
> **Graphical Objects**
> Parts of graphics required to understand the content, except when a particular presentation of graphics is essential to the information being conveyed.

Otherwise we'd have to add definitions separately for what each item is, which would make it less understandable.

**Comment by kerstinp** [comment]
Hi @alastc,

why not offering two versions in the next Working Draft or in a small survey and ask the public which version is more understandable?

**Comment by alastc** [comment]
Well, the deadline for comments passed a while ago, after hours of discussion it got consensus of the group and is going into the next draft.

I believe there is another round after Christmas, is that right @awkawk?

If you have a proposal for the full text that you think would be better, please do post it here.

**Comment by awkawk** [comment]
The comment seems to have been addressed in the latest working draft.
