### ISSUE TITLE
Comment on SC 1.4.10 Zoom Content - Testability

### ISSUE THREAD

**Issue by kerstinp** [w3c/wcag21#414]
Sorry for this long comment...

I think the character of Note 2 is for authors as well as for evaluators not clear enough. My understanding so far is that content-types mentioned in Note 2 are somehow exceptions. But whereas in other SC, like 1.4.3 or 1.4.5, they are not defined as such. And the Note says "Examples of…" which indicates that there might be more content-types where two-dimensional layout is required. 

I'm missing forms and form-fields in Note 2. Because all SC should be technology-agnostic SC 1.4.10 applies to PDF forms and PDF files which contains form-fields. 

In the description of this SC in Issue 77 the Adobe reader reflow is mentioned. According to [Adobe help files](https://helpx.adobe.com/acrobat/using/reading-pdfs-reflow-accessibility-features.html) this will not work: 

"Text that doesn’t reflow includes forms, comments, digital signature fields, and page artifacts, such as page numbers, headers, and footers. Pages that contain both readable text and form or digital signature fields don’t reflow." . 

And it seems that VIP-Reader which provides a reflow for filtered text is not displaying form-fields.

So: In one reader no reflow and in the other reader no displayment of form fields. Files like this would I believe not testable.

One comment on images and diagramms in PDF because they are menioned in Note 2: In case an image is tagged including [all boxes](https://www.prepressure.com/pdf/basics/page-boxes) no scrolling on more than one axis in Adobe Reader must be done. The image itself is not resizable up to 400% but there is no need for a horizontal scrolling. In VIP-Reader a scrolling on more than one axis is always necessary when resizing.

In case the purpose of Note 2 is to define exceptions: which content-types are in scope of SC 1.4.10? It seems the SC will apply to running texts with some paragraphs, headings and lists, or? In this case the name of the SC "Zoom content" is confusing. And in case the content-types mentioned in Note 2 are not meant as exceptions would this not be a complete overriding of SC 1.4.4 WCAG 2.0?

Some questions which I feel are important for PDF web content (I focus on desktop):

In how many PDF-Reader or which PDF-Reader must Zoom Content work to pass the SC? In Adobe Reader, in VIP-Reader, both, other readers? This is very important for testing procedures, contracts, authors and for claiming conformance. 

Because Adobe reader reflow is mentioned in the description ([github-issue 77](https://github.com/w3c/wcag21/issues/77)) and the character of Note 2 is a bit unclear the SC raises many questions. Some examples:

Given a PDF file contains data tables with white texts for headers of rows and columns and/or content in rows or columns. In Adobe reflow the usual result will be: the white texts are not readable. Would this pass because data tables are out of scope or would it fail because of loss of content?

When a PDF file contains in a page text and image(s) without BBox the page will not reflow in Adobe. VIP-Reader ignores images without BBox and is not displaying them. Would it pass because images are not in scope or would it fail?

Also the following can happen: 

A PDF is well-tagged and there is not one single problem which would make the PDF fail. In Adobe reflow (just there, not in the standard view and also not in any other PDF reader) additional text is displayed - let's say comments from the designer. According to the wording of the SC it should pass because it's not a loss of content but additional text, or?

It might happen that Adobe reflow fails completely and that also VIP-Reader can not display the text but gives a red warning. Depending on the reason the PDF file may nevertheless pass all SC and Conformance Requirements of WCAG 2.0 AA. But this would not pass WCAG 2.1 AA. Would this case not have the impact of a complete overriding of SC 1.4.4? 

It is likely that SC Zoom Content in case Adobe reflow must be done - even when not explicitly mentioned in the SC - will also have a critical impact on 1.3.2 Meaningful sequence (WCAG 2.0 Level A) and a re-interpretation could happen. 

While the criterion for the sequence of the content in VIP-Reader is the tag order, the criterion for Adobe reflow is not the tag order but the Adobe reading order. In Adobe reader we can have two sequences of content: One for AT like screen reader (tag order) and another one which is specifically for Adobe reflow (Adobe reading order). 

Presumed the following: VIP-Reader displays the content of a file in it's user interface completely and in a correct order, and Adobe reader displays content completely but in the reflow mode in a wrong order and therefore not in a meaningful sequence. Would it pass or fail? If one would say that it fails: Which SC would be violated? There is no loss of content, so I would think it would not fail 1.4.10 Zoom content. If one would say that 1.3.2 Meaningful Sequence is violated this would I believe be a re-interpretation of a WCAG 2.0 (A) criterium. Without Zoom Content (and without Adobe reflow) the tag order and just the tag order is relevant. 

Another problem can occur when a testing procedure would be based upon Adobe reflow and if Adobe reflow would be mentioned even when this would just happen in the Understanding: If specifically the sequence of the content in Adobe reflow would be adressed in 1.4.10 one would have for one specific technology indirectly a user-agent-specific SC and two SC where a meaningful sequence is covered. How to avoid this? One could say that just VIP-Reader and/or other readers are relevant for SC 1.4.10. But to give legal certainty and maintain the testability as well as avoiding re-interpretations of WCAG 2.0 criteria this must be done in SC 1.4.10 in a normative way. And this would mean that the SC would be technology- and user-agent specific. 

One other example which can be important for passing or failing: Sometime list-item-indicators (squares or whatever) are not unicode-conform and are announced by screen reader in a confusing and/or disturbing way. One would have two options to deal with this: Either making them unicode-conform or defining them as artifacts. For passing WCAG 2.0 AA it would be sufficient defining them as artifacts so that they can be ignored by screen reader. They are of course still visible in standard views. The effect of defining something as artifact is, that it is not displayed in VIP-Reader and Adobe reflow. Which is not a bug the expected outcome. But in VIP-Reader and Adobe reflow the technique "using artifacts for list-item-indicators which are announced in AT in a disturbing way" will have the effect that the lists can just be identified by it's position. Would that pass or fail? And if it would fail what would be sufficient? Visually indenting the list and it's items?

I have also other concerns for the topic "testability". VIP-Reader is filtering the text out of a file and displays the result in it's own user interface. I would say that a testing procedure which would rely on VIP-Reader would be testing of an alternate version (I'm commenting on this also in other issue, sorry for cross-posting).

**Comment by awkawk** [comment]
We do need to conduct implementation testing and it would be great to have some example documents to include in that process, are there any you are able to share? We will keep your concerns in mind as we conduct the implementation testing.

We are tagging this issue with the "Implementation Follow-up" label to ensure that it is re-reviewed at that point in our process.
