### ISSUE TITLE
Comment on SC 1.4.10 Zoom content

### ISSUE THREAD

**Issue by kerstinp** [w3c/wcag21#415]
The comment focuses Desktop PDF reader. 

In github-issue 77 is written: "It is also possible to meet this success criteria in PDF files by using the reflow feature of Acrobat Reader, which works well on many tagged PDFs with a defined order and structure." 

Adobe reflow can work well and can easily be done as long as we are speaking about very simple PDF files with some headings, lists, paragraphs and so on. The less simple the more problems one can have when optimizing for Adobe reflow would be the challenge. Some typical problems:

- White text – often used for headings, in data tables and info boxes or marginalia can't be read in Adobe reflow because it appears white on white.
- When images don't have Bounding Boxes which is usually the case when the file was written in Word or PowerPoint and the PDF was created by "saving as PDF" in Office the page in a PDF file which contains such an image will not reflow in Adobe Reader. Which should be varified or falsified because I have just german versions of MS Office.
- Overlappings of text and images or other objects in Adobe reflow 

This list is not exhaustive. Please find [questions on pass / fail in another comment](https://github.com/w3c/wcag21/issues/414).

So in case SC Zoom Content would rely on "it is possible in Adobe reader" and if there would be testing procedures for Adobe reflow and also when just mentioned in the Understanding, the SC must be guided by a full documentation of Adobe reflow issues, including which of them are user agent issues, which are bugs, which are technology issues and which are failures of the author. 

Also a documentation on wether a technique is a technique or a specific workaround for one user agent would be needed and guidance on what to do if the reason for a loss of content lies in content-types which seems to be out of scope (mentioned in Note 2). Without such a documentation I believe that the SC is not only really testable but would leave authors alone with optimization for a specific mode which is not that much easy to handle.

Optimizing for Adobe reflow is not easy going, can be very tricky and needs much more time – especially when remediating a file. And VIP-Reader which also provides a zoom without scrolling on more than one axis (for running text) has some issues, which I've mentioned in a comment on 1.4.13 Adapting text here. 

I really hate to say it: This SC should not make into WCAG 2.1. I would appreciate having more requirements especially for visually impaired people in WCAG 2.1 but I believe this will end up in either that people simply not do it or that they switch to other standards.

Would there be alternatives for this SC, which are neither technology-specific nor user-agent-specific? 

Helpful would be a fallback-mechanism to WCAG-2.0-AA but I fear this would make SC 1.4.10 and also SC 1.4.13 definitly technology-specific. 

Would it be possible having a wording like "until user agents" (I know this is a WCAG-1.0-oldie and not a goldie -  not even a goodie) with a note that WCAG 2.1 is an interim-version which the WG will revise in future WCAGs?

**Comment by awkawk** [comment]
We do need to conduct implementation testing and it would be great to have some example documents to include in that process, are there any you are able to share? We will keep your concerns in mind as we conduct the implementation testing.

We are tagging this issue with the "Implementation Follow-up" label to ensure that it is re-reviewed at that point in our process.
