### ISSUE TITLE
Comment on SC 1.4.13 Adapting Text

### ISSUE THREAD

**Issue by kerstinp** [w3c/wcag21#417]
Even while I appreciate this new SC for HTML-Content I have many concerns for PDF Web content. In PDF possibilities for doing adaptions are much more limited. When re-reading the discussions around this issue it is my impression and fear that in the context of PDF files SC will rely on "It is possible in VIP-Reader". Given that especially when we think about the wording "if the technology being used allow the user agent" I feel it is important to have a look on what the "it" which is "possible" is.

(like in other comments it's a bit cross-posting, sorry.)

The [description of VIP-Reader on the download-page](https://www.snab.ch/en/hilfsmittel/digital-tools/the-first-pdf-reader-for-visually-impaired-people/) says: 

> "The VIP PDF-Reader filters the text out of a PDF file and presents it in a user-friendly interface."

My understanding is that VIP-Reader is a converter with a user interface around which uses the possibility that PDF allows the filtering of text. 

Would this not be in WCAG-terminology that all procedures for testing conformance with this SC are done in an alternate version from beginning on? And I believe one can not speak about "overridings" because the adaptions are done in the alternative version, or?

VIP-Reader has limitations.

1. Issues with file attachments

Some background on this which I've also mentioned in my comment on SC Graphics contrast. In PDF one can add file attachments in any format for example for important additional informations. And file attachments are very helpful to provide long descriptions of diagramms (data tables for example) and alternate versions for images of texts (like for example screenshots of newspaper articles which are referenced in the text and are therefore informative). But VIP-Reader is not displaying file attachments. I fear that a technique like this which is helpful for many people could be seen as failure just because this user agent is not displaying them.

Despite of this also the testability would be an issue. The testing procedure would be like this: 1. Check in a PDF reader which shows file attachments if one or more file attachments are present. 2. Check wether attached files contains important informations like long descriptions, alternate versions and so on. 3. Save the file attachments. 4. When a file attachment is a PDF file open the attachment in VIP-Reader. 5. Check wether text adaptions can be done. I think this would be a bureaucratic testing procedure, very user agent specific and also not a realistic user scenario.

File attachments is not a technique which is used often, but it is a important technique. When there are many diagramms and/or other images of text one could of course provide alternate texts. But when many long alternate texts are needed long alternate texts can have a negative impact on the scrolling of the file. And an alternate text for a diagramm is sufficient but not the best way for structured data.

2. Loss of content

One reason for a loss of content of text in VIP-Reader is: Not all text is tagged (which is covered already by WCAG 2.0 SC 1.3.1). When all content is tagged, including images and alternate text for images are present (which would be 1.1.1 already) adaptions like required can be done in the user interface of VIP-Reader. But more test cases are needed to make sure that not other technical issues would lead to the situation that a loss of content happens. 

There is a loss of content under the following condition: Images without Bounding Boxes. While I've never see any problem in any PDF-reader in standard views, VIP-Reader is ignoring those images and is not displaying clickable icons for them. A typical example for missing Bounding Boxes which should be verified (I have german versions of MS Office) is: A file which contains images was written in MS Word or Power Point and saved as PDF with MS-option "save as PDF". According to the results of Checking Tools those images don't have Bounding Boxes. 

As long as an image is not informative this is not a loss of content, but in case of an informative image it is. The main question is: Do this occur because of the technology PDF (BBox is required) or is it a user agent issue? In other words: Is VIP-Reader ignoring images without BBox because BBox is required or is VIP-Reader ignoring those images because there is no way to extract them out of file and display them? 

Of course one could say: Microsoft has to rework it's "saving as PDF" and of course this must be done. But even when this is done: What to do with already published PDF files which are created by this option? I think it is not realistic that any person or company will remediate such PDF files and for sure not when they (probably) pass WCAG 2.0 AA, where adaptions like mentioned in this SC are not required. As long as MS has not repaired this I'm much worried because one has to buy additional software.

I think it would be very helpfull if the Working Group would seek additional feedback from Adobe on Bounding-Box and also feedback from the company which developed VIP-Reader.

3. PDF Forms and files contain form-fields

As far as I know VIP-Reader provides no possibility to interact with PDF forms. It seems the user agent just filters texts and not form-fields. This must be verified cause it would mean that PDF with forms or file which contain text and form fields are not testable.

4.  Unclear alerts / warnings

Sometimes VIP-Reader is not opening a PDF-file at all (red warning) and sometimes a blue warning appears, which says that the PDF file "is not fully accessible". There are some examples for this in the spreadsheet for test cases the Working Group started. 

One reason for the blue warning is when a PDF-file is not tagged at all. I've added in one PDF file which is mentioned in the spreadsheet one single P-tag for one of the paragraphs. After this VIP-Reader just displayed this tagged content and ignores the rest. I'm not worried on this because if a file is not tagged correctly in minimum SC 1.3.1 fails already. 

I'm a bit worried because of: No blue warning. But of course just adding one single tag doesn't mean that the PDF file is now "fully accessible" (whatever "fully accessible" means). I think this could be highly confusing for users and authors as well and should be adressed in minimum in the Understanding.

In the warning with the blue background is written that the file "has not been created to be fully accessible and it does not meet the basic quality requirements for PDF files". What exactly are the "basic requirements"? If it might be that a testing procedure would rely specifically for one technology on one single user agent I would think that also Sufficient Techniques and failures must rely on this user agent. I've read through the documentation / tutorial of VIP-Reader and could not find any concrete statement or list with "basic requirements". So my question would be: "Basic requirements" according to which standard or specification (PDF 1.7? PDF/UA-1? WCAG?) and which of the requirements in the relevant spec(s) are the basic ones? "basic" includes for sure tags and the tag order. Which requirements are also "basic"?

Issues which are probably not relevant for the SC itself:

There is no way to interact with content in VIP-Reader when a user needs not only adaptions but in addition also a screen reader, which is a disadvantage for user who are in need of an own colour scheme and a screen reader, for example some users with RP. And VIP-Reader has no speech output. As far as I know VIP-Reader was explicitly not developed for interaction with screen reader.

VIP-Reader displays images not directly but as clickable icons, which can be problematic for some e-learning materials as well as for tutorials and for all cases where it is necessary to have direct displayments of an informative image and a text. In VIP-Reader a user has to switch between the (informative) image and the text.

And: VIP-Reader was published in 2013 without any updates since then and is sponsored software. I am worried relying in testing procedures of an SC in a future recommendation with that much relevance on sponsored software, which seems to be in the moment the case when reading through the descriptions. 

I don't want to blame VIP-Reader or the company which develops VIP-Reader, not the sponsors of this reader or anyone else. VIP-Reader is for sure in a lot of situations a good and helpful Assistive Technology for many visually impaired people. BUT: Is VIP-Reader _good enough_ for an SC with world wide relevance?

**Comment by lauracarlson** [comment]
Hi  @kerstinp,

Can this issue be closed as VIP reader is not mentioned in the understanding document or SC and your other concern seems to covered in #644?

Thanks,
Laura

**Comment by mraccess77** [comment]
Hi @kerstinp (responding as an individual here) the scope of the SC is "when technology allows" this is very similar to the wording that is used in SC 1.4.5 Images of Text (if the technology being used can achieve) and SC 4.1.1 Parsing (in content implemented in markup languages).  That is - while WCAG is technology neutral SC can be scoped to certain technology requirements as evidenced in current WCAG SC.  Thus, this would only apply in these situations and would not cover VIP-Reader.

**Comment by kerstinp** [comment]
Hi @lauracarlson,

I think this one can be closed. 

Hi @mraccess77 

I commented on "technology-agnostic"  [in issue 407](https://github.com/w3c/wcag21/issues/407) and feel it would be better to discuss this there. Or?.
