### ISSUE TITLE
Comment on SC 2.5.3 target size

### ISSUE THREAD

**Issue by kerstinp** [w3c/wcag21#420]
In the exceptions the term "In-Page" is used which is not defined in the glossary. I suspect that "Web Page" is meant? 

In case SC 2.5.3 will make into WCAG 2.1 it would be better using instead of "In-Page" a term which adresses the document (which also would need a definition in the glossary). I remember a bundle of time-consuming discussions on wether a PDF is according to WCAG 2.0 terminology a "Web Page" or not and fear that the term "In-Page" will raise another round of discussions, because a PDF can have one to x pages.  Adressing the document instead of "page" would be very helpful.

**Comment by detlevhfischer** [comment]
Thanks for bringing this up. "In-page" is defined after the term is introduced in the list of exceptions: "The target is a text link where the destination is on the same page".  I believe applied to PDFs, this would mean that targets that link to places not on the current PDF page (i.e. elsewhere in a multi-page PDF -document) would not count as exception. So it may indeed be good to define 'in-page' in a technology-agnostic manner.

**Comment by awkawk** [comment]
In the latest draft we have modified the exceptions related to text links so that text-based links within a sentence or block of text are exempted. We believe that this addressed your concern.
