### ISSUE TITLE
Readability SC language posted on Twitter.

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/wcag21#421]
I thought I should file this regarding the readability SC.

https://twitter.com/g33konaut/status/915921239880937472

**Comment by guyhickling** [comment]
Or how about this one? It's my favourite WCAGism of all time:

> For example, when mixing languages with different directionality in HTML, the bidirectional algorithm may position punctuation in the wrong location in the visual rendering. The visual rendering problem could be corrected by moving the punctuation in the content stream so that the bidirectional algorithm positions it as desired, but this would expose the incorrect content order to assistive technology. The content is both rendered in the correct order visually and exposed to assistive technology in the correct order by using markup to override the bidirectional algorithm.

**Comment by DavidMacDonald** [comment]
As it turns out, this language in the twitter posting above was from an SC that is no longer in the 2.1 Plain Language.

@guyhickling 
Can you provide a pointer to that quote. Thanks?

**Comment by guyhickling** [comment]
@David, yes, it's in technique G57. Happy reading!
