### ISSUE TITLE
IBM comment 2 on 1.4.10 Zoom Content

### ISSUE THREAD

**Issue by mbgower** [w3c/wcag21#434]
This SC does not seem technology agnostic. It appears to place heavy reliance on the existence of responsive design, yet such techniques seem absent in the non-web software space. With the adoption of WCAG as the baseline for Section 508 and EN 301 549 standards, IBM believes it is increasingly important to ensure SC are technology neutral.

**Comment by alastc** [comment]
Hi Mike,

I'm not sure how to respond, we're creating guidelines for "web content", if we were also creating guidelines for "non-web software" we'd need to make a lot more changes than just this.

-Alastair

**Comment by mbgower** [comment]
I understand the conundrum, but I do think that this places a lot of reliance on a common practice which is nonetheless not a required practice. Are there other ways than responsive design to achieve this?

**Comment by alastc** [comment]
Well, I guess we could scope it to markup languages (i.e. HTML & ePub)? I'm not keen on doing that though.

You can also have a small-screen version that is linked to. Not ideal, but a reasonable transition scenario.

Android has an equivalent of responsive in terms of different devices, but I don't think it is available as a user preference?  (No device handy right now.)

iOS allows for multiple sizes, although they are set, you choose the iPhone7 size when you have an iPhone7+. Again, not available for web content.

**Comment by mbgower** [comment]
With the Retitling of the SC to make the requirement to reflow the key consideration, I can live with this.
