### ISSUE TITLE
IBM comment 1 on User Interface Component Contrast (Minimum)

### ISSUE THREAD

**Issue by mbgower** [w3c/wcag21#436]
There is overlap with the existing 2.4.7 Focus Visible SC. "Visible" is not defined in the Glossary, however it seems to be very related to the concept of "visual identifiers" discussed in 1.4.12. For focus to be visible, does the visual indicator of focus state need to meet minimum contrast versus the unfocused state?  Does "visible" focus include contrast from surrounding text (for Text Cursor) or control objects, such as border line of box and visible focus indicator?  IBM recommends yes. 

Adding a Glossary for "visible" is a way to 'improve" 2.4.7 Focus Visible, without changing the SC Title or the normative text of the short description.   

By using this defined term 'visible' (linked to Glossary) instead of the 'visual' term, 1.4.12 becomes:
> Essential _visible_ identifiers of user interface components have a contrast ratio of . . . 
> Note: Examples of essential _visible_ identifiers of user interface components may include (a border, edge, or icon), current value (such as non-text 'visible' indication of aria-valuenow on a slider) and current state (such as selection indicator, focus indicator) or other essential visual indication (which do not rely on color alone).

**Comment by awkawk** [comment]
With the proposed SC text we are adding more specifics about how to make controls and focus visible to 3:1 ratio and we will clarify in the understanding doc.
