### ISSUE TITLE
IBM comment 2 on User Interface Component Contrast (Minimum)

### ISSUE THREAD

**Issue by mbgower** [w3c/wcag21#437]
> Examples of essential visual identifiers of user interface components may include (a border, edge, or icon), current value (such as non-text visual indication of aria-valuenow on a slider) and current state (such as selection indicator, focus indicator) or other essential visual indication (which do not rely on color alone).

Add "text cursor" ([defined in UUAG](https://www.w3.org/TR/UAAG20/#def-cursor), or another agreed on term like "caret") to the list of examples - it is not discussed elsewhere in WCAG 2.1.

**Comment by DavidMacDonald** [comment]
I Propose this comment be accepted and the term "text cursor" be added explicitly as requested.

**Comment by goodwitch** [comment]
+1

(and a huge thanks to you David for all the work you are doing to move the
ball forward!)
Glenda

glenda sims  |   team a11y lead   |    deque.com    |    512.963.3773
*web for everyone. web on everything.* -  w3 goals

[image: IAAP International Association of Accessibility Professionals:
Certified Professional in Accessibility Core Competencies (CPACC)]
<http://www.accessibilityassociation.org/certification>

**Comment by awkawk** [comment]
Good point, we'll clarify in understanding as an aspect of focus indication.

**Comment by awkawk** [comment]
NB: Caret colour can be changed: https://developer.mozilla.org/en-US/docs/Web/CSS/caret-color
