### ISSUE TITLE
IBM comment on 1.4.13 Adapting Text

### ISSUE THREAD

**Issue by mbgower** [w3c/wcag21#438]
For clarity, and to match the language used in the SC, IBM recommends altering the Note to read:
>Examples of  technologies that do not allow the user agent to adapt style properties are open captions and images of text, which are not expected to adapt.

**Comment by awkawk** [comment]
Thank you for your comment. The SC note has been remove per WG Discussion on the November 13, 2017 call. We will be addressing captions and images of text in the understanding document.
