### ISSUE TITLE
IBM comment 1 on 2.2.8 Timeouts

### ISSUE THREAD

**Issue by mbgower** [w3c/wcag21#448]
"User inactivity" should likely be defined. For instance, does timing begin from a user login? What differences should be considered for server-side functionality versus client side?

**Comment by mbgower** [comment]
Rachael, here's what you posted in our chat today. I'll look over and try to tweak...
> User Inactivity:   Any continuous period of time where no user actions occur that trigger tracked client or sever activity.  The method of tracking will be determined by the web site or application and should be consistent with the way the site or application determines time outs.

**Comment by rachaelbradley** [comment]
Discussions at TPAC resulted in the following definition:

**User Inactivity:** Any continuous period of time where no user actions occurs. The method of tracking will be determined by the web site or application.

**Comment by awkawk** [comment]
Finalized by WG 12/5
