### ISSUE TITLE
IBM comment 2 on 2.2.8 Timeouts

### ISSUE THREAD

**Issue by mbgower** [w3c/wcag21#449]
IBM supports users being notified of timeouts at the start of a process. However, IBM has mild concerns that the SC is not scoped. In example if a user is simply signing up as a new user and has 4 fields to fill in-- username, email address, password and password confirmation-- it seems onerous to insist that such a simple design must include text about timeouts.

**Comment by rachaelbradley** [comment]
Proposed response:  This was discussed at TPAC and simple forms where data sits in the form fields but is not removed falls outside of the scope of this SC. This will be included in the understanding document.

**Comment by awkawk** [comment]
Finalized by WG 12/5
