### ISSUE TITLE
IBM comment on 2.2.9 Animation from Interactions

### ISSUE THREAD

**Issue by mbgower** [w3c/wcag21#450]
IBM encourages further research into considerations for support for users with vestibular disorders, with the goal of creating a more refined SC which could be introduced as a level AA.

**Comment by awkawk** [comment]
Official WG Response: Thank you for your comment. The WG has reviewed and discussed this SC and has elected to keep this at AAA. Future research may allow this to be moved to AA, or additional criteria may be added if determined to be needed.
