### ISSUE TITLE
IBM comment on 2.5.2 Concurrent Input Mechanisms

### ISSUE THREAD

**Issue by mbgower** [w3c/wcag21#458]
IBM has concerns that it seems difficult to perform a test to confirm this SC has been achieved. [Conversation in the issue thread](https://github.com/w3c/wcag21/issues/64#issuecomment-266046876) reflects this concern. For web content, it is difficult for the tester to know what input modalities may be used. IBM anticipates that technology-specific failure techniques may be the only means of guiding testing.

**Comment by mbgower** [comment]
https://github.com/w3c/wcag21/issues/64#issuecomment-266603037
https://github.com/w3c/wcag21/issues/64#issuecomment-266046876
https://github.com/w3c/wcag21/issues/64#issuecomment-275620025

**Comment by awkawk** [comment]
The Working Group has decided to move this SC to AAA, in part due to concerns about testability.
