### ISSUE TITLE
IBM comment on 2.6.1 Device Sensors

### ISSUE THREAD

**Issue by mbgower** [w3c/wcag21#459]
IBM feels the title and wording of the SC in its current form does not make it easy to grasp the objective or requirements of the SC. We advocate adopting the language [proposed by Steve Repsher in the Issue thread](https://github.com/w3c/wcag21/issues/67#issuecomment-325716721) 

>Motion Actuation: Functionality which can be operated by device or user motion can also be operated by user interface components and can be disabled to prevent accidental actuation, unless the motion is essential for the function and doing so would invalidate the activity.

>Note: This criterion concerns input through sensors which respond directly to motions such as tilting, shaking, or panning. It is not intended to cover indirect motion associated with operating a keyboard, pointer, or assistive technology.

**Comment by detlevhfischer** [comment]
There is a field of activity which uses the video input (i.e. the camera sensor) and machine learning to detect gestures like hand movements or the number of fingers shown.
An example is https://nhudinhtuan.github.io/jshg/

Other sensors like those detecting ambient light to toggle display modes (like turn on night view)  may also need direct controls as alternative to sensor input.

The question therefore remains whether it is wise to focus entirely on motion activation. I would prefer to keep the SC more open, but explicitly exclude sensor sthat map onto the keyboard interface like keyboard, switch, or speech input. This will need more discussion in the WG.

**Comment by mbgower** [comment]
@detlevhfischer, the video example you mention seems to still be addressed by the new proposed wording. The ambient light setting sounds like an OS setting; to the extent it isn't, it would fail other SCs that cover a users ability to control the presentation of text.
We continue to be concerned that the current title and wording of Device Sensors makes it difficult to understand for web content authors.

**Comment by awkawk** [comment]
Thanks for the comment we have incorporated Steve R. ideas into the latest draft.
