### ISSUE TITLE
IBM comment 1 on 2.6.1 Orientation

### ISSUE THREAD

**Issue by mbgower** [w3c/wcag21#460]
This SC seems to be primarily applicable only to hybrid and native mobile applications. While IBM does not object to its inclusion, it does not seem as relevant to web content guidelines.

**Comment by patrickhlauke** [comment]
see https://github.com/w3c/wcag21/issues/465#issuecomment-335257954 regarding web content applicability

**Comment by mbgower** [comment]
Thanks for that clarification, @patrickhlauke. Assuming those issues will be flagged as Failure Techniques, this issue can be closed.
