### ISSUE TITLE
IBM comment on 2.6.2 Orientation

### ISSUE THREAD

**Issue by mbgower** [w3c/wcag21#461]
IBM requests clarity on the exception for "slides for a projector or television". There is not a requirement in this SC for the content to have its aspect ratio altered, just that there be no suppression to display in a different orientation. A slide with a 16:9 aspect ratio can still be displayed in that format in portrait mode; it would simply take up a smaller part of the screen.

**Comment by awkawk** [comment]
@mbgower This comment is about a previous definition for essential so closing as it is overcome by the events of the recent change.

**Comment by steverep** [comment]
@awkawk, yes it was removed from the definition of essential, but it was still moved to a note under the SC itself, so I don't think this is ready to close.

**Comment by mbgower** [comment]
Okay, thanks. It's a moot point now since the definition was restored, but I also want to flag that changing a glossary definition would seem to be altering a normative part of 2.0. My understanding was that normative language from 2.0 was not going to be modified in 2.1. @awkawk, are glossary changes to existing defined terms considered an exception to this resolution?
