### ISSUE TITLE
Comment on 2.6.2 Orientation

### ISSUE THREAD

**Issue by AidanA11y** [w3c/wcag21#465]
This does not seem to apply to "web" content since the browser would handle the orientation change.  I've never encountered a web page that showed up in a different orientation from the browser.

For mobile apps I see the benefit for users who fix the orientation of a device, however it would not be practical requiring this where the device OS does not support both orientations.  For example, iPhone  home and settings screens do not support landscape, and it seems onerous to require app makers to do so when the OS does not.

**Comment by patrickhlauke** [comment]
CSS Device Adaptation https://www.w3.org/TR/css-device-adapt-1/#orientation-desc will allow pages to be locked to a specific orientation, regardless of the browser/device orientation. This may not be implemented commonly in browsers yet.

Another practice I've seen in some sites is to simply test the width/height ratio of the viewport, and if it's in the "wrong" orientation show a "please rotate your device" message instead of content. https://www.google.co.uk/search?q=please+rotate+your+device

**Comment by AidanA11y** [comment]
Thanks for explaining how this applies to web @patrickhlauke

**Comment by awkawk** [comment]
@AidanA11y Are you satisfied that your comment has been addressed for this issue?

**Comment by AidanA11y** [comment]
@awkawk  and @patrickhlauke  the  explanation about web makes sense and addresses that,  yes.
 
The second part of my comment relates  to mobile apps. I do not think the SC is practical when phone OS system settings and home screen do not support dual orientation. Does 2.1  apply to native mobile apps? It will certainly be used by organizations to evaluate mobile apps.

**Comment by patrickhlauke** [comment]
native mobile apps are not "web content". principles of WCAG 2.X may well be applicable to software/native apps, but these are not the focus or topic of WCAG

**Comment by mbgower** [comment]
IBM has closed our related issue with the understanding that the two techniques @patrickhlauke identifies will become failure techniques for 2.6.2

**Comment by awkawk** [comment]
We are documenting in the Understanding. App developer can build to this requirement, even if the OS (iOS) doesn't. The current language helps alleviate this concern we believe:

“Content does not restrict its view and operation to a single display orientation, such as portrait or landscape, unless a specific display orientation is essential.”
