### ISSUE TITLE
Comment on 1.3.4 Purpose of Controls

### ISSUE THREAD

**Issue by AidanA11y** [w3c/wcag21#466]
This criterion is not very clear, but reading the history I can understand where it is coming from. I do  not think he techniques are sufficiently available or supported to  require this of content makers.

**Comment by jake-abma** [comment]
Hi @AidanA11y thanks a lot for your comment!

We are well aware of the challenge this SC has and are working on it.

The team will need to buckle down and decide on the core lists within the time frame and provide clearance and techniques.

By the time we leave CR we are committed to all SC have working websites and implementations in a few different platforms (or they will be removed from the final draft). Please see [WCAG 2.1 CR Exit Criteria](https://www.w3.org/WAI/GL/wiki/WCAG_2.1_CR_Exit_Criteria) for the details.

We hope that answers your concerns, if not please feel free to open a new issue.

**Comment by awkawk** [comment]
Thank you for your comment. We have made substantial changes to this SC and believe that you will find it far more implementable. Please review the current draft when it comes out this week.
