### ISSUE TITLE
Comment on 1.4.10 Zoom content

### ISSUE THREAD

**Issue by AidanA11y** [w3c/wcag21#467]
This  does seem to be requiring all web content be responsive and able to fit on a tiny screen. This is not realist for complex applications, or would require completely redesigning existing applications.

If there are criteria which are not realistic I think we would see low adoption of 2.1

**Comment by awkawk** [comment]
The working group will be going through the implementation process and demonstrating the implementability of all the new SC. If you know of an application where it would not be possible to meet the SC (not covered by the exceptions), please do add that to this issue.

We are tagging this issue with the "Implementation Follow-up" label to ensure that it is re-reviewed at that point in our process.
