### ISSUE TITLE
Comment on 1.4.13 Adapting Text

### ISSUE THREAD

**Issue by AidanA11y** [w3c/wcag21#469]
I see the benefits but I do not think it is practical to implement, especially outside of the main content area with blocks of text.  It would very hard to support in navigation, custom widgets and some types of forms.  

Would the combinations of these need to be supported? (eg line spacing, letter spacing and word spacing all modified) there are many permutations and combinations to account. 

Even the basic 4 listed items would be very hard to test.

**Comment by awkawk** [comment]
Thank you for your comment.

Based on an evaluation of 67 pages tested between July 25 and August 3, 2017 that included top 50 Alexa pages and some smaller pages, the combined metrics specified in the Adapting Text SC should be feasible in WCAG 2.1 for HTML documents. Spacing is able to adapt without loss of content or functionality across a wide range of sites.

The Working Group will be going through the implementation process and demonstrating the implementability of all the new SCs. If you know of examples where it would not be possible to meet the SC, please add them to this issue.

We are tagging this issue with the "Implementation Follow-up" label to ensure that it is re-reviewed at that point in our process. In addition we will add the following editor's note:

"Editors Note: The Working Group seeks examples in the wild of text content outside of blocks of text where it would be impossible to meet this SC. The SC's scope may be narrowed based upon implementation testing."
