### ISSUE TITLE
Comment on  2.2.7 Interruptions (Minimum)

### ISSUE THREAD

**Issue by AidanA11y** [w3c/wcag21#474]
To be testable the term interruptions needs more specifics.

Here are a few common scenarios that seem to fail but may be problematic:

- validation error messages (these are system generated) 
- a 'toast' message to confirm success of an action
- a contextual help overlay (e.g. "hold camera steady to capture image")  
- an overlay that appears on top of the main content at page load. 
- session timeout warning

**Comment by lseeman** [comment]
We have better wording suggested  at https://www.w3.org/WAI/GL/wiki/2.2.7_Revision

**Comment by AidanA11y** [comment]
Looks good! Thanks @lseeman

**Comment by awkawk** [comment]
Official WG response: Thank you for your comment. This SC has been removed from the draft and will be able to be considered in a future revision.
