### ISSUE TITLE
Comment on 2.2.8 Timeouts

### ISSUE THREAD

**Issue by AidanA11y** [w3c/wcag21#475]
In practice this would be very hard to do.   Timeouts are sometimes determined by mid-tier or back end calls and may not correspond  directly to what a user perceives as activity such as scrolling or entering input. Moving to a new screen may not necessarily reset the timer.   

Also, some security  approaches intentionally vary the length of the timeout without disclosing the time as a fraud prevention measure.

**Comment by rachaelbradley** [comment]
Proposed Response based on discussion at TPAC:

aidanA11y,

Thank you for your comment. The working group discussed the difficulty in determining activity and inactivity is the primary reason this success criteria has been left at the AAA level.  To further clarify, we've added the following definition to the draft:

**User Inactivity:** Any continuous period of time where no user actions occurs. The method of tracking will be determined by the web site or application.

**Comment by AidanA11y** [comment]
Thanks @rachaelbradley
