### ISSUE TITLE
Comment on  2.5.1 Pointer Gestures

### ISSUE THREAD

**Issue by AidanA11y** [w3c/wcag21#478]
> All functionality can be operated with a single untimed pointer gesture unless a multipoint or timed gesture is essential.

This language is  very hard to understand, even for someone immersed in the subject!    I have a general sense of the problem it aims to address but I am stuck understanding what this guideline is requiring of authors.

**Comment by detlevhfischer** [comment]
@AidanA11y Thank you for you input!
An alternative might be:

> "Where complex input gestures are supported, alternative single step gestures (such as one mouse click or one tap on a touchscreen) are also available to operate the functionality."

Would you find that easier to understand? 
The downside is that it is more technology-specific.

At the moment, there are several issues to sort out around the scope and possible exceptions for this SC, so once we have clarified these, we will attempt to make the SC language easier to understand.

**Comment by AidanA11y** [comment]
That’s a lot clearer to me,  @detlevhfischer

**Comment by awkawk** [comment]
We have modified the SC language and believe that it addresses your concerns

“All functionality which uses multipoint or path-based gestures for operation can be operated with a single-point activation, unless a multipoint or path-based gesture is essential.”
 
There will also be a new definition for “path-based gesture” with a definition of: “User input that depends on the path of the user's movement and not just the endpoints.”
