### ISSUE TITLE
Comment for 2.6.1 Device Sensors

### ISSUE THREAD

**Issue by AidanA11y** [w3c/wcag21#481]
This  could be hard to test.  This functionality is not always apparent. How does a tester know what procedure to perform for each screen (eg shake it, tilt it, turn it).  Often the behaviour  is only documented outside the application and is discoverable through use usually.

**Comment by awkawk** [comment]
Discover-ability may be something we will be able to address in the future, but for now it is the same as a keyboard issue with regard to testing.
