### ISSUE TITLE
Comment on 3.2.7 Change of Content

### ISSUE THREAD

**Issue by AidanA11y** [w3c/wcag21#482]
Addressing notifications of changes is beneficial but the scope may be too wide.

As written I am not clear if this is intended to apply to forms where new or modified questions appear further down the page based on the answers provided above. This is a common practice as a way to make forms shorter and more usable by only surfacing relevant questions. A strict interpretation of the criterion as worded may make that behaviour a 'fail' 

In my view web users would be aware of the pattern. Adding extraneous notifications to inform users of every  change based on their input  would make the form harder to complete.  Adding an instruction would unnecessarily clutter the page. 

With complex applications I do not think this criterion is achievable.

**Comment by DavidMacDonald** [comment]
Proposed response

Early on there was an [exception](https://github.com/w3c/wcag21/issues/2#issuecomment-273030495) along the lines that you describe 

> 1. The change immediately follows the control that triggered it, in the programmatic reading order."

This was removed as a result of a [comment from the Paciello Group](https://github.com/w3c/wcag21/issues/2#issuecomment-273804584)
However, the comment was that these notifications are helpful, not that omitting them is a barrier.  It is an courtesy to provide a notification in these cases but not a barrier. 

We've added an exception as follows:
> 1. The change follows the control that triggered it, in the programmatic reading order.

A pull request has been added.
https://github.com/w3c/wcag21/pull/492

**Comment by joshueoconnor** [comment]
Survey https://www.w3.org/2002/09/wbs/35422/Oct_17th_agwg/results

**Comment by awkawk** [comment]
Thanks for the comment. This SC has been scoped more narrowly to address status messages (a new defined term) and requiring that the changes are programmatically determinable. We hope that these changes will address your concerns. Regarding the concern that this SC will create implementation problems or result in extraneous notification, we hope to gather more data on this during the implementation phase.
