### ISSUE TITLE
Add note about "accessible name" to the definition of "name"

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/wcag21#485]
We've [removed](https://github.com/w3c/wcag21/pull/377/files) "accessible name" from the SC that had that title. I'd like to suggest a different approach. Add back "accessible name" and then in our definition of "name" add it in brackets.

name (accessible name)
   [current definition of name from 2.0]

I believe this is also supported by Jake and John Foliot

**Comment by awkawk** [comment]
We have a definition of "name" that covers this. I believe that this will only create more confusion. We aren't changing the name of the WCAG 2.0 SC, so it will be confusing to have one SC "Name, Role, Value" and another "Label in Name [Accessible Name]".

**Comment by steverep** [comment]
I agree with @awkawk.  The entire point of the change is consistency across WCAG.  I'd be open to a new note on the definition of "name" to solidify it with accessibility APIs and other W3C publications, but SC need to use the same terms when referring to the same thing.

**Comment by DavidMacDonald** [comment]
OK

**Comment by DavidMacDonald** [comment]
Adding Pull request to add a note to the definition of "name"
https://github.com/w3c/wcag21/pull/497

This would address the issue for me.

**Comment by joshueoconnor** [comment]
Thanks David - closing
