### ISSUE TITLE
Comment on 1.3.5 Contextual Information

### ISSUE THREAD

**Issue by jnurthen** [w3c/wcag21#487]
This seems to encourage developers to add text in (for example) the title attribute. I can see many developers adding text to a "Save" button of (for example) "Saves the document" in order to meet this. Does this actually help anyone or is it just more text which needs to be understood? 
If this is to stand it needs clarification that this is ONLY necessary in some cases. The majority of controls should not have additional text of this form as this will not help users.

**Comment by awkawk** [comment]
@jnurthen is this actually a comment on Purpose of Controls?

**Comment by jnurthen** [comment]
I don't think so. I think this was related to a long mail from @johnfoliot (which I can't find any more) where it pointed to ```title``` being one of the ways of meeting this. My entire statement here is that in general adding extra text to buttons does not improve the understandability of the UI and often just makes it harder for everyone to use. I'm concerned that this SC would encourage bad practice.

**Comment by lseeman** [comment]
This is about adding metadata to clarify the purpose and context

**Comment by lseeman** [comment]
we should add claification to the understanding sections

**Comment by awkawk** [comment]
Official WG Response: Thank you for your comment. The intent is not to encourage use of the title attribute. We will clarify this in the Understanding and Techniques documents.
