### ISSUE TITLE
Comment on 1.4.10 Zoom Content

### ISSUE THREAD

**Issue by jnurthen** [w3c/wcag21#488]
As previously noted this seems to require responsive design. There are scenarios in applications - especially those that are developed on technology stacks which pre-date the move to mobile - where this will be very costly to implement.

**Comment by awkawk** [comment]
We agree that it can be difficult to implement for legacy applications, or web content created before mobile devices were prevalent. However, there is significant benefit to users with low vision. For legacy systems we anticipate that WCAG 2.0 will continue to be the standard which they aim for.
