### ISSUE TITLE
Comment on 2.2.7 Interruptions (Minimum)

### ISSUE THREAD

**Issue by jnurthen** [w3c/wcag21#493]
Emergency is not linked to the definition. Is the definition the same?

There needs to be an exception for essential messages not just emergency messages. For example in a call center application if a user does not receive the message that there is an incoming call the application would not be functional.
Also in pretty much any application if there is downtime about to start the user needs to know so they can complete their task to avoid losing data. These exceptions must be accounted for by the SC.

**Comment by awkawk** [comment]
We will link to the definition.

**Comment by lseeman** [comment]
we also have additional clarification in the new proposed wording in https://www.w3.org/WAI/GL/wiki/2.2.7_Revision

**Comment by awkawk** [comment]
Official WG response: Thank you for your comment. This SC has been removed from the draft and will be able to be considered in a future revision.
