### ISSUE TITLE
Comment on 2.6.2 Orientation

### ISSUE THREAD

**Issue by jnurthen** [w3c/wcag21#496]
Orientation needs only support the primary orientation of the device (if there is one). For example, an iPhone is not usable if locked to landscape (system menus, phone screen etc all are portrait only) so in order to use the device the user MUST be able to use the portrait orientation. Why require all developers to code and test to see if landscape works if a user must be able to use portrait in order to use the device.

Requiring every application to support landscape on an iphone is very burdensome as many layouts will break for layouts with very small vertical viewport (especially if it is required to also operate when the virtual keyboard is displayed)

**Comment by patrickhlauke** [comment]
> For example, an iPhone is not usable if locked to landscape (system menus, phone screen etc all are portrait only)

however, the system menus etc are still usable in that they are still there, just that the text etc is on its side. what doesn't happen - and what this SC wants to also address - is that the iphone simply shows a blank screen with "please turn your device", which some sites have been doing.

**Comment by steverep** [comment]
> what doesn't happen - and what this SC wants to also address - is that the iphone simply shows a blank screen with "please turn your device", which some sites have been doing.

That's an issue for the Device Sensors SC, and would clearly be disallowed by my proposed revamping in #378.

**Comment by patrickhlauke** [comment]
@jnurthern it seems you *edited* my comment, rather than responding to it...

**Comment by patrickhlauke** [comment]
> That's an issue for the Device Sensors SC

the kind of behavior I described (with the "please turn") does not rely on sensors. you can use media queries, or even simply test the width/height of the viewport in javascript. nothing to do with sensors.

**Comment by jnurthen** [comment]
@patrickhlauke so sorry - wasn't deliberate... I'll try to undo the edit and respond.

**Comment by jnurthen** [comment]
> however, the system menus etc are still usable in that they are still there, just that the text etc is on its side. what doesn't happen - and what this SC wants to also address - is that the iphone simply shows a blank screen with "please turn your device", which some sites have been doing.

But this isn't what the SC says - if that is the intent then this part of the SC needs removing "Content is not locked to a specific display orientation" as this would prohibit this type of behaviour.

**Comment by patrickhlauke** [comment]
and in reponse to @jnurthen's comment: the "please turn..." thing was covered, to my mind, by the "functionality of the content is operable in all display orientations" part. if the screen is blanked with a "please turn..." thing when in the "wrong" orientation, then functionality isn't operable. but granted, as there's an "AND" clause, it also means it can't lock it to an orientation.

**Comment by steverep** [comment]
> the kind of behavior I described (with the "please turn") does not rely on sensors. you can use media queries, or even simply test the width/height of the viewport in javascript. nothing to do with sensors.

At least for my proposal on Motion Actuation, it wouldn't matter.  If you need to "please turn" with no UI component to accomplish the same thing, you fail.

**Comment by patrickhlauke** [comment]
> At least for my proposal on Motion Actuation, it wouldn't matter. If you need to "please turn" with no UI component to accomplish the same thing, you fail.

Hmm, yeah that makes sense. The example of the "please turn your device" would benefit from being included as an example of a failure for the rewritten proposal.

**Comment by patrickhlauke** [comment]
Last case for the orientation locking though: what about web content that explicitly locks the browser to a specific orientation? With the upcoming CSS Device Adaptation https://www.w3.org/TR/css-device-adapt-1/#orientation-desc a page could outright say "this should only display as landscape, and even though the user has NOT set orientation lock on their device and is browsing in portrait, they'd be forced to rotate the screen.

**Comment by awkawk** [comment]
We are documenting in the Understanding. App developer can build to this requirement, even if the OS (iOS) doesn't.  The current language helps alleviate this concern we believe:
“Content does not restrict its view and operation to a single display orientation, such as portrait or landscape, unless a specific display orientation is essential.”
