### ISSUE TITLE
Comment on 2.4.11 Character Key Shortcuts

### ISSUE THREAD

**Issue by jnurthen** [w3c/wcag21#501]
Some clarification still needs to be made as to where a single key shortcut is acceptable and where it is not. The understanding document attempts to do this but IMO it is incomplete.

For example a SELECT does not need to be opened in order to use the single character shortcuts. It merely needs to be focused. There are many similar controls which appear on the web today - both standard and non-standard controls where the single character shortcut helps usability for keyboard users.

It must be clarified that these controls can use single key shortcuts when they have focus.

**Comment by DavidMacDonald** [comment]
Proposed Responses

We've created a pull request https://github.com/w3c/wcag21/pull/512 with an exception for when a character key shortcut is only active on focus rather than on page load.

**Comment by joshueoconnor** [comment]
Survey https://www.w3.org/2002/09/wbs/35422/Oct_17th_agwg/results

**Comment by awkawk** [comment]
RESOLUTION: Add "unless the keyboard shortcut is only active when the user interface component has focus"

"If a keyboard shortcut consisting entirely of one or more character keys is implemented by the content, then a mechanism is available to turn it off or to remap it to a shortcut that uses at least one non-character key, unless the keyboard shortcut for a user interface component is only active when that component has focus."
