### ISSUE TITLE
Mitsue-Links Accessibility Dept. Comment on SC 2.2.6 Accessible Authentication: Change conformance level to AA or AAA

### ISSUE THREAD

**Issue by honoka-h** [w3c/wcag21#503]
It is too hard for web sites to conform to this SC at "the minimum level of conformance" (level A) considering that the web technologies which can be used to implement "alternative essential steps, which do not rely upon recalling and transcribing information;" is not yet mature.

The web technologies which can be used to implement "alternative essential steps" are not yet finalized:

- [Web Authentication](https://www.w3.org/TR/webauthn/) (Working Draft)
- [Credential Management Level 1](https://www.w3.org/TR/credential-management-1/) (Working Draft)

Please change conformance level of this SC to AA or AAA.

**Comment by milk54** [comment]
I have the same opinion.

**Comment by awkawk** [comment]
Official WG response: Thank you for your comment. This SC has been removed from the draft and will be able to be considered in a future revision.
