### ISSUE TITLE
Mitsue-Links Accessibility Dept. Comment on SC 2.5.1 Pointer Gestures: Clarify the term "pointer gesture"

### ISSUE THREAD

**Issue by kurosawa-takeshi** [w3c/wcag21#505]
A phrase ["a single untimed pointer gesture"](https://www.w3.org/TR/2017/WD-WCAG21-20170912/#pointer-gestures) is ambiguous for readers. For example, some people may consider that it includes single-figure swipe gesture and others may not.

Since [SC 3.2.6 Accidental Activation](https://www.w3.org/TR/2017/WD-WCAG21-20170912/#accidental-activation) uses the term "single-pointer activation", let’s use it to clarify the term "pointer gesture".

Currently [the SC](https://www.w3.org/TR/2017/WD-WCAG21-20170912/#pointer-gestures) is written as below,

> All functionality can be operated with a single untimed pointer gesture unless [snip]

but we propose rewording it either as

> All functionality can be operated with a single untimed pointer gesture which causes a [single-pointer activation](https://www.w3.org/TR/2017/WD-WCAG21-20170912/#dfn-single-pointer-activation) unless [snip]

or

> All functionality can be operated with an untimed [single-pointer activation](https://www.w3.org/TR/2017/WD-WCAG21-20170912/#dfn-single-pointer-activation) unless [snip]

**Comment by detlevhfischer** [comment]
I agree that the formulation you suggest, "All functionality can be operated with an untimed single-pointer activation unless a multipoint or timed gesture is essential", has the adantage of synching with the concept of single pointer activation. There are currently other open comments which may impact the scope and wording of sc pointer gestures:
- the SC may become limited to complex gestures, i.e. the decision may be made to exclude functions available to keyboard users that may not be available to users on devices without physical keyboard;
- Some behaviours of web content such as the support of secondary activation events after long presses, would currently be ruled out and may have to be accommodated in the SC text for example, either by a general exception for secondaryactivation via long presses, or by differentiation between 'essential' and 'incidental' functionality (the terms are at present just indicative),

**Comment by awkawk** [comment]
We have modified the SC language and believe that it addresses your concerns

“All functionality which uses multipoint or path-based gestures for operation can be operated with a single-point activation, unless a multipoint or path-based gesture is essential.”
 
There will also be a new definition for “path-based gesture” with a definition of: “User input that depends on the path of the user's movement and not just the endpoints.”
