### ISSUE TITLE
Grammar fix on User Interface components SC

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/wcag21#513]
It says:
> ```Examples of <a>essential</a> visual identifiers of <a>user interface components</a> may include (a border, edge, or icon), current value (such as non-text visual indication ...```

There is a bracket after includes. I think the brackets are examples of the thing before it, but there is nothing before it.

I propose adding the term "visual identifiers"

> ```Examples of <a>essential</a> visual identifiers of <a>user interface components</a> may include visual identifiers (a border, edge, or icon), current value (such as non-text visual indication ...```

Added pull request  #514

May need another tweak because the line ends with "other essential visual indication". This could probably be deleted but should have some discussion first. 

Note: the PR references Issue 506, and that is what the branch is called... but it should be called Resolve issue 513. My bad.

**Comment by joshueoconnor** [comment]
Surveyed https://www.w3.org/2002/09/wbs/35422/Oct_31_2017/

**Comment by awkawk** [comment]
closing as pull request approved by WG
