### ISSUE TITLE
Amend Success Criterion 3.1.2 Language of Parts

### ISSUE THREAD

**Issue by Geert-Frh** [w3c/wcag21#516]
Add this text:
If a site contains any pages or summaries in plain language, each plain language passage in the content can be programmatically determined except for proper names, technical terms, words of indeterminate language, and words or phrases that have become part of the vernacular of the immediately surrounding text.

**Comment by awkawk** [comment]
@Geert-Frh We are not making changes to the WCAG 2.0 SC in WCAG 2.1. Marking this "defer" for future consideration.
