### ISSUE TITLE
Insert new Criterion 3.1.7: Plain Language Summary of site

### ISSUE THREAD

**Issue by Geert-Frh** [w3c/wcag21#517]
When a website requires for most of its pages a reading ability more advanced than the primary education level, a summary page that does not require reading ability more advanced than the primary education level, is available as supplemental content. This Plain Language Summary page includes:

    Information about the purpose of the site
    Summary explanations of and links to the 5 most used pages on the site
    Contact information 

The summary page is clearly identified by a non-verbal icon.

**Comment by awkawk** [comment]
@Geert-Frh A good suggestion but we are not adding additional success criteria to WCAG 2.1 so we will label this item as "defer" to mark this idea for consideration in a future release (whether that is a WCAG 2.2 or some other number).
