### ISSUE TITLE
Extra help (Enhanced)

### ISSUE THREAD

**Issue by lseeman** [w3c/wcag21#52]
<h2><strong> Extra Help (Enhanced)</strong></h2>
<p><strong>SC Shortname: Extra Help (Enhanced) </strong></p>
		        <h2><strong>SC Text</strong></h2>
<p><strong>Extra Help:</strong> Provide easily available beginner's help or human help. </p>
<h2><strong>Suggestion for Priority Level</strong></h2>
		        <p><br>AAA</p>
<p><br>
<strong>Related Glossary additions or changes</strong></p>
<p><strong>beginner's help:</strong> Help that:</p>
<ul>
  <li>Does not assume people are familiar with the Internet</li>
  <li>Does not assume people use other Internet services such as email or social media</li>
  <li>Does not use Internet jargon</li>
  <li>Explains the use of any design patterns other than standard HTML controls of underlined links, buttons and text boxes</li>
  <li>Uses symbols at the beginning of most paragraphs and headings</li>
  <li>Gives detailed instructions on how to complete critical tasks</li>
</ul>
<strong>Easily available</strong> (or easily available mode or setting): One or more of the following is true:
        <ul>
  <li>Can be set once with as wide a scope as possible (such as using the standards of the OS, ETSI or GPII when available) </li>
  <li>
        With the option to save or to change the settings, were available interoperably, but also for the scope of a set of Web pages</li>
  <li>
        Is reachable from each screen where it may be needed, and the path and the control conforms to all of the document.</li>
  </ul>

  <p><br>
  <strong>What Principle and Guideline the SC falls within.</strong></p>
		        <p><br>
		          Principle 3, Guideline 3.3: Help users avoid and correct mistakes.</p>
		        <h2><br>
  <strong>Description</strong></h2>
		        <p>It is hard to find a user interface design that is obvious to all users. Human help or beginner's help gives flexibility and support to people who are struggling with the interface.</p>
<p>Although providing extra help may be a burden, there are content providers who want to be as inclusive as possible. They may look to these guidelines for direction on how to include everyone. This may include educational sites or sites who truly believe that their content is important to everyone. It is therefore important to have an AAA criteria that provides this guidance. </p>
<p>Beginner's help is useful for people who are new to using the Internet, for people who learn slowly or have impaired short term memory and therefore do not remember terms and design.<br>
</p>
                <p>Help related content enables a user to conveniently access information needed to understand how to use a website effectively. Users who need help related content are usually already confused. </p>
                <p>Human help includes: </p>
                <ul>
                  <li>An option for live help. Note: It must be easy and clear to close new windows that open as part of live help functionality. </li>
</ul>
                <ul>
                  <li>A phone number that will automatically call via an interoperable Voice over IP specification. </li>
                </ul>
                <ul>
                  <li>A simple site contact form. </li>
                </ul>
                <ul>
                  <li>Use available standards to get human help for example, using the 0 digit on voice menu systems. </li>
                </ul>

                <h2>Benefits</h2>
                <p> This Success Criterion enables users to:
                <ul>
                  <li>Access quick answers to user questions</li>
                </ul>
<ul>
                  <li>Easily get human help</li>
                </ul>
                 <h3>Related Resources</h3>
	<p>Resources are for information purposes only, no endorsement implied.</p>
                <ul>
                  <li> <a href= "https://rawgit.com/w3c/coga/master/gap-analysis/#table-4-help-and-support"> Gap analysis Table 4: Help and support</a></li>
                </ul>
                <ul>
                  <li> <a href="https://rawgit.com/w3c/coga/master/gap-analysis/table.html">User needs Tables</a> Table 3: Entering data, error prevention &amp; recovery</li>
                </ul>
                <ul>
                  <li><a rel="nofollow" href="https://w3c.github.io/wcag/coga/user-research.html">Background research document</a></li>
                </ul>
                <ul>
                  <li><a rel="nofollow" href="https://w3c.github.io/personalization-semantics/">Semantics for adaptive interfaces</a></li>
                </ul>
                <ul>
                  <li><a href="https://rawgit.com/w3c/coga/master/issue-papers/personalization-preferences.html">Personalization and Preferences</a></li>
                </ul>
                <ul>
                  <li><a href="https://rawgit.com/w3c/coga/master/issue-papers/voice-menus.html">Voice Menu Systems</a></li>
                </ul>
                <ul>
                  <li><a href="https://rawgit.com/w3c/coga/master/techniques/index.htm">COGA Techniques</a></li>
                </ul>
  <h2><strong>Testability</strong></h2>
                <p><br>
                This Success Criterion can be tested manually. </p>
                <p><strong>Test Procedure</strong></p>
                <ul>
                  <li><span dir="LTR"> </span>Identify if this is a critical service according to the definition</li>
                  <li>If this is a critical service confirm that there is one of the following:
                    <ul>
    <li> beginners help</li>
    <li>human help</li>
  </ul>
                  </li>
</ul>
Expected Results: Section saying ‘Passes checks 1 and 2
                <h2><strong>Techniques</strong></h2>
                <p><br>
                </p>
                <ul>
                  <li>Providing a live help option. Note: It must be easy and clear to close the live help session.</li>
                </ul>
                <ul>
                  <li>Providing a  phone number that will automatically call via an interoperable Voice over IP specification. This will be initiated by the user via a link similar to an embedded (Skype) number so that the user is in effect calling the support.  </li>
                </ul>
<ul>
                  <li>Providing a simple contact us form. </li>
                </ul>
                <ul>
                  <li>Using available standards to get human help such as using the 0 digit on voice menu systems.</li>
                  <li>Using COGA semantics to enable extra help on standards controls</li>
                  <li>Using COGA semantics to enable symbols</li>
<li>Adding icons and graphics.</li>
                  <li>
Using coga semantics </li>
                  <li>Advisory: providing both human help and beginners help</li>
                  <li>Advisory: providing beginners help for non-critical content</li>
                  <li>Advisory: providing human help for non-critical content</li>
                </ul>
<h2><strong>Working groups notes (optional)</strong></h2>

**Comment by GreggVan** [comment]
Hmmmm
Provide easily available beginner's help or human help.

This one needs work I think. 

     
Easily is not testable
Does this apply to every page?   Definition says that the help has to be useable by someone who isnt familiar with the internet.  Does that mean they don't know about links?   What does it mean?

Test says 
Identify if this is a critical service according to the definition

The SC doesnt mention critical service.  Should it be 

Provide easily available beginner's help or human help for critical services.

(wrong form for SC  ---  should be 

Beginner's help or human help are provided for critical services.

Refers to COGA semantics.   in techniques -- but no link with that name anywhere I can see.  (link to COGA techniques is  404)

**Comment by lseeman** [comment]
to greggs comente"Easily is not testable" We have defined easily available so it is testable


"Critical service" This should be removed in the test. It is an error from copying from "extra help " SC #45


which is AA. This SC has a broader scope but is AAA. It is not widely applicable 

All the best

Lisa Seeman

LinkedIn, Twitter





---- On Thu, 15 Dec 2016 03:45:41 +0200 GreggVan&lt;notifications@github.com&gt; wrote ---- 

Hmmmm
 Provide easily available beginner's help or human help.
 This one needs work I think.
 Easily is not testable
 Does this apply to every page? Definition says that the help has to be useable by someone who isnt familiar with the internet. Does that mean they don't know about links? What does it mean?
 Test says
 Identify if this is a critical service according to the definition
 The SC doesnt mention critical service. Should it be
 Provide easily available beginner's help or human help for critical services.
 (wrong form for SC --- should be
 Beginner's help or human help are provided for critical services.
 Refers to COGA semantics. in techniques -- but no link with that name anywhere I can see. (link to COGA techniques is 404)

**Comment by GreggVan** [comment]
RE Critical Service —  thanks 

RE   Easily is defined — can you point me to the definition?   Appreciate that. 

gregg

**Comment by lseeman** [comment]
it is defined in the glossary section

Easily available (or easily available mode or setting): One or more of the following is true:

    Can be set once with as wide a scope as possible (such as using the standards of the OS, ETSI or GPII when available)
    With the option to save or to change the settings, were available interoperably, but also for the scope of a set of Web pages
    Is reachable from each screen where it may be needed, and the path and the control conforms to all of the document.

**Comment by GreggVan** [comment]
Great 

Thanks Lisa

Gregg



PS   Is there a typo at the end ?   
             It all makes sense except the phrase "the path and the control conforms to all of the document"
             Can you explain that phrase?          Conform to what? 

g

**Comment by joshueoconnor** [comment]
@lseeman Do we have an SC manager for this one?
