### ISSUE TITLE
Definition of “Change of content” as used in SC 3.2.7:

### ISSUE THREAD

**Issue by spanchang** [w3c/wcag21#527]
Definition reads: "changes made to a web page after it has been delivered to the user agent, whether or not initiated by the user". 
1. What does 'delivered to the user agent mean' ... if the content becomes perceivable "after" when the page appears to have completed loading from the user's perspective? 
How does lazy loading impact 'delivered to the UA'? 
When is 'delivered to UA' take place for tooltips rendered via title attribute  to AT users/ via mouse event or other data-* attributes that are revealed through JS action? 
Should the above be more clearer / easily interpretable from a definition?
2. The term 'change of context defined and articulated very well in WCAG2.0 includes 'Change of content' too. If 'change in content'  was unclear or ambiguous, WCAG 2.0 would have defined it.

**Comment by awkawk** [comment]
Thanks for your comment. The definition your comment is about is no longer in the spec. Instead the SC is focused on "Status Messages" and includes "Changes in content that are not changes in context". We hope that this addresses your concern.
