### ISSUE TITLE
Success Criterion 1.4.12 User Interface Component Contrast (Minimum)

### ISSUE THREAD

**Issue by spanchang** [w3c/wcag21#528]
1. This short name for the SC is misleading.
The SC does not deal with the control itself, rather the visual identifiers.
2. I interpreted 'visual identifiers of  user interface components' to mean visible label of the control. Only after reading the note with example following the SC, I figured the reference is to other visual indicators that convey presence of a UI component like focus or state indicator. 
I suggest not using the term "identifiers" at all because it is commonly used to reference the control's name or label. 
It is not an identifier but  the unique manner in which the control that has focus is presented . 
The example for 'essential' (new definition) too refers to a manner of presentation of content. 

Consider using: "essential visual indicator" for UI component, as the subject matter of the SC.  
The entire phrase needs to be defined ... not just "essential" and should clearly state that it includes state indicator etc. besides keyboard focus indicator as intended by the SC.

**Comment by awkawk** [comment]
The SC have been combined, the new short name is Graphics Contrast. Please review the new draft.

Latest draft: 
Current SC text is:
The visual presentation of the following have a contrast ratio of at least 3:1 against adjacent color(s): (Level AA)
User Interface Components
Visual information used to indicate states and boundaries of active user interface components, except where the appearance of the component is determined by the user agent and not modified by the author.
Graphical objects
Parts of graphics required to understand the content, except when a particular presentation of graphics is essential to the information being conveyed.
