### ISSUE TITLE
SC 2.2.7 Interruptions (minimum) (AA): time out warnings in scope?

### ISSUE THREAD

**Issue by spanchang** [w3c/wcag21#529]
What about session time out warnings? It is not an emergency and; neither referred to in intent.

**Comment by lseeman** [comment]
We have better wording suggested  at https://www.w3.org/WAI/GL/wiki/2.2.7_Revision

**Comment by awkawk** [comment]
Official WG response: Thank you for your comment. This SC has been removed from the draft and will be able to be considered in a future revision.
