### ISSUE TITLE
Understanding Success Criterion 2.4.11 Character Key Shortcuts

### ISSUE THREAD

**Issue by spanchang** [w3c/wcag21#530]
1. The examples given assume that the voice input  s/w is unable to distinguish  voices. 
In fact when installing Dragon (or built-in technologies on mobile devices) an essential step is to record the user's voice so that the s/w recognizes the user's voice.  
2. The SC says 'one or more character keys'. So does the SC require that all character keys for a shortcut can be turned off or remapped? If yes, why not say "mechanism to turn off or remap  a character key should be available for a shortcut that involves at least one  character key"?

Maybe also include a couple of examples  that involve more than one character keys.

**Comment by awkawk** [comment]
Thanks for the comment. Our users of speech recognition software indicate that the ability to distinguish voices is not sufficiently robust to rely on. 

Regarding your second point, the SC does require that shortcuts comprised entirely of character keys need to be able to be turned off or remapped. The same is not true if a modifier key is part of the shortcut.

We will ensure that there are examples involving more than one character key, per your suggestion.
