### ISSUE TITLE
SC 3.2.7: Reason for exception #1

### ISSUE THREAD

**Issue by spanchang** [w3c/wcag21#531]
Why does the first exception listed in the success criterion suffices as a reason for waiving the required programmatic notification. 
How does a programmatically determined relationship between the new content and the control that triggers it help a screen reader user for instance detect
that new content has been presented on the page? 
Such a relationship with the trigger element, whether existing at the time of page load or added dynamically later on, will do nothing to inform the user of the new content. 
Consider an example:

A user enters an invalid email address in the email field and tabs off. Instantly a message pops up and is placed above the form, "Email address is not
valid".

If that message has aria-live, it will be read by a supporting screen reader even when the focus is on the control that follows the email field and there
is no programmatic determinable relationship between the email field and the error message.
If that message is merely associated with the email field via aria-describedby, a screen reader will not read it unless the user tabs back to the email field
assuming it suddenly dawns on the user that the text entered is invalid.

**Comment by awkawk** [comment]
This is about Change of Content, yes?

**Comment by awkawk** [comment]
Thank you for your comment. Exception #1 is no longer in the SC text.
