### ISSUE TITLE
Graphics Contrast (SC 1.4.11): Understanding / Intent

### ISSUE THREAD

**Issue by spanchang** [w3c/wcag21#533]
Refer to the opening statements in the Understanding SC 1.4.11 :    
<start>
The intent of this success criterion is to apply the contrast requirements to "important graphical elements" ... 
If a "graphic is needed to understand the content or functionality of the webpage" ...
</end>
Consider if the following helps to clarify the intent more clearly:

There are two aspects in clarifying the scope of this SC: 
i. the graphical object is essential in the context of the page because the info / content within the object is the only manner the info is available on the page.
ii. for such graphical objects, the content within the object must meet minimum contrast requirements.   
Or, in other words:
"When the content within a graphical object is the only manner in which it is available on a page, then the content within the graphical object must meet minimum contrast requirements". 

Also add: An image of text (defined in WCAG 2.0) is already covered by SC 1.4.3   and is hence is excluded from SC 1.4.11". (Referred in Github 525)

**Comment by alastc** [comment]
Hi @spanchang,

I'm not sure what this version brings?
> When the content within a graphical object is the only manner in which it is available on a page, then the content within the graphical object must meet minimum contrast requirements

That's a long way of saying "are required for understanding the content or functionality", is there a benefit I'm missing?

**Comment by awkawk** [comment]
We have modified the SC language and believe that it addresses your concerns

Current SC text is:
The visual presentation of the following have a contrast ratio of at least 3:1 against adjacent color(s): (Level AA)
User Interface Components
Visual information used to indicate states and boundaries of active user interface components, except where the appearance of the component is determined by the user agent and not modified by the author.
Graphical objects
Parts of graphics required to understand the content, except when a particular presentation of graphics is essential to the information being conveyed.
