### ISSUE TITLE
Graphics Contrast: SC 1.4.11 wording

### ISSUE THREAD

**Issue by spanchang** [w3c/wcag21#534]
1. Refer to the starting words of the SC: "visual presentation of graphical objects that are essential for understanding the content or functionality." 

I do not see how "graphical objects that are essential for understanding the content or functionality" might be interpreted to exclude images that contain text (i.e. images of text) or refer only to interactive graphical controls.
By the way, the title of 1.4.11 is "graphics contrast" ... nothing to indicate it relates to graphical UI controls only.

Also, "essential for understanding the content or functionality" apparently refers to the "content or functionality" on the page, right?  
But the contrast requirements relates to the main (or essential) content of such graphical objects ... and that does not seem to be clear from the SC text IMO.

2. And what does "adjacent color"  refer to in "at least 4.5:1 against the adjacent color"? Adjacent to the graphical object or adjacent for the key content of the graphic inside the complete object? It might help if this clearer. 
Related issue: 533.

**Comment by alastc** [comment]
> I do not see how "graphical objects that are essential for understanding the content or functionality" might be interpreted to exclude images that contain text (i.e. images of text) 

Text is not a graphical object.

> or refer only to interactive graphical controls.

It does not refer only to graphical controls, are you thinking of 1.4.12?

From these two comments:
> the contrast requirements relates to the main (or essential) content of such graphical objects
and
> Adjacent to the graphical object or adjacent for the key content of the graphic inside the complete object?

I think it is worth reading about the graphic object again:
> The term "graphical object" is intended to apply to stand-alone icons such as a print icon (with no text), and the important parts of a more complex diagram such as each line in a graph.

I.e. you would not have 'key content of the graphic inside the complete object', because the graphical object is what it being tested.

The point is that the thing within the image (e.g. a bar on a bar-chart in a JPG), is the graphical object, regardless of whether that is at the edge of the overall graphic.

**Comment by awkawk** [comment]
@spanchang Can you review Alastair's response and confirm if this is ok to close?

**Comment by spanchang** [comment]
The responses above do not address my concerns satisfactorily.   
Let me re-state my concerns:

The SC uses the term graphical object without clearly defining it. 

The Understanding SC 1.4.11 begins, "The intent of this success criterion is to apply the contrast requirements to important graphical elements in a similar way that it is applied to text
in 1.4.3 Contrast (Minimum)".
Even this main intent statement for the SC here simply does not refer to graphical objects.

It appears graphical objects and graphical elements are used interchangeably?
Now are not all "images of text" graphic elements or graphic objects? If it is one but not the other, it is not clear from the normative text. Text that defines the scope of an SC's coverage cannot be conveyed by a non-normative Understanding doc. 

So, from the SC how is it clear that both the images below are excluded from the scope of SC 1.4.11?  
i. Consider a tag line of a company rendered as an image. (I do not mean a logo).
ii. Or a delete.png that has a picture of a trash can to convey delete action and the word "DELETE" written within the image horizontally or vertically on the trashcan or next to (or below) the can. The word helps to convey the function of the element unambiguously for users who may not connect the trash can with the delete action.

It is not clear to me from the SC text if  it covers the words "Quantity" / "Price" written within a demand line graph to label the X and Y axis respectively for example. The text labels are essential content to make the graph meaningful to one who tries to study the graph visually and is part of the praphical object or graphical element.

From the opening statement of the SC it appears the focus is on the contrast of graphical objects. But the first list item for exceptions (for thicker) appears to shift the focus to contrast of "graphics".

Likewise, from the opening statement, it is clear "Adjacent color" refers to the color adjacent to the graphical object as a whole but the first list item (for thicker) refers to the "graphic" without reference to "adjacent color"... in other words  it does not say how contrast for the "graphic" is to be determined.

Another list item under exceptions  simply refers to "non text content" and no "graphic"  or "graphical object" at all.
So by "graphic" does the SC mean "non text content"? Why not use that term instead of "graphic" all across the SC?
Thanks.

**Comment by alastc** [comment]
Hi @spanchang,

Based on this an other discussions, the two new contrast SC have been combined, the proposed normative text is now:

> The visual presentation of graphical information has a contrast ratio of at least 3:1 for each of the following:
> 
> - Controls: focus indicators, borders, and visual information used to indicate state for active user interface components;
> - Graphical objects: Parts of graphics required to understand the content;
> 
> Except:
> 
> - Sensory: Content that is primarily intended to create a <a>specific sensory experience</a>
> - Logotypes: Graphics that are part of a logo or brand name;
> - User Agent Control: The color(s) of the <a>user interface component</a> are determined by the user agent and are not modified by the author.
> - Essential: A particular presentation of the graphic is <a>essential</a> to the information being conveyed; 

Also, I think you were looking at an old Understanding doc. We need to combine the previous ones but it might help to review the [most recent graphics-contrast one](https://rawgit.com/w3c/wcag21/graphics-contrast/understanding/21/graphics-contrast.html).

So "graphical objects" are defined as part of the SC text, and text in graphics is already covered elsewhere in WCAG 2.0, & 2.1. We have had other comments wondering what the effect of text are (i.e. whether that makes it 'not required for understanding'), but I don't think anyone else thought that text-in-graphics would be covered.

I suppose that it could start "The visual presentation of non-text content..." but do you think that is necessary?

**Comment by mraccess77** [comment]
It might be helpful to agree on where font icons fall - on this SC or text and images of text.

**Comment by alastc** [comment]
In terms of contrast? If they are an implementation of an icon, then I think they would fall under graphics contrast. We don't specify how you implement it, just that it is a graphic.

**Comment by spanchang** [comment]
Interesting: In the previous version, it appeared "graphic" was a subset of "graphical object". This definition now has it the other way. This is just an observation, and suppose it is intentional; I have no concern.
If no one else thought that text-in-graphics would be covered, will it be a good idea in order to remove doubt and to prevent queries, the SC should explicitly address it?
It would be good if one can clearly discern the applicability of the SC to examples such as those in my comment of Nov 12. 
By removing "adjacent to" type-of-phrasing the wording is now more aligned to contrast issues in WCAG 2.0.
  
PS: Not sure why I have been pressured (including by Andrew since Nov 5)to review and close  this issue while the concerns raised are actively being addressed.
Thanks

**Comment by alastc** [comment]
Ok, if I'm understanding correctly, you'd rather we use a formulation such as "non-text content"?

All the other aspects have been dealt with?

Also, I think Andrew was just trying to corral all the comments so that we have one issue per conceptual 'thing'. Also,to work out if we've dealt with it, we have to ask!

**Comment by awkawk** [comment]
Sailesh,
The reason that I have been asking you - asking, not "pressuring" - is that you have redundant issues. Each one takes WG resources to respond to, and it is a waste of collective time to have the same comment from the same person multiple times. On top of that, I asked you to review the responses that were given to see whether they addressed your concerns.

If this feels like pressure, I'm sorry, but we are looking to close issues to keep on schedule.

**Comment by spanchang** [comment]
Alastair,
Yes consider "non text content within graphical elements" or the like.
Else my basic question raised first in #525 still remains: Someone who
reads 1.4.11 might  subject all graphical elements to an evaluation
under this SC.
How will one figure out that this SC does not cover the text labels
for the X and Y axis of the graph in my example of Nov 12? or the
other two examples?

By the way, I do not see the new SC text  in the editors draft of Nov 14 at
https://rawgit.com/w3c/wcag21/master/guidelines/index.html#undefined.
It is the same content as the draft of early-Oct I used to make all my
comments last month.
The reason  I raised #533 and #534 are explained in the closing remark of #525.

Also the WCAG 2.1 draft advises: "To file comments on this proposal,
please  raise new issues  for each discrete comment in GitHub".

Thanks

On 11/13/17, Andrew Kirkpatrick <notifications@github.com> wrote:
> Sailesh,
> The reason that I have been asking you - asking, not "pressuring" - is that
> you have redundant issues. Each one takes WG resources to respond to, and it
> is a waste of collective time to have the same comment from the same person
> multiple times. On top of that, I asked you to review the responses that
> were given to see whether they addressed your concerns.
>
> If this feels like pressure, I'm sorry, but we are looking to close issues
> to keep on schedule.
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/w3c/wcag21/issues/534#issuecomment-344091279


-- 
Sailesh Panchang
Principal Accessibility Consultant
Deque Systems Inc
Phone 703-225-0380 ext 105
Mobile: 571-344-1765

**Comment by alastc** [comment]
> How will one figure out that this SC does not cover the text labels for the X and Y axis of the graph

Because common parlance means that 'text labels' are not 'graphics'. 

> Yes consider "non text content within graphical elements" or the like.

Ok, I'll put in a pull request for that.

**Comment by alastc** [comment]
The change (unconfirmed) can be previewed here:
https://rawgit.com/alastc/wcag21/graphics-contrast/guidelines/index.html#graphics-contrast

**Comment by mraccess77** [comment]
The term "non-text content" can include audio, sensory, etc. so I think it is too broad for this SC.

**Comment by spanchang** [comment]
Hello Alastair,
By text labels I do not mean the type of a text label for a form
control. In the example above, it is the text content within the
graphic that labels the X and Y axis or the text marking on the X / Y
axis to indicate scale increments: 100, 200, 300 etc.
Yes just plain "non text" is broad, so I had suggested "non text
within graphical elements" above. Or may be non-text graphic content".

I suppose "adjacent" refers to surrounding the subject item. But it
does not imply background. Is that material in the context of
graphics?
SC 1.4.3 only states  the ratio, should SC 1.4.11 do the same? In a
sense what is unsaid can also be argued to be a weakness of the SC.
But will technology and CSS properties  like opacity that make things
transparent etc impact the contrast computation? Will the contrast
change with mouse action for instance?
In an interaction with Dr. Vanderheiden, I learnt he has concerns
about images that use more than one color: "since graphics are complex
and if they involve more than  two colors (or three colors if one is
essentially black and one is essentialy white)    maintaining the
contrast will be difficult in places  or impossible".
Thanks,


On 11/14/17, Jonathan Avila <notifications@github.com> wrote:
> The term "non-text content" can include audio, sensory, etc. so I think it
> is too broad for this SC.
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/w3c/wcag21/issues/534#issuecomment-344456120


-- 
Sailesh Panchang
Principal Accessibility Consultant
Deque Systems Inc
Phone 703-225-0380 ext 105
Mobile: 571-344-1765

**Comment by alastc** [comment]
> By text labels I do not mean the type of a text label for a form control. In the example above, it is the text content within the graphic that labels the X and Y axis

I understood that, the point is that a bit of text in an image is not a 'graphic' in common language.

I suppose "non-text graphic content" would work, but it is making it more wordy & less understandable (we get complaints about that!) so I would rather clarify that in the understanding.

> I suppose "adjacent" refers to surrounding the subject item. But it does not imply background.

If you have a graphical object (e.g. icon, or a line in a line chart) then the adjacent color is usually the "background", I don't think that is confusing, there really isn't another way to read it.

 > will technology and CSS properties  like opacity that make things transparent etc impact the contrast computation

That makes a difference to the color, but not a relevant one. The only way of testing this is with an eye-dropper style contrast checker, there is no current technology to automate this.

If you have concerns like those raised by Gregg please comment there or open a new issue, we need to keep these issues on-topic.

For this issue, can you live with "graphical information", and clarification in the understanding document that this does not include text?

**Comment by spanchang** [comment]
Alastair,

Instead of using "non text" or "non text graphic",  consider going
back to "graphical info" in the opening statement of the SC.
Then add a note (normative) to the SC that says "any text  that is
part of the graphical element must conform with requirements of SC
1.4.3". That text will then be judged or exempted as per the
requirements of that SC.

I do not wholly agree with your statement, "the point is that a bit of
text in an image is not a 'graphic' in common language".
If it is a picture of a street view and it includes , say, sign boards
 or store signs etc. it is possible that's not the main content of the
picture  and not all signboards are readable though one can clearly
tell there is text within the image.
That's phrased in normative terms in WCAG 2.0 as, "that are part of a
picture that contains significant other visual content" and has not
been dismissed as "a bit of text in an image...".
The text in the example of a graph I have been referring to is
significant content that must be readable by one who studies the
graphic visually in order to make sense of the graph.
Thanks



On 11/15/17, Alastair Campbell <notifications@github.com> wrote:
>> By text labels I do not mean the type of a text label for a form control.
>> In the example above, it is the text content within the graphic that
>> labels the X and Y axis
>
> I understood that, the point is that a bit of text in an image is not a
> 'graphic' in common language.
>
> I suppose "non-text graphic content" would work, but it is making it more
> wordy & less understandable (we get complaints about that!) so I would
> rather clarify that in the understanding.
>
>> I suppose "adjacent" refers to surrounding the subject item. But it does
>> not imply background.
>
> If you have a graphical object (e.g. icon, or a line in a line chart) then
> the adjacent color is usually the "background", I don't think that is
> confusing, there really isn't another way to read it.
>
>  > will technology and CSS properties  like opacity that make things
> transparent etc impact the contrast computation
>
> That makes a difference to the color, but not a relevant one. The only way
> of testing this is with an eye-dropper style contrast checker, there is no
> current technology to automate this.
>
> If you have concerns like those raised by Gregg please comment there or open
> a new issue, we need to keep these issues on-topic.
>
> For this issue, can you live with "graphical information", and clarification
> in the understanding document that this does not include text?
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/w3c/wcag21/issues/534#issuecomment-344634709


-- 
Sailesh Panchang
Principal Accessibility Consultant
Deque Systems Inc
Phone 703-225-0380 ext 105
Mobile: 571-344-1765

**Comment by alastc** [comment]
Hi @spanchang,

I'm afraid other comments and changes have overtaken this issue, neither term is now referenced, the latest text is:

> The visual presentation of the following have a contrast ratio of at least 3:1 against adjacent color(s): (Level AA)
> 
> User Interface Components
> Visual information used to indicate states and boundaries of active user interface components, except where the appearance of the component is determined by the user agent and not modified by the author.
> Graphical objects
> Parts of graphics required to understand the content, except when a particular presentation of graphics is essential to the information being conveyed.

If you have a similar concern please comment here, otherwise please indicate you are happy to close the issue.

**Comment by spanchang** [comment]
Alright. Thanks.
