### ISSUE TITLE
Purpose of control: SC 1.3.4

### ISSUE THREAD

**Issue by spanchang** [w3c/wcag21#538]
Do these lists not appear too prescriptive for a normative
guideline: "conventional" fields, buttons, controls,
links. 

This is alright for a usability guideline IMO.

Another concern: Conventional: Conventions change over time. So will these lists keep getting edited? 
Does the term 'conventional name' need a definition?

'mode' ... is very specific and not conventional

'TOC' is not conventional  and many many users will not understand it
without  reference to its expansion (table of contents).

I  do not see 'salutation' that is also used for 'honorific' like Mr,
Mrs, Dr, etc."

**Comment by jake-abma** [comment]
Hi @spanchang thank you for your feedback

You are right we’re looking for a way to define THE specific lists for this SC to be testable.
You can follow another issue where we are discussing this at #340

The term 'conventional name’, if still used when reading CR, needs a definition and we’re also discussing this.
You can follow the issue where we are discussing this at #486 , #341 and #402 for related info

About the feedback on the lists of terms included in the definitions, we’ll take that into account when refining, removing or adding the items.

Jake

**Comment by awkawk** [comment]
Thank you for your comment. We have made substantial changes to this SC and believe that you will find it far more understandable. Please review the current draft when it comes out this week.
