### ISSUE TITLE
JR comment on Contextual Information

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/wcag21#547]
[Filed by email 14 October 2017](https://lists.w3.org/Archives/Public/public-agwg-comments/2017Oct/0001.html) by @JanRichards

* Again, is this vocabulary planned for a future ARIA iteration?
* This would be difficult to reliably test, but as it is AAA I wouldn’t object to it.

**Comment by awkawk** [comment]
Official WG Response: Thank you for your comment. There is planned work within ARIA, but using COGA semantics in ARIA is not the only way to satisfy this SC.
