### ISSUE TITLE
JR comment on Zoom Content

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/wcag21#548]
[Filed by email 14 October 2017](https://lists.w3.org/Archives/Public/public-agwg-comments/2017Oct/0001.html) by @JanRichards

* Getting there…
* The key concept here is the reflow, not the zoom. Perhaps the handle could be something like “Reflow content on zoom”
* Why not say 400% to align with the existing re-size SC (320 CSS sounds odd)?
* re: "except for parts of the content which require two-dimensional layout for usage or meaning." I'm concerned about things like dashboards, which may not strictly require 2D layout but still have them for design reasons. What about restricting this SC to blocks of text content, since the big problem is the back and forth scrolling required for reading non-reflowed text?

**Comment by awkawk** [comment]
After discussion at TPAC the SC has been focused to reflow, and renamed to that, the SC text is now:

Reflow: Content can be presented at a width equivalent to 320 CSS pixels without loss of information or functionality, and without requiring scrolling in two dimensions, except for parts of the content which require two-dimensional layout for usage or meaning.

We did explore a version of the SC that used 400% zoom (see issue #335), but there are significant issues with requiring all content to resize by 400%, so we are using the combination of Text-size (1.4.4) and this to achieve the goal.

Content such as dashboards have been considered, there are good examples available that meet the guideline and we haven't found a content-intrinsic reason that such functionality could not meet the SC (noting the exception for editing interfaces which manipulate content). It is also worth noting that while reading blocks of text is a big issue, but another significant issue is missing content which is off the screen (horizontally in western languages).

**Comment by JanRichards** [comment]
ok
