### ISSUE TITLE
JR comment on Graphics Contrast

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/wcag21#549]
[Filed by email 14 October 2017](https://lists.w3.org/Archives/Public/public-agwg-comments/2017Oct/0001.html) by @JanRichards

I like the SC for symbols, diagrams and graphs, but I think there should be an exception for photos. For example, take the example of a colour photo of a historical event in a Wikipedia article (e.g. JFK assassination). Is that essential for understanding? It’s pretty important, unless we allow an exception for graphics with text equivalents? Is it intended to create a visual experience? Not exactly. It’s intended to show what the situation looked like.

**Comment by awkawk** [comment]
The Working Group regards photographs as part of the "essential" exception, and will clarify this in the understanding docs.

**Comment by JanRichards** [comment]
It sounds odd to have the word "essential" in both the SC body and the exception. If all photos are exceptions, why not just have a photo exception?
btw: There is a grammatical error: "A particular presentation of the graphical is essential..."
