### ISSUE TITLE
JR comment on Adapting Text

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/wcag21#551]
[Filed by email 14 October 2017](https://lists.w3.org/Archives/Public/public-agwg-comments/2017Oct/0001.html) by @JanRichards

Could this be restricted to blocks of text as opposed to text in UI (e.g. menus, etc.)?

**Comment by awkawk** [comment]
Thank you for your comment.

Based on an evaluation of 67 pages tested between July 25 and August 3, 2017 that included top 50 Alexa pages and some smaller pages, the combined metrics specified in the Adapting Text SC should be feasible in WCAG 2.1 for HTML documents. Spacing is able to adapt without loss of content or functionality across a wide range of sites.

The Working Group will be going through the implementation process and demonstrating the implementability of all the new SCs. If you know of examples in the wild of text in UI - (e.g. menus, etc) where it would not be possible to meet the SC, please add them to this issue.

We are tagging this issue with the "Implementation Follow-up" label to ensure that it is re-reviewed at that point in our process. In addition we will add the following editor's note:

"Editors Note: The Working Group seeks examples in the wild of text content outside of blocks of text where it would be impossible to meet this SC. The SC's scope may be narrowed based upon implementation testing."

**Comment by JanRichards** [comment]
ok
