### ISSUE TITLE
JR comment on Content on Hover or Focus

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/wcag21#552]
[Filed by email 14 October 2017](https://lists.w3.org/Archives/Public/public-agwg-comments/2017Oct/0001.html) by @JanRichards

* Not sure what the “Hover” condition means. The concern seems to be content is triggered by hover but then is dismissed by more hover. Is this right?
* I don’t think this is ready.

**Comment by steverep** [comment]
#### Proposed Response

This condition requires that the content appearing on hover must also be able to be hovered itself.  The [draft understanding](https://rawgit.com/w3c/wcag21/content-on-hover-or-focus/understanding/21/content-on-hover-or-focus.html) for this condition explains it as follows:

> The intent of this condition is to ensure that content which may appear on hover of a target may also be hovered itself. Content which appears on hover can be difficult or impossible to perceive if a user is required to keep their mouse pointer over the trigger. When the added content is large, magnified views may mean that the user needs to scroll or pan to completely view it, which is impossible unless the user is able to move their pointer off the trigger without the additional content disappearing. Another common situation is when large pointers have been selected via platform settings or assistive technology. Here, the pointer can obscure a significant area of the additional content. A technique to view the content fully in both situations is to move the mouse pointer directly from the trigger onto the new content. This capability also offers significant advantages for users who utilize screen reader feedback on mouse interactions. This condition generally implies that the additional content overlaps or is positioned adjacent to the target.

Please also see Example 2 in the Understanding link above which demonstrates one scenario where this is helpful.  Let us know if this does not clarify your concern.  Thanks.

**Comment by steverep** [comment]
@JanRichards, in addition to my comment above, the bullet in question may be reworded to the active voice for better clarity (pending working group approval of #569).  Hopefully this [proposal](http://rawgit.com/w3c/wcag21/hoverable-and-persistent/guidelines/#content-on-hover-or-focus) plus the Understanding helps even more.

**Comment by JanRichards** [comment]
Sounds good.
