### ISSUE TITLE
JR comment on Interruptions (Minimum)

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/wcag21#554]
[Filed by email 14 October 2017](https://lists.w3.org/Archives/Public/public-agwg-comments/2017Oct/0001.html) by @JanRichards

* What if the whole point of the app is content changes? e.g. an email app, a stock trading app, an airport departure board?
* I don’t think this is ready.

**Comment by lseeman** [comment]
are you happy with https://www.w3.org/WAI/GL/wiki/2.2.7_Revision

**Comment by awkawk** [comment]
Official WG response: Thank you for your comment. This SC has been removed from the draft and will be able to be considered in a future revision.
