### ISSUE TITLE
JR comment on Timeouts

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/wcag21#555]
[Filed by email 14 October 2017](https://lists.w3.org/Archives/Public/public-agwg-comments/2017Oct/0001.html) by @JanRichards

Does this include un-submitted data (e.g. in text fields)?

**Comment by rachaelbradley** [comment]
Proposed Response: 

JanRichards, 

Thank you for your question.  Yes. The phrase "...unless the data is preserved" includes user entered data that has not yet been submitted. If this exception is used, then data can be retained by saving every keystroke in an authenticated session, periodic autosaving, or saving the data at the point of timeout.

**Comment by JanRichards** [comment]
Well, periodic auto-saving is prob not enough, because it would allow loss of a few keystrokes at least. But at AAA, this SC seems OK. Can "Success Criterion 2.2.5 Re-authenticating" be deprecated because of this new one?

**Comment by JanRichards** [comment]
OK

**Comment by awkawk** [comment]
Finalized by WG
