### ISSUE TITLE
JR comment on Target Size

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/wcag21#558]
[Filed by email 14 October 2017](https://lists.w3.org/Archives/Public/public-agwg-comments/2017Oct/0001.html) by @JanRichards

* The “In-page” exception seems to be a special case of the “in-line” exception.
* Maybe plain linked text should always be allowed.

**Comment by awkawk** [comment]
In the latest draft we have modified the exceptions related to text links to require that text-based links within a sentence or block of text are exempted. We believe that this addressed your concern.

**Comment by JanRichards** [comment]
Great, thanks.
