### ISSUE TITLE
JR comment on Accidental Activation

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/wcag21#561]
[Filed by email 14 October 2017](https://lists.w3.org/Archives/Public/public-agwg-comments/2017Oct/0001.html) by @JanRichards

Since reversibility condition would almost always be satisfied anyway, maybe just say “Irreversible actions may only be activated on the up-event”

**Comment by awkawk** [comment]
Thank you for the comment. Due to the increase diversity of input events we feel that it is best to not limit reversibility to up-event initiated actions.
