### ISSUE TITLE
JR comment on Change of Content

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/wcag21#562]
[Filed by email 14 October 2017](https://lists.w3.org/Archives/Public/public-agwg-comments/2017Oct/0001.html) by @JanRichards

I like the idea of ensuring user knows about a change of content, but I think setting focus to the top of the newly added or changed content might be enough at AA. e.g.

**Comment by awkawk** [comment]
Thank you for the comment. This has been identified as a problem for users who need to keep their focus on the part of the page that they are active on, so we are working to provide a way. We have updated and hopefully clarified the SC. Please re-review it when the new working draft is available this week.
