### ISSUE TITLE
"Legal requirement" in SC2.2.6

### ISSUE THREAD

**Issue by guyhickling** [w3c/wcag21#564]
It seems to me there is a small loophole in the 2nd exception to SC2.2.7 (as shown in the 12 Sept 2017 draft) that would enable some websites to ignore it:

> This is not achievable due to legal requirements

I think this needs to be a bit more specific as to what is meant, to make it more watertight. A company could easily get round it by creating its own legal requirement. For instance by this means:

If a company requires users to make the usual agreement to a website's Terms and Conditions when signing up to something, then at the point of signing up the user has entered into a legal agreement. It is arguable that this could be a "legal requirement" meeting this exemption in the SC.

And then, in those T&Cs, the company can quietly include a small item in the depths of all the small print legalese saying that the user "must follow our authentication process", perhaps even adding "recalling and transcribing information as required".

Users a) would probably not understand what was being said there, even if they saw it in all the reams of small print that companies typically put into their T&Cs, and b) would not be able to do anything about it if they wanted to continue signing up.

Meanwhile the company has neatly circumvented this SC, allowing it's developers to ignore the matter completely!

### The solution

I assume the "legal requirements" exception refers to the law of the country or legal jurisdiction applying at the time, and is not intended to include any clever tricks used by an unscrupulous business to try to avoid unwanted responsibility.

So maybe ​the SC could have ​something like "...statutory requirements of law in the country having legal jurisdiction over the website owners or publishers"...or maybe "legal requirements outside the control of the website (or document maybe?) owners or publishers".

The exact way to say that needs thinking about of course, and needs to be as general as possible, but I suggest something is needed here to avoid this possible loophole.

**Comment by awkawk** [comment]
Official WG response: Thank you for your comment. This SC has been removed from the draft and will be able to be considered in a future revision.
