### ISSUE TITLE
remove the word "accessible" from handles for SCs

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/wcag21#568]
I think "accessible" is a $10 word in our context... we could put it on every handle. Nothing can be accessible to all people. So I would suggest we remove it from handles and rename them where necessary.

Accessible Authentication
https://www.w3.org/TR/WCAG21/#accessible-authentication
Perhaps here just "Authentication"

Accessible Name
https://www.w3.org/TR/WCAG21/#accessible-name
Perhaps 
"Label in Name"

**Comment by joshueoconnor** [comment]
@DavidMacDonald I see where you are coming from - that would be an interesting proposal for the group.

**Comment by awkawk** [comment]
This is resolved in label in name and accessible authentication is removed in the editor's draft so the comment doesn't apply any longer.
