### ISSUE TITLE
Line Length

### ISSUE THREAD

**Issue by allanj-uaag** [w3c/wcag21#57]
<h2>SC Shortname</h2>
<p>Line Length </p>
<h2>SC Text</h2>
<p>For the visual presentation of all text, a mechanism is available such that line length is user adjustable, to 25 characters, with no two-dimensional scrolling required, and with the following exceptions.</p>
<ol>
  <li> If the user-agent fits the layout to the view port, and does not provide a means of re-flowing content, then two-dimensional scrolling is exempt. </li>
  <li> If the spatial layout of text is essential to its use, then two-dimensional scrolling is exempt. </li>
</ol>
<h2>Suggested Priority Level</h2>
<p>Level A </p>
<h2>Related Glossary additions or changes</h2>
<p>none</p>
<h2>What Principle and Guideline the SC falls within.</h2>
Principle 1, Guideline <a href="http://www.w3.org/TR/WCAG20#visual-audio-contrast-visual-presentation 1.4.8 Visual Presentation"> 1.4.8 Visual Presentation</a>
<h2>Description</h2>
<p>The user can pick the length of lines to fit reading needs. Many user agents already support this using reflow and adjustable viewport size. </p>
<img src="https://www.w3.org/WAI/GL/low-vision-a11y-tf/wiki/images/7/7e/LinLenHTML.png" alt="A reflowed HTML file with reduced line length."/>
<p> This shows how a line length can be shortened by reducing the browser width. The page has been reflowed using a custom style sheet made available through a browser extension.</p>
<p><img src="https://www.w3.org/WAI/GL/low-vision-a11y-tf/wiki/images/thumb/6/65/LinLenPDF.png/300px-LinLenPDF.png" alt="A reflowed display with reduced line length in PDF."/></p>
<p>The same works with reflowed PDF.</p>
<p>Character count was chosen as a metric to measure line length because a character count enables line-length control for both large print with normal width, and narrow columns with normal print. The number 25 was chosen to fall in a range above the length of larger words in most languages. (<a href="http://www.ravi.io/language-word-lengths">Distribution of word lengths in various languages</a>.) This reduces excessive hyphenation. On a 13-inch monitor, one can use 33 point font and fit in 25 characters. Character count size is 72(13cos(30))/25.</p>
<h2>Benefits</h2>
<blockquote> For many people, with and without disabilities, it is harder to read very long lines of text than shorter lines. For people with a small field of vision, it can be even more difficult to read long lines of text, and from the end of a line of text, to find the beginning of the next line.
  
  People with good visual acuity yet small field of vision might want to set the text size small and the text area narrow so they can get more characters in their field of vision.
  
  '''User Need''': Users can set the line length for blocks of text. Often the easiest way to do this (for developers, designers, and users) is for users to resize text areas and the text rewraps to change the line length. 
  
  Source: <a href="http://w3c.github.io/low-vision-a11y-tf/requirements.html#line-length">Accessibility Requirements for People with Low Vision, Section 3.2.3</a> </blockquote>
<h2>Testability</h2>
<ol>
  <li> For HTML: Use a browser with an adjustable view port. Resize the view port so the line length is 25 characters or fewer. If the lines of text word wrap appropriately, the test passes. </li>
  <li> For PDF: Using a user agent that enables reflow and resizing of the view port, reflow the content. Then, adjust the line length to 25 characters or fewer. If the lines of text word wrap appropriately, the test passes.  Note: Each line of text does not have to reach a length of 25 characters, but line length must not exceed 25 characters. </li>
</ol>
<h2>Techniques</h2>
<h3>Existing Techniques</h3>
<ul>
  <li> <a href="https://www.w3.org/TR/WCAG20-TECHS/C20.html">C20: Using relative measurements to set column widths so that lines can average 80 characters or less when the browser is resized (CSS)</a> </li>
  <li> <a href="https://www.w3.org/TR/WCAG20-TECHS/G204.html">G204: Not interfering with the user agent's reflow of text as the viewing window is narrowed</a> </li>
</ul>
<h3>New Techniques</h3>
<ul>
  <li> Using relative measurements so line length can be adjusted to 25 characters, with no two-dimensional scrolling. (Future Technique) </li>
</ul>
<h2>Related Information</h2>
<h3>Actions</h3>
<ul>
  <li> <a href="https://www.w3.org/WAI/GL/low-vision-a11y-tf/track/actions/53">ACTION-53: In user need doc, edit 3.2.3 line length to address issues from 4 may 2016 telecon</a> on Shawn Henry, May 4, 2016 </li>
  <li> <a href="https://www.w3.org/WAI/GL/low-vision-a11y-tf/track/actions/66">ACTION-66 Create another sc mechanism for line length</a> on Jim Allan, July 14, 2016 </li>
</ul>
<h3>Articles</h3>
<ul>
  <li> <a href="https://www.w3.org/WAI/tutorials/page-structure/styling/#line-length">Line length</a> -  Education and Outreach Working Group Tutorial </li>
</ul>
<h3>Email</h3>
<ul>
  <li> <a href="https://lists.w3.org/Archives/Public/public-low-vision-a11y-tf/2016Nov/0082.html">Reflow is ready, and so is Line length</a> - Wayne Dick, 15 November 2016 </li>
  <li><a href="[https://lists.w3.org/Archives/Public/public-low-vision-a11y-tf/2016Nov/0029.html"> Line Length</a> - Wayne Dick, 7 November 2016 </li>
  <li> <a href="https://lists.w3.org/Archives/Public/public-low-vision-a11y-tf/2016Sep/0056.html">Line Length - Full Text Integration</a> - Wayne Dick, 4 September 2016 </li>
</ul>
<h3>GitHub</h3>
<ul>
  <li><a href="https://github.com/w3c/low-vision-SC/issues/13"> Line Length (User Need 2.3.2) LVTF GitHub SC Issue #13 </a></li>
  <li><a href="https://github.com/w3c/low-vision-SC/issues/6"> WCAG 1.4.8 item 2 (80 characters) LVTF GitHub SC Issue #6</a></li>
</ul>
<h3>Resolutions</h3>
<ul>
  <li> <a href="https://www.w3.org/2016/11/17-lvtf-minutes.html#resolution04">Ready for WCAG</a>. - 17 November 2016 </li>
</ul>
<h3>Minutes</h3>
<ul>
  <li> <a href="https://www.w3.org/2016/11/17-lvtf-minutes.html#item02">17 November 2016 LVTF Minutes</a> </li>
  <li> <a href="https://www.w3.org/2016/11/10-lvtf-minutes.html#item03">10 November 2016 LVTF Minutes</a> </li>
</ul>
<h3>Wiki Pages</h3>
<ul>
  <li> <a href="https://www.w3.org/WAI/GL/low-vision-a11y-tf/wiki/Talk:Line_Length">Discussion page for this Line Length SC</a> </li>
</ul>

**Comment by DavidMacDonald** [comment]
Need to define two-dimensional scrolling:

**Comment by DavidMacDonald** [comment]
First attempt to combine Issue #57 and #58 SC Text

Content can be viewed as a single column, with blocks of text in this column user adjustable to 25 characters without requiring two dimentional scrolling. except for the following:

* Data tables may retain their multi-column format with reflow.
* The user agent cannot reflow content containing interactive controls.
* If the user-agent fits the layout to the view port, and does not provide a means of re-flowing content, then two-dimensional scrolling is exempt.
* If the spatial layout of text is essential to its use, then two-dimensional scrolling is exempt.

I've got a side by side at [tinyurl.com/jmo9st4](tinyurl.com/jmo9st4) . See the overlapping issues tab at the bottom.

**Comment by DavidMacDonald** [comment]
Here's a rewrite: 

A mechanism is available to adjust blocks of text to a line length of 25 characters, with no two-dimensional scrolling required except where:
* The user-agent fits the layout to the view port, and does not provide a means of re-flowing content.
* The spatial layout of text is essential to its use.

**Comment by mbgower** [comment]
Continuing with my discussions on themes in the LVTF candidate SCs and their relationship to the existing 1.4.8 Visual Presentation, I'm going to discuss Reflow to a Single Column, Line Length and Resize Content here.

It seems to me there are 2 broad principles being advocated:
- no horizontal scrolling
- resize content to 400%

I don't understand the value of considering Reflow to a Single Column and Line Length separately. They seem highly dependent. @DavidMacDonald is already proposing merging the two. Can anyone explain what is gained by separating them?

**Comment by joshueoconnor** [comment]
I like the idea of merging this with #58 because it bypasses the mechanism issue as well as the proscriptive 25 characters issues.

**Comment by lauracarlson** [comment]
[January 10, 2017 Line Length Survey Results](https://www.w3.org/2002/09/wbs/35422/WCAG21_SCs_1/results)

**Comment by DavidMacDonald** [comment]
I think what is emerging is two amendments to the proposal
(1) Line length can be narrowed to around 50-60 characters rather than 25
(2) a baseline font size of 100% (no zoom) for the purposes of measuring whether the SC was met or not.

So the new proposal, addressing some of Greg Lowney's, Mike Pluke's comments and others could be something like:
=============
For all visual presentation of text, a mechanism is available to adjust the line length to a maximum of 50 characters without increasing the font in the user agent, and without requiring two-dimensional scrolling, except where:
(1) The user-agent provides no means of re-flowing content.
(2) The spatial layout of text is essential to its use.
==========

I also would not rule out integrating this (#57) into a 1.4.8 omnibus text SC (Issue #51 COGA), or merging with (#58) in future drafts, but I think for the first draft in 6 weeks this is sufficient.

**Comment by awkawk** [comment]
Thanks David. It seems that the internationalization question is still open. John has expressed concerns about using a specific number of characters, but if we do we should model after the 1.4.8 80/40 split to support CJK.

**Comment by DavidMacDonald** [comment]
> For all visual presentation of text, a mechanism is available to adjust the line length to a maximum of 50 characters (25 if CJK) without increasing the font size in the user agent, and without requiring two-dimensional scrolling, except where:
> *  The user-agent provides no means of re-flowing content.
> * The spatial layout of text is essential to its use.

**Comment by jnurthen** [comment]
This is going to be really hard to implement in a way that doesn't make the entire construct more difficult to use for many widgets. For example, if you wrap in a tree it is going to be really difficult to tell apart the wrapped line vs the next object in the tree. Same applies for menus.
Can this be limited to paragraphs of text which I think is its original aim?

**Comment by DavidMacDonald** [comment]
My instinct was "blocks of text" which is a familiar construct and I edited the SC. On the call some argued that blocks of text refer to more than 1 sentence, and there are times when there is less than a sentence that needs to be included. I personally prefer "blocks of text" but there are those who object. Here it is with "Blocks of Text".

> A mechanism is available to adjust the line length of all blocks of text to a maximum of 25 characters (13 if CJK) without increasing the font size in the user agent, and without requiring two-dimensional scrolling, except where:
> 
> The user-agent provides no means of re-flowing content.
> The spatial layout of the text is essential to its use.
> A line has a word which is longer than 25 (13 if CJK) characters.

**Comment by DavidMacDonald** [comment]
I just got off a meeting with the low vision task force and the consensus is to retire #57, this one on line length, and to focus on #58 reflow. So the LVTF is retiring this issue.

**Comment by DavidMacDonald** [comment]
I'll let @alastc jump in... it was his suggestion... @patrickhlauke

**Comment by alastc** [comment]
Shouldn't we move discussion onto #89?

**Comment by lseeman** [comment]
What is the status with this SC? Can it cover some of  #51 ?

**Comment by mbgower** [comment]
> What is the status with this SC? Can it cover some of #51 ?

@lseeman, see the post about 4 comments back from 25 days ago:
> I just got off a meeting with the low vision task force and the consensus is to retire #57, this one on line length, and to focus on #58 reflow. So the LVTF is retiring this issue.

**Comment by alastc** [comment]
@lseeman This one has been retired, but I'll comment on 51 about the overlap.

**Comment by allanj-uaag** [comment]
closed see #89
