### ISSUE TITLE
SC Device Sensors: Breaking Down the Scope

### ISSUE THREAD

**Issue by steverep** [w3c/wcag21#572]
I'm filing this issue to accompany pull request #378 and to provide a framework for discussing problems with the scope of the current Device Sensors SC.  For background, there were multiple objections to this SC surrounding too wide a scope and redundancy with 2.1.1 Keyboard, and these were temporarily waived in favor of the current editors' note.

My goal is to methodically break down the possibilities around input from various device sensors, and discuss when and how they do or do not disadvantage people with disabilities.  Here goes...

# Sensor Input
The first question to ask is whether or not the sensor is actively tied to a function which can be performed by the user, or is just passively providing data.

## Passive Data Input (No Functionality)
In many cases, sensors just provide data for an application as opposed to being used as a required part of a function.  Some examples might be:
- GPS coordinates being used to display my position on a map
- Magnetometer used to display the cardinal direction I'm facing
- Accelerometer used to estimate how many times I drop my phone in a month
- Optical sensor on wrist measuring heart rate
- Camera used to stream video of my surroundings for analysis
- Thermometer and barometer data correlated to my walking speed

Obviously the path to obtaining this input needs to conform in order to be accessible, but the sensor input itself creates no issue for people with disabilities as far as the authored content is concerned.  To the extent that a sensor used as passive data input might disadvantage PWDs, it is outside the scope of WCAG and would likely require device manufacturers to create accessibility.  For example, a person without writsts cannot wear a smart watch on their wrist.

I believe that as long as the SC continues to only talk about "functionality" (per the WCAG 2.0 definition), then this type of input is scoped out and this should be explained clearly in Understanding.  We should not discourage the use of sensors, but rather their misuse.

## Active User Input (Functionality)
When the sensor is used as part of actual user functionality, the question needs to be asked  about whether or not the operation of the sensor in that scenario disadvantages PWDs.  If there is no physical operation by the user required, i.e. the mere ownership of the device sensor constitutes operating it, then it cannot be a disadvantage.

### No Physical User Operation Required
Examples I can think of in this category border on the absurd, but the lack of inaccessibility should be clear:
- GPS used to restrict an app only to certain countries
- Temperature used to only allow login at 60 degrees or below
- Barometer used to unlock content only when you are skydiving

The solution is that the SC needs to talk about the operational restrictions rather than lumping in the myriad of potential sensors as all being inaccessible.

### Physical User Operation Required
My current proposal scopes the SC down to physical operation by talking about functionality  operated by device or user motion and renaming the SC to "Motion Actuation".  This cuts straight to the point  without too wide a scope or trying to be a catch all in my opinion.  Examples of such functionality would be:
- Gyroscope responds to tilting to turn a page in a document
- Accelerometer responds to shaking to clear a text entry field
- Proximity IR sensor responds to a hand wave to go to the next step in a process
- Speed (from GPS coordinates over time) required to  perform an unrelated 
- Camera is only option for a profile picture

One issue with scoping to user or device motion though is that in reality all input devices require some level of motion, even when they are assistive technologies.  For example, operating keyboards, mice, touch screens, mouth movement using speech recognition, and eye gaze all require motion.

*To be continued in next comment...*

**Comment by awkawk** [comment]
Thanks for the explanation Steve. Closing as this is provided as input into the current draft.

**Comment by steverep** [comment]
@awkawk, I'm confused by the closure - the draft still has the language that was objected to.  I'd prefer to keep this open until the normative text changes to resolve the scope issue.

**Comment by steverep** [comment]
This can now be closed after the merge of #378
