### ISSUE TITLE
Adapting text: Ensure end users get the results with only changing 4 items in CSS

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/wcag21#577]
Capturing my concern as we closed out the call.

In responding to a comment #409 requesting we fix the definition of adapting text, we reworded the SC to remove adapt

> If the technologies being used allow the user agent to change text style properties, the following can be achieved with no loss of essential content or functionality:  
* the 4 things 

The problem with this wording is that​ an author could get a pass on this if the only way to achieve the 4 things was to change box properties and a bunch of other CSS tweaks in addition to those 4 things.​ I propose instead we go back to the previous language which was painfully and carefully crafted, and swap out "adapt" for "change"

> If the technologies being used allow the user agent to change text style properties, then no loss of essential content or functionality occurs by changing all of the following:
* the 4 things

​It is only 10 characters longer than the new proposal, and it preserves the word ALL, as well as ensuring the end user would only have to over ride those 4 text properties, and wouldn't be required to write a bunch of other CSS like box padding, margins etc...​

**Comment by awkawk** [comment]
Thank you, David for pointing out that the language proposed at the November 13 meeting would introduce a loophole.

As discussed on the Working Group list between November 13-20, 2017, the SC has been reworded to close that loophole.
