### ISSUE TITLE
 For purpose of controls, more terms are needed

### ISSUE THREAD

**Issue by User1stAmihai** [w3c/wcag21#586]
Hello, 
Based on our research, we learned that some users are interested in the ability to control the screen. We collected this information from 3 of our customers.  Having to participate in the COGA group, I believe that there is a clear need for more terms to be added. For those 3 customers, we are looking into the means to implement it over their websites.
We believe the following terms should be in used for 
A>	links list (https://www.w3.org/TR/WCAG21/#dfn-conventional-links): Top, Bottom, Start, End, Related (gallery of products, one of the products - may have a related products), Page map, New, down (scroll down), up (scroll up)
B>	Buttons and controls list (https://www.w3.org/TR/WCAG21/#dfn-conventional-buttons-or-controls) : Call (for any voice communication needs), Connect (for any voice communication needs), Release (similar to Esc), Mute (for any voice communication needs), Settings (general), Comment (general), Collapse (verse expand), Open popup, Open window, Download, Upload, Share, drag (in case the button needs to be dragged right or left top or bottom), next step (1/4).

Thank you

**Comment by joshueoconnor** [comment]
Looping in @lseeman so she is aware of this, thanks.

**Comment by joshueoconnor** [comment]
@johnfoliot With your input into the personalisation/metadata work - Would you have anything to add?

**Comment by awkawk** [comment]
(Official WG response)
Unfortunately, due to issues around the implementation and feasibility the purposes related to links and buttons have been removed, but the purposes related to form inputs were retained and expanded. We do intend to expand on this work in future, and would like to defer this comment for future work.
