### ISSUE TITLE
Understanding document Zoom Content / Reflow Content

### ISSUE THREAD

**Issue by kerstinp** [w3c/wcag21#589]
I've read through - it seems latest - version of the [Understanding for SC Zoom Content](https://rawgit.com/w3c/wcag21/zoom-content/understanding/21/zoom-content.html) which seems now is Reflow Content and want to comment on these two things:

"A PDF is created that conforms to PDF/Universal Accessibility (ISO 14289), the content can be reflowed and zoomed in to make reading possible for someone with low-vision.

And a planned Sufficient Technique

"@@ New: Using PDF/UA when creating PDFs."

I know that neither an Understanding nor a Sufficient Technique is normative but I see many problems cause this may likely bring in a normative PDF/UA-Conformance through the back door.

There are several requirements in PDF/UA-1 which have no impact on reflow according to PDF/UA-1. Just two of them are:

PDF/UA-1 requires for every link a contents key – even when the link text itself is perfect and the purpose of the link is clear to everyone. Mentioning PDF/UA-1 in the Understanding and having a Sufficient Technique "Using PDF/UA" could have the impact that this overrides SC 2.4.4 and 2.4.9 WCAG 2.0 while the contents key itself has no impact on Zoom/Reflow.

PDF/UA-1 requires a PDF/UA-Identifier. What is the specific impact of the PDF/UA-Identifier on Zoom/Reflow? I would say that there is none. But it would bring a lot of other problems. Even when just a Sufficient Technique: Not one single PDF which was made by Saving as PDF in Word will pass a Sufficient Technique "Using PDF/UA". The Identifier must be manually attached or one has to buy a software.

I have other concerns too:

Of course until now in the Understanding is just the title. So it may be a bit early to something. Can "Using PDF/UA when creating PDFs" be a sufficient technique? Is it possible that a ISO-Standard in whole can function as a Sufficient Technique?

How will a testing procedure look like? One can check those requirements which are automatically testable for example with the Commonlook Checker or with PAC 2.0. But the results may differ. Which testing tool would be THE testing tool for a Sufficient Technique "Using PDF/UA"? 

The Commonlook Checker has several testing options. One of them is a check for WCAG 2.0 and a another one checks PDF/UA-1. The results differ regularely. Would a Sufficient Technique "Using PDF/UA" not mean that instead of using the testing option WCAG 2.0 the testing option PDF/UA must be used and would not this have the effect of overriding WCAG 2.0?

Which user agent would be part of a testing procedure of an SC "Using PDF/UA-1"? 

In the moment one can conform nicely with WCAG 2.0 AA with a lot of documents created by "Save as PDF" in Word without any additional software. But not one single PDF which was created in this way conforms with PDF/UA-1 without additional manual work or by using additional software which are not free of charge. The reason is not only the PDF/UA-Identifier.

The technique PDF4 of WCAG 2.0 says: "Hiding decorative images with the Artifact tag in PDF documents". It is a Sufficient Techniqe for WCAG 2.0 but it is not a failure, when not for example paths are not defined as artifacts. PDF/UA-1 requires the Artifact tag for decorative images otherwise it is a failure. Would mentioning PDF/UA in the Understanding and as sufficient technique not mean that this would override PDF4? So something which is in WCAG 2.0 just a sufficient technique would be a failure in WCAG 2.1 when you don't do it, or? And it must also be tested if not hiding decorative image by using the Artifact tag has a real impact on Zoom/Reflow Content in (which?) user agent. In case there is no impact in one way or the other it would be another reason why PDF/UA-Conformance should not become a Sufficient Technique and should also not mentioned.

I appreciate that Adobe reflow seems to be out, which must be made very clear! But I don't think that now relying on PDF/UA-Conformance is a proper way. And I think that every required reflow for PDF will in minimum override SC 1.4.4.

**Comment by awkawk** [comment]
(Official WG response)
Thank you for your comment. We understand your concern about PDF/UA including requirements that are unrelated to reflow in a PDF document. The possible technique has not been drafted or approved, so we appreciate your feedback. It is important to point out that techniques are not required, but they are sufficient, so if a PDF/UA conforming document would always meet the reflow requirements, we could make a technique that clarified this connection, but we would undoubtedly include other techniques as well that would allow a PDF to meet the reflow SC without conforming to PDF/UA.

Of course, as you indicate, to include a PDF/UA-related technique we would need to consider the testing questions you mention and more.

We have work to do to ensure that the understanding and techniques documents are up to date and accurate, but it is worth mentioning that the plan moving forward is that the non-normative techniques and understanding documents will be able to be updated continuously in the event that new information or errors are identified.
