### ISSUE TITLE
Pointer

### ISSUE THREAD

**Issue by kwahlbin** [w3c/wcag21#59]
# Current versions of SC and Definitions
- [SC for viewing](https://rawgit.com/w3c/wcag21/pointer_ISSUE-59/guidelines/sc/21/pointer.html) | [SC for editing](https://github.com/w3c/wcag21/blob/pointer_ISSUE-59/guidelines/sc/21/pointer.html)
- [Pointer inputs definition for viewing](https://rawgit.com/w3c/wcag21/pointer_ISSUE-59/guidelines/terms/21/pointer-input.html) | [Pointer inputs definition for editing](https://github.com/w3c/wcag21/blob/pointer_ISSUE-59/guidelines/terms/21/pointer-input.html)
- [SC in full draft guideline](https://rawgit.com/w3c/wcag21/pointer_ISSUE-59/guidelines/#pointer)

# SC Shortname

Pointer

# SC Text

All functionality can be operated with pointer inputs. If functionality requires text entry, a mechanism is available for users to enter the text using pointer inputs (for instance, through an on-screen keyboard).

Note 1: in most cases, the on-screen keyboard will already be provided by the operating system or user agent.

# Suggestion for Priority Level (A/AA/AAA)

Level A

# Related Glossary additions or changes

Pointer inputs: input devices that can target a specific coordinate (or set of coordinates) on a screen, such as a mouse, pen, or touch contact. (modified slightly from https://w3c.github.io/pointerevents/#glossary)

# What Principle and Guideline the SC falls within.

Principle 2, *new* Guideline "Pointer Accessible"

# Description

While it is important for authors to ensure that content/functionality is operable using a keyboard, there are situations in which a user may not be able to operate a keyboard or keyboard-like interface. For instance, on mobile/tablet devices, the primary input mechanism is a touchscreen. While these devices do provide on-screen keyboards, generally these keyboards are only available to the user when focus is in an interface component that expects keyboard entry (such as a text input field). Moreover, these on-screen keyboards usually lack many of the keys available on regular physical keyboards (such as cursor keys, TAB, ESC).

If content is designed with the expectation that users can, at any given point, press a particular key or key combination, it will not be possible to operate the content in these situations. Examples include

* Pop-up windows that can only be closed / dismissed via the ESC key
* Custom text input fields, not coded as standard `<input>` elements. Applications may not automatically trigger the display of an on-screen virtual keyboard
* Situations where important functionality may only be displayed when an element is focused via the keyboard (by listening for the TAB/SHIFT+TAB key combination)

As such, authors must ensure that all content and functionality can also be operated using only a pointer input.

Editorial note: WCAG 2.0 currently takes it for granted that content will be designed/built to work with pointer inputs (generally, mouse). This is not always a given, and for completeness should be added. Needs cautious wording to ensure we're not requiring authors to build their own on-screen keyboards etc, probably through use of "a mechanism is available" language which would then cover situations where the OS/UA themselves provide on-screen keyboards (see discussion https://lists.w3.org/Archives/Public/public-mobile-a11y-tf/2016Jul/0014.html)

# Benefits

Making sure that all functionality can be used via pointer input (mouse, stylus, touch) helps users of devices without keyboard. When applications support keyboard commands for specific functions, this success criterion ensures that there are equivalent means to activate these functions via pointer input.

# Testability

Check if all functions designed for keyboard input (e.g. functions detecting specific key presses) can also be activated via pointer (this is usually the case if device independent event handler like `onclick`, `onfocus` or `onblur` have been used, rather than `onkeypress`, `onkeydown`, `onkeyup`).

# Techniques

* Use device independent input events 
* If needed, double up event handlers to also include touch events/pointer events
* Use standard HTML form controls, rather than custom-built inputs
* could be a variant of "SCR35: Making actions keyboard accessible by using the onclick event of anchors and buttons" - 
(suggestion: could be reworked as "SCR35: Making actions both keyboard and pointer accessible by using the onclick event of anchors and buttons")

**Comment by alastc** [comment]
From reading the SC text, I got very hung up on the onscreen keyboard aspect.

Then reading the description, I see the need for this ("for completeness") to provide the reverse of ensuring keyboard access. 

Does the SC text really need to provide the onscreen keyboard as an example? In most cases it is probably having a button (e.g. the close-button for a pop-over), putting the onscreen keyboard in the SC text provides a large red-herring! I think it would better fit in the understanding documentation as an edge case (from a content point of view).

**Comment by patrickhlauke** [comment]
Having discussed this SC further with colleagues, I'm now almost convinced that perhaps this is not necessary. The main use case / failure I had in mind were sites/apps that use custom keyboard handling (e.g. listening to `keydown`/`keyup` to trigger actions), and how these would not work for users that only have a touchscreen interface WITHOUT the ability to raise an on-screen keyboard arbitrarily (e.g. iPhone). While true that in this case the site/app would not be operable/usable, this affects all users, not just those with potential disabilities.

My gut still tells me that if we've got a "must work just with keyboard", there should also be a "must work just with a pointer" to match, but realistically it feels like this may go beyond addressing situations that disproportionately affect PWDs.

**Comment by awkawk** [comment]
I like the brevity of "All functionality can be operated with pointer inputs", but do which that we had more use cases for why this causes problems for PWD. For a site which doesn't pop up the keyboard for a custom text input, is that just a "this site not built for mobile" issue?

**Comment by patrickhlauke** [comment]
> For a site which doesn't pop up the keyboard for a custom text input, is that just a "this site not built for mobile" issue?

well, it gives preference to users with an actual keyboard. but in the wild, it would impact every user on a touchscreen, or on some device that only has a mouse/trackball and no on-screen keyboard that can be raised arbitrarily...so not PWDs exclusively, but more of a "this site won't work for mobile etc users" yes

**Comment by DavidMacDonald** [comment]
I support Patrick's proposal to retire this.

**Comment by kwahlbin** [comment]
I am also ok with retiring this.  We may want to look at this again for Silver.

**Comment by patrickhlauke** [comment]
> We may want to look at this again for Silver.

agreed, together with a more holistic approach to user input, including the SC we retired about ensuring users can seamlessly switch between input modalities (e.g. go from mouse to touchscreen in the same session/interaction)

**Comment by mbgower** [comment]
+1 for retire.

**Comment by goodwitch** [comment]
+1 to defer to Silver

**Comment by kwahlbin** [comment]
Based on the WCAG WG call on 1/31, this will remain open.  We should suggest changes for a more holistic approach for consideration.

**Comment by mbgower** [comment]
As per the brief discussion in #60 Target Size, my understanding is that failure to provide an equivalent for right-click (i.e., context menus) and hover (i.e., display of Title information) for touch interfaces would fail this SC.
This SC still seems to me to be at least partially a user agent matter; I'm not sure what we can or should expect an author to do if a mobile browser doesn't support a touch-and-hold action to reveal context menu items or title content.

**Comment by patrickhlauke** [comment]
> I'm not sure what we can or should expect an author to do if a mobile browser doesn't support a touch-and-hold action to reveal context menu items or title content.

Then authors should not rely on these sorts of patterns and provide at least an alternative that fulfills the same purpose.

**Comment by michael-n-cooper** [comment]
Being covered under #64
