### ISSUE TITLE
Exit criteria technology-specific?

### ISSUE THREAD

**Issue by kerstinp** [w3c/wcag21#598]
In case [this ](https://www.w3.org/WAI/GL/wiki/WCAG_2.1_CR_Exit_Criteria) is the latest version of the exit criteria it seems that especially the first one is technology-specific or would that include PDF? 

In my comments I raised some issues for SC 1.4.10 and 1.4.13. Without a clarification which reflow is relevant for 1.4.10 it is unclear what "at least two implementations (exist)" means.

**Comment by joshueoconnor** [comment]
@kerstinp can you please clarify as I don't see how the Exit Criteria are technology specific? Thanks

**Comment by kerstinp** [comment]
Hi @joshueoconnor, the first bullet point speaks about "Web sites". Therefore it seems to be unclear wether this includes PDF or not, Because a PDF is not a "Web _site_". In case also 5 PDF will be tested, I think this should be mentioned so that it is documented for the whole WCAG21-procedure. Or?

**Comment by awkawk** [comment]
(Official WG comment)
Thank you for the comment. We intend to include PDF documents in the implementations for review. PDF documents can satisfy the WCAG definition for "web page", which is: "a non-embedded resource obtained from a single URI using HTTP plus any other resources that are used in the rendering or intended to be rendered together with it by a user agent". This is the same reasoning used to include techniques for PDF for WCAG 2.0 in the past, and we will be looking to offer PDF techniques for WCAG 2.1 Success Criteria as well.
