### ISSUE TITLE
Success Criterion 2.5.2 Pointer Cancellation  [Trace]

### ISSUE THREAD

**Issue by GreggVan** [w3c/wcag21#603]
Was reviwing the wrong version of the DOC -- so I am deleting my comment.

**Comment by steverep** [comment]
Are you purposely trying to substitute in the glossary definitions and expect the grammar to be perfect?

**Comment by GreggVan** [comment]
No
I was just quoting from the Editors draft at 
https://rawgit.com/w3c/wcag21/master/guidelines/index.html?defs#pointer-cancellation <https://rawgit.com/w3c/wcag21/master/guidelines/index.html?defs#pointer-cancellation>

oh my — is this a special version that substitutes all of the definitions in for the text? 

No wonder these are so wordy. 


PS - you should ALWAYS be able to substitute the definition for the term and have the sentence make sense for good definitions. 

But no - I wasn’t doing that — I was looking at the draft that does this evidently.  (or is there a switch that turns this on and off?)

**Comment by steverep** [comment]
You clearly have Michael Cooper's substitution tool still active.  I pointed you to the raw version, but you can also see the latest editor's draft here: https://w3c.github.io/wcag21/guidelines/

Note that a new working draft is also scheduled to be published shortly, so I'd suggest holding comments until then.

**Comment by jnurthen** [comment]
It looks like you add ?refs at the end of the URL (before the # fragment) to get this.
This one has the definitions inline:
https://rawgit.com/w3c/wcag21/master/guidelines/index.html?defs#pointer-cancellation
This one does not:
https://rawgit.com/w3c/wcag21/master/guidelines/index.html#pointer-cancellation

**Comment by GreggVan** [comment]
I see I was looking at the wrong version of the WCAG 2.1    

so I am deleting this comment issue
