### ISSUE TITLE
Success Criterion 2.2.6 Accessible Authentication§

### ISSUE THREAD

**Issue by GreggVan** [w3c/wcag21#608]
> - alternative essential steps, which do not rely upon recalling or transcribing information
> - an authentication-credentials reset process, which does not rely upon recalling or transcribing information

Wrong use of Which.  which is used for non restrictive phrases that can be dropped without changing the meaning of the sentence (just the information conveyed). 

WCAG is a standard, which is long. 

in the above requirements -- the phrase at the end is not  informative -- but is a part of the requirement.    These need to be changed to THAT.

> - alternative essential steps that do not rely upon recalling or transcribing information
> - an authentication-credentials reset process that does not rely upon recalling or transcribing information

(SEE ALSO following issue which is a global comment on fixing WHICH and THAT -- to make the document read (and mean) what we intended.

**Comment by awkawk** [comment]
WG Response: Thank you for your comment. We are closing this issue as it is redundant to issue #609.
