### ISSUE TITLE
Understanding {Shortname}

### ISSUE THREAD

**Issue by ChrisLoiselle** [w3c/wcag21#613]
When following the understanding link on https://www.w3.org/TR/WCAG21/ to review the detail of the understanding documentation related to the new criteria, the H1 sometimes appears as "Understanding {Shortname}" rather than pulling in the associated name of the new criteria , see https://www.w3.org/WAI/WCAG21/Understanding/21/identify-common-purpose.html for an example. 

This also happens on:

https://www.w3.org/WAI/WCAG21/Understanding/21/contextual-information.html https://www.w3.org/WAI/WCAG21/Understanding/21/content-on-hover-or-focus.html https://www.w3.org/WAI/WCAG21/Understanding/21/accessible-authentication.html  https://www.w3.org/WAI/WCAG21/Understanding/21/timeouts.html  https://www.w3.org/WAI/WCAG21/Understanding/21/animation-from-interactions.html https://www.w3.org/WAI/WCAG21/Understanding/21/pointer-gestures.html  https://www.w3.org/WAI/WCAG21/Understanding/21/target-size.html  https://www.w3.org/WAI/WCAG21/Understanding/21/target-size-enhanced.html https://www.w3.org/WAI/WCAG21/Understanding/21/concurrent-input-mechanisms.html  https://www.w3.org/WAI/WCAG21/Understanding/21/orientation.html

Also of note: The detail pages mentioned above also have template based pages for understanding rather than going into detail of the understanding document for each criteria.  Is this to be pushed live at a later date?

**Comment by awkawk** [comment]
Thanks for the comment. The non-normative understanding content is lagging behind the spec itself, and in these cases the understanding documents are not yet completed. We will be updating these in the coming days.
