### ISSUE TITLE
Success Criterion 1.4.10 Reflow

### ISSUE THREAD

**Issue by ChrisLoiselle** [w3c/wcag21#614]
When following the understanding link for reflow,  and arriving here, https://www.w3.org/WAI/WCAG21/Understanding/21/reflow.html  , the H1 is listed as Understanding Zoom Content. I apologize for not knowing this, but was this done on purpose? I understand that users of document may more clearly understand terminology of Zoom Content vs. the word reflow, however wanted this to be consistent on the name of the Success Criterion and the Understanding Detail page.

**Comment by awkawk** [comment]
Thanks for the comment. This is an editorial oversight that we have now fixed.
