### ISSUE TITLE
Success Criterion 2.6.1 Motion Actuation

### ISSUE THREAD

**Issue by ChrisLoiselle** [w3c/wcag21#615]
When following the detail link for understanding Motion Actuation, https://www.w3.org/WAI/WCAG21/Understanding/21/motion-actuation.html, the user is brought to a page which has a H1 of Understanding Device Sensor. I understand that the user may more clearly understand Device sensor vs. Motion Actuation, however want to make sure this is consistent in terms of the detail page and Motion Actuation SC.

**Comment by awkawk** [comment]
Thank you for the comment. We have updated the H1 to match the SC title.
