### ISSUE TITLE
Typos and things

### ISSUE THREAD

**Issue by StommePoes** [w3c/wcag21#618]
On https://www.w3.org/TR/2017/WD-WCAG21-20171207/
Duplicate texts: "Please create a new issue for each comment; *do not add comments your comments* to existing issues."

On https://www.w3.org/TR/2017/WD-WCAG21-20171207/#x7-2-common-input-control-purposes
Duplicate texts: "Credit Card - Inputs used to handle information about credit card payments" twice around Name on Credit Card

Additionally Name on Credit Card is not matching the naming scheme of the others (could be "Credit Card Holder Name" for example).

On https://www.w3.org/TR/2017/WD-WCAG21-20171207/#accessible-authentication
US-centric text?
"Authentication process involves basic personal identification information to which the user has easy access, such as name, address, email address and identification *or social security number*."
Are we expecting a majority of readers to be US-based? Most other countries have only an identification number or for something special that de facto does the same thing (pension numbers, insurance numbers, taxation numbers) but few if any others have one for "social security", a US program.  "National identification number" should, honestly, cover everything.

Additionally, are the links for (example) "Understanding [x]" supposed to work or no? Currently they all seem to link to a template page (example https://www.w3.org/WAI/WCAG21/Understanding/21/accessible-authentication.html) yet I saw a real-ish page from Alastair C so maybe the links are just bad.

I'll tack on if I find more typos/text things.

**Comment by joshueoconnor** [comment]
Good catches @StommePoes - Understanding content etc will be updated etc as we go. First two typos etc fixed in current live branch, regarding matching of naming scheme etc for card, noted and I'll follow up with that - as well as US centric language.

**Comment by awkawk** [comment]
(Official WG response):
Thank you for your comment. The first two items in your comment are editorial and have been changed as suggested (see https://github.com/w3c/wcag21/pull/643). Regarding the comment about the use of "social Security" we will change the SC text to use your suggestion of "national identification number" as follows:

"Authentication process involves basic personal identification information to which the user has easy access, such as name, address, email address, and National identification number."

**Comment by awkawk** [comment]
Realized when I went to merge the change that the WG had not achieved consensus on other parts of the authentication SC, so the SC was removed from the editor's draft. Marking this as defer so the WG will use the latest language when reconsidering the SC in a future round.
