### ISSUE TITLE
Success Criterion 2.6.1 Motion Actuation: Probably need to establish scale of motion within the understanding documentation

### ISSUE THREAD

**Issue by SuzanneTaylor** [w3c/wcag21#619]
I assume if your device is required to be inside a relatively large geographic **location**, this SC doesn't apply. So, for example, if a device **location** is used to determine which state, street or building you are in, the SC is probably not meant to apply. In other words, you don't need to provide controls to let the user say they are in a different building or on a different street. 

But, if device location (better term is **position** in this case) is used related to sub-locations within a room, a park, a field, or even city, then it should apply. For example, if users have to place their phones into a virtual fountain fill something with virtual water, there is an option, **once the fountain is found**, to use a different method to fill something with virtual water, such as just pointing the phone in the direction of the fountain and activating a button, once the user is in range.

**Comment by joshueoconnor** [comment]
Interesting points @SuzzaneTaylor - would you be interested in helping do draft same?

**Comment by SuzanneTaylor** [comment]
Yes, I can help with that.

**Comment by joshueoconnor** [comment]
@suzzanetaylor - thanks, thats great.

**Comment by joshueoconnor** [comment]
@detlevhfischer  will be in touch you about next steps. Thanks @SuzanneTaylor. It looks like this comment can shortly be closed.

**Comment by SuzanneTaylor** [comment]
sounds good @detlevhfischer - just let me know when/where is the best place/time to write the text so that I can match it to the rest of the writing

**Comment by awkawk** [comment]
@SuzanneTaylor (Official WG response):
Thank you for your suggestion. We agree that for interactions that include activation by positioning the device in a particular geographic location (your virtual fountain example), the requirement to provide alternative means of input does not apply. However, pointing a phone in the direction of a virtual location would still be a problem for a user with a motor impairment or a mounted device, so this would not negate the need for keyboard/pointer-accessible alternative modes of input. We believe the provision of alternative accommodations like the one you suggest could be included in a future SC focused on the use scenario of AR / Vr applications, and we are marking this issue as "defer" to ensure that it is reviewed at an appropriate time.

**Comment by SuzanneTaylor** [comment]
Thanks for considering these points. Actually, this SC covers AR/VR just fine, in my opinion. The suggestion was just to clarify in the understanding document, that the SC doesn't apply to geographic location (finding the fountain from my example in the city, or a requirement to be inside a museum or amusement park) but does apply to motion within the geographic location (any actions needed to actually use the virtual fountain, or to interact with museum displays or amusement park features)
