### ISSUE TITLE
TOC does not look like links

### ISSUE THREAD

**Issue by MichellanneLi** [w3c/wcag21#627]
This is more about the design of the guidelines than the content, but I did not realize that the table of contents was a nav because there are no visual indicators that the titles of sections are links.

**Comment by awkawk** [comment]
Assigning @michael-n-cooper - as far as I know this is part of the template that we need to use. The best we can do may be to pass the information on to the owners of the template. Michael?

**Comment by michael-n-cooper** [comment]
Yes, this is part of the design required for W3C publications. Issues on that design can be filed at https://github.com/w3c/tr-design/issues.
