### ISSUE TITLE
Success Criterion 1.4.11 Graphics Contrast

### ISSUE THREAD

**Issue by MichellanneLi** [w3c/wcag21#628]
As a web designer, I think this criteria meets a gap in 2.0 and is overall well considered. However, I think additional examples in the Understanding document would be helpful, such as the flower icon.

**Comment by alastc** [comment]
HI @MichellanneLi,

Totally agree, it is in my to-do list for asap!

Is there a particular type of graphic you'd particularly be interested in seeing done?

Thanks,

-Alastair

**Comment by awkawk** [comment]
Thank you for the comment. We are marking this with the "implementation follow up" label to keep track of the suggestion for improvements to the understanding documents.
