### ISSUE TITLE
Success Criterion 2.5.3 Target Size

### ISSUE THREAD

**Issue by MichellanneLi** [w3c/wcag21#631]
How did the team land on 44 x 22 CSS pixels? Has user research been done to determine the ideal target size? For such a strict criteria, I would like to know more about the logic behind it.

**Comment by awkawk** [comment]
(Official WG Response)
Thank you for your question. This Success Criteria was developed in the Mobile Task Force with the primary purpose to ensure that pointer targets are large enough for people with dexterity disabilities to hit the touch target in mobile, with the additional benefit of providing larger click targets for mouse users on desktop who have dexterity disabilities. This was not covered in WCAG 2.0. The task force looked at a number of studies and other standards, such as the BBC Mobile Guidelines. One study demonstrated that some people with dexterity disabilities needed a target size of 100px by 100px. So we knew that we could only provide a minimum value and encourage the author to make targets as large as possible. The idea of the minimum size requirement in the success criteria was to choose a value as large as possible without negatively impacting design. Google mobile developer guidelines recommended 48px by 48px.

We took Apple's recommendation and amended one dimension in response to comments that 44px by 44px was too large for many interfaces, especially vertical lists of text links, and we added a list of exceptions, including specifying a smaller dimension (22px) for some situations. Unfortunately, the SC language was not able to be agreed on within the Working Group, and as a result the AA version of this SC has been removed from the draft.
