### ISSUE TITLE
Typo (two colons) in Success Criterion 1.4.11 Graphics Contrast

### ISSUE THREAD

**Issue by carmacleod** [w3c/wcag21#632]
The string "User Interface Components: " in https://w3c.github.io/wcag21/guidelines/#graphics-contrast
doesn't need the extra colon and space on the end, because there's an sc style that adds the colon:
```
.sc dt:after {
  content: ":";
}
...
<dt>User Interface Components: </dt>
```

**Comment by awkawk** [comment]
fixed: https://github.com/w3c/wcag21/commit/d836296b2e102c5e10eda3e9c8bafb78490daff1
Thanks.
