### ISSUE TITLE
single pointer definition

### ISSUE THREAD

**Issue by detlevhfischer** [w3c/wcag21#634]
Currently, the new definition term 'single pointer'
https://www.w3.org/TR/WCAG21/#dfn-single-pointer
is defined as:
> one point of contact with the screen

My concern is that this does not make it clear whether this means an untimed action on one point on the display (x/y coord), or whether it would also include long press and double click / double taptap.

@mbgower had concerns in an earlier comment that limiting 'single pointer' to just one untimed click or tap would be too restrictive, basically disallowing long press and double click which authors might want to port over to web apps from general software.
While the term 'untimed' has been removed in the latest SC language for 2.6.1 Pointer Gestures
https://www.w3.org/TR/WCAG21/#x2-5-1-pointer-gestures
it is now unclear what "can be operated with a single pointer" exactly means. Does it include long press / double click? Can we leave that to the Understanding doc or do we need to amend the definition of 'Single Pointer' and/or the text of 2.6.1 'Pointer Gestures' to clarify that?

**Comment by awkawk** [comment]
@steverep can we assign making a response to this for you?

**Comment by steverep** [comment]
The term "single pointer" needs to include single, double, triple, etc. clicks, long presses, and single point gestures, otherwise the most recent version of the [Pointer Cancellation SC](https://www.w3.org/TR/WCAG21/#pointer-cancellation) becomes largely worthless.  My interpretation of the definition was basically only an exclusion for multiple points of contact.

I presume this is the desired definition for both SC, and I agree it could use some additional clarity.

**Comment by detlevhfischer** [comment]
I have created a pull request for an updated single pointer definition: https://github.com/w3c/wcag21/pull/664
@steverep: With reference to the comment in issue #663 by @mapluke, I think 'single pointer' would not just exclude multi-point, but also path based-gestures (and the SC text of 2.5.1 Pointer Gestures should be extended to make this clear), in other words, single pointer activation happens at the same screen position.

**Comment by awkawk** [comment]
(Official WG Response)
Thanks for the comment. We agree that the definition needs to be clarified. We are changing the definition to:

"Pointer input that operates with one point of contact with the screen, including single taps and clicks, double-taps and clicks, long presses, and path-based gestures"
