### ISSUE TITLE
Mentioning RFC 2119 keywords on the body text

### ISSUE THREAD

**Issue by momdo** [w3c/wcag21#637]
Most of specs not only refer RFC 2119 as normative reference but also state the RFC 2119 keywords like this:

> The key words MAY, MUST, MUST NOT, SHOULD, and SHOULD NOT are to be interpreted as described in [RFC2119].
https://www.w3.org/TR/2017/REC-wai-aria-1.1-20171214/#conformance

I think that WCAG 2.1 needs to do so.

**Comment by awkawk** [comment]
Thank you for the comment. We will add the notice as done in ARIA. Please note that these are the correct interpretations for these terms even without this sentence since the document indicates that it is governed by the process document and the process document makes this same claim.

**Comment by awkawk** [comment]
Changes implemented - see at http://rawgit.com/w3c/wcag21/master/guidelines/index.html#conformance
