### ISSUE TITLE
Typo (shortc) in Understanding Character-key Shortcuts

### ISSUE THREAD

**Issue by carmacleod** [w3c/wcag21#638]
[Understanding Character-key Shortcuts](https://w3c.github.io/wcag21/understanding/21/character-key-shortcuts.html)
The following sentence seems to have been truncated:
> Those users would be able to to avoid problematic single character shortcuts by turning off or modifying the shortc

Probably something like the following was intended:
> Those users would be able to to avoid problematic single character shortcuts by turning off or modifying the shortcuts to use at least one non-character key.

Or more simply:
> Those users would be able to to avoid problematic single character shortcuts by turning them off or modifying them to use at least one non-character key.

**Comment by awkawk** [comment]
Thanks, fixed: https://github.com/w3c/wcag21/commit/dbbe8341abc09727f666661cc9230da1717a46ef
