### ISSUE TITLE
working on  re-authentication

### ISSUE THREAD

**Issue by lseeman** [w3c/wcag21#639]
see current  wording: https://www.w3.org/WAI/GL/wiki/2.2.7_Revision#

or
re-authentication

 re-authentication processes  do not rely upon the user's ability to do any of the following:

memorize information; or
perform calculations, such as including correctly identifying and entering numbers and letters from a character string; or
reliably produce gestures; or
recognize characters presented on screen, and then enter them into an input field; or
speak; or
transcribe information.
Exceptions: 

Re-authentication process only relies on basic personal identification information to which the user has easy access, such as name, address, email address and national identification number.
This is not achievable due to governing statutory requirements.

comments - we lost the "speech" criteria, but at this point I do not remember why. I do not think speach signatures are included in 1.1.1 or captions etc as it is not a percivability  issue.

**Comment by awkawk** [comment]
This is not an issue, this is a work item. Please do this on a wiki page or in email, or anywhere other than in the issue database.

**Comment by mbgower** [comment]
Sorry, Andrew, this was my suggestion.
Folks, I've made a [wiki page](https://github.com/w3c/wcag21/wiki/Accessible-Authentication-discussion) for this

**Comment by mbgower** [comment]
Lisa, you may want to make a google doc on second thought, since there is no commenting facility on the wiki pages.

**Comment by awkawk** [comment]
No worries I just want to keep the issues list as clean as possible and worry that this type of activity might turn it into a workspace more than a comment receiving/responding space.
