### ISSUE TITLE
When vertical text mode, are SC 1.4.8/1.4.12 applicable as they are?

### ISSUE THREAD

**Issue by momdo** [w3c/wcag21#657]
On SC 1.4.8
https://www.w3.org/TR/2017/WD-WCAG21-20171207/#visual-presentation

> Width is no more than 80 characters or glyphs (40 if CJK).

On SC 1.4.12
https://www.w3.org/TR/2017/WD-WCAG21-20171207/#text-spacing

> Line height (line spacing) to at least 1.5 times the font size;
> Spacing underneath paragraphs to at least 2 times the font size;
> Letter spacing (tracking) to at least 0.12 times the font size;
> Word spacing to at least 0.16 times the font size.

It seems me that these sentences consider <a href="https://www.w3.org/TR/jlreq/#term.horizontal-writing-mode">horizontal writing mode</a> implicitly. If Web page is <a href="https://www.w3.org/TR/jlreq/#term.vertical-writing-mode">vertical writing mode</a>, How should we interpret SC 1.4.8/1.4.12?

In vertical writing mode, is it enough to just change the height and width?
For example: "Height is no more than 80 characters or glyphs (40 if CJK)."

In some Japanese content, vertical writing mode is used. e.g.: https://tategaki.github.io/awards2016/

**Comment by awkawk** [comment]
@momdo (this is not an official WG response, just a follow-up question) - are line spacing, paragraph spacing, and letter and word spacing not concepts that are used in vertical writing mode content? I do see in the example you share that CSS rules that define line-height and spacing after the paragraph are used already, and letter spacing could be used for space between characters, but I understand that this might be more like word spacing at times.

It seems that we probably need to address this in the understanding document, but I'm interested in your thought and reactions to my question above to help the WG form a plan.  (cc @MakotoUeki for additional thoughts).

**Comment by momdo** [comment]
These concepts (line spacing, paragraph spacing, and letter and word spacing) exist regardless of writing mode, but word spacing is language specific. In my understanding, Japanese usually doesn't have word spacing except of <a href="https://www.w3.org/TR/jlreq/#japanese_and_western_mixed_text_composition">Japanese and Western mixed text composition</a> on typography (e.g. epub).

My question is whether these SCs are requiring to set the same value regardless of writing modes. It seems me that <a href="https://www.w3.org/WAI/WCAG21/Understanding/21/text-spacing.html">Understanding Text Spacing</a> consider only Western languages. Does the WG have any basis to positively endorse the values of these SCs (especially SC 1.4.12) in vertical writing mode?

**Comment by MakotoUeki** [comment]
I agree with @momdo that "Word spacing to at least 0.16 times the font size." is not applicable requirement for Japanese web content because we don't put white space between words in Japanese language for both horizontal and vertical mode. We should add exception for Japanese (maybe CJK?) to the "word spacing" requirement.

As to "the values of these SCs (especially SC 1.4.12) in vertical writing mode", we need to find research-based basis. I'm not sure whether such kind of research have been done. 

@momdo Do you have any information about this?

**Comment by momdo** [comment]
> Do you have any information about this?

I have no information in terms of research, but Advanced Publishing Laboratory might be interested in this issue.
@murata2makoto @imagedrive @kzakza Do you have any comment?

**Comment by alastc** [comment]
It does appear we need to put in an exception for CJK, that will resolve 3 issues on text-adaptation that I've noted in github.

For future, I'm quite curious about whether this:
>  we don't put white space between words in Japanese language for both horizontal and vertical mode

Is from a writing convention, and whether there is some user-benefit from being able to space out Japanese characters. They appear more readable to me, except that I can't actually read them!

In any case we have no basis for the values chosen for CJK, so should remove the requirement for CJK until we do.

**Comment by awkawk** [comment]
How about adding:
Exception: Languages which do not typically make use of one or more of these text style properties in written text can conform using only the properties that are typically used.

That way we are covered for other languages that the WG isn't well-versed in.

**Comment by MakotoUeki** [comment]
> In any case we have no basis for the values chosen for CJK, so should remove the requirement for CJK until we do.

I agree with Alastair on this point. I'm not sure if we should include other languages like Arabic though. As to vertical text mode, we need to find basis for each value.

> Exception: Languages which do not typically make use of one or more of these text style properties in written text can conform using only the properties that are typically used.

I'm not sure if this exception address the vertical text mode as line/paragraph/letter spacing can be used.

**Comment by murata2makoto** [comment]
I am sorry for my late reply.  First of all, I think that we should invite the I18N WG for this discussion.  Richard, are you there?  @r12a

**Comment by alastc** [comment]
He has been involved over here: https://github.com/w3c/wcag21/issues/677#issuecomment-357805870

Mostly comes down to the sam issue I think.

**Comment by murata2makoto** [comment]
I notified this issue and #677 to the JLreq WG of the Keio APL.

**Comment by MakotoUeki** [comment]
@murata2makoto ,
Thank you very much for your help. I'm wondering if we have research-based basis for horizontal and vertical text written in Japanese language on this issue.

**Comment by murata2makoto** [comment]
@MakotoUeki There are some very interesting results by Kobayashi Jumpei.  They are available from [this page](https://researchmap.jp/jkbys/), although most of the papers are written in Japanese.

**Comment by MakotoUeki** [comment]
Hi @murata2makoto ,
Thank you very much for sharing this page. I'll dive into his papers.

**Comment by alastc** [comment]
There are two primary questions we're trying to work out, per language, but trying to generalise as much as possible:

1. Does changing the factors listed in the requirement (letter spacing, word spacing, paragraph spacing, line height) **change the meaning of the content**, or otherwise prevent understanding the content (in which case we should exclude either the factor, or the language).

2. Does changing those factors **help people with low vision** to read more easily. This is not necessarily the same as reading speed for the general population.

If the answer to 1 is no, and 2 is yes, it's fine as-is.

If the answer to 1 is yes, we need to exclude that language/script type and work out how to phrase what it is we are excluding, because CJK doesn't seem appropriate.

If the answer to 1 is yes and 2 is no (or unknown), I'm not sure of hte most appropriate approach, but it may well be to exclude that as well.

**Comment by MakotoUeki** [comment]
The answer to 1 is no, and 2 is yes for Japanese.

What I'm not sure is each value (1.5 times for line spacing, 2 times for paragraph spacing and 0.12 times for letter spacing) is valid for Japanese text (both horizontal and vertical mode). But I could say increasing each spacing would benefit Japanese users with low vision and dyslexia.

My feeling is that each value should be larger for Japanese text. So it might be enough as the minimum requirement as it is. I just can't find research-based basis for Japanese text yet.

**Comment by alastc** [comment]
Hi Makoto,

Thanks, good to know. We'll run into trouble with latin based languages if we increase it. I suggest more poking around for research (for the next version), perhaps we can create a values-list for different languages? E.g. have a default, but a look-up table that countries maintain themselves?
For next time...

**Comment by murata2makoto** [comment]
@alastc I think that we should not embed values tailored for particular languages in WGCA.   I propose to set up a registry of recommended values.  That registry should contain entries for different languages and culture.  Entries in the registry can be updated without updating WGCA.

**Comment by MakotoUeki** [comment]
I come up with an idea. It might be one of possible solutions to remove each value from SC text if possible. Each value for different languages can be set in Techniques docs.

For WCAG 2.0, we did the same kind of approach for SC 1.4.3.

https://www.w3.org/TR/2008/REC-WCAG20-20081211/#visual-audio-contrast-contrast

>**1.4.3 Contrast (Minimum):** The visual presentation of text and images of text has a contrast ratio of at least 4.5:1, except for the following: (Level AA)
>**Large Text**: Large-scale text and images of large-scale text have a contrast ratio of at least 3:1;

and the definition of "Large-scale"
https://www.w3.org/TR/2008/REC-WCAG20-20081211/#larger-scaledef

> **large scale (text)**
>with at least 18 point or 14 point bold or font size that would yield equivalent size for Chinese, Japanese and Korean (CJK) fonts

and there is "Note 5".

>Note 5: The 18 and 14 point sizes for roman texts are taken from the minimum size for large print (14pt) and the larger standard font size (18pt). For other fonts such as CJK languages, the "equivalent" sizes would be the minimum large print size used for those languages and the next larger standard large print size.

For Japanese standard (JIS X 8341-3), we set 22pt and 18pt for Japanese characters based on the same basis (standard large print sizes).

If we need to have a default in SC text, I can live with it as it is if we add the rationale for the other languages than latin based languages, and add Andrew's suggested exception to SC:
> Exception: Languages which do not typically make use of one or more of these text style properties in written text can conform using only the properties that are typically used.

**Comment by alastc** [comment]
Hi @MakotoUeki, good idea, but we do need to include default values in the SC text for testability.

I think the creation of values for spacing might be a bit more tricky than font size, but I'd be happy to try it.

**Comment by momdo** [comment]
@murata2makoto 
Regardless of sudden mention, thank you so much for replying to this issue. 
 
It seems to me that Kobayashi's papers don't show answer to this issue directly, but Stepped-line text layout method is interesting to me.

**Comment by awkawk** [comment]
(Official WG Response)
Thank you for your comment. These properties are defined in CSS and in typographical principals, and they adhere to the meaning used in CSS. We will modify the description for paragraph spacing to "spacing following paragraphs" instead of "spacing underneath paragraphs" to address the implicit western language bias in this item. We will also add the following exception to address cases such as in Japanese where word-spacing is not typically used.

Exception: Human languages and scripts which do not make use of one or more of these text style properties in written text can conform using only the properties that are used.

https://github.com/w3c/wcag21/pull/729
