### ISSUE TITLE
Glossary: viewport

### ISSUE THREAD

**Issue by momdo** [w3c/wcag21#658]
https://www.w3.org/TR/2017/WD-WCAG21-20171207/#dfn-viewport

The current definition is based on UAAG 1.0, but I feel that it need to be based on <a href="https://www.w3.org/TR/UAAG20/#def-viewport">UAAG 2.0</a> and <a href="https://www.w3.org/TR/css-device-adapt-1/#the-viewport">CSS Device Adaptation Module Level 1</a>.

**Comment by awkawk** [comment]
@momdo, this definition is from WCAG 2.0, and we are not modifying WCAG 2.0 SC, and that includes glossary terms that would affect the understanding of the SC text. I'm marking this very valid suggestion as "defer" to ensure that it gets reviewed for the next major update.
