### ISSUE TITLE
Ambiguous definition

### ISSUE THREAD

**Issue by jrpool** [w3c/wcag21#659]
This formulation is ambiguous and misleading: “letters of the alphabet including capitals, punctuation, numbers, and symbols”. “The alphabet” isn’t technically accurate, since there are multiple alphabets, not only one. The contents of the list are ambiguous. It may be a list of 4 items, whose first item is “letters of the alphabet including capitals”. Or it may be a list of 4 items, whose first item is “capitals”. In the latter case, the definition would be classifying punctuation, numbers, and symbols as letters of the alphabet. That would deviate from any other common or technical usage. It would be best to formulate the definition to eliminate this ambiguity. For example: “letters (including upper- and lower-case letters), punctuation, numbers, and symbols”. This issue relates to #386.

**Comment by awkawk** [comment]
(Official WG Response)
Thank you for the comment. We have re-written the criterion to incorporate your suggestion. The updated SC can be viewed at: http://rawgit.com/w3c/wcag21/master/guidelines/index.html#character-key-shortcuts
