### ISSUE TITLE
Pointer inputs with additional sensors

### ISSUE THREAD

**Issue by kwahlbin** [w3c/wcag21#66]
# Current versions of SC and Definitions

- [SC for viewing](https://rawgit.com/w3c/wcag21/pointer-inputs-with-additional-sensors_ISSUE-66/guidelines/sc/21/pointer-inputs-with-additional-sensors.html) | [SC for editing](https://github.com/w3c/wcag21/blob/pointer-inputs-with-additional-sensors_ISSUE-66/guidelines/sc/21/pointer-inputs-with-additional-sensors.html)
- [SC in full draft guideline](https://rawgit.com/w3c/wcag21/pointer-inputs-with-additional-sensors_ISSUE-66/guidelines/#pointer-inputs-with-additional-sensors)
- [Additional Pointer sensor information definition for viewing](https://rawgit.com/w3c/wcag21/pointer-inputs-with-additional-sensors_ISSUE-66/guidelines/terms/21/additional-pointer-sensor-information.html) | [Additional Pointer sensor information definition definition for editing](https://github.com/w3c/wcag21/blob/pointer-inputs-with-additional-sensors_ISSUE-66/guidelines/terms/21/additional-pointer-sensor-information.html)

# SC Shortname

Pointer inputs with additional sensors

# SC Text
All pointer functionality can be operated using screen coordinate information, without requiring additional pointer sensor information except when the underlying function requires input beyond x/y coordinates.

# Suggestion for Priority Level (A/AA/AAA)

Level AA

# Related Glossary additions or changes

Additional Pointer sensor information: pointer information beyond position, such as pointer pressure (for instance on pressure-sensitive touch screens), pointer tilt or/and pointer twist (for instance on advanced pen/stylus digitizers)
See Pointer Events Level 2 [pointerevents2].

# What Principle and Guideline the SC falls within.

Principle 2, *new* Guideline "Additional sensor inputs"

# Description

Some pointer input devices provide sensors to detect - beyond simple x/y screen coordinates - additional values such as twist, tilt, pressure. Not all users may have these advanced pointer input devices (e.g. users may have a touch screen, but not a pressure-sensitive touch screen), OR they may have the device, but may be unable to operate the advanced functionality (at all, or precisely enough).

[Editorial comment: this may be seen as a deepening/clarification of 2.5.1; also, 2.1.1/2.1.3 are of course also still valid, so beyond dropping down from "advanced" to "non-advanced" pointer, functionality must also be operable with just the keyboard]

# Benefits

Users who can use a pointer, but lack dexterity to perform precise movements such as twist, tilt and pressure would not be able to perform functions unless they can be done with simple pointer input.

# Testability

Test each function with a simple pointer (no pressure, tilt, ext of the pointer)

# Techniques

Functionality/content must not solely rely on advanced pointer input information (e.g. an alternative which does not require advanced sensors, but just plain x/y screen coordinate information only, must be available)

[Note: the techniques M3 and M9 are related and may be combined in 2.1. M3 requires that functionality work without timing or multi gestures, M9 requires it works without tilt, specific pressure, or angle, etc...]

**Comment by alastc** [comment]
Looks clear, presumably a mouse is a "simple pointer"? I.e. the testing doesn't require testing both mouse and touch screen?

It does seem to be a fairly unlikely thing to happen though? At least in a way that would dis-advantage people with disabilities? Surely there will be lots of people (for the foreseeable future, which isn't very far, but anyway) who don't have an advanced pointer? 

It also seems very closely related to Pointer gestures #61, but much less likely to happen?

I don't feel strongly about this, it just seems to be an criteria awaiting a problem, so less important than some of the others. (I'm happy to be wrong if there is evidence of the issue, it is just a feeling at this stage.)

**Comment by mbgower** [comment]
Agree with @alastc. Outlier situation. My comments on #61 Pointer Gestures and #67 Device Sensors would need to be resolved before I would want to tackle this.

**Comment by awkawk** [comment]
https://github.com/w3c/wcag21/pull/144

**Comment by awkawk** [comment]
Updated the issue description to reflect the FPWD text and reopening issue.
