### ISSUE TITLE
Characters

### ISSUE THREAD

**Issue by jrpool** [w3c/wcag21#660]
“the Space and Enter keys, which return empty spaces rather than characters, are not character keys” seems confusing, because the space character is a character, as that word is customarily used. There is a larger set of whitespace characters in Unicode. The quoted statement does not make it clear whether the keys that produce those characters are to be classified as “character keys”. An example of an expert who classifies space not only as a character but also as a printable character is http://web.itu.edu.tr/sgunduz/courses/mikroisl/ascii.html. It could be better to invent a term, if necessary, to designate the set of characters that are covered by Success Criterion 2.4.11. This issue relates to #386 and to #659.

**Comment by awkawk** [comment]
(Official WG Response)
Thank you for the comment. We have clarified the criterion to ensure that Space and Enter are not referred to incorrectly. The updated SC can be viewed at: http://rawgit.com/w3c/wcag21/master/guidelines/index.html#character-key-shortcuts
