### ISSUE TITLE
Additional words for 2.5.1 Pointer Gestures

### ISSUE THREAD

**Issue by mapluke** [w3c/wcag21#663]
The European team STF536 discussed 2.1.1 and suggested adding some words to read:

>All functionality which uses multipoint or path-based gestures for operation can be operated with a single pointer @@without a path-based gesture@@, unless a multipoint or path-based gesture is essential.

Rationale: Since the statement says “OR  path based” -- this applies to multipoint and (single point) path based gestures.  So this should say that the solution is not multipoint and not path based --  unless either or both is essential.

**Comment by awkawk** [comment]
(Official WG response)
Thank you for your suggestion. We agree that your addition clarifies the text of SC 2.5.1 Pointer gestures. Path-based gestures are often carried out with a single pointer (as in drag-and-drop) so including an explicit reference ("...can be operated with a single pointer without a path-based gesture") leaves less room for misunderstanding.
