### ISSUE TITLE
SC 1.3.5 - Proposal for change of wording

### ISSUE THREAD

**Issue by MakotoUeki** [w3c/wcag21#666]
-- Current wording --

Success Criterion 1.3.5 Contextual Information

In content implemented using markup languages, contextual information for controls, symbols, and regions can be programmatically determined using a publicly available vocabulary.

-- Suggested revisions --

Success Criterion 1.3.5 Contextual Information

Contextual information for controls, symbols and regions can be programmatically determined by employing established vocabulary of Web-related technical standards when content is implemented using markup languages.

--

The intention of the revisions is to simplify the sentence structure by bringing the subject and the verb forward. Also, "a publicly available vocabulary" is too vague to be readily understandable.

**Comment by awkawk** [comment]
(Official WG Response)
Thank you for your feedback. We agree that the wording "a publicly available vocabulary" is problematic. It has been changed in the latest version.
