### ISSUE TITLE
SC 2.2.8 Timeouts - Proposal for change of wording

### ISSUE THREAD

**Issue by MakotoUeki** [w3c/wcag21#667]
-- Current wording --

Success Criterion 2.2.8 Timeouts

Where data can be lost due to user inactivity, users are warned about the estimated length of inactivity that generates the data loss, unless the data is preserved for a minimum of 20 hours of user inactivity.

-- Suggested revisions --

Success Criterion 2.2.8 Timeouts

Users are warned of the duration of user inactivity that would result in data loss, unless the data is preserved for more than 20 hours when the user does not take any actions.

--

The verb “generate” does not go well with “loss.” It’s a kind of oxymoron and confusing. Also “duration” feels more natural than “length.” The sentence structure should be simplified, as well.

**Comment by awkawk** [comment]
How about: 
Where data can be lost due to user inactivity, users are warned about the estimated duration of inactivity that could result in data loss, unless the data is preserved for a minimum of 20 hours of user inactivity.

**Comment by awkawk** [comment]
or "cause" instead of "result in"

**Comment by MakotoUeki** [comment]
It looks good to me. Thanks.

**Comment by awkawk** [comment]
(Official WG Response)
Thank you for the comment. We will adjust the SC text to make it easier to translate. The new SC text will read:

"Users are warned of the duration of any user inactivity that could cause data loss, unless the data is preserved for more than 20 hours when the user does not take any actions."
