### ISSUE TITLE
SC 2.2.9 Animation from Interactions - Proposal for change of wording

### ISSUE THREAD

**Issue by MakotoUeki** [w3c/wcag21#668]
-- Current wording --

Success Criterion 2.2.9 Animation from Interactions

For non-essential animations triggered by a user action, there is a mechanism to disable the animations yet still perform the action.

-- Suggested revisions --

Success Criterion 2.2.9 Animation from Interactions

Non-essential animations triggered by a user action can be disabled without losing the functionality of the component.

--

The sentence structure should be simplified. Also, “perform the action” is confusing, especially when used in the same sentence in which “a user action” that triggers animations is mentioned. I assume what the WG meant to say “without losing the functionality of the component.”

**Comment by awkawk** [comment]
Makoto - the text was updated in the editor's draft before your comment. Please see http://rawgit.com/w3c/wcag21/master/guidelines/index.html#animation-from-interactions and if you think that this addresses your comment please close the issue. If not, let us know.

**Comment by MakotoUeki** [comment]
No problem with the updated text.
