### ISSUE TITLE
SC 2.4.12 Label in Name - Proposal for change of wording

### ISSUE THREAD

**Issue by MakotoUeki** [w3c/wcag21#670]
-- Current wording --

Success Criterion 2.4.12 Label in Name

For user interface components with labels that include text or images of text, the name contains the text presented.

-- Suggested revisions --

Success Criterion 2.4.12 Label in Name

A user interface component is given a name that contains the same text presented by its label containing text or an image of text.

--

A sentence is easier to follow and translate when the subject and the verb are clearly identifiable. The essence of this Criterion is whether a UI component has an appropriate name, which should be clearly stated upfront.

**Comment by steverep** [comment]
Hi @MakotoUeki,

I was fairly involved in creating the current wording so hopefully I can address your concerns.  Regarding your suggested wording:

> A user interface component is given a name that contains the same text presented by its label containing text or an image of text.
-
I think the final phrase has some grammar issues, but there's a larger problem.  A user interface component is not required to have a label in WCAG, and even if it does, the label is not required to have presented text (e.g. it could be an icon with alternative text).  The wording currently in the draft acknowledges that fact through the initial clause, and that is not done in your suggestion.  We can try a more translation-friendly version, but some sort of "if" or "for" clarifier is going to be needed at the beginning.

> A sentence is easier to follow and translate when the subject and the verb are clearly identifiable. 

Granted, I'm not a translator and can only say 2 words and count to 10 in Japanese, but isn't the subject and verb easy to pick out after the initial clause, i.e. "name" and "contains", respectively?

> The essence of this Criterion is whether a UI component has an appropriate name, which should be clearly stated upfront.
 
Agreed.  We just need to be cognizant of the limitation previously mentioned.

**Comment by MakotoUeki** [comment]
Hi @steverep 

I can live with the current wording. 

One question. Can we say "the text visually presented" instead of  "the text presented"? It might be more clearly understandable.

**Comment by steverep** [comment]
I agree with @awkawk.  Looks good to me.

**Comment by MakotoUeki** [comment]
Looks good to me as well.

**Comment by awkawk** [comment]
(Official WG response)
Thank you for the comment. The specific phrasing of the SC is designed to match phrasing used in other SC. As a result, the WG needs to keep the SC text the same, except for adding "visually" to the end of the SC to provide additional clarity. See https://github.com/w3c/wcag21/pull/728/files for the specific change.
