### ISSUE TITLE
Move SC 1.3.4 Identify Common Purpose to Level AAA

### ISSUE THREAD

**Issue by MakotoUeki** [w3c/wcag21#672]
I understood that SC 1.3.4 is crucially important and this is a chicken-and-egg issue. It would be more reasonable to have this SC at Level AAA in WCAG 2.1 as the first step. If we'll have real examples of user agents in the near future, then we can move this SC to Level AA.

My concern is that WCAG 2.1 can be apporoved as the next version of ISO/IEC 40500. It will affect the national standards in some countries/regions. Actually Japanese standard (JIS X 8341-3) might need to follow the next version of ISO/IEC 40500.

It is hard for content authors to understand why they have to do this. There is no user agents out there which utilize the listing of common user interface component purposes. It means content authors can't understand the real users' benefits. Then this SC could result in burden for content authors until user agents will .....

So I would suggest that WCAG 2.1 has this SC at Level AAA at first, and then we can move it to Level AA at more reasonable timing (WCAG 2.2 or Silver?).

**Comment by awkawk** [comment]
(Official WG Response)
The SC has been changed to focus on currently supported attributes, so browsers support this across the board: https://caniuse.com/#feat=input-autocomplete-onoff (There are some issues with browser implementations, but they do not appear to affect the autofill part of autocomplete.)

This aspect alone is very helpful to some people with cognitive issues.

For the aspect of adding icons for users (another goal of the SC) It is also worth noting that there are several implementations already: Chrome extension: http://accessibility.athena-ict.com/personlization.shtml Script: https://github.com/ayelet-seeman/coga.personalisation Website based implementation: https://a11y-resources.com/developer/coga-personalisation

These are at early stages and have been using the COGA semantics spec, but these can be updated to cover the autofill attributes as well, while the other aspects mature.

Overall, there is basic support for the proposal already, and people committed to expanding the functionality during the CR stage.

Given the user-need, and that this new version is far easier to implement, there does not seem to be an issue with including this SC at level AA.
