### ISSUE TITLE
Microsoft comment on 1.4.11 

### ISSUE THREAD

**Issue by alexswli** [w3c/wcag21#680]
Microsoft remains skeptical of the testing reliability and objectivity as it relates to determining which part of the graphics is required to understand content, especially those of any complexity. As part of the CR test, we will examine whether independent testers can reliably test this SC with consistency. While we acknowledge the necessity for users to perceive, please be prepare to withdraw this SC due to its potential inability to yield consistent testing regiment.

In addition, we believe it is reasonable to assume that users in need of higher contrast in graphics would also need the same higher contrast when they are not using the web. It stands to reason that high contrast theme or similar OS accessibility features should already be in use. With high-contrast (or equivalent) turned on, the test result would likely be different. How does the WG propose to deal with potentially different test results depending on the OS setting? If there is agreement, we propose adjusting OS settings as one technique to meet this SC.

**Comment by alastc** [comment]
Hi Alex,

Testing in Windows 10, high contrast mode doesn't affect graphics. In MacOS using the conrast setting makes low-conrast graphics disappear...

What sort of theme or OS setting would improve the contrast of graphics?

-Alastair

**Comment by alexswli** [comment]
Here’re couple of screen shots of the same screen viewed under different high contrast settings. The results are clearing different since the background color are flipped from white to black.

[cid:image003.png@01D38E2E.E7083170]
[cid:image005.png@01D38E2E.E7083170]

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by alastc** [comment]
Sorry, attachments don't come through on email.

From what I can tell by changing it myself, backgrounds and foreground colours in the CSS are changed, which can help with standard controls.

However, it doesn't affect embedded graphics or custom control, unless there are other settings I haven't found.

Alastair

**Comment by alexswli** [comment]
![high contrast white](https://user-images.githubusercontent.com/24412193/35072344-05eb8524-fb99-11e7-909a-2498ea36939a.PNG)
![regular screen](https://user-images.githubusercontent.com/24412193/35072345-06153482-fb99-11e7-8921-257c8d897723.PNG)
Attached are two screen captures of an identical screen--one with high contrast white turned on and the other one with it off. You can see that the lock icon next the to the web authentication api performs differently under different two settings. With high contrast turned off, the lock is in blue. With it on, the lock is black. The GitHub icon also performs better with high contrast white setting turn on going from black on grey to black on white.
We believe this reflects the real condition that one should be expected for end users and thus should be considered as part of test procedure. Crystal has deeper expertise in the topic. I'll let her pitch in if she has more to add.

**Comment by alastc** [comment]
Hi @alexswli, the lock is a font icon, so the text colour settings from the theme are over-riding the color.

If you look at the other images, they are not changed. The background behind the 'fork on github' graphic changes so changes the contrast there, but I assume with the black theme on that would visually disappear?

In terms of what authors are responsible for, it has to be the author styles, otherwise it's not testable.

**Comment by alexswli** [comment]
@alastc, are you saying that the 1.4.11 does not apply to the lock?

I probably should have split the comments into two since the main issue is how independent tester can consistently determine which part of the graphics is required to understand content. The high contrast issue should be deprioritized as part of testing discussion.

**Comment by alastc** [comment]
Hi Alex, no, it should apply to the lock, but font-icons are increasingly rare (SVG is taking over from those, like the github icons). It is a hack, not a recommended practice from W3C (or [popular FE resources](https://css-tricks.com/icon-fonts-vs-svg/)). So I don't think that the fact that font-styles apply to those few icons does justifies a change to the SC.

Regarding independant testers, I agree it should be tested. Is that an objection?

**Comment by alexswli** [comment]
Just want to process this issue properly and put this SC to "at risk" status during CR so as not to jeopardize all the rest of WCAG 2.1.

**Comment by alastc** [comment]
From how things seem to work, it seems everything is at risk until the end ;-)

**Comment by mraccess77** [comment]
I personally object to marking this SC at risk.  Putting an SC at risk is something that must be decided by consensus and not one person or organization.

**Comment by mraccess77** [comment]
I do not agree that users should be forced in putting the whole operating system into high contrast mode in lieu of asking author to supply a very minimal level of 3:1 contrast.   That is not a reasonable thing to force users into who do not need nor want an ugly high contrast display which is to high contrast on the eyes.  People with low vision often do not want high contrast but may need a minimal level.  The effects of putting the OS in high contrast mode have other serious consequences and what is described is likely only specific to one platform and WCAG is a neutral standard that does not just apply to Windows operating systems.

**Comment by goodwitch** [comment]
+1 to both of Jonathan Avila's comments.  I object to marking this SC at
risk based on one individual's comments/concerns.  I also do not think
users should be forced to use high contrast mode (for the reasons Avila
stated).

Glenda

glenda sims  |   team a11y lead   |    deque.com    |    512.963.3773
*web for everyone. web on everything.* -  w3 goals

[image: IAAP International Association of Accessibility Professionals:
Certified Professional in Accessibility Core Competencies (CPACC)]
<http://www.accessibilityassociation.org/certification>

**Comment by alexswli** [comment]
Glenda and Jonathan, there was no objection to putting this SC as at risk during our meeting. I’m just dotting the I and crossing the t here.

________________________________

**Comment by Ryladog** [comment]
I also do not want to see this SC marked as at risk for CR.

** katie **

Katie Haritos-Shea

Senior Accessibility SME (WCAG/Section 508/ADA)

703-371-5545

ryladog@gmail.com

People may forget exactly what it was that you said or did,
but people will never forget how you made them feel.......

Our scars remind us of where we have been........they do not have to
dictate where we are going.

**Comment by alexswli** [comment]
But are you confident that independent testers will consistently yield the same results when determining which part of the graphics are required to understand the content. What we want is different from impassionate assessment of what is and isn’t likely to happen. Mind you that all of WCAG 2.1 goes down if this SC is not marked as at risk and that the testing show inconsistencies in testing. Unless you’re ready to risk take everything down, there is only one option.

________________________________

**Comment by mraccess77** [comment]
I unfortunately have not been on calls because I had conflicts with client meetings.  So I wanted my voice heard.  Thanks for letting me know it was discussed in the meetings.  Really there should be a CFC for putting a label of at risk on an SC in my opinion.  But if the group discussed it and there was consensus then it is what it is.

**Comment by alexswli** [comment]
sad news is that most SC are at risk. @alastc is only half joking that everything is at risk.

**Comment by Ryladog** [comment]
Some SC do not have identical testing results from testers, but more of a
general consistent to pass or fail based out the tested outcome. And they
are still provide good outcomes for users.

** katie **

Katie Haritos-Shea

Senior Accessibility SME (WCAG/Section 508/ADA)

703-371-5545

ryladog@gmail.com

People may forget exactly what it was that you said or did,
but people will never forget how you made them feel.......

Our scars remind us of where we have been........they do not have to
dictate where we are going.

**Comment by awkawk** [comment]
(Official WG Response)
Thank you for your comment, as a member of the working group we assume there is no need to outline the CR process. Every SC should be tested, thank you for offering that support.

Regarding high contrast mode, from some initial testing neither Windows (10 + Edge) or OSX (+Safari) help with perceiving graphics embedded into web pages, which highlights the importance of that part of this SC even more.

Using a high-contrast mode could assist with the user-interface controls, but would be limited to standard controls, not custom ones created by authors.

If there are user-agent factors that haven't been considered, please do comment on how those might impact the SC. However, it is worth nothing that the requirement from the Low Vision Task Force was that it should be a minimum standard for those without user-agent /OS support for contrast.
