### ISSUE TITLE
Sign Language

### ISSUE THREAD

**Issue by MartinStehle** [w3c/wcag21#683]
About Success Criterion 1.2.6 Sign Language (Prerecorded)

> (Level AAA) Sign language interpretation is provided for all prerecorded audio content in synchronized media.

Sign language should not have the lowest level but should be provided like captions and Audio descriptions. That means:
> **(Level A)** Sign language is provided for prerecorded media.
> **(Level AA)** Sign language is provided for live media.

If doubts due to too high costs for producing Sign language videos should be raised this alternative rating could be:
> **(Level AA)** Sign language is provided for prerecorded media.
> **(Level AAA)** Sign language is provided for live media.

**Comment by awkawk** [comment]
(Official WG Response)
Thank you for the comment. It is too late to address these changes, and the changing of existing SC was out of scope for WCAG 2.1, but we will mark this issue with the "defer" label to ensure it is considered at an appropriate future time.
