### ISSUE TITLE
Comments on 2.5.3 and 2.5.4

### ISSUE THREAD

**Issue by jasonjgw** [w3c/wcag21#687]
Based on a review of relevant literature and an analysis of the issues raised, ETS maintains that more research and discussion are needed to establish a requirement that will address the challenges encountered by people with dexterity limitations in interacting with touch-based displays. The proposed success criteria are problematic in their present form. Details of our findings will be added to this issue. In general, it appears that a 44 by 44 pixel target size may well be inadequate to address the accessibility-related need. It is also acknowledged that the amount of space between targets is an important consideration.

There are measures which can be taken by user agents or assistive technologies to improve the interaction of users who have dexterity limitations with touch-based interfaces. These options should be further developed as a means of addressing the accessibility problem. More research and discussion are needed to determine what requirements should be applied to Web sites and Web-based applications via WCAG.

**Comment by awkawk** [comment]
(Official WG Response)
Thank you for the comment. The Working Group was not able to reach consensus on Target Size, and as a result the Target Size (SC) is now removed from the Editor's Draft. The Target Size (Enhanced) SC at AAA will be renamed to "Target Size".
