### ISSUE TITLE
Mitsue-Links Accessibility Dept. Comment on SC 3.2.6 Status Changes: Clarify the term "status messages"

### ISSUE THREAD

**Issue by honoka-h** [w3c/wcag21#691]
From the current SC, it is difficult to decide whether status messages (i.e. error messages) that receives focus would pass this SC or not.

A typical situation of status messages that receive focus:

https://hiddedevries.nl/en/blog/2017-04-04-how-to-make-inline-error-messages-accessible
> When preventing submit, because there are still errors
> If you have prevented submit, because there are still errors on the page, it could be useful to send focus to a list of errors that you have prepared at the start of the form. 

To clarify the issue above, we suggest adding words like "status messages that don't receive focus" and/or changing the definition of the term "[status message](https://www.w3.org/TR/2017/WD-WCAG21-20171207/#dfn-status-message)".

**Comment by awkawk** [comment]
Thanks you for your comment. The deadline for comments has passed, but the Working Group will make efforts to consider your comment and any suggestions for improvements.

**Comment by awkawk** [comment]
(Official WG response)
Thank you for your comment. We have introduced and modified the definition in the time since the last Working Draft.

**Comment by honoka-h** [comment]
I know you have closed this, but we could not find the modification. Could you let us know where we can see the modification?

**Comment by awkawk** [comment]
@honoka-h The CR publication is at https://www.w3.org/TR/2018/CR-WCAG21-20180130/#status-changes. The definition is at https://www.w3.org/TR/2018/CR-WCAG21-20180130/#dfn-status-messages

**Comment by honoka-h** [comment]
@awkawk Thank you for the URLs. We have checked them both, but we believe there were editorial changes only. Could you please give us some details on the decision made by the WG?
