### ISSUE TITLE
The Paciello Group comment on 1.3.4 Identify Common Purpose

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/wcag21#692]
The SC appears fine, but W3C should take first step and publish an initial vocabulary and example implementation with a documented technique.

**Comment by awkawk** [comment]
Thanks you for your comment. The deadline for comments has passed, but the Working Group will make efforts to consider your comment and any suggestions for improvements.

**Comment by patrickhlauke** [comment]
(adding this only to this one issue) Sorry about that @awkawk ... completely missed that the deadline was *before* 12 January rather than *by* 12 January. Hope the comments can still help inform the further development/refinement of the SCs.

**Comment by awkawk** [comment]
Thanks for the comment - marking this as "implementation follow up" to make sure it is consider in techniques development.
