### ISSUE TITLE
The Paciello Group comment on 1.3.5 Contextual Information

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/wcag21#693]
Could the glossary definition contain an actual example?

"publicly available vocabulary" is still extremely vague, as previously commented. Does it need to be independent/third party? Would a vocabulary a site invented for themselves and published on their own site count, and have same importance/weight as a large scale ecosystem site? Does it need to be standardised/peer reviewed? Maintained/sustainable through a community? This needs at the very least to be defined in the glossary.

**Comment by awkawk** [comment]
Thanks you for your comment. The deadline for comments has passed, but the Working Group will make efforts to consider your comment and any suggestions for improvements.

**Comment by awkawk** [comment]
(Official WG Response)
Thank you for your comment. We have removed the definition that included the "publicly available vocabulary" wording.
