### ISSUE TITLE
The Paciello Group comment on 1.4.13 Content on Hover or Focus

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/wcag21#695]
> Hoverable: If pointer hover can trigger the additional content, then the pointer can be moved to hover the additional content;

Perhaps remove the second "hover", as it makes it sound unnecessarily confusing, leaving just "then the pointer can be moved to the additional content"?

**Comment by awkawk** [comment]
Thanks you for your comment. The deadline for comments has passed, but the Working Group will make efforts to consider your comment and any suggestions for improvements.

**Comment by steverep** [comment]
Hi @patrickhlauke.  Several folks suggested just changing it to "hover over" instead.  I am working on a pull request for that and other changes now.  I assume that would address your issue.

**Comment by patrickhlauke** [comment]
not quite sure. would that preclude the user then being able to also click or similar actions other than hover? it's not a big deal either way, just seemed unnecessarily complex to talk about being able to hover over what appeared after hovering.

alternatively, expanding the above suggestion, to make absolutely clear what i assume is meant "then the pointer can be moved to the additional content without the content disappearing" or similar.

**Comment by awkawk** [comment]
(Official WG response)
Thank you for your comment. While the intent and requirement for the Hoverable condition has always been the same, we've struggled to state it as simply as possible in the SC. We have taken your suggestion to state it more plainly and edited it to read:

> **Hoverable:** If pointer hover can trigger the additional content, then the pointer can be moved over the additional content without the additional content disappearing;
