### ISSUE TITLE
The Paciello Group comment on 2.2.6 Accessible Authentication

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/wcag21#696]
* From the normative text itself, and the understanding document, this SC seems to mix "authentication" (who you are) with the more general idea of "CAPTCHA" (are you a bot). While it's true that login forms sometimes contain CAPTCHAs as well, these are a distinct problem from that of authentication - and if they are not adequately covered yet by existing SCs, they'd warrant having their very own separate SC, not being bundled in with authentication.
* the "transcribing" clause as currently worded excludes 2FA that send a code as text message, or traditional physical/software tools (e.g. RSA SecurID fobs or applications) that provide a second factor (as a user would need to "transcribe" a PIN from these). It may even preclude transcribing from, say, a password manager that isn't integrated directly with the browser (but shows credentials/passwords in one window) to a web form.
* authentication by definition relies on "recalling" information that is not readily available. Web Auth API is mentioned often as the panacea for this, but under most situations even a web auth provider needs in many cases to be set up (or will occasionally re-request) another piece of information (like a PIN). Web Auth API use also relies on the browser supporting it (though implementations are progressing), and the user's device having appropriate additional sensors (fingerprint? appropriate webcam?) that allow biometric, rather than recall-based, authentication (i.e. even if the web content relies on just Web Auth, if the user is using a device without any additional biometric sensors, they may end up having to enter a password or PIN on their device to authenticate themselves to the Web Auth provider/system). It feels that the actual problem of difficulty in recall is being simply shuffled over to Web Auth.

We don't disagree with the intent, but the implementation requirement is quite onerous and overall it seems very "handwavy" for something that is so fundamental to many sites.

**Comment by awkawk** [comment]
Thanks you for your comment. The deadline for comments has passed, but the Working Group will make efforts to consider your comment and any suggestions for improvements.

**Comment by awkawk** [comment]
The WG has not been able to reach consensus on this Success Criteria for inclusion in the Candidate Recommendation, so this SC has been removed.
