### ISSUE TITLE
The Paciello Group comment on 2.4.11 Character Key Shortcuts

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/wcag21#698]
Very dense/difficult to read. Some further wordsmithing may be in order to make it more easily understandable.

"If a keyboard shortcut consisting entirely" perhaps change "entirely" to "only"

This should include the exemption for things that are done by the user agent by default?

>If a keyboard shortcut consisting entirely of one or more character keys is implemented in content

"in content" should be removed, as it's implied (since these are the Web Content Accessibility Guidelines). Unless *this* is a roundabout way of excluding user agent default shortcuts? If so, it's not clear and should be reworded/spelled out.

**Comment by awkawk** [comment]
Thanks you for your comment. The deadline for comments has passed, but the Working Group will make efforts to consider your comment and any suggestions for improvements.

**Comment by awkawk** [comment]
(Official WG Response)
Thank you for the comment. The language of the SC has changed substantially and we believe that it addresses your concerns.
