### ISSUE TITLE
The Paciello Group comment on 2.4.12 Label in Name

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/wcag21#699]
Note that the SC's understanding https://www.w3.org/WAI/WCAG21/Understanding/21/label-in-name.html still talks about hidden labels, accidental triggering, which is now not part of the SC's scope.

**Comment by awkawk** [comment]
Thanks you for your comment. The deadline for comments has passed, but the Working Group will make efforts to consider your comment and any suggestions for improvements.

**Comment by awkawk** [comment]
Thanks. We will update the understanding document based on the final form of the SC text.
