### ISSUE TITLE
Small change to 3.1

### ISSUE THREAD

**Issue by lseeman** [w3c/wcag21#7]
## SC Shortname

content (was text)

### Current:

Guideline 3.1: Make text content readable and understandable.

### Proposed:

Guideline 3.1: Make content readable and understandable.

(the word "text" is removed)

## Suggestion for Priority Level (A/AA/AAA)

N/A it is a guideline

## Related Glossary additions or changes

NA

## What Principle and Guideline the SC falls within.

Principle 3 
## Description

This is a small but important change. Content needs to be understandable whether it is text, video or audio. Using clear words will help with any of these modalities.

## Benefits

The benefit is that people will understand the content, including many people with learning and cognitive disabilities. For example, if a bot uses complex words and sentences, many people with language processing impairments will not be able to use that bot.

An audio stream has uncommon words and complex sentences it will not be usable by many people with cognitive disabilities.

## Related Resources (optional)

Resources are for information purposes only, no endorsement implied.

See the road-map

User needs Table (table number 5 and 7)

related issue papers

- Multi-modal Content Delivery
- Distractions
- Voice Menu Systems
- Symbols for Non-Verbal
- Numbers and Math

**Comment by awkawk** [comment]
I believe that we should put off this change until we know better what success criteria changes/additions get accepted under this guideline.

**Comment by patrickhlauke** [comment]
Cautious +1 on this from me
