### ISSUE TITLE
The Paciello Group comment on 2.5.3 Target Size

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/wcag21#701]
This SC seems to exempt more than it specifies.

> User Agent Control: The size of the target is determined by the user agent and is not modified by the author.

This leaves a few questions open:
* what if an author chooses an image which is smaller than 44x22 CSS pixels, and - without any modification - wraps a link around it? Does this exception exempt that image link from needing to be 44x22, since the author hasn't "modified" the target? Is it not the type of content (its rendered size) that matter?
* what specifically counts as "modified by the author"? If an author sets a very high-level CSS style that just minimally changes the default font size (e.g. `body { font-size: 0.99em; }`) does that count as "modified by the author" (as it affects the actual rendered size of both static and interactive text, the size of `<button>` elements, etc)? Where is the line drawn?

Fundamentally, users that find controls too small to accurately click/tap can zoom in (provided zooming isn't counteracted in some way). While zooming does not change the CSS pixel dimensions, it still renders everything larger (CSS pixel to hardware pixel ratio changes, real-world - as measured on screen - dimensions increase), meaning a user can very easily make previously hard to click/tap targets large enough for their needs. This would obviously not work in situations where content is prevented from zooming, but as most user agents (including on mobile) now either ignore things like `user-scalable=no` in viewport meta, or provide the user with an option to ignore it, and there are no other mechanisms for web content to "lock" a particular size, it seems there's a fairly common standard way for users to ensure they can always tap/click. It may not be user-friendly, but this feels like it veers into trying to codify a usability recommendation into a hard accessibility requirement. The ability/inability of users to zoom into content also crosses over with the proposed SC 1.4.10 Reflow, which requires content to be zoomable/scalable up to 400% on desktop.

There's uncertainty about whether this SC can be met by offering a setting/option (e.g. a switch to change from "mouse optimized" to "touch optimized", as is the case in software like MS Word), or to use other means (e.g. checking for presence of a touchscreen) to determine if targets should be rendered at a particular (larger) size.

In light of these two points, would it be more appropriate to:
* keep the first exception (about alternatives)
* drop the other exceptions
* instead include "A mechanism is available..." type language? This would require some consideration - since, as stated above, zooming does not alter the actual CSS pixel dimensions.

As a side note, since the SC leans on Apple/Google/Microsoft guidance for (native) apps: note that in these guides, the minimum target size is *suggested*, often for "important" controls, and Apple etc break their own guidance in certain situations.

**Comment by awkawk** [comment]
Thanks you for your comment. The deadline for comments has passed, but the Working Group will make efforts to consider your comment and any suggestions for improvements.

**Comment by awkawk** [comment]
(Official WG Response)
Thank you for the comment. The Working Group was not able to reach consensus on Target Size, and as a result the Target Size (SC) is now removed from the Editor's Draft. The Target Size (Enhanced) SC at AAA will be renamed to "Target Size".
