### ISSUE TITLE
The Paciello Group comment on 2.5.4 Target Size (Enhanced)

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/wcag21#702]
If 2.5.3 changes as per https://github.com/w3c/wcag21/issues/701, drop the "User Agent Control" (as it still has problems in its wording, as noted in #701) and leave the rest as is (without the "a mechanism is available" proposed in #701).

This would then retain a hard requirement for large targets in WCAG 2.1, but at AAA (allowing sites to do the right thing if they so wish, and achieving compliance with this SC to prove it).

**Comment by awkawk** [comment]
Thanks you for your comment. The deadline for comments has passed, but the Working Group will make efforts to consider your comment and any suggestions for improvements.

**Comment by awkawk** [comment]
(Official WG Response)
Thank you for the comment. The Working Group has elected to retain the "user agent control" exception, but is offering a AAA version of Target Size.

**Comment by patrickhlauke** [comment]
I'll note that the WG has not actually responded in any meaningful way TO the "user agent control" exception (other than simply "electing to retain it"), it seems.
