### ISSUE TITLE
The Paciello Group comment on 2.5.5 Concurrent Input Mechanisms

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/wcag21#703]
Could do with a glossary definition/link for "input modalities".

Achieving this SC doesn't seem to be difficult, so could potentially be moved to AA or even A?

**Comment by awkawk** [comment]
Thanks you for your comment. The deadline for comments has passed, but the Working Group will make efforts to consider your comment and any suggestions for improvements.

**Comment by awkawk** [comment]
(Official WG Response)
Thank you for the comment. The WG did not decide to add a definition for input modalities as both "input" and "modalities" are used in WCAG 2.0, so it is important to continue to use these terms in the conventional ways rather than potentially redefine the terms.
