### ISSUE TITLE
The Paciello Group comment on 2.6.1 Motion Actuation

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/wcag21#704]
Motion has been picked out, but what about other uses of sensors as inputs (e.g. light sensor, blowing on a microphone)? Is it restricted just to motion because it's more common?

Fundamentally, this seems to already be covered by SC Keyboard (though the wording there, focusing on "keyboard", and the fact that 2.1 was not meant to "touch" any existing 2.0 content, may be the reason why this was special-cased)?

**Comment by awkawk** [comment]
Thanks you for your comment. The deadline for comments has passed, but the Working Group will make efforts to consider your comment and any suggestions for improvements.

**Comment by steverep** [comment]
> Motion has been picked out, but what about other uses of sensors as inputs (e.g. light sensor, blowing on a microphone)? Is it restricted just to motion because it's more common?

Scoping to motion was based on the documented examples from the MATF as well as being cognizant that far from all "sensors" are inaccessible.  How they are used and what functionality they provide must be considered.  See #572 for an attempt at methodically breaking this down.  In your example, how could an ambient light sensor be used to disadvantage people with disabilities?

Sound actuation via a microphone, on the other hadn, could certainly affect PWDs and may be able to be added to the SC.  There were no documented examples of this being a problem though.

> Fundamentally, this seems to already be covered by SC Keyboard (though the wording there, focusing on "keyboard", and the fact that 2.1 was not meant to "touch" any existing 2.0 content, may be the reason why this was special-cased)?

Certainly if changing 2.0 criteria were open this may or may not have looked very different.  However, the current Motion Actuation criterion requires UI component to perform the same function and that a mechanism be available to disable the detection of motion.  This goes beyond what is required by 2.1.1.

**Comment by patrickhlauke** [comment]
> In your example, how could an ambient light sensor be used to disadvantage people with disabilities?

It could be used as a form of input - rather than measuring the ambient light in general, it could be used in interactions like a "light-sensor based theremin" or similar (the more the user's hand is occluding the sensor, the more a certain value changes). similar to proximity sensors. but yes, granted, it starts getting a bit esotheric at that point.

**Comment by patrickhlauke** [comment]
> Sound actuation via a microphone, on the other hadn, could certainly affect PWDs and may be able to be added to the SC. There were no documented examples of this being a problem though.

that would either need a renaming/rewriting of the SC altogether, or a separate SC. but yes, since it's not been brought up, probably late to the party...

**Comment by awkawk** [comment]
(Official WG Response)
This SC is focused on motion, but we will mark this comment as "defer" to ensure it is review an an appropriate time for future consideration.
