### ISSUE TITLE
The Paciello Group comment on 2.6.2 Orientation

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/wcag21#705]
Fundamentally fine, but examples may not always be "essential" because of something intrinsic about the type of content, but rather because they may be difficult/onerous for authors to make workable in other orientation? There's a danger that authors/designers may claim something as being "essential" when in fact the reason why only one orientation is supported is simply because considering other orientation involved more work/design.

For instance, for the "piano app" example in understanding, it would be possible for the keyboard to be displayed in an alternative way in portrait (for instance, split into two rows of keys).

**Comment by awkawk** [comment]
Thanks you for your comment. The deadline for comments has passed, but the Working Group will make efforts to consider your comment and any suggestions for improvements.

**Comment by awkawk** [comment]
(Official WG Response)
Thank you for the comment. We will clarify this in the understanding documents.
