### ISSUE TITLE
The Paciello Group comment on 3.2.6 Status Changes

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/wcag21#706]
"such that they can" awkwardly worded.

"can be programmatically determined through role or properties" the role/properties part seems redundant, as that is what "programmatically determined" generally is https://www.w3.org/TR/WCAG21/#dfn-programmatically-determinable ?

Related: in the definition of role https://www.w3.org/TR/WCAG21/#dfn-role: the second sentence "A number..." appears old/broken/irrelevant?

**Comment by awkawk** [comment]
Thanks you for your comment. The deadline for comments has passed, but the Working Group will make efforts to consider your comment and any suggestions for improvements.

**Comment by awkawk** [comment]
(Official WG Response)
Thank you for the comment. The Working Group has not made changes to address your points but these may be possible to address through editorial changes in CR.

**Comment by awkawk** [comment]
I'll also add that the definitions being commented on are from WCAG 2.0 and we cannot change them at this time.

**Comment by patrickhlauke** [comment]
I'll note that the definition from WCAG 2.0 is nonsensical (role isn't "A number"), so would strongly suggest an errata/correction (at whatever time may be appropriate)
