### ISSUE TITLE
Intopia Feedback - SC 1.3.4 Identify Common Purpose

### ISSUE THREAD

**Issue by AndrewArch** [w3c/wcag21#707]
1.	This SC seems very complicated. Is it practical for implementation at present? How would it be satisfied?
2.	Will the purposes in 7.1/7.2 be translated into languages other than EN?
3.	Will these be implemented in ARIA?
4.	Which semantic schemas are user agents and assistive tech expected to recgonise?
5.	Some phrases are very similar, particularly sign in/sign up/sign out. Will users appreciate the difference?
6.	How granular should markup be for multi-field inputs such as address?
7.	"Credit card" appears twice in 7.2.
8.	"Credit card" maps to an element containing multiple inputs? Or is it applied to every credit-card related input individually?
9.	"URL" (7.2) - will users appreciate that this markup only relates to URLs related to themselves? Would it apply if a user was asked "Enter the URL of your favourite news website"?
10.	"Birthdate" (7.2) - Does it have to correspond to the user or does it apply to any birthdate (e.g. family members in genealogy, insurance, etc.)

**Comment by awkawk** [comment]
Thanks you for your comment. The deadline for comments has passed, but the Working Group will make efforts to consider your comment and any suggestions for improvements.

**Comment by awkawk** [comment]
(Official WG Response)
> This SC seems very complicated. Is it practical for implementation at present? How would it be satisfied?

The SC has changed in ways for which implementations already exist, using the autocomplete/autofill features in browsers.

> Will the purposes in 7.1/7.2 be translated into languages other than EN?

This will depend on translations of the HTML 5.2 specification.

> Will these be implemented in ARIA?

That will depend on the ARIA personalization work, but we expect that they will.

> Which semantic schemas are user agents and assistive tech expected to recognise?

The SC has changed in ways for which implementations already exist, using the autocomplete/autofill features in browsers.

> Some phrases are very similar, particularly sign in/sign up/sign out. Will users appreciate the difference?

This is no longer an issue with the new wording.

> How granular should markup be for multi-field inputs such as address?

Developers will follow the guidance for the autofill meanings in the HTML 5.2 spec.

> "Credit card" appears twice in 7.2.

This is no longer an issue with the new wording.

> "Credit card" maps to an element containing multiple inputs? Or is it applied to every credit-card related input individually?

Developers will follow the guidance for the autofill meanings in the HTML 5.2 spec.

> "URL" (7.2) - will users appreciate that this markup only relates to URLs related to themselves? Would it apply if a user was asked "Enter the URL of your favourite news website"?

We will make sure to cover this in understanding but for the news website example it would not apply.

> "Birthdate" (7.2) - Does it have to correspond to the user or does it apply to any birthdate (e.g. family members in genealogy, insurance, etc.)

Only to the user.
