### ISSUE TITLE
Intopia Feedback - SC 1.4.10 Reflow

### ISSUE THREAD

**Issue by AndrewArch** [w3c/wcag21#708]
1.	CSS pixels need a simple explanation in order for designers and developers to adopt.

**Comment by patrickhlauke** [comment]
Should be linked to the definition https://www.w3.org/TR/WCAG21/#dfn-css-pixels

**Comment by awkawk** [comment]
Thanks you for your comment. The deadline for comments has passed, but the Working Group will make efforts to consider your comment and any suggestions for improvements.

**Comment by alastc** [comment]
I think a response has been drafted for #717, so this one is a duplicate. (Different SC, but same definition.)

**Comment by awkawk** [comment]
(Official WG Response)
Thank you for the comment. The CSS pixel is defined and in the definition there is a reference to the CSS specification for additional information. We will also make sure to clarify this and provide examples in the Understanding document.
