### ISSUE TITLE
Non-interference with Assistive Technology

### ISSUE THREAD

**Issue by kwahlbin** [w3c/wcag21#71]
# Current versions of SC and Definitions
- [SC for viewing](https://rawgit.com/w3c/wcag21/non-interference-with-assistive-technology_ISSUE-71/guidelines/sc/21/non-interference-with-assistive-technology.html) | [SC for editing](https://github.com/w3c/wcag21/blob/non-interference-with-assistive-technology_ISSUE-71/guidelines/sc/21/non-interference-with-assistive-technology.html)
- [Non-interference definition for viewing](https://rawgit.com/w3c/wcag21/non-interference-with-assistive-technology_ISSUE-71/guidelines/terms/21/non-interference.html) | [Non-interference definition for editing](https://github.com/w3c/wcag21/blob/non-interference-with-assistive-technology_ISSUE-71/guidelines/terms/21/non-interference.html)
- [SC in full draft guideline](https://rawgit.com/w3c/wcag21/non-interference-with-assistive-technology_ISSUE-71/guidelines/#non-interference-with-assistive-technology)

# SC Shortname

Non-interference with Assistive Technology

# SC Text
Content does not interfere with the normal operation of the platform assistive technology, or a mechanism is available to override the interference, unless:

* it is essential for use of the content, and
* the user is warned before using the component.

# Suggestion for Priority Level (A/AA/AAA)
Level A

# What Principle and Guideline the SC falls within.

Principle 4, Guideline 4.1 - Compatible (Or perhaps this is really a 4.2)

# Description

The intent of this success criterion is to prevent content from interfering with platform assistive technology.  

A common scenario is passing touch through directly to the content, bypassing the AT entirely. Touch ATs rely on the users ability to interact with a series of gestures to control focus, interact, and speak descriptions of on screen elements.  If the content overrides these gestures, users dependent upon these mechanisms for content interaction will be unable to perform basic functions. While this may be required for certain types of content, if such content covers significant area of the screen, it could completely block the use of the device by touch AT users, as performing swipe gestures on small patches of screen can be difficult.  

A further scenario is the inappropriate use of `role="application"` on regular content (rather than in "app-like" situations), which in the case of many current assistive technologies in a desktop environment results in standard AT controls (such as quick navigation and reading keys) being disabled.

Users should be warned before entering any section of content that changes the way the platform AT intercepts touch gestures.

Note for WCAG WG: This criterion differs from the proposed "Touch with AT" (m5) success criterion, in that the latter is concerned with a site/app using gestures which cannot be triggered due to assistive technologies that intercept the gesture as a command, whereas this SC is concerned with sites/apps that explicitly attempt to disable/disrupt AT to prevent this interception from happening, thus preventing AT from working altogether.

Note for WCAG WG: the intent behind this SC is possibly already covered by https://www.w3.org/TR/WCAG20/#cc5. However, it's not clearly called out, and ensuring that (particularly touch) AT isn't blocked/circumvented is not explicitly covered in the list of SCs that still need to apply to all page content (1.4.2, 2.1.2, 2.3.1, 2.2.2). There is further concern that although https://www.w3.org/TR/WCAG20/#cc5 is part of the normative spec text, it is slightly "buried" (as many authors will simply work their way through the SCs), so having an explicit SC (which could then be cross-referenced from https://www.w3.org/TR/WCAG20/#cc5) would arguably be the more robust approach.

# Benefits

* Users who use a mobile device where touch screen is the primary mode of interaction
* Users with visual impairments who depend on spoken feedback

# Testability

The specific test procedure will depend on the particular platform/AT combination used. In general, testing aims to ensure that all standard AT features and controls are not suppressed.

1. Locate all major content sections, and ensure AT controls (in the case of touchscreen devices, gesture navigation; for keyboard/desktop environments, standard controls including quick navigation and reading keys) works as expected for all sections.
2. Locate any items that bypass AT gesture navigation.
3. Ensure that either the control that loaded this content warned of its presence OR that the content has a preview mode that does not bypass gesture navigation.

# Techniques

Content Preview with Available Mechanism: Load the content first, without gesture overrides/AT Bypassing mechanisms, and confirm that the user wants gestures overridden.  EX: A confirmation dialogue before asking for a signature, confirmation dialogue re-appears each time focus leaves the signature panel.

Content Warning: An element that will load a control that bypasses the AT warns the user. EX: A warning on a control that loads a "paint" window.

Failure: A "paint" drawing screen with no heading, no warning, and no preview.  Content fills up screen, making ANY gesture based navigation difficult, trapping the user on that screen, unless they have a device with a hardware back button.

Technique: only use `role="application"` for app-like web applications (and ensure that all content relationships are explicitly defined using `aria-label`, `aria-labelledby`, `aria-describedby` etc); ensure that `role="document"` is added for content sections (which will allow desktop/AT users to use quick navigation and reading keys to navigate the structured content itself).

**Comment by alastc** [comment]
The method of testing seems a little problematic to me, it relies on developers (or anyone responsible for testing) to be expert across all potential AT. (And know what is 'expected' for each AT across scenarios.)

WCAG 2.0 focuses on what the content does or is, and uses concepts like 'programmatically determinable' or 'a mechanism is available' to avoid making it a test of user-agents. It has to be something in the page that you can say is there, or not there, or whether it is appropriate.

Would it be possible to either re-phrase to make it about the content, or break-down to the specific issues about the content that cause issues? 

Given the existence of the "Touch with AT" SC, would it make sense to focus this on the inappropriate use of direct input detection or role="application"? To throw out some ideas:
_Web pages do not rely on direct events from touch or mouse except_ or
_Structured content is not wrapped in an application role unless_ ...

I'm not sure about the solution, but I am worried about the testability as it stands.

**Comment by mbgower** [comment]
Going to need to define "platform assistive technology". Some will recall the debate that arose about whether Zoom on iOS constituted an assistive technology (and thus could not be used to meet Resize Text).
I anticipate some headaches here, trying to distinguish between what Section 508 Refresh assigns to 

> 502.2.2 No Disruption of Accessibility Features. Software shall not disrupt platform
features that are defined in the platform documentation as accessibility features

and what falls under

> 503.2 User Preferences. Applications shall permit user preferences from platform
settings for color, contrast, font type, font size, and focus cursor.

As an example, in iOS, do all items that fall underneath Settings>General>Accessibility amount to platform assistive technology? That would include big ATs like Zoom and VoiceOver, but would also include smaller features like Reduce Motion and Shake to Undo. Do items that fall outside this _not_ rate as "platform assistive technology", for example, Siri? What about items like Text Size and Bold Text, which appear both inside and outside these accessibility menus?

**Comment by DavidMacDonald** [comment]
I feel this is already covered under conformance requirement 5 non-interference
https://www.w3.org/TR/2008/REC-WCAG20-20081211/#cc5

**Comment by mbgower** [comment]
Thanks @DavidMacDonald. Perhaps I need to be more specific. In my experience, the non-interference conformance has tended to be used almost entirely to capture disruptions with keyboard shortcuts used by the OS to bring about their accessibility features. An example in Windows is the use of assigned keys to turn on High Contrast Mode (ALT+left SHIFT+ PRINT SCREEN). But with mobile, there isn't the same paradigm -- no protected keystrokes, for instance. It sounds like you are focusing considerations primarily on reserved gestures and (I'm assuming) reserved or assignable actions on the few physical buttons on most devices. However, as is clear from a review of the Accessibility items on the iOS menu, a great deal of other settings that do not involve physical activation can also be construed as "platform accessibility features". So, if user preferences for shaking the device or using Increased Contrast are interfered with by an author, does that violate this? And how does an author determine what is considered one of these features? Hence my suggestion for a clearer definition.

**Comment by DavidMacDonald** [comment]
Perhaps I can clarify better. I don't think we need this SC because non-interference is substantially covered under conformance requirement 5 non-interference
https://www.w3.org/TR/2008/REC-WCAG20-20081211/#cc5. 

I agree that the Conformance Criteria have largely been misunderstood, underused and ignored. We should address that through education and outreach. I don't think creating a Success Criteria overlapping with it is a good idea.

**Comment by mbgower** [comment]
Ah, okay, thanks. I assume that would also be your perspective for #62 ?
One point I would mention is that at IBM we introduced a checkpoint called "Accessibility-supported technologies only." Which lifts the conformance language as its short language:

> Use accessibility supported technologies. Any information or functionality that is implemented in technologies that are not accessibility supported must also be available via technologies that are accessibility supported.

It has been _very_ handy having this checkpoint against which we can fail applications for such scenarios as described in this SC.

**Comment by lseeman** [comment]
Can we merge in Standardized APIs #46 
we would need to include:
things like spell checking and the right click menu is not disabled (augmented is fine)
content works with apis like nternet of Things that allow for simplified and personalized interfaces such as the ISO/IEC 24752 “Universal Remote Console Framework” standard
Can these be merged as usecase?

**Comment by lseeman** [comment]
note that coga users are not using AT that uses the api of the operating system but use browser plugins and others as AT

**Comment by patrickhlauke** [comment]
From a pure web content point of view, it is currently not possible for a web page to disable touch AT operation. It is possible in native mobile applications, but I'd argue that's beyond the scope of the Web Content Accessibility Guidelines (though that could be noted in a companion document mapping native apps to WCAG).

As for the issue of `role="application"`, I'm wondering if that very specific problem can be addressed in the understanding part of 2.1.1 as it relates to keyboard interaction. If so, then I'd propose that this can be retired.

**Comment by DavidMacDonald** [comment]
I agree that we should retire this SC. If it proceeds it could confuse even more the current conformance requirement of non-interference and lead jurisdictions where WCAG 2.0 is required to think that non-interference is reserved for 2.1. There is already quite a bit of misunderstanding of "non-interference" in 2.0 and this would deepen that confusion about 2.0, to the point that many may think it's not a requirement.

**Comment by mraccess77** [comment]
The non-interference requirements from the conformance section of WCAG are limited to four specific things.  We need something that is broader.  Let me give you an issue that I face --  this may be covered under another SC -- but it's one example.  On Pokémon Go for example, if you use the three finger pan gesture on iOS to move around and you are on your Pokedex or your backpack the individual touches are instantly detected and actions start occurring as you move your three fingers around.  So effectively you can't use the zoom feature on iOS with Pokémon Go because you can't pan without triggering all sorts of things.  This is a native app -- but I don't see why the same thing couldn't happen in a web app.   Furthermore, if these SC were to apply to non-web content there would be all sorts of issues that arise.  For example, apps crashing when you turn on zoom, apps conflicting with the zoom gestures, apps that slow down when assistive technology is running, etc.  Perhaps some of these could be put under accessibility supported -- but that's not a clear line.  Accessibility supported feels different to me and at least for non-web content non-interference should be expanded in the WCAG conformance requirements.

**Comment by patrickhlauke** [comment]
> This is a native app -- but I don't see why the same thing couldn't happen in a web app. 

because for native, there are explicit ways in code to disable/circumvent AT, while for web content there is no way to do it for a content author.

**Comment by mraccess77** [comment]
When zoom is enabled three finger touches are indeed not sent through to web apps as @patrickhlauke indicates -- iOS seems to trap the gestures. so we need to known what if anything web apps can do to interfere.  I'm curious to know if the same applies with Android's magnification feature.

**Comment by DavidMacDonald** [comment]
I think the Pokemon scenario is covered under #63 Touch with Assistive Technology. Touch no longer works with AT enabled...

**Comment by lseeman** [comment]
can we merge some use cases from #46
