### ISSUE TITLE
Intopia Feedback – SC 1.4.12 Text Spacing

### ISSUE THREAD

**Issue by AndrewArch** [w3c/wcag21#710]
1.	What tools exist that enable users to manipulate text spacing (apart from adjusting the CSS directly)? Use case for testing purposes.

**Comment by awkawk** [comment]
Thanks you for your comment. The deadline for comments has passed, but the Working Group will make efforts to consider your comment and any suggestions for improvements.

**Comment by alastc** [comment]
Hi Andrew,

There is a [bookmarklet](https://github.com/alastc/adaptation-scripts/blob/master/scripts/text-adaptation.js), but the [stylish plugin](https://userstyles.org/) is probably easiest and works on sites with content-security-policies.

Add this as a style:
```
* {
    line-height: 1.5 !important;
}
p {
    margin-bottom: 2em !important;
}
* {
    letter-spacing: 0.12em !important;
}
* {
    word-spacing: 0.16em !important;
}
```

**Comment by awkawk** [comment]
(Official WG Response)
Thank you for the comment. As Alastair stated, a bookmarklet and a stylish plugin exist. Alternatively the user CSS is:

```
   * {
   line-height: 1.5 !important;
   }
   p {
   margin-bottom: 2em !important;
   }
   * {
   letter-spacing: 0.12em !important;
   }
   * {
   word-spacing: 0.16em !important;
   }

```
