### ISSUE TITLE
Intopia Feedback – SC 1.4.13 Content on Hover or Focus

### ISSUE THREAD

**Issue by AndrewArch** [w3c/wcag21#711]
1.	We think that ‘hoverable’ needs to be expressed more plainly (rather than relying on the explanation in Understanding)

**Comment by awkawk** [comment]
Thanks you for your comment. The deadline for comments has passed, but the Working Group will make efforts to consider your comment and any suggestions for improvements.

**Comment by awkawk** [comment]
(Official WG Response)
Thank you for your comment. While the intent and requirement for the Hoverable condition has always been the same, we've struggled to state it as simply as possible in the SC. We have taken your suggestion to state it more plainly and edited it to read:

> **Hoverable:** If pointer hover can trigger the additional content, then the pointer can be moved over the additional content without the additional content disappearing;
