### ISSUE TITLE
Intopia Feedback – SC 2.2.6  Accessible Authentication

### ISSUE THREAD

**Issue by AndrewArch** [w3c/wcag21#712]
1.	Is “social security number” - too specific to North America?
2.	Seems like this might rule out CAPTCHA unless there is a ‘non-recall or transcribe’ alternative? Will 1.1.1 be updated?
3.	How can one have a secure site without having to recall a password?
a.	Security without a password is not likely to be accepted by financial institutions
b.	Is resetting a serious option? (and ‘display current’ isn't a practical option in many situations and hence won’t be adopted)
c.	Hardware tokens listed in the techniques pose access issues for some people

**Comment by awkawk** [comment]
Thanks you for your comment. The deadline for comments has passed, but the Working Group will make efforts to consider your comment and any suggestions for improvements.

**Comment by awkawk** [comment]
The WG has not been able to reach consensus on this Success Criteria for inclusion in the Candidate Recommendation, so this SC has been removed.
