### ISSUE TITLE
Intopia Feedback – SC 2.2.7 Interruptions (minimum)

### ISSUE THREAD

**Issue by AndrewArch** [w3c/wcag21#713]
1.	Not clear how this is different from 2.2.4
2.	‘interruption’ and ‘emergency’ need definitions
3.	Agree that Understanding needs to have ‘popup’ defined
4.	Agree that ‘Media events can be easily delayed or turned off’ in Understanding seems that same as 2.2.2

**Comment by awkawk** [comment]
Thanks you for your comment. The deadline for comments has passed, but the Working Group will make efforts to consider your comment and any suggestions for improvements.

**Comment by awkawk** [comment]
The WG has not been able to reach consensus on this Success Criteria for inclusion in the Candidate Recommendation, so this SC has been removed.
