### ISSUE TITLE
Intopia Feedback – SC 2.4.11 Character Key Shortcuts

### ISSUE THREAD

**Issue by AndrewArch** [w3c/wcag21#714]
1.	Glossary - add CTRL and ALT and other standard non-character keys

**Comment by awkawk** [comment]
Thanks you for your comment. The deadline for comments has passed, but the Working Group will make efforts to consider your comment and any suggestions for improvements.

**Comment by awkawk** [comment]
(Official WG Response)
Thank you for the comment. We have changed the text of the SC significantly, and removed the definition. We believe that these changes address your concerns.
