### ISSUE TITLE
Intopia Feedback – SC 2.5.1 Pointer Gestures

### ISSUE THREAD

**Issue by AndrewArch** [w3c/wcag21#715]
1.	Might need to make it clearer that this doesn’t exclude ‘pinch to zoom’, just that an alternative must exist. 
BUT, what about 2-finger map move that we often see at present?

**Comment by awkawk** [comment]
Thanks you for your comment. The deadline for comments has passed, but the Working Group will make efforts to consider your comment and any suggestions for improvements.

**Comment by awkawk** [comment]
(Official WG Response)
Thank you for your comment. The text of SC 2.5.1 Pointer Gestures focuses on the need for alternatives to path-based or multipoint gestures. The Understanding text makes it clear that this in no way restricts authors from implementing complex gestures. It states explicitly: "When they implement complex multi-point or path-based gestures, they should ensure that the functionality can also be operated via single-point activation." This also applies to pinch-to-zoom gestures. They can and should be supported but another way to zoom content should be available (e.g., appropriately labelled [+] and [-] icons).

As to panning with two fingers, the most frequent implementation of Google maps included on a web page offers an alternative in that a shift of the visible section can also be achieved by zooming out via the [-] button and then zooming in on any particular location via double tapping, a gesture which is included in single pointer. This is certainly more cumbersome and can be tricky if the target is near the edge of the visible map section, but arguably it would qualify as alternative.
