### ISSUE TITLE
Intopia Feedback – SC 2.5.2 pointer Cancellation

### ISSUE THREAD

**Issue by AndrewArch** [w3c/wcag21#716]
1.	Does every form-submission need an ‘un-submit’? (seems impractical)
2.	In Understanding, more guidance is needed about ‘Abort or Undo’

**Comment by awkawk** [comment]
Thanks you for your comment. The deadline for comments has passed, but the Working Group will make efforts to consider your comment and any suggestions for improvements.

**Comment by steverep** [comment]
Hi @AndrewArch,

Thanks for your comment.  I think I can quickly address your concerns on this criterion.

> 1. Does every form-submission need an ‘un-submit’? (seems impractical)

No, the SC states that only 1 of the 4 conditions must be true (and typically **only** one will be true).  By far, the easiest way to pass this for a single click operation, as with most form submissions, is via the first possibility of no down-event.  The native user agent behavior of a button is to only fire on the up-event.  If, for example, the form could be submitted after a drag and drop, then a mechanism to abort could simply be a dialog asking "Are you sure you want to submit this?".  The distinction is that an abort would cancel the function before it executes whereas an undo would reverse it after the fact.

> 2. In Understanding, more guidance is needed about ‘Abort or Undo’
 
Yes, agreed.  The Understanding document reflects a slightly older version of this SC and will be updated in the coming months.  In the meantime, a brief explanation for the Abort or Undo possibility is to allow for operations which must use the down-event, such as drag and drop or other gestures, to satisfy the criterion.  By simply providing an abort possibility (e.g. via a confirmation dialog) or the ability to undo the action, users are afforded a measure to fix accidents for these types of events.  Please see issue #380 for some additional details on this criterion's latest revision.

**Comment by awkawk** [comment]
(Official WG Response)
Thank you for your comment.

> 1. Does every form-submission need an ‘un-submit’? (seems impractical)

No, the SC states that only 1 of the 4 conditions must be true (and typically **only** one will be true). By far, the easiest way to pass this for a single click operation, as with most form submissions, is via the first possibility of no down-event. The native user agent behavior of a button is to only fire on the up-event. If, for example, the form could be submitted after a drag and drop, then a mechanism to abort could simply be a dialog asking "Are you sure you want to submit this?". The distinction is that an abort would cancel the function before it executes whereas an undo would reverse it after the fact.

> 2. In Understanding, more guidance is needed about ‘Abort or Undo’

Yes, we agree. The Understanding document reflects a slightly older version of this SC and will be updated in the coming months. In the meantime, a brief explanation for the Abort or Undo possibility is to allow for operations which must use the down-event, such as drag and drop or other gestures, to satisfy the criterion. By simply providing an abort possibility (e.g. via a confirmation dialog) or the ability to undo the action, users are afforded a measure to fix accidents for these types of events. Please see issue #380 for some additional details on this criterion's latest revision.
