### ISSUE TITLE
Intopia Feedback – SC 3.2.6  Status Changes

### ISSUE THREAD

**Issue by AndrewArch** [w3c/wcag21#718]
1.	We disagree with Eg 3 in Understanding (Status Message Examples) which potentially interrupts the users’ workflow and adds to cognitive load and noise for screen reader users. Our anecdotal user feedback is they don’t want all the errors announced onblur.
2.	Is there any conflict with 2.2.7 or with 1.4.13?
3.	We’re not sure about “such that they can be presented to the user by assistive technologies without receiving focus” vs must.
4.	Does Advisory technique ‘Moving focus to new content’ conflict with “without receiving focus”? We suggest that better advice about technique [using role="status"] is needed.

**Comment by awkawk** [comment]
Thanks you for your comment. The deadline for comments has passed, but the Working Group will make efforts to consider your comment and any suggestions for improvements.

**Comment by awkawk** [comment]
(Official WG Response)
Thank you for the feedback. We do not believe that this SC conflicts with other SC, and we will mark this issue with the "implementation follow up" label to address the other parts of your comment in Understanding.
