### ISSUE TITLE
Funka Feedback - SC 1.3.4 Identify Common Purpose 

### ISSUE THREAD

**Issue by SusannaLaurin** [w3c/wcag21#719]
Agree this SC needs clarification, but it should stay on the AA level. This is the best possibility we have to support persons with cognitive disabilities any time soon. If the new European legislation will be pointing to a standard that still, after years of critisism, does not really help this large target group ... well, that would be highly unfortunate to say the least.

Without this SC in place, no AT makers will develop the solutions desperately needed.

We would be happy to help with testing and implementation if needed.

**Comment by awkawk** [comment]
Thanks you for your comment. The deadline for comments has passed, but the Working Group will make efforts to consider your comment and any suggestions for improvements.

**Comment by lseeman** [comment]
Hi Susanna
 Can I ask for some clarification? 
Are you asking for us to remove the " at risk" label so that common purpose can make the next draft of the EU legislation?

Thanks for your comment
Lisa

**Comment by SusannaLaurin** [comment]
Good evening,

Sorry if I was unclear.
The Web Accessibility Directive will enter into force this September, making the harmonised EN (HEN) the minimum requirements for public sector websites and apps.
If the SC doesn’t survive into WCAG 2.1, it will not make it into the HEN301549 either. Anything outside of HEN will not be covered by EU legislation.
That would mean a legislation that tries to make life easier for persons with various kinds of physical disabilities, but leaves people with cognitive impairments behind.

//Susanna

Från: Lisa Seeman <notifications@github.com>
Svara till: w3c/wcag21 <reply@reply.github.com>
Datum: måndag 15 januari 2018 18:53
Till: w3c/wcag21 <wcag21@noreply.github.com>
Kopia: Susanna Laurin <susanna.laurin@funka.com>, Author <author@noreply.github.com>
Ämne: Re: [w3c/wcag21] Funka Feedback - SC 1.3.4 Identify Common Purpose (#719)


Hi Susanna
Can I ask for some clarification?
Are you asking for us to remove the " at risk" label so that common purpose can make the next draft of the EU legislation?

Thanks for your comment
Lisa

**Comment by awkawk** [comment]
(Official WG Response)
Thank you for the feedback. 1.3.4 is offered at AA in the latest draft.
