### ISSUE TITLE
Proposed change in definition to "set of web pages"

### ISSUE THREAD

**Issue by awkawk** [w3c/wcag21#72]
A proposal to add an example to the definition for "Set of web pages".

Current definition:
collection of Web pages that share a common purpose and that are created by the same author, group or organization
Note: Different language versions would be considered different sets of Web pages.

Proposal is to keep the current definition and add:
Example: A publication is split across multiple Web pages, where each page contains one chapter or other significant section of the work. The publication is logically a single contiguous unit, and contains navigation features that enable access to the full set of pages.

**Comment by joshueoconnor** [comment]
CFC Passed: https://lists.w3.org/Archives/Public/w3c-wai-gl/2016OctDec/0674.html

**Comment by joshueoconnor** [comment]
Updated in wcag21 source files b32ee2f
