### ISSUE TITLE
The label in name success criterion does not address the most common situations where the accessible name of a control differs from its visible label

### ISSUE THREAD

**Issue by Wildebrew** [w3c/wcag21#724]
The [Label in name](http://www.w3.org/TR/WCAG21/#label-in-name) does not address situations where a control has no visible text label, (e.g. "icon buttons" such as a magnifying glass on a search button or an x symbol on a close button), 
"search" and "close" and similar, or form fields that require no visible label, as documented in technique [G167](http://www.w3.org/TR/WCAG20-TECHS/G167.html) and HTmL technique [H65](http://www.w3.org/TR/WCAG20-TECHS/H65.html).

The first rule of [using ARIA](https://www.w3.org/TR/using-aria/) note clearly states that ARIA should not be used if there is a native way to do things.
IN the case of labeling, this means that the visible label should be paired with the input field (in which case the accessible name of the form control matches the visible label).

The situations where the title attribute or ARIA is required to provide an accessible name are primarily in situations where there is no visible label at all.
This success criterion, as I understand it, does not address those situations.
Isn't it more logical to expect speech recognition software to expose the calculated accessible name for all controls on the page, just like a screen reader does?

**Comment by awkawk** [comment]
Thank you for the comment. The deadline for comments has passed, but the Working Group will make efforts to consider your comment and any suggestions for improvements.

**Comment by steverep** [comment]
Hi @Wildebrew,

Hopefully I can address your comment.  You wrote:

> The Label in name does not address situations where a control has no visible text label, (e.g. "icon buttons" such as a magnifying glass on a search button or an x symbol on a close button),
"search" and "close" and similar, or form fields that require no visible label, ...

I'm not sure how you were thinking those situations *should* be addressed, but we did design the SC with those situations in mind.  The criterion starts off by saying:

> For user interface components with labels that include text or images of text, ...

So, if the UI component either does not have a label (per the WCAG definition) or has a label that is an image or icon with alternative text, then the criterion does not apply.

**Comment by awkawk** [comment]
(Official WG response)
Thank you for your comment. The SC was not designed to account for situations where a label is not presented as text. The scenario you describe is worth considering for a future release, so we will mark this issue as "defer" to ensure that it is reviewed at an appropriate time.
