### ISSUE TITLE
Use a "sweapstakes" style deadline date format for the next call for comments

### ISSUE THREAD

**Issue by nschonni** [w3c/wcag21#725]
This isn't a criticism, but I was just going through all my GitHub alerts today and had an idea that might help with some of people's confusion around the deadline next time.

Next time a deadline is given be really specific like "The deadline for feedback is 11:59:59PM GMT on January 11th, 2018. The group will use the timestamp on the GitHub issues and emails to calculate late submissions time. For late submissions the Working Group will make efforts to consider your comment and any suggestions for improvements."

**Comment by awkawk** [comment]
Totally agree. We've discussed this already and are sure that it will be more specifically defined next time.
