### ISSUE TITLE
Graphics Contrast For Disabled Buttons 1.4.11 

### ISSUE THREAD

**Issue by slafleche** [w3c/wcag21#745]
The contrast for disabled buttons is tricky, because the low contrast conveys to the user that the button is disabled. It's important (from a sighted user point of view) that the contrast is low enough to remove doubt that the colour choice isn't an aesthetic design choice and in fact disabled.

I propose there's an exception added for disabled buttons, which would have a lower required contrast ratio.

**Comment by slafleche** [comment]
I've asked our designer at work and he says rule of thumb the disabled button needs to be around 50% opacity of the original.

I did a test with #FFFFFF and #959595 (contrast ratio of 1:3). With 50% opacity on the grey, we end up with #CACACA. That ends up with a ratio of 1.6:1, so looks like it about halves the ratio.

Suggestion:

Exception: It is an inactive user interface component. It must then have a contrast ratio of at least 1.5:1.

**Comment by awkawk** [comment]
@slafleche The text in the Working draft included an exception for disabled controls, and the current version that the WG is considering is "User Interface Components
Visual information used to indicate states and boundaries of user interface components, except for inactive components or where the appearance of the component is determined by the user agent and not modified by the author;" which may make it more clear.

**Comment by awkawk** [comment]
We should also clarify this in the understanding document.

**Comment by awkawk** [comment]
[Official WG Response]

The text in the Working draft included an exception for disabled controls, and the current version that the WG is considering is "User Interface Components
Visual information used to indicate states and boundaries of user interface components, except for inactive components or where the appearance of the component is determined by the user agent and not modified by the author;" which may make it more clear.

We will clarify this in the Understanding document.

Please confirm is you are satisfied with the response within 1 week. If we haven't heard a response in a week we will regard the resolution as satisfactory.

**Comment by slafleche** [comment]
That's great, thank you!
