### ISSUE TITLE
WCAG 2.1 Editor's Draft "How to Meet" links are broken

### ISSUE THREAD

**Issue by carmacleod** [w3c/wcag21#749]
In the [WCAG 2.1 Editor's Draft](https://w3c.github.io/wcag21/guidelines/) on github.io, the "How to Meet" links all 404. Here's one example: https://www.w3.org/TR/WCAG21/quickref/#non-text-content

**Comment by alastc** [comment]
Just to note that it appears (from looking at the ones I've been following closely) that the understanding docs **for the new ones** are there, but not the old ones.

I think there's a process of re-arranging the docs for 2.1 going on, and links are fragile at the moment, but I'm sure it's in hand.

**Comment by carmacleod** [comment]
The first broken one I noticed was for [How to Meet Identify Common Purpose](https://www.w3.org/TR/WCAG21/quickref/#identify-common-purpose) which is new.
I'm sure you're right that the links are only temporarily broken due to some rearranging.  :)

**Comment by awkawk** [comment]
Thank you - before we publish the Candidate Rec the content needs to pass a link test, so this will be taken care of.

**Comment by joshueoconnor** [comment]
Fixed by @michael-n-cooper
