### ISSUE TITLE
SC 1.3.4/1.3.5 are confused (dare I say they have an Identity problem?)

### ISSUE THREAD

**Issue by peterkorn** [w3c/wcag21#755]
The December 7, 2017 draft text of SC 1.3.4 Identify Common Purpose has now oddly moved (with edits) to a new SC 1.3.5 Identify Purpose.  The new title makes sense, but now new content under the old title/SC 1.3.4 Identify Common Purpose has issues, and should the SC that is "at risk".

First, the text of 1.3.4 doesn't speak to the commonality of the purpose.  Second, the first bullet is really a Technique for HTML.  In fact, fundamentally this are both getting at what we call the AccessibleRole in an accessibility API, which is already addressed in 4.1.2.  Best to make all of this stuff a Technique for 4.1.2, but if you must keep something, keep the title "Identify Purpose" (in whatever numbered SC you have), with the language that is currently there, as scoped to markup languages, with appropriate Techniques.

**Comment by awkawk** [comment]
Thank you for commenting. For more information about how the AG WG will process this issue, see the following:
- [Issue Processing](https://www.w3.org/WAI/WCAG21/comments/#issueprocessing) - How the WG will discuss the issue
- [Issue Resolution](https://www.w3.org/WAI/WCAG21/comments/#issueresolution) - Identifying and responding to the official WG response
- [Issue Notification](https://www.w3.org/WAI/WCAG21/comments/#issuenotification) - How to limit notifications from GitHub

**Comment by awkawk** [comment]
[Proposed Response]
Thank you for the comment. The intent of 1.3.4/1.3.5 is to get to a level of information that is more specific than what is covered by the accessibility role in 4.1.2. For example, all of the elements covered by 1.3.4 Identify Common Purpose are input elements and looking at two covered tokens "given-name" and 'family-name", both are likely to be on text input elements which would share the same role but not the same purpose.

The Working Group will change the title of 1.3.4 Identify Common Purpose to "Identify Input Purpose" to clarify that the AA criteria is scoped to user input.  We will also be refining the understanding content and developing techniques to make this more clear.

**Comment by awkawk** [comment]
The WG decided on the above response, so we changed the text in the comment containing the proposed response to read "[Official WG Response]". Please confirm is you are satisfied with the response within 3 days. If we haven't heard a response by then we will regard the resolution as satisfactory.

**Comment by awkawk** [comment]
Leaving open for understanding changes

**Comment by michael-n-cooper** [comment]
Referencing #779 and #780 for actioning.

Please note we have specific issues setup iterative updates to the understanding documents, this issue is not lost, but will be tracked on that issue.
