### ISSUE TITLE
SC 1.4.8 needs better scoping on "blocks of text"; perhaps scope with "In content implemented using markup languages"?

### ISSUE THREAD

**Issue by peterkorn** [w3c/wcag21#756]
In far too many user interfaces, presentation of text in error/dialog boxes may be "more than one sentence of text".  This can be addressed by scoping it to "content implemented using markup languages".

**Comment by awkawk** [comment]
Thank you for commenting. For more information about how the AG WG will process this issue, see the following:
- [Issue Processing](https://www.w3.org/WAI/WCAG21/comments/#issueprocessing) - How the WG will discuss the issue
- [Issue Resolution](https://www.w3.org/WAI/WCAG21/comments/#issueresolution) - Identifying and responding to the official WG response
- [Issue Notification](https://www.w3.org/WAI/WCAG21/comments/#issuenotification) - How to limit notifications from GitHub

**Comment by awkawk** [comment]
(proposed response)
Thank you for the comment. The requirements for WCAG 2.1 (http://w3c.github.io/wcag/wcag21/requirements/) include a requirement for backward compatibility with WCAG 2.0, and this rules out a variety of potential changes, including changes to 1.4.8. We will mark this comment with the "defer" label to ensure that it is considered at the appropriate time.

**Comment by awkawk** [comment]
The WG decided on the above response, so we changed the text in the comment containing the proposed response to read "[Official WG Response]". Please confirm is you are satisfied with the response within 1 week. If we haven't heard a response in a week we will regard the resolution as satisfactory.
