### ISSUE TITLE
Does SC 2.5.4 need a note on completing input using a given modality?  Or text in Understanding?

### ISSUE THREAD

**Issue by peterkorn** [w3c/wcag21#764]
Is there any risk of confusion about operations that may be partially done in one modality needing to be "completable" in another?  E.g. if I'm using a touch screen keyboard and I press the shift key using the touch screen, must I then be able to press an alphanumeric key on a connected physical keyboard to get a capital letter?  I suspect there are a number of corner cases like this that could be very difficult to implement correctly, and for which doing so yields de minimus customer value.  A note or further text in Understanding could help eliminate angst for those cases.

**Comment by awkawk** [comment]
Thank you for commenting. For more information about how the AG WG will process this issue, see the following:
- [Issue Processing](https://www.w3.org/WAI/WCAG21/comments/#issueprocessing) - How the WG will discuss the issue
- [Issue Resolution](https://www.w3.org/WAI/WCAG21/comments/#issueresolution) - Identifying and responding to the official WG response
- [Issue Notification](https://www.w3.org/WAI/WCAG21/comments/#issuenotification) - How to limit notifications from GitHub

**Comment by CityMouse** [comment]
[Proposed response]
Thank you for commenting.
Upon looking at it we propose to add following text to understanding document:

The SC neither mandates nor forbids content authors support multiple modes of input to be used in combination.  This SC does not restrict modes of input and input modes would be dependent on the technology used.

**Comment by awkawk** [comment]
The WG decided on the above response, so we changed the text in the comment containing the proposed response to read "[Official WG Response]". Please confirm is you are satisfied with the response within 3 days. If we haven't heard a response by then we will regard the resolution as satisfactory.
