### ISSUE TITLE
editorial double :: after first bullet in graphic contrast

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/wcag21#766]
https://www.w3.org/TR/WCAG21/#graphics-contrast

**Comment by awkawk** [comment]
@David, I think that this is from the Dec WD since there is no Graphics Contrast SC and I don't see the "::" anymore in the CR.

**Comment by awkawk** [comment]
After double and triple checking this I'm convinced that this isn't an issue in the CR or in the Master branch, so closing.
