### ISSUE TITLE
2.5.1 pointer gestures - clarification about keyboard gestures

### ISSUE THREAD

**Issue by becka11y** [w3c/wcag21#774]
2.5.1 seems clearly targeted to mobile and touch interfaces.  The way it is worded makes be believe it may also apply to mouse dragging.  If that is the case then, is a keyboard equivalent also acceptable?  I would think so but that could be made clearer. 

The understanding document has an example of a slider:"A slider control can be operated by dragging the thumb. Buttons on both sides of the slider increment and decrement the selected value and update the thumb position."

I would guess that incrementing the slider via an arrow or other key press in a desktop environment would also be an acceptable way to meet this SC since it meets,  "Authors must ensure that their content can be operated without complex gestures.?"

It would probably be helpful to include the example of incrementing via key press (via a single switch device, etc) to make it a bit clearer. 

thanks

**Comment by patrickhlauke** [comment]
using keyboard is already covered by 2.1.1. this is specifically about, as per the normative text, making sure that something "can be operated with a single pointer without a path-based gesture".

**Comment by mraccess77** [comment]
@becka11y this was meant to go above keyboard access to make sure that simple gestures can be used without requiring mobile users to have a keyboard.  But as I understand it -- it would also go beyond that to make sure that all pointer gestures including those made with a mouse would have pointer based equivalents that were single point functionable unless essential.  For mouse/touchpad/trackball users this would require alternative gestures that required less fine motor coordination without relying on a keyboard interface.

**Comment by awkawk** [comment]
[Proposed Response]
Thank you for the comment. This SC specifically addresses cases where a multi-point or path-based gesture is used. Using your example of a slider control with a slider head that can be moved left or right in a press and drag gesture, this would need to be possible with a single press, for example on a button that increments up or down or by clicking on a desired position on the slider bar.

The keyboard access requirements in 2.1.1 would apply to the slider control's keyboard access. We will mark this issues with the "understanding" label to remind us to clarify this distinction in the understanding document.

**Comment by awkawk** [comment]
The WG decided on the above response, so we changed the text in the comment containing the proposed response to read "[Official WG Response]". Please confirm is you are satisfied with the response within 3 days. If we haven't heard a response by then we will regard the resolution as satisfactory.

**Comment by awkawk** [comment]
Leaving open for understanding work.

**Comment by becka11y** [comment]
I am satisfied with this response, thank you.

**Comment by michael-n-cooper** [comment]
Referencing #790 for actioning.

Please note we have specific issues setup iterative updates to the understanding documents, this issue is not lost, but will be tracked on that issue.
