### ISSUE TITLE
Understanding   Identify Purpose

### ISSUE THREAD

**Issue by awkawk** [w3c/wcag21#780]
<p>The <a   href="https://www.w3.org/TR/WCAG21/#identify-purpose"   target="_blank">1.3.5 Identify Purpose (AAA) SC</a> has   draft Understanding content that can be viewed at <a href="https://rawgit.com/w3c/wcag21/identify-purpose/understanding/21/identify-purpose.html"   target="_blank">Understanding Identify   Purpose</a>.</p><p>Please review the Understanding document   and submit a comment on this issue for any changes that are needed to the   content.</p>

**Comment by michael-n-cooper** [comment]
Understanding content for this issue should address the change agreed to by the WG in issue #755.

**Comment by lseeman** [comment]
very confused. I added a lot of content 
where is it?

**Comment by michael-n-cooper** [comment]
This issue was moved to w3c/wcag#344
