### ISSUE TITLE
Understanding Reflow

### ISSUE THREAD

**Issue by awkawk** [w3c/wcag21#781]
<p>The <a   href="https://www.w3.org/TR/WCAG21/#reflow"   target="_blank">1.4.10 Reflow (AA) SC</a> has draft   Understanding content that can be viewed at <a   href="https://rawgit.com/w3c/wcag21/reflow/understanding/21/reflow.html"   target="_blank">Understanding   Reflow</a>.</p><p>Please review the Understanding document   and submit a comment on this issue for any changes that are needed to the   content.</p>

**Comment by alastc** [comment]
Actions from isseu #813:

> The issue of what needs to be considered by authors when making decisions about content on a page when implementing a responsive layout needs more attention in the Understanding document.

Also, moving Laura's wiki page into a technique.

**Comment by detlevhfischer** [comment]
I will review this one. Have created a branch for understanding reflow, working on it now:
https://rawgit.com/w3c/wcag21/reflow-comments-Detlev/understanding/21/reflow.html

**Comment by allanj-uaag** [comment]
edits to clarify a bit based on #813 ... https://github.com/w3c/wcag21/edit/reflow-comments-jallan/understanding/21/reflow.html

**Comment by lauracarlson** [comment]
Hello @detlevhfischer and everyone,

After [discussion on the LVTF list](https://lists.w3.org/Archives/Public/public-low-vision-a11y-tf/2018Apr/thread.html#msg22), I suggest adding a bit to first paragraph to make the point that that for people with low vision, enlarged text with reflow is critical. This may be accomplished by adding something such as the [following proposal]( https://lists.w3.org/Archives/Public/public-low-vision-a11y-tf/2018Apr/0025.html) after the first sentence:

>For people with low vision, enlarged text with reflow enables reading. It is critical. Enlargement enables perception of characters. Reflow enables tracking. Tracking is following along lines of text, including getting from the end of one line to the beginning of the next line.

Thank you for your consideration,
Laura

CC @alastc , @WayneEDick , @Ryladog , @mraccess77 , @allanj-uaag

**Comment by alastc** [comment]
Detlev's pull request is for review at #893

**Comment by michael-n-cooper** [comment]
This issue was moved to w3c/wcag#345
