### ISSUE TITLE
Understanding Non-text Contrast

### ISSUE THREAD

**Issue by awkawk** [w3c/wcag21#782]
<p>The   <a href="https://www.w3.org/TR/WCAG21/#non-text-contrast"   target="_blank">1.4.11 Non-text Contrast (AA) SC</a> has   draft Understanding content that can be viewed at <a   href="https://rawgit.com/w3c/wcag21/non-text-contrast/understanding/21/non-text-contrast.html"   target="_blank">Understanding Non-text   Contrast</a>.</p><p>Please review the Understanding   document and submit a comment on this issue for any changes that are needed   to the content.</p>

**Comment by michael-n-cooper** [comment]
Understanding content for this issue should address the change agreed to by the WG in issue #805.

**Comment by bocampbell** [comment]
Review Comments: 

Intent 
- P2 - "controls" is not defined. what is a control? 

Active User Interface Components 
- P2,3  what does it mean for a control to have or not have a visual indicator? 
- P4 this sentence isn't clear to me. visible indication of the hit area doesn't immediately mean anything to me. would this be the cursor turning into a hand? 

Active User Interface Component Examples
- P1 using the term "components" here when "controls" were used early. looking for a specific definition.
- P2 (after table) "html elements" is being used rather than control or component

Inactive User Interface Components
- I typically explain this to designers as a decision about whether the disabled component is meaningful in its disabledness so they can decide how visible to make them.

BREAK POINT. I WILL CONTINUE REVIEWING AGAIN AT MY NEXT OPPORTUNITY.

**Comment by lseeman** [comment]
Can we add that:
For people with cognitive disabilities, it is also recommended to use clear affordances, such that interactive controls are visually discriminable and have a border around the interactive area. Alternitvly  controls are available in a standard style that indicates how they can be used and what action it will trigger or have clearly labeled instructions that explains their use. 
@NeilMilliken any suggested changes?

**Comment by MikeElledge** [comment]
P2 "Regardless of the whether or not there is a visible indication of the hit area for the button, the focus indicator for the component must have sufficient contrast when the component is focused." It might be helpful to mention in the first paragraph that this Success Criteria does not apply to the target (i.e., clickable) area of controls.

Also, like Bo, I don't understand the paragraph about Dynamic Controls.

**Comment by mbgower** [comment]
@alastc , I'm incorporating folks' feedback, but I'm stumped in one place so far:
> like Bo, I don't understand the paragraph about Dynamic Controls.

could we link to that dynamic pie chart as an illustration of dynamic examples, or find a visual to incorporate?

This is really becoming a coherent piece of work overall, but I think the Understanding document could benefit from a whole lot more visual examples, even in the Intent section. It would really solidify understanding for many.

**Comment by mbgower** [comment]
Submitted changes as https://github.com/w3c/wcag21/pull/885
@alastc there are some conflicts, it looks like with something you did with David's feedback. i'll see if I can figure out the issue.

**Comment by alastc** [comment]
> I think the Understanding document could benefit from a whole lot more visual examples, even in the Intent section.

I'll take a look, but if you'd like to put in some suggestions I can try and get some design time. Our designers are **_much_** better & quicker than me if I can give a clear brief.

E.g. @@@ example of graphic showing X and Y.

**Comment by mbgower** [comment]
Okay, here you go, https://github.com/w3c/wcag21/pull/888

**Comment by alastc** [comment]
Added pull request #924 which includes the graphics examples and does some re-structuring.

Mostly editorial and obvious graphics updates. Two key changes though:
- Removed the bit about relative luminance in the 1.4.1 section. I don't think it is an agreed interpretation that each state has to differ from the other states.
- Added a possibly controversial example (4) in the inputs table, similar to an example from the Material Design library.

Probably easiest to read in the [rendered version](https://rawgit.com/w3c/wcag21/non-text-contrast-ac/understanding/21/non-text-contrast.html).

**Comment by michael-n-cooper** [comment]
This issue was moved to w3c/wcag#346
