### ISSUE TITLE
Understanding Content   on Hover or Focus

### ISSUE THREAD

**Issue by awkawk** [w3c/wcag21#784]
<p>The <a   href="https://www.w3.org/TR/WCAG21/#content-on-hover-or-focus"   target="_blank">1.4.13 Content on Hover or Focus (AA)   SC</a> has draft Understanding content that can be viewed at <a   href="https://rawgit.com/w3c/wcag21/content-on-hover-or-focus/understanding/21/content-on-hover-or-focus.html"   target="_blank">Understanding Content on Hover or   Focus</a>.</p><p>Please review the Understanding document   and submit a comment on this issue for any changes that are needed to the   content.</p>

**Comment by StommePoes** [comment]
Has there already been a discussion about adding screenshots to visually illustrate some of the examples (of both problems and solutions)? This is a good candidate.

**Comment by alastc** [comment]
@guyhickling noted that the understanding doc doesn't match the SC text anymore in issue #807

**Comment by mbgower** [comment]
> @guyhickling noted that the understanding doc doesn't match the SC text anymore in issue #807

I believe I resolved many of those concerns in changes on a commit on April 6th. Guy is correct that there is still language about a hidden trigger, but that IS a consideration in all this (although no longer in the SC wording) -- if the new content obscures the target, it is at least a potentially confusing experience which should be down as a consideration/best practice. I'm reviewing, so I'll try to clean up.

**Comment by mbgower** [comment]
Created minor changes to contain visible trigger language to align with SC wording . https://github.com/w3c/wcag21/pull/869
@steverep you may want to review.

**Comment by lseeman** [comment]
under Hoverable i would add that the content should stay visable while the pointer in on any  direct paths between the triger and the new content . Otherwise the content disapears

**Comment by alastc** [comment]
> content should stay visible while the pointer in on any direct paths between the trigger and the new content . Otherwise the content disappears

Some of the better hoverable menus use a time-out to control when the additional content disappears which helps with cutting corners. For example, if you go to [John Lewis](https://www.johnlewis.com/) and hover over 'furniture and lights', then move the mouse to 'lighting' on the right, it doesn't matter if you clip 'electrical'. Saying 'direct paths' doesn't work for that.

I don't think that is a reasonable requirement to add, especially in the understanding document.

**Comment by alastc** [comment]
From #808 we agreed that the third bullet in 'Additional notes' should be:
> Content which can be triggered via pointer hover must also be accessible via the keyboard. Refer to Success Criterion 2.1.1, Keyboard.

Also, consider adding a note below that to the effect that it's bad usability to display things on focus and on hover (rather than after an explicit action by the user).

**Comment by michael-n-cooper** [comment]
This issue was moved to w3c/wcag#348
