### ISSUE TITLE
Understanding   Animation from Interactions

### ISSUE THREAD

**Issue by awkawk** [w3c/wcag21#786]
<p>The <a   href="https://www.w3.org/TR/WCAG21/#animation-from-interactions"   target="_blank">2.2.7 Animation from Interactions (AAA)   SC</a> has draft Understanding content that can be viewed at <a   href="https://rawgit.com/w3c/wcag21/animation-from-interactions/understanding/21/animation-from-interactions.html"   target="_blank">Understanding Animation from   Interactions</a>.</p><p>Please review the Understanding   document and submit a comment on this issue for any changes that are needed   to the content.</p>

**Comment by lseeman** [comment]
a change of brighness is another good example

**Comment by goodwitch** [comment]
I reviewed the Understanding doc for Animations from Interactions.  I made changes (with Alastair's blessing) to make it easier to read/understand (at least according to the HemingwayApp.  The pull request is awaiting Alastair's review at https://github.com/w3c/wcag21/pull/874

**Comment by michael-n-cooper** [comment]
This issue was moved to w3c/wcag#350
