### ISSUE TITLE
Understanding   Character Key Shortcuts

### ISSUE THREAD

**Issue by awkawk** [w3c/wcag21#787]
<p>The <a   href="https://www.w3.org/TR/WCAG21/#character-key-shortcuts"   target="_blank">2.4.11 Character Key Shortcuts (A) SC</a>   has draft Understanding content that can be viewed at <a   href="https://rawgit.com/w3c/wcag21/character-key-shortcuts/understanding/21/character-key-shortcuts.html"   target="_blank">Understanding Character Key   Shortcuts</a>.</p><p>Please review the Understanding   document and submit a comment on this issue for any changes that are needed   to the content.</p>

**Comment by joshueoconnor** [comment]
Too many commas. Consider writing shorter sentences.

**Comment by mbgower** [comment]
I have made various editorial changes for clarity and consistency and created [Pull Request 801](https://github.com/w3c/wcag21/pull/801).
I also removed Example 4, which does not seem to meet the requirements of the SC. I am pasting it here for reference:
<h3><strong>Example 4: Native Speech Alternate Control</strong></h3>
<p>A mechanism is provided to allow users to change character-key shortcuts including to strings of up to 25 characters. These can directly serve as native speech commands for any speech engine.</p>

**Comment by awkawk** [comment]
@mbgower Process correction for you - don't worry about making a pull request from the Character key shortcut understanding document into the Master branch - once the group agrees with the content we will handle it.

If you feel like you have significant changes that you want to suggest, then create a branch for those changes and once people review them we can pull them into the Character-key-shortcut branch and THEN we can do the pull and merge into Master.

I think that removing example 4 is one change that I would want to make sure that the TF was in agreement on, but the way you did it here that example won't be in the rawgit version linked in this issue.

**Comment by lauracarlson** [comment]
Editorial comment:

To match the other Understand documents, consider starting the Intent section with, "The intent of this success criterion is..."  It is a good way to get straight to the point.

**Comment by lseeman** [comment]
Can we add that: allowing all short cut keys to be personlized and remaped could help all users , as the same keys can have the same actions across all content. This is particularly helpful for people with impaired memory function or reduced learning speed.

**Comment by michael-n-cooper** [comment]
This issue was moved to w3c/wcag#351
