### ISSUE TITLE
Understanding Pointer   Gestures

### ISSUE THREAD

**Issue by awkawk** [w3c/wcag21#790]
<p>The <a   href="https://www.w3.org/TR/WCAG21/#pointer-gestures"   target="_blank">2.5.1 Pointer Gestures (A) SC</a> has   draft Understanding content that can be viewed at <a   href="https://rawgit.com/w3c/wcag21/pointer-gestures/understanding/21/pointer-gestures.html"   target="_blank">Understanding Pointer   Gestures</a>.</p><p>Please review the Understanding   document and submit a comment on this issue for any changes that are needed   to the content.</p>

**Comment by michael-n-cooper** [comment]
Understanding content for this issue should address the change agreed to by the WG in issue #774 .

**Comment by joshueoconnor** [comment]
@greglowney has provided the following re-write in a Word doc with track changes. It just needs to go into a PR. Thanks Greg.

[2018-04-20 Understanding Pointer Gestures - review.docx](https://github.com/w3c/wcag21/files/1934381/2018-04-20.Understanding.Pointer.Gestures.-.review.docx)

**Comment by lseeman** [comment]
i dont think having diffrent things for single tap and double tap and long tap is good for  users with cognitive or learning disabilities. can you explain were this is coming from?

**Comment by detlevhfischer** [comment]
I think Gerg's changes and extensions of this understanding text review much improve it.
One issue that still needs addressing is the comment regarding the single pointer glossary definition ( #868 )
wich currently does not match the use in SC Pointer Gestures (and its understanding text).

**Comment by detlevhfischer** [comment]
@lseeman 
I am not sure what you mean by "having different things" for single tap and double tap and long tap. Ideally (and this is what we had in an early version of this SC) the requirement would be that everything can (also) be done by single taps only. 
Then we got comments that stressed that web apps may need to support pointer gestures known from the non-web-world and OSs, and that large systems out there rely on differentiating between single click/tap and click-and-hold/long-press input.  An example were sortable tables where a single click on an icon in the column header may invert sorting order, while a click-and-hold gesture woud bring up a menue. It was argued that allowing single untimed pointer gestures only would (in the case of such tables, for example) force the addition of additional controls to show the menu, which would increase visual noise and cognitive complexity and add additional tab stops for keyboard users, so it would slow down or have disadvantages for other users. In sum, a typical trade-off situation. 
These arguments led to the weakening of the definition of "single pointer" to encompass double tap/click and long presses. ("Path-based" however got into the current "single pointer" definition by mistake, in my view.)

**Comment by lseeman** [comment]
by "having different things" i mean having different functionality. It is hugely confusing when that is the default design

**Comment by mraccess77** [comment]
Does the exception for user agent based gestures apply to standard controls like input type range with a slider?  If the author uses a built-in slider that requires dragging does that pass because it's controlled by the user agent and not customized?

**Comment by patrickhlauke** [comment]
To be hardline, I'd say yes it should, as it's then the user agent's responsibility to provide alternatives that work well for all users.

**Comment by michael-n-cooper** [comment]
Moved to https://github.com/w3c/wcag/issues/354
