### ISSUE TITLE
Understanding Pointer   Cancellation

### ISSUE THREAD

**Issue by awkawk** [w3c/wcag21#791]
<p>The <a   href="https://www.w3.org/TR/WCAG21/#pointer-cancellation"   target="_blank">2.5.2 Pointer Cancellation (A) SC</a> has   draft Understanding content that can be viewed at <a   href="https://rawgit.com/w3c/wcag21/pointer-cancellation/understanding/21/pointer-cancellation.html"   target="_blank">Understanding Pointer   Cancellation</a>.</p><p>Please review the Understanding   document and submit a comment on this issue for any changes that are needed   to the content.</p>

**Comment by mbgower** [comment]
I think in order to complete an analysis of this Understanding document, we must resolve the [existing issue with the SC wording](https://github.com/w3c/wcag21/issues/773). I have proposed splitting Undo/Abort into separate bullets to address.
Existing

> Abort or Undo
>    Completion of the function is on the up-event, and a mechanism is available to abort the function before completion or undo the function after completion;

Proposed:

- Undo:
    A mechanism is available to undo the function after completion;
- Abort:
     Where completion of the function is on the up-event, a mechanism is available to abort the function before completion;

**Comment by joshueoconnor** [comment]
The understanding documentation is good. One suggestion, where it says:
"Despite its name, the onclick event handler works both for mouse interaction as well as for touch interaction."

that should also cover keyboard a11y:

"Despite its name, the onclick event handler works both for mouse interaction as well as for keyboard and touch interaction.

**Comment by lauracarlson** [comment]
The understanding documentation is good.  One typo: "ony occurs " should be "only occurs ".

**Comment by michael-n-cooper** [comment]
Understanding content for this issue should address the change agreed to by the WG in issue #773.

**Comment by lseeman** [comment]
I would like to add that providing an easy way for users to undo any action is a recommended practice. For example, many users with mild cognitive disabilities or learning disabilities may activate events unintentionally and need a clear way to get back to  the previous state of the content

**Comment by alastc** [comment]
Adding comment from #837 from @cyns:
> Despite its name, the Click event is a device-independent up-event. Please clarify that Click/onclick are an up-event. (probably in Understanding? or linking to some of the existing onclick techniques?)

**Comment by mbgower** [comment]
I have created a pull request which I believe addresses these concerns https://github.com/w3c/wcag21/pull/884. It is ready for WG review, so I am adding that label.

**Comment by michael-n-cooper** [comment]
This issue was moved to w3c/wcag#355
