### ISSUE TITLE
See All Elements

### ISSUE THREAD

**Issue by allanj-uaag** [w3c/wcag21#80]
<h2>SC Shortname</h2>
<p>Seeing all elements </p>
<h2>SC Text</h2>
<p>Users can see and interact with all content and user interface controls presented visually, including when users have changed display settings such as text size. </p>
<h2>Suggested Priority Level</h2>
<p>Level AA </p>
<h2>Related Glossary additions or changes</h2>
<p>None </p>
<h2>What Principle and Guideline the SC falls within.</h2>
<p>Principle 1, Guideline <a href="https://www.w3.org/TR/2008/REC-WCAG20-20081211/#visual-audio-contrast-visual-presentation"> 1.4.8 Visual Presentation</a> or 
  Principle 1, Guideline <a href="https://www.w3.org/TR/2008/REC-WCAG20-20081211/#visual-audio-contrast-scale"> 1.4.4 Resize text</a> ?? </p>
<h2>Description</h2>
<p>Simply Put: Enlarged text fits in text boxes, content does not overlap, and button content stays on the page. </p>
<h2>Benefits</h2>
<blockquote>
  <p>When people increase text size, increase line spacing, or change other text display aspects through text-only zoom or other text settings, content that is poorly designed can become unusable. For example, with text areas in web pages, sometimes columns and sections overlap, the space between lines disappears, lines of text become too long, or text disappears. </p>
  <p> Figure 14: Example showing that when text size is increased, the heading overlaps the main text, the main text overlaps the sidebar text, and the sidebar text is cut off at the bottom. </p>
  <p> <img src="https://www.w3.org/WAI/GL/low-vision-a11y-tf/wiki/images/7/71/Zoom-100.png" alt="web page with larger text"/> <img src="https://www.w3.org/WAI/GL/low-vision-a11y-tf/wiki/images/2/2a/Zoom-overlap.png" alt="web page with larger text, text overlapping other text"/> </p>
  <p>Often it is best for text areas to automatically resize to fit the text, and for users to be able to change the size of text areas. When the areas cannot be resized to accommodate all content, usually a scrollbar should be available. See also the <a href="http://w3c.github.io/low-vision-a11y-tf/requirements.html#rewrap-for-one-direction-scrolling"> Rewrap for one direction scrolling</a> section. </p>
  <p>When people use large fonts or lower screen resolution, it is not uncommon for dialog boxes to include information that is not in the viewport. In such cases, it is usually best practice for scrollbars to be provided for the dialog box. </p>
  <p>Scrollbars generally provide the additional benefit of communicating where the user is in an interface. </p>
  <p>Some users increase the size of mouse pointers in their operating system or with screen magnification software. These should not overlap tooltip text. </p>
  <p>Source: <a href="http://w3c.github.io/low-vision-a11y-tf/requirements.html#seeing-all-interface-elements"> Accessibility Requirements for People with Low Vision, Section 3.7.1</a></p>
</blockquote>
<strong>User Need</strong>: All Elements
<blockquote> Users can see and interact with all content and user interface controls presented visually, including when users have changed display settings such as text size, magnification, and cursor appearance. </blockquote>
<h2>Testability</h2>
<ol>
  <li> Display content in a user agent. </li>
  <li> Increase text size in user agent settings </li>
  <li> Check whether all content is perceivable with no loss of content or functionality (e.g., text does not overlap, buttons remain visible, etc.). </li>
</ol>
<p>Expected Results</p>
<ul>
  <li> Check #2 is true. </li>
</ul>
<h2>Techniques</h2>
<h4>Related Existing Technique</h4>
<ul>
  <li><a href="https://www.w3.org/TR/WCAG20-TECHS/F69.html"> F69: Failure of Success Criterion 1.4.4 when resizing visually rendered text up to 200 percent causes the text, image or controls to be clipped, truncated or obscured</a></li>
  <li> <a href="https://www.w3.org/TR/WCAG20-TECHS/F80.html"> F80: Failure of Success Criterion 1.4.4 when text-based form controls do not resize when visually rendered text is resized up to 200%</a></li>
</ul>
<h4>New Techniques</h4>
<p>none </p>
<h2>Related Information</h2>
<h3>Actions </h3>
<ul>
  <li><a href="https://www.w3.org/WAI/GL/low-vision-a11y-tf/track/actions/39"> ACTION-39: Craft user need on obscured perception and operability</a> On Wayne Dick, 2 March 2016</li>
  <li> <a href="https://www.w3.org/WAI/GL/low-vision-a11y-tf/track/actions/25"> Think about 3.7.1 seeing all interface elements with andrew and others input from 20 jan telecon</a> On Shawn Henry, 20 January 2016 </li>
</ul>
<h3>Articles </h3>
<ul>
  <li><a href="http://simplyaccessible.com/article/title-attributes/"> Title Attributes</a> - Joanna Briggs, (Article regarding tooltips and large cursors. "When hovering over a link that has a title attribute, the large mouse pointer covers the start of the title attribute. Longer title attributes may not fit inside the viewport with higher levels of magnification.")</li>
  <li> <a href="http://www.d.umn.edu/~lcarlson/wcagwg/obscured_tooltip_on_hover/index.html"> Obscured Tooltip on Hover</a> - Laura Carlson</li>
  <li> <a href="http://www.d.umn.edu/~lcarlson/wcagwg/obscured_tooltip_on_hover/test.html"> Obscured Tooltip Test</a> - Laura Carlson</li>
</ul>
<h3> Email </h3>
<ul>
  <li><a href="https://lists.w3.org/Archives/Public/public-low-vision-a11y-tf/2016Oct/0048.html"> Resize Content, Size of All Interface and Resize Text.</a> - Laura Carlson, 18 October 2016 </li>
  <li> <a href="https://lists.w3.org/Archives/Public/public-low-vision-a11y-tf/2016Oct/0049.html"> Resize Content, Size of All Interface and Resize Text.</a> Erich Manser, 18 October 2016 </li>
  <li> <a href="https://lists.w3.org/Archives/Public/public-low-vision-a11y-tf/2016Oct/0050.html"> Re: Resize Content, Size of All Interface and Resize Text.</a> - Wayne Dick, 18 October 2016 </li>
  <li> <a href="https://lists.w3.org/Archives/Public/public-low-vision-a11y-tf/2016Oct/0055.html"> Re: Resize Content, Size of All Interface and Resize Text.</a> - Laura Carlson, 19 October 2016 </li>
  <li> <a href="https://lists.w3.org/Archives/Public/public-low-vision-a11y-tf/2016Oct/0063.html"> Re: Resize Content, Size of All Interface and Resize Text.</a> - Alastair Campbell, 19 October 2016</li>
  <li> <a href="https://lists.w3.org/Archives/Public/public-low-vision-a11y-tf/2016Oct/0067.html"> Re: Resize Content, Size of All Interface and Resize Text.</a> - Laura Carlson, 20 October 2016</li>
  <li> <a href="https://lists.w3.org/Archives/Public/public-low-vision-a11y-tf/2016Oct/0068.html"> Re: Resize Content, Size of All Interface and Resize Text.</a> - Alastair Campbell, 20 October 2016</li>
  <li> <a href="https://lists.w3.org/Archives/Public/public-low-vision-a11y-tf/2016Oct/0071.html"> Re: Resize Content, Size of All Interface and Resize Text.</a> - Laura Carlson, 20 October 2016</li>
  <li> <a href="https://lists.w3.org/Archives/Public/public-low-vision-a11y-tf/2016Sep/0047.html"> 1st draft: Seeing All Interface Elements SC</a> - Laura Carlson, 12 September 2016</li>
  <li> <a href="https://lists.w3.org/Archives/Public/public-low-vision-a11y-tf/2016Mar/thread.html#msg24"> Thread: Obscuring active elements and text</a> - March 2016 </li>
  <li><a href="https://lists.w3.org/Archives/Public/public-low-vision-a11y-tf/2016Mar/thread.html#msg4"> lvtf-ACTION-39: Craft user need on obscured perception and operability</a> - March 2016</li>
</ul>
<h3> GitHub </h3>
<ul>
  <li> <a href="https://github.com/w3c/wcag21/issues/8"> WCAG WG Github Issue 11</a> - Opened by Jim Allan, September 15 2016 </li>
  <li><a href="https://github.com/w3c/low-vision-a11y-tf/blob/a4e633a7fc5bd59cbb0af5530af0d39051ec143a/WC-UA-alignment.html"> WC-UA-alignment.html</a> </li>
</ul>
<h3>Minutes </h3>
<ul>
  <li><a href="https://www.w3.org/2016/12/01-lvtf-minutes.html#item07"> 1 December 2016 LVTF Minutes</a> </li>
  <li><a href="https://www.w3.org/2016/10/13-lvtf-minutes.html"> 13 October 2016 LVTF Minutes</a> </li>
  <li><a href="https://www.w3.org/2016/09/15-lvtf-minutes.html#item03 15 September 2016 LVTF minutes</a>
*<a href="https://www.w3.org/2016/05/19-lvtf-minutes.html#item06"> 19 May 2016 LVTF minutes</a> </li>
  <li><a href="http://www.w3.org/2016/03/09-lvtf-minutes.html#item06"> 9 March 2016 LVTF minutes</a> - Craft user need on obscured perception and operability</li>
  <li> <a href="http://www.w3.org/2016/03/09-lvtf-minutes.html#resolution01"> RESOLUTION</a> "All Elements: Users can see and interact with all content and user interface controls presented visually, including when users have changed display settings such as text size, magnification, and cursor appearance."</li>
  <li> <a href="https://www.w3.org/2016/01/20-lvtf-minutes.html#item02"> 20 January 2016 LVTF minutes</a></li>
</ul>
<h3>Resolutions </h3>
<ul>
  <li><a href="https://www.w3.org/2016/12/01-lvtf-minutes.html#resolution07"> Ready for WCAG</a> - 1 December 2016 </li>
</ul>
<h3>Surveys </h3>
<ul>
  <li> <a href="https://www.w3.org/2002/09/wbs/81151/lvtf18jan2016/results#xseeall"> Should this be one point or more than one?</a> 18 January 2016 LVTF</li>
</ul>
<h3> Survey Results</h3>
<h3> TPAC 2016</h3>
<ul>
  <li> <a href="https://www.w3.org/2016/09/19-wai-wcag-minutes.html"> TPAC Minutes</a> - September 19, 2016
    <ul>
      <li> AC: There is a requirement for increasing the size of text without increasing other elements. </li>
      <li> AC: What is the problem with also zooming images? </li>
      <li> JF: Horizontal scroll.
        RM: Is that a failure? </li>
      <li> JA: Dont know if it is.
        AWK: Its not when things go off a page?</li>
      <li> AC: With a RWD that shouldn't happen.</li>
      <li> AC: Its only the text only version of this thats the problem.</li>
      <li> david-macdonald: Wiki Page: <a href="https://www.w3.org/WAI/GL/wiki/Possible_wording_from_Jason/David_for_LVTF_re:_zoom_without_horizontal_scroll"> Possible wording from Jason/David for LVTF re: zoom without horizontal scroll</a> </li>
      <li> MichaelC: The proposed wording doesn't seem to achieve what I think it aims to do. Some aspects are supposed to be true at all times, but this only upto 200%? Gets confused when expanding a guideline. 1.4.8 (triple A). </li>
      <li> JamesN: Doesn't 1.4.4 cover this, as overlapping text is an issue then. Tooltips are an issue, but then they don't work in other cases either.</li>
      <li> Rachael: If this goes forward, I'd ask for technical constraints like how much zoom, what size etc.</li>
      <li> David: We have worked on an expansion to 1.4.4, not specifically on the overlapping issue but it is in the same space. </li>
    </ul>
  </li>
  <li> <a href="https://lists.w3.org/Archives/Public/public-low-vision-a11y-tf/2016Sep/0062.html"> Jim's TPAC notes</a> - 27 September 2016
    <ol>
      <li> increase text size only is an issue. conflicts with responsive design </li>
      <li> sc should be reworded to specifically talk about overlapping content not obscuring other content.</li>
      <li> what is difference between this and WCAG 1.4.4 - seems identical. </li>
    </ol>
  </li>
</ul>
<h3>Wiki Pages </h3>
<ul>
  <li><a href="https://www.w3.org/WAI/GL/low-vision-a11y-tf/wiki/User_stories_-_use_cases"> Obscured Tooltip on Hover</a> - Use case Wiki page, Laura, UC-5.</li>
  <li> <a href="https://www.w3.org/WAI/GL/low-vision-a11y-tf/wiki/LVTF_Open_Issues#Work_with_User_Settings"> Work with User Settings</a> </li>
</ul>

**Comment by DavidMacDonald** [comment]
Seems to be a duplicate with Issue #8

**Comment by allanj-uaag** [comment]
Closed, covered by #77  and #58

**Comment by allanj-uaag** [comment]
# A test heading
