### ISSUE TITLE
SC1.4.13 - Understanding document different to the SC

### ISSUE THREAD

**Issue by guyhickling** [w3c/wcag21#807]
The Understanding document for SC1.4.13 (Content on Hover or Focus), in the 30 Jan 2018 release, has a section headed "1. Visible Trigger". This section, including the things said in its content, no longer aligns with the SC itself. The first requirement in the SC is now "Dismissable" and is rather different from the original version.

Some of the content in this section of the Understanding document, especially the stuff about obscuring the trigger, needs to be deleted or reworded to align with what the SC now says.

**Comment by allanj-uaag** [comment]
Thanks for the comment, the working group is aware of this issue and it is actively being worked on by @steverep. We will be re-issuing an updated Understanding doc in due course that will contain the new information.

**Comment by alastc** [comment]
This is being worked on, if you track #784 you'll get any updates.

I'm going to close this issue as effectively a duplicate, but it's not lost, I'll tag it from there as well.
