### ISSUE TITLE
Let's limit Duplicate ids in 4.1.1

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/wcag21#81]
Proposed change to 4.1.1 for WCAG 2.1

Most duplicate ids are not a problem for accessibility. Only IDs referenced by Assistive Tech. aare affected (`<input>`, aria references etc.) This can end up eating up accessibility budgets for remediation which could be put towards making the site more accessible.

Current
4.1.1 Parsing: In content implemented using markup languages, elements have complete start and end tags, elements are nested according to their specifications, elements do not contain duplicate attributes, and any IDs are unique, except where the specifications allow these features. (Level A)

Proposed
4.1.1 Parsing: In content implemented using markup languages, elements have complete start and end tags, elements are nested according to their specifications, elements do not contain duplicate attributes, and any IDs are unique **`<add>that are referenced by assistive technology</add>`**, except where the specifications allow these features. (Level A)

# Note:
The only issue is whether this is backwards compatible with WCAG 2 which requires ALL ids to be unique.

**Comment by mattgarrish** [comment]
This sounds troubling from a publishing perspective. Duplicate IDs break navigation and can cause problems for annotating documents, and those just jump immediately to mind.

Yes, these problems will manifest for everyone, but trying to figure out which IDs are valueless, if any, seems like more work than just fixing any duplicates.

**Comment by jnurthen** [comment]
Wouldn't this be a problem from a backwards compatibility standpoint too? If the aim is that something complying with 2.1 automatically meets 2.0 then this would break this model.

**Comment by DavidMacDonald** [comment]
Both the previous comments are reasons not to proceed with this recommendation. I withdraw the issue for 2.1.
