### ISSUE TITLE
Special mention of box-shadow and Windows High Contrast?

### ISSUE THREAD

**Issue by StommePoes** [w3c/wcag21#811]
I don't know if it is too technology-specific for a mention, but many developers wanting to conform to 1.4.11 will not know about box-shadow specifically (as opposed to border or outline) going completely invisible in Windows High contrast. Often while a border is used to show the component, a box-shadow would for example do the job of showing a focus or error state.

Box shadow'd input:
![An input type=text whose edges are only shown using a grey box shadow](https://user-images.githubusercontent.com/136210/37742285-4864ceb2-2d65-11e8-89e1-a66629a1b80a.png)

...in Windows High Contrast (ZoomText happens to also be running)
![The same input in Windows High Contrast (a default theme). ZoomText is also running and is showing focus on a link further down. The input is completely invisible.](https://user-images.githubusercontent.com/136210/37742303-5ecc0990-2d65-11e8-9b22-f070cbb79189.png)

Input's focus only visible from ZoomText. Only the cursor is default (and it's set thicker than normal in Windows Accessibility settings).
![The same input being focussed. The cursor is visible, but the focus ring seen is coming from ZoomText. Without ZoomText running, no focus ring would be visible.](https://user-images.githubusercontent.com/136210/37742330-7aa8e458-2d65-11e8-9217-8dbc71e01f21.png)

**Comment by jake-abma** [comment]
@StommePoes good point but turning MS high contrast mode on specifically will not be part of conformance. Also High Contrast Modes differ by program and operating system.

So what are you suggesting to add?

Will it be enough to add a technique explaining this and maybe add the **-ms-high-contrast media feature** OR do you think MS should fix it so we need to add an issues for Windows?

Or, as we're talking about box-shadow, and thus it's not part of the 'foreground color' nor 'background' as mentioned in https://www.w3.org/TR/WCAG20-TECHS/F24.html we need another Failure like this but than with box-shadow i.c.w. borders...?

My opinion would be for MS to fix this.

**Comment by StommePoes** [comment]
I was thinking more of a warning in a supporting doc (either as an example in understanding or a note in meeting), since it is software-specific (I don't believe this is an issue on Macs for example). Background images vanishing while they may contain important information (such as an icon) is a long-time, known problem (though not all devs know that one either).

**Comment by Ryladog** [comment]
It could possibly be identified as a failure

** katie **

**Comment by awkawk** [comment]
Thank you for the comment. We will mark this issue with the "understanding" label to ensure that it is considered as we work on our edits to those resources.
