### ISSUE TITLE
Consider lightboxes for 'How to meet...' and 'Understanding...' 

### ISSUE THREAD

**Issue by devarshipant** [w3c/wcag21#812]
There are numerous ways to get overwhelmed reading WCAG and when additional windows / tabs open from within page, it becomes a complex document to navigate. Would it help usability if the 'How to ...' and 'Understanding ...' links opened modals? I think when a Success Criterion serves as the background for lightbox, it may make the document more readable when keyboard focus is back on the link that opens the lightbox.

**Comment by awkawk** [comment]
Thank you for the comment. In the WCAG 2.1 spec we are constrained by the template provided by the W3C for specs. If you have suggestions that impact the content of the understanding documents or techniques we do have more control over those and appreciate any input.

**Comment by devarshipant** [comment]
thanks @awkawk -- shouldn't there be a usability study on the use of lightbox dialogs within WCAG 2.1? You may have noticed, clicking in-page links causes major disruption in the flow. Clicking 'How to meet...' and 'Understanding...' is a distraction when focus is in a new tab.
