### ISSUE TITLE
At a talk question was Does the full his aria need to have a visual indicator with passing contrast/

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/wcag21#814]
[EDIT: Adding the resulting question as description]

The question was... what if there is an button that is an icon like a ">" or something and no visual affordance for the button (border or shading on the button) does the contrast requirement kick in for the whole hit area OR only when there is a visual indicator for the button.

He wondered if the contrast ONLY for the > would need to apply, and not for the total hit area, I don't remember any conversation about it on meetings so I said we'd have to discuss it and add to the understanding anything that isn't clear.

**Comment by awkawk** [comment]
Thank you for commenting. For more information about how the AG WG will process this issue, see the following:
- [Issue Processing](https://www.w3.org/WAI/WCAG21/comments/#issueprocessing) - How the WG will discuss the issue
- [Issue Resolution](https://www.w3.org/WAI/WCAG21/comments/#issueresolution) - Identifying and responding to the official WG response
- [Issue Notification](https://www.w3.org/WAI/WCAG21/comments/#issuenotification) - How to limit notifications from GitHub

**Comment by awkawk** [comment]
@DavidMacDonald Can you clarify this question - I don't understand what it is actually saying...

**Comment by DavidMacDonald** [comment]
The question was... what if there is an button that is an icon like a ">" or something and no visual affordance for the button (border or shading on the button) does the contrast requirement kick in when a hit area is present OR only when there is a visual indicator for the button.

He wondered if the contrast ONLY for the > would need to apply, and not for the total hit area,  I don't remember any conversation about it on meetings so I said we'd have to discuss it and add to the understanding anything that isn't clear.

**Comment by awkawk** [comment]
I would say that when you have a button and the only aspect of the button that is discernible is the text ">" then that is the only part that needs to meet WCAG contrast. If the button has a border then the non-text contrast SC kicks in.

**Comment by DavidMacDonald** [comment]
I agree... 
> ... Visual information used to indicate states and boundaries of user interface components, ...

The the example there is no visual information used to indicate the boundaries for ANYONE, so there is no requirement for it to be at a particular contrast ... I suggest we add to Understanding something like the following:

> If there is an interface component that has only text and no other visual information or affordance (such as border or shading)  the contrast requirement does not kick in for the whole hit area. The contrast requirement only kicks in when there is a visual indicator for the interface component. However, the focus indicator when it lands on the component would have to have sufficient contrast.

**Comment by awkawk** [comment]
@DavidMacDonald I added:

Regardless of the whether or not there is a visible indication of the hit area for the button, the focus indicator for the component must have sufficient contrast when the component is focused.

If you're happy and think that this is addressed, feel free to close the issue.

**Comment by StommePoes** [comment]
I was wondering the same thing as the guy asking the question, since "icon buttons" are what he's talking about (a "x" close button where all you see is the X is quite common).

Some ideas of possible test cases http://www.stommepoes.nl/work/button.html  I would certainly want to fail the focus states on these since while it may be visible in Firefox or IE, it's absolutely invisible in blink browsers or whoever adds blue focus rings.

**Comment by jake-abma** [comment]
It's not only about icons, but could be images, emoji etc. so we should add something like:

> If there is an interface component that has only an icon, graphic or other non-text visual and no other visual information or affordance...

It's not only about buttons so would change it back to UIC:

> Regardless of the whether or not there is a visible indication of the hit area for the user interface component, the focus indicator for the component must have sufficient contrast when the component is focused.

@StommePoes With Focus Visible SC 2.4.7 and Non-text Contrast SC 1.4.11 I think you're totally covered and the fail kicks in for the blue-on-blue

**Comment by mraccess77** [comment]
The issue we struggled with before is -- is the greater than considered text by the definition of text required by 1.4.3.   I suppose it depends on how you interpret it?

Definition "text: sequence of characters that can be programmatically determined, where the sequence is expressing something in human language"

Some have said icons don't fit into this -- while others have.  Greater than seems to fall more closely into this definition -- but is 1 character a sequence?  If greater than is text then why would a heart icon not be text?

**Comment by alastc** [comment]
I agree with Andrew's update.

For @mraccess77: We have a few potential ways of defining text vs images for 1.4.3 / 1.4.11, but the result would mean testing against 4.5:1 and 3:1, both would now require contrast.

The possible scenarios I can think of are Xs which are:

1. Created with text, displayed as text.
2. Created with a custom font-icon, displayed as a text.
3. Created with a vector editor using text, displayed as an SVG with text in it.
4. Created with a vector editor using line drawing, displayed as an SVG.
5. Created with a graphical editor using a text editing part of the program, displayed as a raster image (e.g. jpg/gif/png)
6. Created with a graphical editor using line-drawing (not text), displayed as a raster image.

We basically have some Venn diagrams of overlapping things going on, although 1 and 6 are clear cut, the others all have varying properties that affect readability (e.g. changing display preferences can change the colours of 1 & 2, but not 3-6).

Personally, I would rather not have to work that out in every instance. If it is showing an icon then it isn't a sequence of characters, it's a graphic and can be tested at 3:1.

**Comment by mraccess77** [comment]
Hi @alastc this SC was initially indicated at risk -- if the SC continues forward which I think it will and I hope it is the case it will be the difference between 3:1 and 4.5:1 as you said any icons of 1 character of text including an asterisk, less than, ampersand, etc. would then need to meet 3:1.  However, if this SC were to not make it -- then I think this group would need to be prepared to determine whether a character such as these would fall under 1.4.3 or have no contrast requirement.  Either way use of characters like this is something we will need to document in understanding materials to be sure that all providing guidance and testing will give clear and consistent feedback to authors.

**Comment by alastc** [comment]
A single character icon doesn't appear to match the definition of text, can you point to someone saying that? I'd like to know the rational.

**Comment by mraccess77** [comment]
@alastc -- It was a question -- although In some languages like Korean a whole word maybe one character.    Would those single character words not need to meet SC 1.4.3?

**Comment by alastc** [comment]
Fair point, but thinking about it, we are best off using a user-side metric rather than how it is created. 

For example, if it means "X" as human language, then it is text rather than icon.

However, if it means "close", represented by an x icon, then it is image. 

But, this is a tangent, the original question around content vs outline has been answered.

**Comment by DavidMacDonald** [comment]
@awk
> Regardless of the whether or not there is a visible indication of the hit area for the button, the focus indicator for the component must have sufficient contrast when the component is focused.

> If you're happy and think that this is addressed, feel free to close the issue.

I would add A sentence before that.

>If only the text is visible and there is no visual indication of the hit area, then there is no contrast requirement beyond the text contrast  (as per 1.4.3) or icon contrast as per this Success Criteria. Regardless of the whether or not there is a visible indication of the hit area for the button, the focus indicator for the component must have sufficient contrast when the component is focused.

**Comment by awkawk** [comment]
@DavidMacDonald can you add that to understanding and then we can close this issue?

**Comment by DavidMacDonald** [comment]
I've done that, I suggest we wait until Pull request is incorporated before closing.
