### ISSUE TITLE
Character Key Remap Misunderstanding

### ISSUE THREAD

**Issue by kwahlbin** [w3c/wcag21#817]
**From Kim Patch:**  The “string of up to 25 characters” mechanism was removed from Character Key Shortcuts understanding as there was misunderstanding as to what was meant by mechanism in _2.4.11 Remap A mechanism is available to remap the shortcut to use one or more non-printable keyboard characters (e.g. Ctrl, Alt, etc)._

The following text was removed:
_“Providing a mechanism to adjust any customizable key shortcut on the webpage to an alternative control of a string of up to 25 Characters, including spaces.”_

Removing this is counterproductive in terms of what this SC aims to accomplish. This would discourage an author from enabling speech users to use the best type of shortcuts for speech commands.

This was noted in this thread: https://github.com/w3c/wcag21/issues/769. 

**The suggested change to clarify what is meant by SC 2.4.11 Remap** is to add the following to the understanding document:

A mechanism is provided to allow users to change character-key shortcuts. The remapping mechanism includes non-printing characters. The alternative shortcuts could be longer strings of up to 25 characters that would directly serve as native speech commands for any speech engine.

**Comment by Ryladog** [comment]
+1 to include this text in Understanding!

**Comment by alastc** [comment]
Please merge the change in.
