### ISSUE TITLE
Success Criterion 1.4.11 Non-text Contrast

### ISSUE THREAD

**Issue by MarcSolo** [w3c/wcag21#818]
1.4.11 will close an existing gap in WCAG by requiring icon based UI components and visual effects that indicate state to have sufficient contrast with their backgrounds. Closing this gap is very important because a proliferation of iconography usage and low contrast state indication in modern web apps and Mobile native apps.

**Comment by MarcSolo** [comment]
I urge the W3C to keep this SC in WCAG 2.1 to help improve digital accessibility especially for people with low vision and low contrast sensitivity.

**Comment by awkawk** [comment]
Thank you for commenting. For more information about how the AG WG will process this issue, see the following:
- [Issue Processing](https://www.w3.org/WAI/WCAG21/comments/#issueprocessing) - How the WG will discuss the issue
- [Issue Resolution](https://www.w3.org/WAI/WCAG21/comments/#issueresolution) - Identifying and responding to the official WG response
- [Issue Notification](https://www.w3.org/WAI/WCAG21/comments/#issuenotification) - How to limit notifications from GitHub

**Comment by DavidMacDonald** [comment]
# Proposed Response

Thank you for the comment. We will draw it into any future discussions about this at risk SC.
