### ISSUE TITLE
Contributing guidelines don't seem appropriate for public comments

### ISSUE THREAD

**Issue by cyns** [w3c/wcag21#820]
https://github.com/w3c/wcag21/blob/master/CONTRIBUTING.md

WCAG 2.1 points to this github for making public comments, but the contributing guidelines seem to be about wg participation. Please add a paragraph about using github to make public comments.

**Comment by awkawk** [comment]
Thank you for commenting. For more information about how the AG WG will process this issue, see the following:
- [Issue Processing](https://www.w3.org/WAI/WCAG21/comments/#issueprocessing) - How the WG will discuss the issue
- [Issue Resolution](https://www.w3.org/WAI/WCAG21/comments/#issueresolution) - Identifying and responding to the official WG response
- [Issue Notification](https://www.w3.org/WAI/WCAG21/comments/#issuenotification) - How to limit notifications from GitHub

**Comment by DavidMacDonald** [comment]
# Proposed Response

We agree and have added a pull request for for an additional paragraph to the contributing.md file.

https://github.com/w3c/wcag21/pull/849
