### ISSUE TITLE
0.2 New Features: Additive approach is good

### ISSUE THREAD

**Issue by cyns** [w3c/wcag21#821]
I appreciate the additive approach in moving from WGAC 2.0 to 2.1. It's clear to me how to roll this out in an enterprise that's in the process of implementing WCAG 2.0. It's clear how WCAG 2.1 interacts with legal and regulatory requirements based on WCAG 2.0. I hope that there will also be a WCAG 2.2, 2.3, etc. as more features reach maturity.

**Comment by awkawk** [comment]
Thank you for commenting. For more information about how the AG WG will process this issue, see the following:
- [Issue Processing](https://www.w3.org/WAI/WCAG21/comments/#issueprocessing) - How the WG will discuss the issue
- [Issue Resolution](https://www.w3.org/WAI/WCAG21/comments/#issueresolution) - Identifying and responding to the official WG response
- [Issue Notification](https://www.w3.org/WAI/WCAG21/comments/#issuenotification) - How to limit notifications from GitHub

**Comment by awkawk** [comment]
Proposed response:
Thank you for your comment. The Working Group is pleased to hear that you agree with that additive approach. While we have not yet made a determination about whether to pursue a WCAG 2.2 or to move to the "Silver" approach for the next version of accessibility standards, our intention is to update the standard on a more regular and shorter interval than in the past.
