### ISSUE TITLE
0.4 Conformance: Backward compatibility is good

### ISSUE THREAD

**Issue by cyns** [w3c/wcag21#822]
I appreciate the backward compatible approach to conformance for WCAG 2.1, allowing sites that conform to WCAG 2.0 to continue to make that claim while also making progress towards 2.1.

**Comment by awkawk** [comment]
Thank you for commenting. For more information about how the AG WG will process this issue, see the following:
- [Issue Processing](https://www.w3.org/WAI/WCAG21/comments/#issueprocessing) - How the WG will discuss the issue
- [Issue Resolution](https://www.w3.org/WAI/WCAG21/comments/#issueresolution) - Identifying and responding to the official WG response
- [Issue Notification](https://www.w3.org/WAI/WCAG21/comments/#issuenotification) - How to limit notifications from GitHub

**Comment by awkawk** [comment]
Proposed response:
Thank you for your comment. The Working Group appreciates your voicing agreement with the approach that results in backward compatibility.
