### ISSUE TITLE
1.3.4 Identify Common Purpose

### ISSUE THREAD

**Issue by cyns** [w3c/wcag21#823]
This is a good addition. I like the way it leverages html autocomplete.

**Comment by awkawk** [comment]
Proposed response:
Thank you for your comment. The Working Group has made a decision to integrate the list of specific tokens into the WCAG 2.1 document directly, but it will be the same list as is found in the HTML 5.2 specification.

**Comment by awkawk** [comment]
Thank you for commenting. For more information about how the AG WG will process this issue, see the following:
- [Issue Processing](https://www.w3.org/WAI/WCAG21/comments/#issueprocessing) - How the WG will discuss the issue
- [Issue Resolution](https://www.w3.org/WAI/WCAG21/comments/#issueresolution) - Identifying and responding to the official WG response
- [Issue Notification](https://www.w3.org/WAI/WCAG21/comments/#issuenotification) - How to limit notifications from GitHub
