### ISSUE TITLE
1.4.12 Text Spacing editorial issue

### ISSUE THREAD

**Issue by cyns** [w3c/wcag21#827]
Editorial: In the exception "Exception: Human languages and scripts which do not make use of one or more of these text style properties in written text can conform using only the properties that are used." 
"using only the properties that are used" doesn't work, with using/used referring to different things. Maybe "that exist in that language" instead?

**Comment by lauracarlson** [comment]
Proposed response:

Thank you for the suggestion. The Working Group agrees that your suggestion would make the SC clearer. We will change it to read:

>Exception: Human languages and scripts that do not make use of one or more of these text style properties in written text can conform using only the properties that exist in that language.

**Comment by awkawk** [comment]
The WG decided on the above response, so we changed the text in the comment containing the proposed response to read "[Official WG Response]". Please confirm is you are satisfied with the response within 3 days. If we haven't heard a response by then we will regard the resolution as satisfactory.
