### ISSUE TITLE
1.4.12 Text Spacing: Understanding editorial issue

### ISSUE THREAD

**Issue by cyns** [w3c/wcag21#828]
The Intent in Understanding Text Spacing should say what disabilities are impacted, and how changing spacing helps. It's covered further down, but a sentence or two in Intent would be helpful.

**Comment by awkawk** [comment]
The WG decided on the above response, so we changed the text in the comment containing the proposed response to read "[Official WG Response]". Please confirm is you are satisfied with the response within 1 week. If we haven't heard a response in a week we will regard the resolution as satisfactory.

**Comment by awkawk** [comment]
Implemented suggested text from WG at https://github.com/w3c/wcag21/blob/text-spacing/understanding/21/text-spacing.html - more edits needed by this document but the text is incorporated.
