### ISSUE TITLE
1.4.13 Content on Hover and Focus shouldn't have UA exception

### ISSUE THREAD

**Issue by cyns** [w3c/wcag21#829]
I don't think the exception for UI rendered by the UA should exist, for example for @title. Authors can choose to use a different mechanism to display the hover content if the one provided by the user agent is inaccessible.

**Comment by awkawk** [comment]
Thank you for commenting. For more information about how the AG WG will process this issue, see the following:
- [Issue Processing](https://www.w3.org/WAI/WCAG21/comments/#issueprocessing) - How the WG will discuss the issue
- [Issue Resolution](https://www.w3.org/WAI/WCAG21/comments/#issueresolution) - Identifying and responding to the official WG response
- [Issue Notification](https://www.w3.org/WAI/WCAG21/comments/#issuenotification) - How to limit notifications from GitHub

**Comment by cwadamsoforacle** [comment]
Proposed response:
As many existing implementations would be in violation of this success criteria, the decision was made to allow this exception.  Removing this exception will be considered in future guidelines.

**Comment by awkawk** [comment]
The WG decided on the above response, so we changed the text in the comment containing the proposed response to read "[Official WG Response]". Please confirm is you are satisfied with the response within 3 days. If we haven't heard a response by then we will regard the resolution as satisfactory.
