### ISSUE TITLE
2.2.6 Timeouts: Understanding needs to clarify difference from 2.2.6

### ISSUE THREAD

**Issue by cyns** [w3c/wcag21#830]
I initially thought that 2.2.6 should be made a technique of 2.2.1. On closer reading, I see now the hole it's trying to fill. Please include something near the beginning of the Intent section of each SC to clarify the difference.

**Comment by awkawk** [comment]
Thank you for commenting. For more information about how the AG WG will process this issue, see the following:
- [Issue Processing](https://www.w3.org/WAI/WCAG21/comments/#issueprocessing) - How the WG will discuss the issue
- [Issue Resolution](https://www.w3.org/WAI/WCAG21/comments/#issueresolution) - Identifying and responding to the official WG response
- [Issue Notification](https://www.w3.org/WAI/WCAG21/comments/#issuenotification) - How to limit notifications from GitHub

**Comment by alastc** [comment]
I'll add this as something for the main thread on the Timeouts understanding document.

I'll close the issue, but it is not lost, it should be dealt with on issue #785.
