### ISSUE TITLE
2.2.6 Timeouts: Understanding Intent section is too long

### ISSUE THREAD

**Issue by cyns** [w3c/wcag21#831]
The intent section of the Understanding Timeouts doc is a wall of text. Please tighten up the first four paragraphs, and change the options for complying into a bullet list. Some of the other understanding docs have a section of common ways to comply that is easier to parse.

**Comment by awkawk** [comment]
Thank you for commenting. For more information about how the AG WG will process this issue, see the following:
- [Issue Processing](https://www.w3.org/WAI/WCAG21/comments/#issueprocessing) - How the WG will discuss the issue
- [Issue Resolution](https://www.w3.org/WAI/WCAG21/comments/#issueresolution) - Identifying and responding to the official WG response
- [Issue Notification](https://www.w3.org/WAI/WCAG21/comments/#issuenotification) - How to limit notifications from GitHub

**Comment by michael-n-cooper** [comment]
This issue was moved to w3c/wcag#362
