### ISSUE TITLE
2.5.2 Pointer Cancellation: clarify that "onclick" is an up-event

### ISSUE THREAD

**Issue by cyns** [w3c/wcag21#837]
Despite its name, the Click event is a device-independent up-event. Please clarify that Click/onclick are an up-event. (probably in Understanding? or linking to some of the existing onclick techniques?)

**Comment by awkawk** [comment]
Thank you for commenting. For more information about how the AG WG will process this issue, see the following:
- [Issue Processing](https://www.w3.org/WAI/WCAG21/comments/#issueprocessing) - How the WG will discuss the issue
- [Issue Resolution](https://www.w3.org/WAI/WCAG21/comments/#issueresolution) - Identifying and responding to the official WG response
- [Issue Notification](https://www.w3.org/WAI/WCAG21/comments/#issuenotification) - How to limit notifications from GitHub

**Comment by alastc** [comment]
Hi, I've added this to the main Pointer cancellation thread in #791, so although this is being closed, it is not lost.
Just trying to make it easier for people updating the docs.

**Comment by mbgower** [comment]
Latest version makes this point. https://github.com/w3c/wcag21/pull/884
