### ISSUE TITLE
2.5.1 Pointer Gestures: Clarify relationship to 2.1.1 Keyboard

### ISSUE THREAD

**Issue by cyns** [w3c/wcag21#838]
If a site had complex-gesture functionality and all of it could be done with a keyboard, would it pass? Or is it required to have both single-point activation and keyboard support? I can see arguments for either, but it's not clear which is the case. Maybe add some clarification to the Understanding doc?

**Comment by patrickhlauke** [comment]
if a user is on a device that does not have an external keyboard, and cannot arbitrarily trigger a virtual keyboard (which is the case for most mobile/tablet environments, where the on-screen keyboard is only shown when required - e.g. when focus is in a text entry field), then it's of no use to them whether or not there's full keyboard support.

making sure things work with a keyboard is a separate SC, they need to be evaluated independently from each other. a site may pass 2.1.1 but fail 2.5.1, or it may fail 2.1.1 but pass 2.5.1. they're not interdependent.

**Comment by awkawk** [comment]
Thank you for commenting. For more information about how the AG WG will process this issue, see the following:
- [Issue Processing](https://www.w3.org/WAI/WCAG21/comments/#issueprocessing) - How the WG will discuss the issue
- [Issue Resolution](https://www.w3.org/WAI/WCAG21/comments/#issueresolution) - Identifying and responding to the official WG response
- [Issue Notification](https://www.w3.org/WAI/WCAG21/comments/#issuenotification) - How to limit notifications from GitHub

**Comment by detlevhfischer** [comment]
Proposed Working Group response:
Thank you for your comment.
This SC focuses specifically on the availability of single-point activation options, i.e., pointer input.
If a user is on a device that does not have an external keyboard and  cannot arbitrarily trigger a virtual keyboard (which is the case for  most mobile/tablet environments, where the on-screen keyboard is only  shown when required - e.g. when focus is in a text entry field), then  it's of no use to them whether or not there is full keyboard support. 
Making sure things work with a keyboard is a separate SC, both need  to be evaluated independently. A site may pass 2.1.1 but  fail 2.5.1, or it may fail 2.1.1 but pass 2.5.1.
--

**Comment by awkawk** [comment]
The WG decided on the above response, so we changed the text in the comment containing the proposed response to read "[Official WG Response]". Please confirm is you are satisfied with the response within 3 days. If we haven't heard a response by then we will regard the resolution as satisfactory.
