### ISSUE TITLE
2.5.3 Target Size: Don't use specific pixel numbers

### ISSUE THREAD

**Issue by cyns** [w3c/wcag21#839]
It's important to get the target size requirement in to support touch-only interfaces. Similar to my comment on 1.4.10 Reflow #825, the specific pixel size seems likely to become stale. Could a physical size (for example 1 cm) be used instead? Or the pixel number moved to a non-normative document?

**Comment by patrickhlauke** [comment]
not possible to give a physical size, because authors have no way of controlling at what physical size something gets rendered. it varies between devices. this would also make it impossible to test when auditing, as a pass/fail would ultimately depend on the device/operating system/user agent the auditor used.

**Comment by awkawk** [comment]
Thank you for commenting. For more information about how the AG WG will process this issue, see the following:
- [Issue Processing](https://www.w3.org/WAI/WCAG21/comments/#issueprocessing) - How the WG will discuss the issue
- [Issue Resolution](https://www.w3.org/WAI/WCAG21/comments/#issueresolution) - Identifying and responding to the official WG response
- [Issue Notification](https://www.w3.org/WAI/WCAG21/comments/#issuenotification) - How to limit notifications from GitHub

**Comment by awkawk** [comment]
The WG decided on the above response, so we changed the text in the comment containing the proposed response to read "[Official WG Response]". Please confirm is you are satisfied with the response within 3 days. If we haven't heard a response by then we will regard the resolution as satisfactory.
