### ISSUE TITLE
2.5.4 Concurrent Input Mechanism: Add mouse/keyboard menu example

### ISSUE THREAD

**Issue by cyns** [w3c/wcag21#840]
So glad to see this in there! Please add an example to the Understanding doc along the lines of:
"User opens a menu with a mouse, and then navigates between the menu items with arrow keys." This is one of the bugs I run into over and over in the wild.

**Comment by awkawk** [comment]
Thank you for commenting. For more information about how the AG WG will process this issue, see the following:
- [Issue Processing](https://www.w3.org/WAI/WCAG21/comments/#issueprocessing) - How the WG will discuss the issue
- [Issue Resolution](https://www.w3.org/WAI/WCAG21/comments/#issueresolution) - Identifying and responding to the official WG response
- [Issue Notification](https://www.w3.org/WAI/WCAG21/comments/#issuenotification) - How to limit notifications from GitHub

**Comment by alastc** [comment]
I've created a pull request for review in #931

**Comment by michael-n-cooper** [comment]
This issue was moved to w3c/wcag#363
