### ISSUE TITLE
2.6.2 Orientation: Add vision impairment benefit and example

### ISSUE THREAD

**Issue by cyns** [w3c/wcag21#842]
This also benefits users with mild vision impairment. I will often rotate my phone to read text in article if the default font is too small. It works better than pinch zoom, and doesn't require changing phone or browser settings.

**Comment by awkawk** [comment]
Thank you for commenting. For more information about how the AG WG will process this issue, see the following:
- [Issue Processing](https://www.w3.org/WAI/WCAG21/comments/#issueprocessing) - How the WG will discuss the issue
- [Issue Resolution](https://www.w3.org/WAI/WCAG21/comments/#issueresolution) - Identifying and responding to the official WG response
- [Issue Notification](https://www.w3.org/WAI/WCAG21/comments/#issuenotification) - How to limit notifications from GitHub

**Comment by alastc** [comment]
That can work in iOS for non-repsonsive sites, but I'm not sure that behavious is intended (by the browser makers). I'm a little wary of including it in the understanding document because that behaviour is likely to become less common as time goes on. 

I'll check my assumptions on it thought.

**Comment by michael-n-cooper** [comment]
Ported to https://github.com/w3c/wcag/issues/364
