### ISSUE TITLE
Understandable>Readable is more flexible renamed Understandable>Meaningful

### ISSUE THREAD

**Issue by mbgower** [w3c/wcag21#853]
See the [latter comments in issue 806](https://github.com/w3c/wcag21/issues/806#issuecomment-373720799) for background.

Renaming the **3.1 Readable** guideline under the Understandable principle to **3.1 Meaningful** sets us up better as the home for future coga SCs, and also provides a place to relocate both of the Common Purpose SCs.

All the existing items in 3.1 still fit with that editorial change -- in fact "meaning" is called out in many of them (as quoted below in square brakcets) and most are made more precise and understandable with that word change --and none are reduced.

- Language of Page [i.e., making text meaningful by designating its language]
- Language of Parts [designate 'foreign' phrases except where their meaning is clear in the "vernacular" of the default page language]
- Unusual Words ["definitions of words or phrases used in an unusual or restricted way" AKA meaning]
- Abbreviations ["meaning of abbreviations is available"]
- Reading Level [making content meaningful to lower-secondary-education-level users]
- Pronunciation ["...where meaning of the words, in context, is ambiguous without knowing the pronunciation"]

With that word change in effect, both 1.3.4 and 1.3.5 can be moved under the Understandable principle where they more naturally fit; if desired, 1.3.4 can be moved to the precise Input Assistance guideline, with 1.3.5 fitting underneath the more general Meaningful. Or they can both be put under Understandable>Meaingful. Either options allows them to remain under the same Principle, which addresses some of the concerns expressed about moving only 1.3.4.

**Comment by mbgower** [comment]
@awkawk, if you feel this issue was discussed adequately at CSUN and gained no traction, you can close it. Katie's [comments ](https://github.com/w3c/wcag21/issues/806#issuecomment-379247603)about 806 not being fully addressed may have only applied to Non-Keyboard Accessible, which I made a [separate issue](https://github.com/w3c/wcag21/issues/852)..

**Comment by alastc** [comment]
I think this one might have been passed by other changes?

**Comment by awkawk** [comment]
This was resolved with the changes right before PR that moved several SC around.
