### ISSUE TITLE
Sc 1.4.11 non text contrast 

### ISSUE THREAD

**Issue by goetsu** [w3c/wcag21#875]
Hi,

I think may an exception must be considered for 1.4.11 on logotypes as we currently have on 1.4.3

Logotypes
Graphical objects that are part of a logo or brand name has no contrast requirement.

**Comment by alastc** [comment]
Previous iterations of the SC had several bullets for exceptions, but they all came down to being 'essential' (in the defined meaning of that from WCAG 2.0).

The logo example is described in the [understanding doc](https://rawgit.com/w3c/wcag21/non-text-contrast/understanding/21/non-text-contrast.html), does that cover it for you?

-------------------

Thank you for commenting. For more information about how the AG WG will process this issue, see the following:
- [Issue Processing](https://www.w3.org/WAI/WCAG21/comments/#issueprocessing) - How the WG will discuss the issue
- [Issue Resolution](https://www.w3.org/WAI/WCAG21/comments/#issueresolution) - Identifying and responding to the official WG response
- [Issue Notification](https://www.w3.org/WAI/WCAG21/comments/#issuenotification) - How to limit notifications from GitHub

**Comment by goetsu** [comment]
yes thanks. I still have some other issue with this SC but I will open new bug

**Comment by alastc** [comment]
Thanks for letting us know, I'll close this one then.
