### ISSUE TITLE
Inappropriate example in Understanding doc for Identify Input Purpose

### ISSUE THREAD

**Issue by guyhickling** [w3c/wcag21#880]
The Understanding document for this SC, in the new draft released today, still contains the example demo previously included when this SC had wider coverage. I thought I read in some other discussion that the demo was going to be removed. (For reference, that's the demo linked to in the words "..... such as this personalization demo provides....." in the "Intent of..." section.) It isn't appropriate anymore because it adds icons to the buttons, and buttons are no longer in scope of the SC. 

Can the example be removed from the Understanding doc? But I guess it would be appropriate for the AAA level Identify Purpose SC?

**Comment by alastc** [comment]
Hi Guy,

For reference we're working in branches that should be ahead of the published and editors drafts. In this case the rendered view is in the identify-common-input branch, [rendered view](https://rawgit.com/w3c/wcag21/identify-input-purpose/understanding/21/identify-common-purpose.html).

I was about to close and reference #779, but I'm not sure I agree with removing it.

That paragraph starts with:
> **In the future** a more robust set of personalization abilities should be available, such as ...

Part of the rational for including this SC was to say that the work will continue, and should provide more personalisation in future. Paragraphs 3-5 of the intent (and this is in paragraph 5) are all about the future, not what we are asking of authors now.

I would like to replace the demo when a more refined version is available at a stable URL, but in the meantime I think the context is clear.

**Comment by guyhickling** [comment]
Yes, the paragraph as a whole is clear, but I'm thinking that a better demo, in this SC, would be to have some icons appear beside the input fields since that is what this SC is now about, and remove the icons from the buttons, which are a throwback to the way this SC originally started. It seems a bit confusing to readers of the Understanding document to have so much included in the paragraph that does not apply to input fields.

In saying this, I am assuming that a) it is too late now for the future plans for personalisation for buttons and links to be included in WCAG 2.1, and b) if they are added in a 2.2 (if it happens) then they would have to be in a new SC in order to retain backwards compatibility for the 2.1 stuff (just as 2.1 is not changing any of the SCs that were in 2.0)?

**Comment by alastc** [comment]
NB there is an [updated version](https://rawgit.com/w3c/wcag21/identify-input-purpose/understanding/21/identify-input-purpose.html) of this understanding doc that has removed the example:

Can we close this issue?

Thanks,
-Alastair

**Comment by guyhickling** [comment]
Yes, I have looked through the new Understanding that you linked in above and that solves this issue. (I assume it will replace the current version in due course.) This can be closed.
