### ISSUE TITLE
0.5.1 "new features" summary - mistake

### ISSUE THREAD

**Issue by Itakora** [w3c/wcag21#886]
In https://www.w3.org/TR/2018/PR-WCAG21-20180424/#new-features-in-wcag-2-1 the following criteria have been listed, but they are not accurate:

-     2.5.3 Character Key Shortcuts (A): It should be 2.1.4
-     2.5.4 Label in Name (A): It should be 2.5.3
-     2.5.7 Motion Actuation (A) : It should be 2.5.4

**Comment by Iz-a11y** [comment]
In the same list, 2.4.10 - section headings - is missing.

**Comment by awkawk** [comment]
Fixed in editor's draft. @Iz-a11y I didn't add 2.4.10 because that isn't new to WCAG 2.1.
