### ISSUE TITLE
Number of guidelines - mistake

### ISSUE THREAD

**Issue by Itakora** [w3c/wcag21#887]
In https://www.w3.org/TR/WCAG/#wcag-2-layers-of-guidance, paragraph #3, they say there are 12 guidelines. This was true in 2.0, but in 2.1 there is a new one (2.5), so there are 13  guidelines.

**Comment by awkawk** [comment]
Fixed: https://github.com/w3c/wcag21/commit/780dafb4a555a286571a9fc51b4607bcc62de822
