### ISSUE TITLE
Link to SC 4.2.1 - mistake

### ISSUE THREAD

**Issue by Itakora** [w3c/wcag21#899]
In https://www.w3.org/WAI/WCAG21/Understanding/identify-input-purpose.html, there is a missing link to "(as required by 4.2.1 @@@ link)."
However, it should be 4.1.2 instead

**Comment by awkawk** [comment]
Fixed: https://github.com/w3c/wcag21/commit/ff1d4307d4c1acdc060b5f9653c68b3b00150fef
Thanks.
