### ISSUE TITLE
Understanding SC 1.4.11 - Mistake

### ISSUE THREAD

**Issue by Itakora** [w3c/wcag21#901]
In the sufficient techniques at https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html the G18 and G145 texts are the same (correct one is G18, the G145 is 3:1)

However, the SC demands at least 3:1, so maybe G18 should be moved to advisory techniques.

**Comment by alastc** [comment]
Will action after the current round of updates.

**Comment by alastc** [comment]
Oh, just to note, if text is being used that removes the need for the graphical objects to meet contrast, but, if the text is small it should still be 4.5:1. 

We should probably make the 'and' relationship clearer for those techniques.

**Comment by awkawk** [comment]
I've corrected the reference to G145 to use the proper title. 

We don't include the and relationships in the understanding documents, just in the QRG. Recommend closing this one as complete.

**Comment by michael-n-cooper** [comment]
This issue was moved to w3c/wcag#397
