### ISSUE TITLE
Carry out editorial review for consistent structure

### ISSUE THREAD

**Issue by mbgower** [w3c/wcag21#904]
Understanding docs should be compared for the amount and type of content in sections (e.g., Intent), and an attempt made to align style and volume. The editorial pass should also consider adding subheadings or moving content to make the Understanding documents more consistent.

**Comment by mbgower** [comment]
Note: this is a different editorial pass than the straightforward Style Consistency phase, where editors confirm that the same stock headings and other structural material appears in each document.

**Comment by michael-n-cooper** [comment]
This issue was moved to w3c/wcag#398
