### ISSUE TITLE
Error Prevention SCs seem to be incomplete

### ISSUE THREAD

**Issue by SteveALee** [w3c/wcag21#92]
https://github.com/w3c/wcag21/blob/master/guidelines/index.html#L815
https://github.com/w3c/wcag21/blob/master/guidelines/index.html#L829

The content ends in ```one of following is true:``` but no list is supplied

Note due to a large block change I could not use blame to find the source of this line

**Comment by awkawk** [comment]
Steve,
This issue has been addressed in the current draft: http://rawgit.com/w3c/wcag21/master/guidelines/index.html#error-prevention-(legal,-financial,-data)
