### ISSUE TITLE
In Orientation need to change language of Understanding around functionality.

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/wcag21#921]
As per [meeting discussion today May 15](https://www.w3.org/2018/05/15-ag-minutes.html), testing the functionality of the web site in all orientations is beyond the scope of this SC. The SC is to ensure user is not "restricted" which means the author would have to take an action to lock the operation of the website to one orientation to fail rather than the myriad of hiccups that can happen as users change orientation ... 

Currently doing a pull request for Understanding language. Will follow up here.

**Comment by awkawk** [comment]
@david, I think:
Therefore, websites and applications need to support both orientations by making sure content and functionality is available in each orientation. While changing the orientation may affect the ordering of content and the specific implementation of functionality, all content and functionality must be available regardless of orientation.
changes to
Therefore, websites and applications need to support both orientations by making sure content is operable in each orientation. Changing the orientation may affect the ordering of content and the specific implementation of functionality but the focus of this Success Criterion is to not prevent user choice of device orientation.

In examples:
Videos are not locked to a specific orientation. A user can start a video with their device in a portrait orientation, resulting in a smaller video being displayed and then rotate the device to landscape and have the video expand to fill the entire screen. All controls and functionality are available in either orientation.
Change to:
Videos are not locked to a specific orientation. A user can start a video with their device in a portrait orientation, resulting in a smaller video being displayed and then rotate the device to landscape and have the video expand to fill the entire screen. 

A messaging website can display messages in both portrait and landscape orientations without a loss of content or functionality.
Change to:
A messaging website can allow a user to read and send messages in both portrait and landscape orientations.

An eReader web app can display the contents of a book in both portrait and landscape mode without a loss of content or functionality
change to:
An eReader web app can display the contents of a book in both portrait and landscape mode.

In Failure section:
Functionality that is only available in one orientation.
Change:
This can be removed as the previous "locking the orientation" failure covers this.

**Comment by DavidMacDonald** [comment]
There is a difference between allowing content to operate in either orientation and requiring a switch of orientation after page load... 

> Videos are not locked to a specific orientation. A user can start a video with their device in a portrait orientation, resulting in a smaller video being displayed and then rotate the device to landscape and have the video expand to fill the entire screen.

So I would strike the second half of the sentence.

> Videos are not locked to a specific orientation. A user can start a video with their device in a portrait orientation.

**Comment by awkawk** [comment]
@DavidMacDonald ok to close?
