### ISSUE TITLE
Something is ignoring .editorconfig leading to trailing spaces

### ISSUE THREAD

**Issue by SteveALee** [w3c/wcag21#93]
Several lines like
https://github.com/w3c/wcag21/blob/master/guidelines/index.html#L23

Have training linespace even though .editorconfig declares this should be trimmed (```trim_trailing_whitespace = true```).

I spotted this when checking my changes for a coga PR which has these lines as extra changes. My editor (VS code) is following .editorconfig.

**Comment by awkawk** [comment]
That example line has been the same since Michael checked in the initial HTML in November, so it is likely an artifact from his initial XSLT transformation to get started.

**Comment by SteveALee** [comment]
@awkawk Yes that makes sense and explains the block changes I see. I'll fix with my PR

**Comment by SteveALee** [comment]
Another discrepancy is the indent style is specified as 2 spaces in .editorconfig but is tabs in the file.

I'll adjust my PR to use the same but it should be fixed or file will become a mixture.

**Comment by SteveALee** [comment]
correction it already a mixture of tabs a spaces. Not a big issues but I suggest a clean up at some point.

**Comment by awkawk** [comment]
We will do a cleanup at some point.
