### ISSUE TITLE
I don't see any of the SC notes sections in guidelines/index.html

### ISSUE THREAD

**Issue by SteveALee** [w3c/wcag21#94]
Looking through index.html the notes sections do not appear. 

eg 2.2.1 has a single Note in the live docs.
http://www.w3.org/TR/WCAG20/#time-limits-required-behaviors

Does the live doc generated from the older XML and somehow the notes got missed of in the transfer to index.html?

**Comment by SteveALee** [comment]
More, "Time Adjustable", the subject of 2.2.1 is not in index.html either?

What am I not understanding?

**Comment by inclusiveThinking** [comment]
Are you referring to the Working Group Notes (option) that we used in COGA for example. My understanding is that those should not be included/

**Comment by awkawk** [comment]
@SteveALee - I think that this was an artifact of the process used to bring the 2.0 SC over to 2.1. It should be all set now. Please verify if your concern was addressed: http://rawgit.com/w3c/wcag21/master/guidelines/index.html#timing-adjustable

**Comment by SteveALee** [comment]
Looks good. Thanks!
