### ISSUE TITLE
Understanding doc for Guideline 2.5 lists old SC numbering

### ISSUE THREAD

**Issue by mraccess77** [w3c/wcag21#950]
Old numbering is listed in this understanding document. Concurrent input mechanisms should be 2.5.6 not 2.5.2 and so forth.
https://rawgit.com/w3c/wcag21/master/understanding/21/input-modalities.html

**Comment by michael-n-cooper** [comment]
You can fix this in the file if you want. But to reduce this sort of error in published versions, the generator I use to publish to github.io and /WAI/WCAG21/Understanding overrides these sort of cross references and generates them based on the current version of the guidelines. For instance, https://w3c.github.io/wcag21/understanding/input-modalities.html.
