### ISSUE TITLE
1.4.13 on Hover indicates that additional content must be dismissable without moving keyboard or hover yet understanding document indicates a close button is a solution

### ISSUE THREAD

**Issue by mraccess77** [w3c/wcag21#952]
The understanding document may need to be updated to remove the bit about a close button being an option for dismissing since it would require the user to move the pointer hover or keyboard focus.  If there is some nuance I am missing then we should update the understanding to make that more clear.

https://www.w3.org/WAI/WCAG21/Understanding/content-on-hover-or-focus.html

**Comment by michael-n-cooper** [comment]
This issue was moved to w3c/wcag#409
