### ISSUE TITLE
Editorial correction in Understanding Reflow

### ISSUE THREAD

**Issue by sidnc86** [w3c/wcag21#953]
Under the section "Intent of this Success Criterion", there is a text content that starts like "Avoiding the need to scroll in the direction of reading in order to reveal lines that are cut off by the viewport is important, because such scrolling signiicantly increases the effort required to read."
The spelling of "signiicantly" needs to be corrected to "significantly"

**Comment by awkawk** [comment]
closing here - resolved in w3c/wcag repo.
