### ISSUE TITLE
Editorial issue with Understanding Pointer Cancellation

### ISSUE THREAD

**Issue by sidnc86** [w3c/wcag21#954]
Under the section "Intent of this Success Criterion", there is a paragraph
"Up-event activation refers to the activation of a target when the pointer is released. In a touchscreen interaction, when the finger touches a target, the up-event activation ony occurs when the finger is lifted while still being within the target boundary."
We need to change "the up-event activation ony occurs" to "the up-event activation only occurs." (corect spelling of "ony" to "only")

**Comment by awkawk** [comment]
thanks, fixed.
