### ISSUE TITLE
Duplicate paragraph in the "Status of This Document" section of WCAG 2.1

### ISSUE THREAD

**Issue by lauracarlson** [w3c/wcag21#955]
It seems that following paragraph is repeated twice in the [Status of This Document](https://www.w3.org/TR/WCAG21/#status-of-this-document) section of 2.1:

> This document has been reviewed by W3C Members, by software developers, and by other W3C groups and interested parties, and is endorsed by the Director as a W3C Recommendation. It is a stable document and may be used as reference material or cited from another document. 
W3C's role in making the Recommendation is to draw attention to the specification and to promote its widespread deployment. This enhances the functionality and interoperability of the Web.

**Comment by michael-n-cooper** [comment]
This issue was moved to w3c/wcag#410
