### ISSUE TITLE
Small typo for Note 5.2.2 Full pages

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag21#959]
at https://www.w3.org/TR/WCAG21/#cc2 there's a Note where the note starts with the text "New A full page includes..."

> NOTE
> New A full page includes each variation of the page that is automatically presented by the page for various screen sizes (e.g. variations in a responsive Web page). 

If "New" is supposed to be present a colon ":" should be added, or the text "New" should be deleted.

**Comment by michael-n-cooper** [comment]
This issue was moved to w3c/wcag#413
