### ISSUE TITLE
Table of contents missing, big gap Understanding pages

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag21#962]
When visiting a understanding doc I see a gap / space from the left of 29em
```
@media screen and (min-width: 78em)
body:not(.toc-inline) {
    padding-left: 29em;
}
```
see: https://www.w3.org/WAI/WCAG21/Understanding/orientation.html

When I'm zoomed in (not browser zoom) this results in a 'blank' page as the content is out of view.
The 29em is for the TOC but not present.
Page should be properly left aligned without TOC.

**Comment by michael-n-cooper** [comment]
This issue was moved to w3c/wcag#415
