### ISSUE TITLE
Understanding Success Criterion 1.3.4: Orientation

### ISSUE THREAD

**Issue by devarshipant** [w3c/wcag21#963]
https://www.w3.org/WAI/WCAG21/Understanding/orientation.html

Please refer to the following paragraphs:

> "The goal of this Success Criterion is that authors should never restrict content's orientation, thus ensuring that it always match the device display orientation."

1. Isn't "Content's Orientation" similar to "system-level orientation" setting? 

2. It is not clear what orientation settings can be controlled by content authors? I see Content, System-level, and Device-level Display orientation settings in use.

3. Should it be mentioned that restricting a display setting is fine if that specific display orientation is essential?

> " ...current orientation determined by any device senors."

senors should be sensors.

**Comment by NIKHILSAIREDDY** [comment]
Then what about the gaming softwares

**Comment by michael-n-cooper** [comment]
This issue was moved to w3c/wcag#416
